import { safeBestEffort } from '../../shared/bestEffort.ts';
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
import { requireAdminOrInternal } from '../../shared/internalGate.ts';
import { policyIsActive } from '../../shared/commercialAutonomy.ts';
import { canOpenRFP, truthfulDemandSnapshot, AGGREGATE_ENGINE_VERSION } from '../../shared/aggregateCore.ts';
import { sha256 } from '../../shared/intelligenceCore.ts';
import { emergencyState } from '../../shared/operationalControl.ts';
import { sendingProfileIsValid } from '../../shared/commercialActivation.ts';
import { guardedScheduledServe } from '../../shared/schedulerRun.ts';
const slug=(v:any)=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
guardedScheduledServe({"worker_key":"aggregateProcurementWorker","cadence_seconds":86400},createClientFromRequest,async(req)=>{try{
 const b=createClientFromRequest(req),body=await req.json().catch(()=>({})),g=await requireAdminOrInternal(req,b,body);if(!g.ok)return g.response;const s=b.asServiceRole;const emergency=await emergencyState(s);if(emergency.safe_mode||emergency.negotiations_paused)return Response.json({ok:false,error:'emergency_control_paused:negotiations',safe_mode:emergency.safe_mode,reason:emergency.reason||null},{status:409});const internal=Deno.env.get('INTERNAL_CALL_SECRET')||'';const now=new Date().toISOString();
 const policies=await s.entities.CommercialPolicy.filter({engine:'aggregate_procurement',status:'active'},'-approved_at',10).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:[],severity:'secondary'}));const policy=policies.find((p:any)=>policyIsActive(p))||null;
 const pools=await s.entities.AggregatePool.filter({status:{$in:['negotiation_ready','rfp_preparing','rfp_open','negotiating','renegotiating']}},'-aggregation_power_score',200).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:[],severity:'secondary'}));let prepared=0,opened=0,casesCreated=0,contacted=0,skipped=0;
 for(const pool of pools){if(!canOpenRFP(pool)){skipped++;continue}let rfp=(await s.entities.AggregateRFP.filter({pool_id:pool.id,status:{$in:['prepared','open','negotiating','final_offer','human_approval','contracting']}},'-created_at',1).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:[],severity:'secondary'})))[0]||null;
  if(!rfp){const demand=truthfulDemandSnapshot(pool);const snapPayload={pool_id:pool.id,pool_key:pool.pool_key,demand,provider_intelligence_rule:'provider candidates require compatible P12 pricing/capability evidence',aggregate_engine_version:AGGREGATE_ENGINE_VERSION};const hash=await sha256(snapPayload);const snap=await s.entities.IntelligenceSnapshot.create({snapshot_key:`aggregate-rfp:${pool.id}:${hash.slice(0,16)}`,snapshot_type:'aggregate_rfp_open',related_entity_type:'AggregatePool',related_entity_id:pool.id,brand_id:'_platform',vertical:pool.vertical,claim_ids:[],pricing_version_ids:[],benchmark_refs_json:{},policy_version:policy?.version||'policy-not-active',model_policy_version:'cambra-model-router',calculation_version:AGGREGATE_ENGINE_VERSION,snapshot_json:snapPayload,snapshot_hash:hash,captured_at:now});rfp=await s.entities.AggregateRFP.create({rfp_key:`rfp:${pool.id}:${Date.now()}`,pool_id:pool.id,vertical:pool.vertical,status:'prepared',provider_ids:[],demand_snapshot_json:demand,requirements_json:{multi_provider_allowed:true,requested:['base_pricing','volume_tiers','fixed_fees','rebates','settlement','implementation','support','term','notice','price_review'],misrepresentation_guard:'observed/addressable/committed labels must be preserved'},authority_policy_key:policy?.policy_key||'',authority_policy_version:policy?.version||'',intelligence_snapshot_id:snap.id,created_at:now});await s.entities.AggregatePool.update(pool.id,{status:'rfp_preparing',active_rfp_id:rfp.id,updated_at:now});prepared++;}
  if(!policy){continue}
  let sendingProfile:any=null;for(const profileKey of policy.sending_profile_keys||[]){const rows=await s.entities.OutboundSendingProfile.filter({profile_key:profileKey},'-created_date',1).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:[],severity:'secondary'}));if(rows[0]?.provider==='outlook'&&sendingProfileIsValid(rows[0])){sendingProfile=rows[0];break}}if(!sendingProfile){skipped++;continue}
  const providers=await s.entities.Provider.filter({category:'payments'},'-strategic_importance',500).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:[],severity:'secondary'}));const pricing=await s.entities.ProviderPricingVersion.filter({vertical:'payments',knowledge_state:{$in:['active','verified','corroborated','observed']}},'-effective_at',3000).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:[],severity:'secondary'}));const eligible:any[]=[];
  for(const p of providers){const ps=slug(p.name);const matches=pricing.filter((x:any)=>slug(x.provider_slug)===ps&&(!x.country||!pool.country||String(x.country).toUpperCase()===String(pool.country).toUpperCase())&&(!x.currency||String(x.currency).toUpperCase()===String(pool.currency).toUpperCase())&&!x.is_demo);if(!matches.length)continue;const official=matches.some((x:any)=>x.truth_level==='verified_official');eligible.push({provider:p,score:(official?40:25)+Math.min(30,Number(p.strategic_importance||0)*.3)+Math.min(20,matches.length*2),pricing_ids:matches.slice(0,20).map((x:any)=>x.id)});}
  eligible.sort((a,b)=>b.score-a.score);const candidates=eligible.slice(0,4);if(!candidates.length){skipped++;continue}
  if(rfp.status==='prepared'){await s.entities.AggregateRFP.update(rfp.id,{status:'open',provider_ids:candidates.map(x=>x.provider.id),opened_at:now,authority_policy_key:policy.policy_key,authority_policy_version:policy.version});await s.entities.AggregatePool.update(pool.id,{status:'rfp_open'});opened++;}
  for(const c of candidates){const prior=(await s.entities.NegotiationCase.filter({aggregate_rfp_id:rfp.id,provider_id:c.provider.id},'-created_date',1).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:[],severity:'secondary'})))[0];if(prior)continue;const resolved=await s.functions.invoke('providerContactResolver',{provider_id:c.provider.id,internal_secret:internal}).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:null,severity:'secondary'}));const rd=resolved?.data||resolved||{};if(!rd?.ok||!rd?.contact?.email){skipped++;continue}
   const caseRow=await s.entities.NegotiationCase.create({recover_id:`aggregate:${pool.id}`,brand_id:'_platform',provider_id:c.provider.id,provider_name:c.provider.name,status:'ready',round:0,currency:pool.currency||'EUR',current_economics_json:{aggregate_pool:true},target_economics_json:{objective:'best_total_economic_value',request_dynamic_tiers:true},authority_snapshot_json:{policy_key:policy.policy_key,policy_version:policy.version,max_rounds:6,prohibited:['exclusivity','guaranteed_volume','minimum_spend','financial_liability','binding_contract_without_l4'],allowed:['request_pricing','counteroffer','request_dynamic_tiers','request_rebates','request_better_terms']},authority_hash:String(policy.version),strategy_json:{aggregate:true,competitive_process:true},unresolved_items:[],next_action:'aggregate_initial_rfp_contact',next_action_at:now,contract_match_status:'not_received',started_at:now,negotiation_scope:'aggregate',aggregate_pool_id:pool.id,aggregate_rfp_id:rfp.id,demand_snapshot_json:truthfulDemandSnapshot(pool),misrepresentation_guard_json:{observed_label_required:true,addressable_label_required:true,committed_claim_requires_explicit_commitment:Number(pool.committed_annual_volume_minor||0)>0,committed_volume_minor:Number(pool.committed_annual_volume_minor||0)},intelligence_snapshot_id:rfp.intelligence_snapshot_id});
   const thread=await s.entities.CommunicationThread.create({thread_key:`aggregate:${rfp.id}:${c.provider.id}`,engine:'aggregate_procurement',related_entity_type:'NegotiationCase',related_entity_id:caseRow.id,provider_id:c.provider.id,counterparty_email:rd.contact.email,counterparty_name:rd.contact.name||c.provider.name,language:'en',status:'open',policy_key:policy.policy_key,policy_version:policy.version,automation_paused:false,summary:`CAMBRA Aggregate RFP · ${pool.pool_key} · ${c.provider.name}`,sending_profile_key:sendingProfile.profile_key});await s.entities.NegotiationCase.update(caseRow.id,{thread_id:thread.id});casesCreated++;
   const sent=await s.functions.invoke('collectiveNegotiationAgent',{action:'initial_contact',case_id:caseRow.id,internal_secret:internal}).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:null,severity:'secondary'}));const sd=sent?.data||sent||{};if(sd?.ok)contacted++;
  }
  await s.entities.AggregateRFP.update(rfp.id,{status:'negotiating'}).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:null,severity:'secondary'}));await s.entities.AggregatePool.update(pool.id,{status:'negotiating'}).catch((error:any)=>safeBestEffort(error,{operation:'aggregateProcurementWorker',fallback:null,severity:'secondary'}));
 }
 return Response.json({ok:true,pools:pools.length,policy_active:!!policy,prepared,opened,cases_created:casesCreated,provider_contacts_sent:contacted,skipped,note:policy?'Autonomous procurement ran inside active aggregate_procurement policy.':'Pools/RFPs may be prepared, but no provider communication occurs without an active founder-approved aggregate_procurement policy.'});
}catch(e){console.error(e);return Response.json({ok:false,error:'aggregate_procurement_worker_failed'},{status:500})}});
