import{createClientFromRequest}from'npm:@base44/sdk@0.8.41';
const now=()=>new Date().toISOString();
const CONFIRM_ON='ACTIVATE_CAMBRA_SAFE_MODE',CONFIRM_OFF='RESTORE_CAMBRA_AUTONOMY';
async function getOrCreate(s:any){const rows=await s.entities.EmergencyControl.filter({control_key:'global'},'-updated_at',1).catch(()=>[]);if(rows[0])return rows[0];return s.entities.EmergencyControl.create({control_key:'global',safe_mode:false,communications_paused:false,negotiations_paused:false,migrations_paused:false,billing_issuance_paused:false,reason:'',updated_at:now(),updated_by:'system'})}
Deno.serve(async req=>{try{const b=createClientFromRequest(req),u=await b.auth.me().catch(()=>null);if(!u||u.role!=='admin')return Response.json({ok:false,error:'Forbidden'},{status:403});const body=await req.json().catch(()=>({})),action=String(body.action||'status'),s=b.asServiceRole,row=await getOrCreate(s);if(action==='status')return Response.json({ok:true,control:row,semantics:{safe_mode:'Pauses new external communications, negotiations, migrations and new billing issuance. Monitoring, reconciliation, evidence and already-earned obligations continue.',billing:'Only NEW invoice issuance is paused. Reconciliation and payment-state observation remain active.',routing:'Real payment routing is already disabled elsewhere and is unaffected.'}});
 const reason=String(body.reason||'founder emergency control').slice(0,500),at=now(),by=String(u.email||u.id||'admin');let patch:any={updated_at:at,updated_by:by,reason};
 if(action==='safe_mode_on'){if(body.confirmation!==CONFIRM_ON)return Response.json({ok:false,error:'confirmation_required',required:CONFIRM_ON},{status:409});patch={...patch,safe_mode:true,communications_paused:true,negotiations_paused:true,migrations_paused:true,billing_issuance_paused:true,activated_at:at,previous_state_json:{safe_mode:row.safe_mode,communications_paused:row.communications_paused,negotiations_paused:row.negotiations_paused,migrations_paused:row.migrations_paused,billing_issuance_paused:row.billing_issuance_paused}};}
 else if(action==='safe_mode_off'){if(body.confirmation!==CONFIRM_OFF)return Response.json({ok:false,error:'confirmation_required',required:CONFIRM_OFF},{status:409});const p=row.previous_state_json||{};patch={...patch,safe_mode:false,communications_paused:p.communications_paused===true,negotiations_paused:p.negotiations_paused===true,migrations_paused:p.migrations_paused===true,billing_issuance_paused:p.billing_issuance_paused===true};}
 else if(['pause_communications','resume_communications','pause_negotiations','resume_negotiations','pause_migrations','resume_migrations','pause_billing_issuance','resume_billing_issuance'].includes(action)){const map:any={pause_communications:['communications_paused',true],resume_communications:['communications_paused',false],pause_negotiations:['negotiations_paused',true],resume_negotiations:['negotiations_paused',false],pause_migrations:['migrations_paused',true],resume_migrations:['migrations_paused',false],pause_billing_issuance:['billing_issuance_paused',true],resume_billing_issuance:['billing_issuance_paused',false]};const[k,v]=map[action];patch[k]=v;if(action.startsWith('resume_')&&row.safe_mode)return Response.json({ok:false,error:'safe_mode_active_restore_safe_mode_first'},{status:409});}
 else return Response.json({ok:false,error:'unsupported_action'},{status:400});
 const updated=await s.entities.EmergencyControl.update(row.id,patch);if(action==='safe_mode_on'){const oc=(await s.entities.OutboundControl.filter({control_key:'global'},'-created_date',1).catch(()=>[]))[0];if(oc)await s.entities.OutboundControl.update(oc.id,{acquisition_enabled:false,premium_outlook_enabled:false,volume_resend_enabled:false,paused_reason:'p18_safe_mode'}).catch(()=>null);const policies=await s.entities.CommercialPolicy.filter({status:'active'},'-approved_at',200).catch(()=>[]);for(const p of policies)await s.entities.CommercialPolicy.update(p.id,{status:'paused'}).catch(()=>null);}
 await s.entities.OperationalLog.create({event_type:'emergency_control_changed',message:action,data_json:{action,reason,control_id:row.id,safe_mode:updated.safe_mode,communications_paused:updated.communications_paused,negotiations_paused:updated.negotiations_paused,migrations_paused:updated.migrations_paused,billing_issuance_paused:updated.billing_issuance_paused},actor_email:by,created_at:at}).catch(()=>null);return Response.json({ok:true,action,control:updated})}catch(e){console.error(e);return Response.json({ok:false,error:'emergency_control_failed',message:String((e as Error)?.message||e).slice(0,300)},{status:500})}});
