import { CreditCard, Truck, Package, Shield, Building2, Warehouse } from "lucide-react";

export const DEALS = [
  {
    id: "payments-stripe",
    category: "payments",
    icon: CreditCard,
    provider: "Stripe",
    title: "Network Payment Rate",
    headline: "1.4% effective rate",
    normal_rate: "2.9% + €0.25",
    node_rate: "1.4% + €0.10",
    estimated_savings: 8400,
    saving_note: "Based on €500K/yr GMV",
    desc: "THE NoDE has negotiated enterprise-level Stripe processing fees on behalf of the collective. Available immediately to all members upon activation.",
    tags: ["Live", "Payments"],
    phase: "live",
    region: ["EU", "Global"],
    activation: "Connect your Stripe account and THE NoDE will automatically apply negotiated rates to your account within 5 business days.",
    steps: ["Click Activate Deal", "Connect your Stripe account", "Network rates applied within 5 days"],
  },
  {
    id: "payments-adyen",
    category: "payments",
    icon: CreditCard,
    provider: "Adyen",
    title: "Adyen Volume Discount",
    headline: "Up to 0.9% processing",
    normal_rate: "Interchange + 0.3%",
    node_rate: "Interchange + 0.08%",
    estimated_savings: 12000,
    saving_note: "Based on €1M/yr GMV",
    desc: "Adyen's enterprise interchange++ pricing, unlocked for THE NoDE members processing above €100K/month.",
    tags: ["Live", "Payments", "Enterprise"],
    phase: "live",
    region: ["EU", "Global"],
    activation: "Submit your Adyen MID and THE NoDE will negotiate updated pricing on your behalf.",
    steps: ["Click Activate Deal", "Submit your Adyen MID", "Negotiation completed within 10 days"],
  },
  {
    id: "shipping-dhl",
    category: "shipping",
    icon: Truck,
    provider: "DHL Express",
    title: "DHL Network Contract",
    headline: "−18% on all shipments",
    normal_rate: "Standard retail",
    node_rate: "−18% collective discount",
    estimated_savings: 5200,
    saving_note: "Based on 400 shipments/mo",
    desc: "Collective volume across the network unlocks DHL business account pricing normally reserved for brands shipping 10,000+ parcels per month.",
    tags: ["Live", "Shipping"],
    phase: "live",
    region: ["EU", "Global"],
    activation: "Link your DHL account number and we'll migrate it to the network contract within 3 business days.",
    steps: ["Click Activate Deal", "Provide your DHL account number", "Network pricing applied within 3 days"],
  },
  {
    id: "shipping-dpd",
    category: "shipping",
    icon: Truck,
    provider: "DPD",
    title: "DPD Pan-European Rate",
    headline: "−15% pan-EU parcels",
    normal_rate: "Standard B2C rate",
    node_rate: "−15% on all zones",
    estimated_savings: 3800,
    saving_note: "Based on 300 shipments/mo",
    desc: "THE NoDE's DPD network contract covers all 35+ European countries. Ideal for brands scaling cross-border.",
    tags: ["Live", "Shipping", "EU"],
    phase: "live",
    region: ["EU", "Eurozone"],
    activation: "Activate to connect your DPD account to the network master contract.",
    steps: ["Click Activate Deal", "Provide your DPD depot code", "Migration completed within 5 days"],
  },
  {
    id: "saas-klaviyo",
    category: "saas",
    icon: Package,
    provider: "Klaviyo",
    title: "Klaviyo Group License",
    headline: "30% off any plan",
    normal_rate: "Standard pricing",
    node_rate: "30% perpetual discount",
    estimated_savings: 2160,
    saving_note: "Based on 50K contacts plan",
    desc: "Group licensing agreement with Klaviyo delivers a 30% perpetual discount on all plans — no cap on contacts tier.",
    tags: ["Soon", "SaaS", "Email"],
    phase: "soon",
    region: ["EU", "Global"],
    activation: "Join the waitlist and you'll be activated when the group contract launches in Q2 2026.",
    steps: ["Join the waitlist", "Get notified when live", "Switch billing to group contract"],
  },
  {
    id: "saas-shopify",
    category: "saas",
    icon: Package,
    provider: "Shopify",
    title: "Shopify Plus Network",
    headline: "€500/mo off Plus",
    normal_rate: "€2,000/mo",
    node_rate: "€1,500/mo",
    estimated_savings: 6000,
    saving_note: "Per brand on Shopify Plus",
    desc: "Group agreement with Shopify negotiated for brands already on Plus, or brands migrating to Plus through THE NoDE.",
    tags: ["Soon", "SaaS", "Platform"],
    phase: "soon",
    region: ["EU", "Global"],
    activation: "Express interest and we'll include you in the group contract negotiation.",
    steps: ["Express interest", "We negotiate on your behalf", "Receive updated contract"],
  },
  {
    id: "insurance",
    category: "insurance",
    icon: Shield,
    provider: "AXA / Specialist",
    title: "Group Business Insurance",
    headline: "−25% on premiums",
    normal_rate: "Individual underwriting",
    node_rate: "Group risk pool",
    estimated_savings: 4000,
    saving_note: "Based on typical SME cover",
    desc: "THE NoDE is building a group insurance product for independent brands — covering product liability, D&O, and e-commerce specific risk.",
    tags: ["Planned", "Insurance"],
    phase: "planned",
    region: ["EU", "Eurozone"],
    activation: "Register interest to join the founding group for the insurance product.",
    steps: ["Register interest", "Provide cover requirements", "Receive group quote in Q4 2026"],
  },
  {
    id: "banking",
    category: "banking",
    icon: Building2,
    provider: "Pan-European Bank",
    title: "Business Banking Bundle",
    headline: "Zero FX + credit lines",
    normal_rate: "Retail bank rates",
    node_rate: "Zero-fee FX + group credit",
    estimated_savings: 3500,
    saving_note: "FX savings for EU cross-border",
    desc: "A dedicated business banking product built for THE NoDE — zero-fee FX, instant IBAN, and group credit facilities for inventory and growth.",
    tags: ["Planned", "Banking"],
    phase: "planned",
    region: ["EU", "Eurozone"],
    activation: "Join the waitlist. Banking product launches 2027.",
    steps: ["Join the waitlist", "KYB process", "Account activated 2027"],
  },
  {
    id: "warehousing",
    category: "logistics",
    icon: Warehouse,
    provider: "Network 3PL",
    title: "Shared Fulfillment Network",
    headline: "From €2.50/fulfillment",
    normal_rate: "€4–6 per fulfillment",
    node_rate: "From €2.50 shared network",
    estimated_savings: 18000,
    saving_note: "Based on 500 orders/mo",
    desc: "Distributed fulfillment centers across Europe, shared across the network. Pick, pack, ship — at wholesale cost.",
    tags: ["Planned", "Logistics"],
    phase: "planned",
    region: ["EU"],
    activation: "Join the waitlist for when the first fulfillment nodes launch.",
    steps: ["Join the waitlist", "Onboarding call", "Go live in network node"],
  },
];

export const PHASE_CONFIG = {
  live: { label: "Live", dot: "bg-green-500", badge: "bg-green-500/10 text-green-600 border-green-500/20" },
  soon: { label: "Q2 2026", dot: "bg-blue-500", badge: "bg-blue-500/10 text-blue-600 border-blue-500/20" },
  planned: { label: "Planned", dot: "bg-border", badge: "bg-secondary text-muted-foreground/60 border-border/50" },
};

export const STATUS_CONFIG = {
  waitlist: { label: "Waitlist", color: "text-blue-600", bg: "bg-blue-500/8 border-blue-500/20" },
  pending: { label: "Pending", color: "text-orange-500", bg: "bg-orange-500/8 border-orange-500/20" },
  active: { label: "Active", color: "text-green-600", bg: "bg-green-500/8 border-green-500/20" },
  expired: { label: "Expired", color: "text-muted-foreground", bg: "bg-secondary border-border/40" },
};

export const CATEGORIES = [
  { id: "all", label: "All Deals" },
  { id: "payments", label: "Payments" },
  { id: "shipping", label: "Shipping" },
  { id: "saas", label: "SaaS" },
  { id: "insurance", label: "Insurance" },
  { id: "banking", label: "Banking" },
  { id: "logistics", label: "Logistics" },
];

export const REGIONS = [
  { id: "all", label: "All Regions" },
  { id: "EU", label: "EU" },
  { id: "Eurozone", label: "Eurozone" },
  { id: "Global", label: "Global" },
];

export function getDealById(id) {
  return DEALS.find(d => d.id === id);
}

export function formatSavings(amount) {
  if (!amount) return "€0";
  if (amount >= 1000) return `€${(amount / 1000).toFixed(1)}K`;
  return `€${amount.toLocaleString()}`;
}