import { CreditCard, Truck, Package, Shield, Building2, Warehouse } from "lucide-react";

// mode: "negotiated" = complex contract flow | "instant" = lightweight access flow
// mode is INTERNAL ONLY — never exposed in UI copy
export const DEALS = [
  {
    id: "payments-stripe",
    category: "payments",
    mode: "negotiated",
    icon: CreditCard,
    provider: "Stripe",
    title: "Network Payment Rate",
    headline: "Access preferred payment conditions",
    advantage: "Up to 52% better processing fees",
    normal_rate: "2.9% + €0.25",
    node_rate: "1.4% + €0.10",
    estimated_savings: 8400,
    saving_note: "Based on €500K/yr GMV",
    desc: "THE NoDE has secured enterprise-level payment terms with Stripe on behalf of the collective. Members access conditions normally reserved for platforms processing €50M+ annually.",
    phase: "live",
    region: ["EU", "Global"],
    acceptance_items: [
      "I authorise THE NoDE to submit my Stripe MID for rate renegotiation",
      "I understand that the new rate applies within 5 business days of acceptance",
      "I confirm this brand is registered and operates within the EU or EEA",
    ],
    action_label: "Request optimised terms",
    action_note: "THE NoDE submits the request to Stripe on your behalf. You'll receive confirmation by email.",
  },
  {
    id: "payments-adyen",
    category: "payments",
    mode: "negotiated",
    icon: CreditCard,
    provider: "Adyen",
    title: "Adyen Enterprise Conditions",
    headline: "Preferred interchange++ pricing",
    advantage: "Conditions available only above €50M volume — unlocked collectively",
    normal_rate: "Interchange + 0.3%",
    node_rate: "Interchange + 0.08%",
    estimated_savings: 12000,
    saving_note: "Based on €1M/yr GMV",
    desc: "Adyen's enterprise interchange++ model is unlocked for all THE NoDE members, regardless of individual volume. Collective scale does the negotiating.",
    phase: "live",
    region: ["EU", "Global"],
    acceptance_items: [
      "I authorise THE NoDE to submit my Adyen Merchant ID for rate review",
      "I understand renegotiation is completed within 10 business days",
      "I confirm processing volume above €100K/month",
    ],
    action_label: "Request optimised terms",
    action_note: "THE NoDE submits your Adyen MID and negotiates updated pricing on your behalf.",
  },
  {
    id: "shipping-dhl",
    category: "shipping",
    mode: "negotiated",
    icon: Truck,
    provider: "DHL Express",
    title: "DHL Network Contract",
    headline: "Preferred carrier conditions",
    advantage: "−18% on all shipments via collective volume",
    normal_rate: "Standard retail rate",
    node_rate: "−18% collective discount",
    estimated_savings: 5200,
    saving_note: "Based on 400 shipments/mo",
    desc: "Collective shipment volume across THE NoDE unlocks DHL business account pricing normally reserved for brands shipping 10,000+ parcels/month. You access enterprise rates regardless of your individual volume.",
    phase: "live",
    region: ["EU", "Global"],
    acceptance_items: [
      "I authorise migration of my DHL account to the THE NoDE master contract",
      "I understand my existing DHL account number will be preserved",
      "I confirm this account is active and in good standing",
    ],
    action_label: "Request optimised terms",
    action_note: "Migration to network contract is completed within 3 business days. No service interruption.",
  },
  {
    id: "shipping-dpd",
    category: "shipping",
    mode: "negotiated",
    icon: Truck,
    provider: "DPD",
    title: "DPD Pan-European Conditions",
    headline: "Preferred pan-EU parcel rates",
    advantage: "−15% across all 35+ European zones",
    normal_rate: "Standard B2C rate",
    node_rate: "−15% on all zones",
    estimated_savings: 3800,
    saving_note: "Based on 300 shipments/mo",
    desc: "THE NoDE's DPD network contract provides preferential rates across the full European zone — ideal for brands scaling cross-border without enterprise volume.",
    phase: "live",
    region: ["EU", "Eurozone"],
    acceptance_items: [
      "I authorise THE NoDE to migrate my DPD account to the network master contract",
      "I understand that the new rates apply within 5 business days",
      "I confirm this account operates within the EU",
    ],
    action_label: "Request optimised terms",
    action_note: "Your DPD account will be moved to the network master contract. Rates apply automatically.",
  },
  {
    id: "saas-klaviyo",
    category: "saas",
    mode: "instant",
    icon: Package,
    provider: "Klaviyo",
    title: "Klaviyo Preferred Pricing",
    headline: "Access preferred Klaviyo conditions",
    advantage: "Up to 30% better pricing — perpetual, all plans",
    normal_rate: "Standard pricing",
    node_rate: "30% perpetual reduction",
    estimated_savings: 2160,
    saving_note: "Based on 50K contacts plan",
    desc: "Group licensing through THE NoDE delivers a 30% perpetual reduction on all Klaviyo plans. No cap on contacts tier. Available to all members once the contract launches.",
    phase: "soon",
    region: ["EU", "Global"],
    acceptance_items: [],
    action_label: "Join the access list",
    action_note: "You'll be automatically activated when the group contract launches in Q2 2026.",
  },
  {
    id: "saas-shopify",
    category: "saas",
    mode: "instant",
    icon: Package,
    provider: "Shopify",
    title: "Shopify Plus Network Terms",
    headline: "Access preferred Shopify conditions",
    advantage: "€500/mo better terms on Shopify Plus",
    normal_rate: "€2,000/mo",
    node_rate: "€1,500/mo",
    estimated_savings: 6000,
    saving_note: "Per brand on Shopify Plus",
    desc: "THE NoDE is finalising a group agreement with Shopify for members on Plus — or migrating to Plus. Preferred conditions negotiated at collective scale.",
    phase: "soon",
    region: ["EU", "Global"],
    acceptance_items: [],
    action_label: "Join the access list",
    action_note: "Express interest and we'll include you in the group contract negotiation.",
  },
  {
    id: "insurance",
    category: "insurance",
    mode: "negotiated",
    icon: Shield,
    provider: "AXA / Specialist",
    title: "Group Business Insurance",
    headline: "Preferred insurance conditions",
    advantage: "Up to 25% better premiums via collective risk pool",
    normal_rate: "Individual underwriting",
    node_rate: "Group risk pool pricing",
    estimated_savings: 4000,
    saving_note: "Based on typical SME cover",
    desc: "THE NoDE is building a group insurance product for independent brands — product liability, D&O, and e-commerce specific risk, underwritten collectively.",
    phase: "planned",
    region: ["EU", "Eurozone"],
    acceptance_items: [],
    action_label: "Register interest",
    action_note: "Register your interest to join the founding group. Group quote available in Q4 2026.",
  },
  {
    id: "banking",
    category: "banking",
    mode: "negotiated",
    icon: Building2,
    provider: "Pan-European Bank",
    title: "Business Banking Bundle",
    headline: "Preferred banking conditions",
    advantage: "Zero-fee FX and group credit facilities",
    normal_rate: "Retail bank rates",
    node_rate: "Zero-fee FX + group credit",
    estimated_savings: 3500,
    saving_note: "FX savings for EU cross-border",
    desc: "A dedicated business banking product for THE NoDE — zero-fee FX, instant IBAN, and group credit for inventory and growth. Built exclusively for network members.",
    phase: "planned",
    region: ["EU", "Eurozone"],
    acceptance_items: [],
    action_label: "Join the access list",
    action_note: "Banking product launches 2027. Founding members get priority onboarding.",
  },
  {
    id: "warehousing",
    category: "logistics",
    mode: "negotiated",
    icon: Warehouse,
    provider: "Network 3PL",
    title: "Shared Fulfillment Network",
    headline: "Preferred fulfillment conditions",
    advantage: "From €2.50/fulfillment — wholesale infrastructure cost",
    normal_rate: "€4–6 per fulfillment",
    node_rate: "From €2.50 shared network",
    estimated_savings: 18000,
    saving_note: "Based on 500 orders/mo",
    desc: "Distributed fulfillment across Europe, shared across the network. Pick, pack, ship at wholesale cost — without building your own logistics.",
    phase: "planned",
    region: ["EU"],
    acceptance_items: [],
    action_label: "Join the access list",
    action_note: "Join the waitlist for when the first fulfillment nodes launch.",
  },
];

export const PHASE_CONFIG = {
  live: { label: "Live", dot: "bg-green-500", badge: "bg-green-500/10 text-green-600 border-green-500/20" },
  soon: { label: "Q2 2026", dot: "bg-blue-500", badge: "bg-blue-500/10 text-blue-600 border-blue-500/20" },
  planned: { label: "Planned", dot: "bg-border", badge: "bg-secondary text-muted-foreground/60 border-border/50" },
};

export const STATUS_CONFIG = {
  waitlist: { label: "Waitlist", color: "text-blue-600", bg: "bg-blue-500/8 border-blue-500/20" },
  pending: { label: "Pending", color: "text-orange-500", bg: "bg-orange-500/8 border-orange-500/20" },
  active: { label: "Active", color: "text-green-600", bg: "bg-green-500/8 border-green-500/20" },
  expired: { label: "Expired", color: "text-muted-foreground", bg: "bg-secondary border-border/40" },
};

export const CATEGORIES = [
  { id: "all", label: "All Deals" },
  { id: "payments", label: "Payments" },
  { id: "shipping", label: "Shipping" },
  { id: "saas", label: "SaaS" },
  { id: "insurance", label: "Insurance" },
  { id: "banking", label: "Banking" },
  { id: "logistics", label: "Logistics" },
];

export const REGIONS = [
  { id: "all", label: "All Regions" },
  { id: "EU", label: "EU" },
  { id: "Eurozone", label: "Eurozone" },
  { id: "Global", label: "Global" },
];

export function getDealById(id) {
  return DEALS.find(d => d.id === id);
}

export function formatSavings(amount) {
  if (!amount) return "€0";
  if (amount >= 1000) return `€${(amount / 1000).toFixed(1)}K`;
  return `€${amount.toLocaleString()}`;
}