import { EUROPE_MARKETS } from './generated/europeMarkets.js';

const split=(value)=>String(value||'').split('|').map(item=>item.trim()).filter(Boolean);
const options=(value)=>split(value).map(label=>({value:label.toLowerCase().replaceAll(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''),label}));

// Canonical launch geography: EU-27 + NO/IS/LI + CH/GB/AD. Regions are the
// first-level administrative/commercial regions used by CAMBRA. The picker also
// accepts any additional city/region, so a valid location is never blocked by
// the curated quick-pick catalogue.
export const DISCOVERY_GEOGRAPHY=Object.freeze({
  AT:{regions:split('Burgenland|Carinthia|Lower Austria|Upper Austria|Salzburg|Styria|Tyrol|Vorarlberg|Vienna'),cities:split('Vienna|Graz|Linz|Salzburg|Innsbruck|Klagenfurt|Villach|Wels|Sankt Pölten')},
  BE:{regions:split('Brussels-Capital|Flanders|Wallonia|Antwerp|East Flanders|Flemish Brabant|Hainaut|Liège|Limburg|Luxembourg|Namur|Walloon Brabant|West Flanders'),cities:split('Brussels|Antwerp|Ghent|Charleroi|Liège|Bruges|Leuven|Namur|Mons|Mechelen')},
  BG:{regions:split('Blagoevgrad|Burgas|Dobrich|Gabrovo|Haskovo|Kardzhali|Kyustendil|Lovech|Montana|Pazardzhik|Pernik|Pleven|Plovdiv|Razgrad|Ruse|Shumen|Silistra|Sliven|Smolyan|Sofia City|Sofia Province|Stara Zagora|Targovishte|Varna|Veliko Tarnovo|Vidin|Vratsa|Yambol'),cities:split('Sofia|Plovdiv|Varna|Burgas|Ruse|Stara Zagora|Pleven|Sliven|Dobrich|Shumen')},
  HR:{regions:split('Bjelovar-Bilogora|Brod-Posavina|Dubrovnik-Neretva|Istria|Karlovac|Koprivnica-Križevci|Krapina-Zagorje|Lika-Senj|Međimurje|Osijek-Baranja|Požega-Slavonia|Primorje-Gorski Kotar|Šibenik-Knin|Sisak-Moslavina|Split-Dalmatia|Varaždin|Virovitica-Podravina|Vukovar-Syrmia|Zadar|Zagreb County|City of Zagreb'),cities:split('Zagreb|Split|Rijeka|Osijek|Zadar|Pula|Slavonski Brod|Karlovac|Varaždin|Dubrovnik')},
  CY:{regions:split('Famagusta|Kyrenia|Larnaca|Limassol|Nicosia|Paphos'),cities:split('Nicosia|Limassol|Larnaca|Paphos|Famagusta|Kyrenia')},
  CZ:{regions:split('Prague|Central Bohemia|South Bohemia|Plzeň|Karlovy Vary|Ústí nad Labem|Liberec|Hradec Králové|Pardubice|Vysočina|South Moravia|Olomouc|Zlín|Moravian-Silesian'),cities:split('Prague|Brno|Ostrava|Plzeň|Liberec|Olomouc|České Budějovice|Hradec Králové|Pardubice|Zlín')},
  DK:{regions:split('Capital Region|Central Denmark|North Denmark|Region Zealand|Southern Denmark'),cities:split('Copenhagen|Aarhus|Odense|Aalborg|Esbjerg|Randers|Kolding|Horsens|Roskilde|Vejle')},
  EE:{regions:split('Harju|Hiiu|Ida-Viru|Jõgeva|Järva|Lääne|Lääne-Viru|Põlva|Pärnu|Rapla|Saare|Tartu|Valga|Viljandi|Võru'),cities:split('Tallinn|Tartu|Narva|Pärnu|Kohtla-Järve|Viljandi|Rakvere|Maardu|Kuressaare|Võru')},
  FI:{regions:split('Åland|Central Finland|Central Ostrobothnia|Kainuu|Kanta-Häme|Kymenlaakso|Lapland|North Karelia|North Ostrobothnia|North Savo|Ostrobothnia|Päijät-Häme|Pirkanmaa|Satakunta|South Karelia|South Ostrobothnia|South Savo|Southwest Finland|Uusimaa'),cities:split('Helsinki|Espoo|Tampere|Vantaa|Oulu|Turku|Jyväskylä|Kuopio|Lahti|Pori|Vaasa|Rovaniemi')},
  FR:{regions:split('Auvergne-Rhône-Alpes|Bourgogne-Franche-Comté|Brittany|Centre-Val de Loire|Corsica|Grand Est|Hauts-de-France|Île-de-France|Normandy|Nouvelle-Aquitaine|Occitanie|Pays de la Loire|Provence-Alpes-Côte d’Azur|Guadeloupe|Martinique|French Guiana|Réunion|Mayotte'),cities:split('Paris|Marseille|Lyon|Toulouse|Nice|Nantes|Montpellier|Strasbourg|Bordeaux|Lille|Rennes|Reims|Le Havre|Saint-Étienne|Toulon|Grenoble|Dijon|Angers|Nîmes|Clermont-Ferrand')},
  DE:{regions:split('Baden-Württemberg|Bavaria|Berlin|Brandenburg|Bremen|Hamburg|Hesse|Lower Saxony|Mecklenburg-Vorpommern|North Rhine-Westphalia|Rhineland-Palatinate|Saarland|Saxony|Saxony-Anhalt|Schleswig-Holstein|Thuringia'),cities:split('Berlin|Hamburg|Munich|Cologne|Frankfurt|Stuttgart|Düsseldorf|Leipzig|Dortmund|Essen|Bremen|Dresden|Hanover|Nuremberg|Duisburg|Bochum|Wuppertal|Bielefeld|Bonn|Münster')},
  GR:{regions:split('Attica|Central Greece|Central Macedonia|Crete|East Macedonia and Thrace|Epirus|Ionian Islands|North Aegean|Peloponnese|South Aegean|Thessaly|West Greece|West Macedonia'),cities:split('Athens|Thessaloniki|Patras|Piraeus|Larissa|Heraklion|Peristeri|Kallithea|Acharnes|Kalamaria')},
  HU:{regions:split('Budapest|Bács-Kiskun|Baranya|Békés|Borsod-Abaúj-Zemplén|Csongrád-Csanád|Fejér|Győr-Moson-Sopron|Hajdú-Bihar|Heves|Jász-Nagykun-Szolnok|Komárom-Esztergom|Nógrád|Pest|Somogy|Szabolcs-Szatmár-Bereg|Tolna|Vas|Veszprém|Zala'),cities:split('Budapest|Debrecen|Szeged|Miskolc|Pécs|Győr|Nyíregyháza|Kecskemét|Székesfehérvár|Szombathely')},
  IE:{regions:split('Carlow|Cavan|Clare|Cork|Donegal|Dublin|Galway|Kerry|Kildare|Kilkenny|Laois|Leitrim|Limerick|Longford|Louth|Mayo|Meath|Monaghan|Offaly|Roscommon|Sligo|Tipperary|Waterford|Westmeath|Wexford|Wicklow'),cities:split('Dublin|Cork|Limerick|Galway|Waterford|Drogheda|Dundalk|Swords|Bray|Kilkenny')},
  IT:{regions:split('Abruzzo|Aosta Valley|Apulia|Basilicata|Calabria|Campania|Emilia-Romagna|Friuli Venezia Giulia|Lazio|Liguria|Lombardy|Marche|Molise|Piedmont|Sardinia|Sicily|Trentino-Alto Adige|Tuscany|Umbria|Veneto'),cities:split('Rome|Milan|Naples|Turin|Palermo|Genoa|Bologna|Florence|Bari|Catania|Venice|Verona|Messina|Padua|Trieste|Brescia|Parma|Prato|Modena|Reggio Calabria')},
  LV:{regions:split('Kurzeme|Latgale|Riga|Vidzeme|Zemgale'),cities:split('Riga|Daugavpils|Liepāja|Jelgava|Jūrmala|Ventspils|Rēzekne|Valmiera|Jēkabpils|Ogre')},
  LT:{regions:split('Alytus|Kaunas|Klaipėda|Marijampolė|Panevėžys|Šiauliai|Tauragė|Telšiai|Utena|Vilnius'),cities:split('Vilnius|Kaunas|Klaipėda|Šiauliai|Panevėžys|Alytus|Marijampolė|Mažeikiai|Jonava|Utena')},
  LU:{regions:split('Capellen|Clervaux|Diekirch|Echternach|Esch-sur-Alzette|Grevenmacher|Luxembourg|Mersch|Redange|Remich|Vianden|Wiltz'),cities:split('Luxembourg City|Esch-sur-Alzette|Differdange|Dudelange|Ettelbruck|Diekirch|Wiltz|Echternach|Rumelange|Grevenmacher')},
  MT:{regions:split('Central Region|Gozo Region|Northern Region|Port Region|South Eastern Region|Southern Region'),cities:split('Valletta|Birkirkara|Mosta|Qormi|Sliema|St Julian’s|Rabat|Victoria|Mellieħa|Żabbar')},
  NL:{regions:split('Drenthe|Flevoland|Friesland|Gelderland|Groningen|Limburg|North Brabant|North Holland|Overijssel|South Holland|Utrecht|Zeeland'),cities:split('Amsterdam|Rotterdam|The Hague|Utrecht|Eindhoven|Groningen|Tilburg|Almere|Breda|Nijmegen|Enschede|Haarlem|Arnhem|Amersfoort|Apeldoorn')},
  PL:{regions:split('Lower Silesia|Kuyavia-Pomerania|Lublin|Lubusz|Łódź|Lesser Poland|Masovia|Opole|Podkarpackie|Podlaskie|Pomerania|Silesia|Świętokrzyskie|Warmia-Masuria|Greater Poland|West Pomerania'),cities:split('Warsaw|Kraków|Wrocław|Łódź|Poznań|Gdańsk|Szczecin|Bydgoszcz|Lublin|Białystok|Katowice|Gdynia|Częstochowa|Rzeszów|Toruń')},
  PT:{regions:split('Aveiro|Beja|Braga|Bragança|Castelo Branco|Coimbra|Évora|Faro|Guarda|Leiria|Lisbon|Portalegre|Porto|Santarém|Setúbal|Viana do Castelo|Vila Real|Viseu|Azores|Madeira'),cities:split('Lisbon|Porto|Vila Nova de Gaia|Amadora|Braga|Coimbra|Funchal|Setúbal|Aveiro|Faro|Leiria|Évora|Viseu')},
  RO:{regions:split('Alba|Arad|Argeș|Bacău|Bihor|Bistrița-Năsăud|Botoșani|Brașov|Brăila|Bucharest|Buzău|Caraș-Severin|Călărași|Cluj|Constanța|Covasna|Dâmbovița|Dolj|Galați|Giurgiu|Gorj|Harghita|Hunedoara|Ialomița|Iași|Ilfov|Maramureș|Mehedinți|Mureș|Neamț|Olt|Prahova|Sălaj|Satu Mare|Sibiu|Suceava|Teleorman|Timiș|Tulcea|Vâlcea|Vaslui|Vrancea'),cities:split('Bucharest|Cluj-Napoca|Iași|Constanța|Timișoara|Brașov|Craiova|Galați|Oradea|Ploiești|Brăila|Arad|Pitești|Sibiu|Bacău')},
  SK:{regions:split('Banská Bystrica|Bratislava|Košice|Nitra|Prešov|Trenčín|Trnava|Žilina'),cities:split('Bratislava|Košice|Prešov|Žilina|Banská Bystrica|Nitra|Trnava|Trenčín|Martin|Poprad')},
  SI:{regions:split('Central Slovenia|Drava|Mura|Carinthia|Savinja|Central Sava|Lower Sava|Southeast Slovenia|Littoral-Inner Carniola|Coastal-Karst|Gorizia|Upper Carniola'),cities:split('Ljubljana|Maribor|Kranj|Koper|Celje|Novo Mesto|Velenje|Nova Gorica|Ptuj|Murska Sobota')},
  ES:{regions:split('Andalusia|Aragon|Asturias|Balearic Islands|Basque Country|Canary Islands|Cantabria|Castile and León|Castilla-La Mancha|Catalonia|Extremadura|Galicia|La Rioja|Madrid|Murcia|Navarre|Valencian Community|Ceuta|Melilla'),cities:split('Madrid|Barcelona|Valencia|Seville|Zaragoza|Málaga|Murcia|Palma|Las Palmas de Gran Canaria|Bilbao|Alicante|Córdoba|Valladolid|Vigo|Gijón|A Coruña|Granada|Vitoria-Gasteiz|Elche|Oviedo')},
  SE:{regions:split('Blekinge|Dalarna|Gävleborg|Gotland|Halland|Jämtland|Jönköping|Kalmar|Kronoberg|Norrbotten|Örebro|Östergötland|Skåne|Södermanland|Stockholm|Uppsala|Värmland|Västerbotten|Västernorrland|Västmanland|Västra Götaland'),cities:split('Stockholm|Gothenburg|Malmö|Uppsala|Västerås|Örebro|Linköping|Helsingborg|Jönköping|Norrköping|Lund|Umeå')},
  NO:{regions:split('Agder|Akershus|Buskerud|Finnmark|Innlandet|Møre og Romsdal|Nordland|Oslo|Rogaland|Telemark|Troms|Trøndelag|Vestfold|Vestland|Østfold'),cities:split('Oslo|Bergen|Trondheim|Stavanger|Drammen|Fredrikstad|Kristiansand|Sandnes|Tromsø|Sarpsborg|Skien|Ålesund')},
  IS:{regions:split('Capital Region|Southern Peninsula|Western Region|Westfjords|Northwestern Region|Northeastern Region|Eastern Region|Southern Region'),cities:split('Reykjavík|Kópavogur|Hafnarfjörður|Reykjanesbær|Akureyri|Garðabær|Mosfellsbær|Árborg|Akranes|Fjarðabyggð')},
  LI:{regions:split('Balzers|Eschen|Gamprin|Mauren|Planken|Ruggell|Schaan|Schellenberg|Triesen|Triesenberg|Vaduz'),cities:split('Vaduz|Schaan|Balzers|Triesen|Eschen|Mauren|Triesenberg|Ruggell|Gamprin|Schellenberg|Planken')},
  CH:{regions:split('Aargau|Appenzell Ausserrhoden|Appenzell Innerrhoden|Basel-Landschaft|Basel-Stadt|Bern|Fribourg|Geneva|Glarus|Graubünden|Jura|Lucerne|Neuchâtel|Nidwalden|Obwalden|Schaffhausen|Schwyz|Solothurn|St. Gallen|Thurgau|Ticino|Uri|Valais|Vaud|Zug|Zurich'),cities:split('Zurich|Geneva|Basel|Lausanne|Bern|Winterthur|Lucerne|St. Gallen|Lugano|Biel/Bienne|Thun|Köniz|Fribourg|Schaffhausen|Chur')},
  GB:{regions:split('England|Scotland|Wales|Northern Ireland|East Midlands|East of England|London|North East England|North West England|South East England|South West England|West Midlands|Yorkshire and the Humber'),cities:split('London|Birmingham|Manchester|Glasgow|Leeds|Liverpool|Edinburgh|Sheffield|Bristol|Cardiff|Belfast|Newcastle upon Tyne|Nottingham|Leicester|Cambridge|Oxford|Brighton|Southampton|Aberdeen')},
  AD:{regions:split('Andorra la Vella|Canillo|Encamp|Escaldes-Engordany|La Massana|Ordino|Sant Julià de Lòria'),cities:split('Andorra la Vella|Escaldes-Engordany|Encamp|Sant Julià de Lòria|La Massana|Santa Coloma|Ordino|Canillo')},
});

export const DISCOVERY_COUNTRY_OPTIONS=Object.freeze([...EUROPE_MARKETS].sort((a,b)=>a.canonical_name.localeCompare(b.canonical_name)).map(market=>({value:market.iso2,label:`${market.canonical_name} (${market.iso2})`,description:`${market.subregion} · ${market.primary_currency}`,group:market.subregion})));

const TAXONOMY=Object.freeze({
  MERCHANT:{
    industry:options('Ecommerce|Retail|Fashion & apparel|Footwear|Jewellery & watches|Eyewear|Luxury|Beauty & cosmetics|Skincare|Health & wellness|Supplements|Pharmacy|Consumer electronics|Home & furniture|Home improvement|Garden|Office supplies|Food & beverage|Grocery|Alcohol & beverages|Restaurants|Quick-service restaurants|Food delivery|Pet care|Baby & maternity|Toys & games|Books & publishing|Sporting goods|Outdoor recreation|Automotive|Mobility|Car rental|Travel|Airlines|Hospitality|Hotels|Vacation rentals|Marketplaces|B2B marketplaces|Subscription commerce|Subscription boxes|SaaS|Digital goods|Gaming|Streaming|Entertainment|Events|Ticketing|Education|Professional services|B2B wholesale|Manufacturing|Logistics|Real estate|Telecom|Insurance|Fintech|Nonprofit|Creator economy'),
    company_size:options('1–10 employees|11–50 employees|51–200 employees|201–500 employees|501–1,000 employees|1,001–5,000 employees|5,001–10,000 employees|10,000+ employees'),
    technology:options('Shopify|Shopify Plus|WooCommerce|Magento / Adobe Commerce|PrestaShop|BigCommerce|Salesforce Commerce Cloud|commercetools|SAP Commerce|Shopware|VTEX|Spryker|Elastic Path|Oracle Commerce|HCL Commerce|Ecwid|OpenCart|Sylius|Saleor|Medusa|Wix|Squarespace|Custom / headless|Adobe Experience Manager|Contentful|Sanity|Strapi|Stripe|Stripe Connect|Stripe Radar|Adyen|PayPal|Braintree|Checkout.com|Mollie|Worldline|Nexi|SumUp|Square|Klarna|Amazon Pay|Apple Pay|Google Pay|Revolut Pay|GoCardless|Airwallex|Rapyd|Primer|Spreedly|Gr4vy|Nuvei|Fiserv|Global Payments|ACI Worldwide|Cybersource|Authorize.net|BlueSnap|dLocal|EBANX|Trustly|Tink|TrueLayer|Yapily|Plaid|Mangopay|Lemonway|Paddle|Chargebee|Recurly|Zuora|Riskified|Forter|Sift|Signifyd|Ravelin|Kount|SEON|Sardine|Cloudflare|AWS|Google Cloud|Azure|Akamai|Fastly|Segment|Snowflake|HubSpot|Salesforce|Klaviyo|Braze|Bloomreach|Algolia|Google Analytics 4|Mixpanel|Amplitude|Datadog|New Relic|Sentry|Zendesk|Intercom|SAP S/4HANA|Oracle NetSuite|Microsoft Dynamics 365|Odoo|Sage|Xero|QuickBooks|Pennylane|Exact Online|Lightspeed|Shopify POS|Square POS|Zettle|Toast|NCR Voyix|Cegid|Oracle MICROS|SumUp POS'),
    business_model:options('DTC|B2C|B2B|B2B2C|Marketplace|Subscription|Franchise|Platform|Wholesale|Omnichannel retailer|Aggregator|On-demand|Usage-based|Nonprofit'),
    sales_channel:options('Ecommerce website|Marketplace|Mobile app|Social commerce|POS / in-store|Telesales / MOTO|Invoice|Subscription|Omnichannel'),
    customer_type:options('Consumers|SMB|Mid-market|Enterprise|Public sector|Nonprofits|Mixed customer base'),
    presence:options('Online-only|Store-only|Omnichannel|Multi-location|Cross-border ecommerce|Marketplace seller|Marketplace operator|Mobile-first'),
    contact_availability:options('Unknown|Professional email available|Verified professional email|Decision maker identified|LinkedIn only|Phone available|No contact found'),
    payment_stack:options('Multi-PSP|Single PSP|High card mix|Cross-border payments|High FX exposure|Recurring payments|Marketplace split payments|In-store + online|Digital wallets|BNPL|High chargebacks|High interchange exposure|Routing opportunity|Reconciliation pain|Settlement mismatch|Contract renewal|Legacy gateway|Unknown PSP'),
    exclusions:options('Existing customer|Already contacted|Suppressed|Competitor|Payment provider|Agency / partner|Inactive company|Duplicate|No professional contact|Below minimum size|Outside enabled markets'),
  },
  PARTNER:{
    partner_type:options('Accounting firm|Ecommerce agency|Fractional CFO|Consultancy|Systems integrator|ERP integrator|PSP referral partner|Bank|VC / PE|Accelerator|Trade association|Chamber of commerce|Law firm|Tax adviser|Implementation partner|Marketplace ecosystem|Technology vendor'),
    client_portfolio:options('Unknown portfolio|Under 25 clients|25–99 clients|100–249 clients|250–999 clients|1,000+ clients|Ecommerce-heavy|Retail-heavy|SaaS-heavy|Enterprise-heavy|Cross-border-heavy'),
    expertise:options('Ecommerce|Payments|Treasury|Finance operations|Accounting|ERP|Shopify|Magento|Salesforce Commerce|Omnichannel|International expansion|Procurement|Fraud|Compliance|Tax|Digital transformation'),
    partner_size:options('1–10 employees|11–50 employees|51–200 employees|201–500 employees|501–1,000 employees|1,001–5,000 employees|5,000+ employees|Boutique firm|Regional network|Global network'),
    contacts:options('Owner / founder|Partner / director|Business development|Alliances|Payments lead|Ecommerce lead|Verified professional email|Professional email available|Phone available|No contact found'),
    partner_fit:options('High fit|Medium fit|Low fit|Distribution reach|Trusted adviser|Technical delivery|Regional access|Enterprise access'),
    exclusions:options('Existing partner|Already contacted|Suppressed|Competitor|Inactive firm|Duplicate|No professional contact|Outside enabled markets'),
  },
  PROVIDER:{
    provider_type:options('PSP|Acquirer|Gateway|Payment orchestration|Payment facilitator|Issuer processor|Acquiring processor|Merchant acquirer|Bank|Alternative payment method|Wallet|BNPL|Fraud provider|Chargeback provider|FX provider|Treasury provider|Payouts provider|Open banking|POS provider|Terminal provider|Subscription billing|Tax provider|Reconciliation provider'),
    merchant_fit:options('SMB|Mid-market|Enterprise|Ecommerce|Omnichannel|Marketplace|SaaS|Travel & hospitality|High-risk|Cross-border|Subscription|In-store'),
    capabilities:options('Acquiring|Gateway|Orchestration|Smart routing|Tokenization|Network tokens|3DS|Fraud prevention|Chargebacks|Payouts|Split payments|Recurring payments|Vault|FX / DCC|Reporting|Reconciliation|Dispute management|POS / terminals|Open banking|Pay by bank|Local payment methods'),
    payment_methods:options('Visa|Mastercard|American Express|Maestro|V Pay|UnionPay|JCB|Discover|Diners Club|SEPA Direct Debit|SEPA Credit Transfer|iDEAL|Bancontact|Cartes Bancaires|Girocard|Dankort|EPS|Przelewy24|BLIK|Swish|Vipps|MobilePay|TWINT|PostFinance|Multibanco|MB WAY|Bizum|PagoBANCOMAT|BANCOMAT Pay|MyBank|Satispay|Payconiq|KBC / CBC|Belfius|Wero|Trustly|Sofort|Giropay|Klarna|Alma|Scalapay|Clearpay|Riverty|Billie|Walley|Oney|Apple Pay|Google Pay|Samsung Pay|PayPal|Amazon Pay|Revolut Pay|Pay by bank|Open banking payment|Cash on delivery|Bank transfer|Direct debit|Gift card|Store credit'),
    pricing:options('Public pricing|Custom quote|Interchange++|Blended pricing|Scheme fee transparency|FX markup|Cross-border markup|Monthly fee|Gateway fee|Refund fee|Chargeback fee|Payout fee|Minimum commitment|Missing pricing|Stale pricing|Conflicting pricing evidence'),
    authorization:options('Authorized|Passported|Local licence|EEA licence|FCA authorized|FINMA authorized|Licence applicant|Restricted|Unknown / unverified'),
    integrations:options('REST API|GraphQL API|Mobile SDK|Web SDK|Hosted checkout|Shopify plugin|WooCommerce plugin|Magento plugin|PrestaShop plugin|Salesforce Commerce|commercetools|SAP Commerce|ERP integration|Accounting integration|POS integration|Webhook support'),
    relevance:options('High relevance|Medium relevance|Low relevance|Merchant demand|Pricing gap|Authorization gap|Product gap|Migration candidate|Negotiation leverage|Benchmark relevance'),
    contacts:options('Relationship owner|Sales|Partnerships|Pricing|Legal / compliance|Technical|Support|Verified professional email|No contact found'),
  },
});

export function getDiscoveryFilterDefinition(type,key,selectedCountries=[]){
  if(key==='country'||key==='markets_served')return{options:DISCOVERY_COUNTRY_OPTIONS,allowCustom:false,placeholder:'Choose one or more of 33 markets',allLabel:'Select all 33 markets'};
  if(key==='region'){
    const codes=(selectedCountries.length?selectedCountries:DISCOVERY_COUNTRY_OPTIONS.map(option=>option.value)).filter(code=>DISCOVERY_GEOGRAPHY[code]);
    const marketByCode=new Map(EUROPE_MARKETS.map(market=>[market.iso2,market]));
    const locationOptions=codes.flatMap(code=>{
      const market=marketByCode.get(code);const geography=DISCOVERY_GEOGRAPHY[code];
      return[...geography.regions.map(name=>({value:`${name}, ${code}`,label:name,description:`Region · ${market?.canonical_name||code}`,group:`${market?.canonical_name||code} · Regions`})),...geography.cities.map(name=>({value:`${name}, ${code}`,label:name,description:`City · ${market?.canonical_name||code}`,group:`${market?.canonical_name||code} · Cities`}))];
    });
    return{options:locationOptions,allowCustom:true,placeholder:'Choose regions or cities',allLabel:'Select all shown locations',customHint:'Type any other city or region and press Enter'};
  }
  return{options:TAXONOMY[type]?.[key]||[],allowCustom:true,placeholder:'Choose one or more options',allLabel:'Select all options',customHint:'Type another valid option and press Enter'};
}

export const DISCOVERY_FILTER_TAXONOMY=TAXONOMY;
