import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import { P7_ALLOWLIST, P8_ALLOWLIST, STAGE_ECL_P6, STAGE_ECL_P7, STAGE_ECL_P8, STAGE_TRANSITIONS, allowlistForStage } from '../../scripts/lib/preEclFreeze.mjs';
const read = p => fs.readFileSync(new URL(`../../${p}`, import.meta.url), 'utf8');
const APP = read('src/App.jsx'); const NAV = read('src/pages/admin/AdminLayout.jsx'); const AGENT_UI = read('src/pages/admin/AdminAgents.jsx'); const AGENT_OPS = read('base44/functions/adminAgentOperations/entry.ts'); const COCKPIT = read('base44/functions/getAdminOperationsCockpit/entry.ts');
const cfg = p => JSON.parse(read(p));
describe('ECL P8 — Production Admin, Automation & AI Operations', () => {
  it('advances only P7 ⇄ P8 and keeps a code-owned exact allowlist', () => { expect(STAGE_TRANSITIONS[STAGE_ECL_P7]).toEqual([STAGE_ECL_P6, STAGE_ECL_P8]); expect(STAGE_TRANSITIONS[STAGE_ECL_P8]).toEqual([STAGE_ECL_P7]); expect(allowlistForStage(STAGE_ECL_P8)).toEqual(P8_ALLOWLIST); expect(P8_ALLOWLIST.slice(0,P7_ALLOWLIST.length)).toEqual(P7_ALLOWLIST); });
  it('adds the admin cockpit, AI ops, automation surfaces and four versioned schedules', () => { for (const p of ['base44/functions/getAdminOperationsCockpit/entry.ts','base44/functions/adminAgentOperations/entry.ts','src/pages/admin/AdminCommand.jsx','src/pages/admin/AdminAgents.jsx','src/pages/admin/AdminAutomations.jsx','base44/functions/retryPendingRecoverContracts/function.jsonc','base44/functions/purgePaymentsAnalysisSessions/function.jsonc','base44/functions/purgeInactiveLeads/function.jsonc','base44/functions/scheduledBenchmarkRecompute/function.jsonc','src/lib/eclP8Closure.test.js']) expect(P8_ALLOWLIST).toContain(p); });
  it('mounts AI Operations and Automations only inside the protected admin shell', () => { const shell=APP.indexOf('<Route element={<AdminRoute><AdminLayout /></AdminRoute>}>'); expect(APP.indexOf('path="/admin/agents"')).toBeGreaterThan(shell); expect(APP.indexOf('path="/admin/automations"')).toBeGreaterThan(shell); expect(NAV).toMatch(/AI Operations/); expect(NAV).toMatch(/Automations/); });
  it('keeps manual AI execution admin-only and closed to arbitrary function names', () => { expect(AGENT_OPS).toMatch(/user\.role !== 'admin'/); expect(AGENT_OPS).toMatch(/ALLOWED\.has\(functionName\)/); expect(AGENT_OPS).not.toMatch(/functions\.invoke\(body\?\.function/); expect(AGENT_OPS).toMatch(/admin_agent_manual_run/); });
  it('shows the observed run result and does not lose older agent status behind the first 500 tasks', () => { expect(AGENT_OPS).toContain("AgentTask.list('-created_date', 5000"); expect(AGENT_OPS).toContain("result?.ok !== false"); expect(AGENT_UI).toContain('role="status"'); expect(AGENT_UI).toContain('task.output_summary'); expect(AGENT_UI).toContain('Open Discovery results'); expect(AGENT_UI).not.toContain("|| 'never run'"); });
  it('keeps cockpit read-only over economic truth', () => { expect(COCKPIT).not.toMatch(/entities\.(Invoice|MonthlySavingsReport|ReviewCase)\.(create|update|delete)/); expect(COCKPIT).not.toMatch(/functions\.invoke/); expect(COCKPIT).toMatch(/overall_status/); });
  it('versions safe production schedules and does not automate human economic approval/issuance', () => { const configs=[['retryPendingRecoverContracts',15,'minutes'],['purgePaymentsAnalysisSessions',24,'hours'],['purgeInactiveLeads',30,'days'],['scheduledBenchmarkRecompute',7,'days']]; for(const [name,n,u] of configs){const c=cfg(`base44/functions/${name}/function.jsonc`); expect(c.automations).toHaveLength(1); expect(c.automations[0].is_active).toBe(true); expect(c.automations[0].repeat_interval).toBe(n); expect(c.automations[0].repeat_unit).toBe(u);} expect(fs.existsSync(new URL('../../base44/functions/createEligibleRecoverInvoices/function.jsonc',import.meta.url))).toBe(false); expect(fs.existsSync(new URL('../../base44/functions/generateMonthlySavingsReport/function.jsonc',import.meta.url))).toBe(false); });
});
