import{describe,it,expect}from'vitest';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';const R=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');const r=p=>fs.readFileSync(path.join(R,p),'utf8');const j=p=>JSON.parse(r(p));
describe('Final Autonomous Revenue Engine Seal',()=>{
 it('has explicit deterministic revenue lifecycle states',()=>{const p=j('base44/entities/RevenueLifecycle.jsonc').properties.state.enum;for(const x of ['opportunity','savings_identified','savings_accepted','implementation_pending','implemented','verification_pending','savings_verified','billable','invoiced','payment_pending','paid','partially_paid','disputed','failed','written_off','cancelled'])expect(p).toContain(x)});
 it('revenue lifecycle projects from authoritative truth instead of rewriting it',()=>{const s=r('base44/functions/revenueLifecycleWorker/entry.ts');for(const x of ['MonthlySavingsReport','Invoice','DealActivation'])expect(s).toContain(x);expect(s).toContain('Projection only');expect(s).not.toContain('MonthlySavingsReport.update');expect(s).not.toContain('Invoice.update')});
 it('estimated verified billable invoiced and collected remain distinct',()=>{const s=r('base44/functions/getFinancialControlTower/entry.ts');for(const x of ['estimated_savings','verified_savings','billable_savings','invoiced_revenue','collected_cash'])expect(s).toContain(x);expect(s).toContain("measurement_mode==='fully_verified'");expect(s).toContain("verification_status==='realized'")});
 it('real-world pilot excludes internal test data',()=>{const s=r('base44/functions/realWorldValidationWorker/entry.ts');expect(s).toContain("data_classification:'production',learning_eligible:true");expect(s).toContain('Only explicitly production-classified payment evidence')});
 it('golden path self-test never moves external money',()=>{const s=r('base44/functions/revenueGoldenPathSelfTest/entry.ts');expect(s).toContain('external_money_movement:false');expect(s).toContain('real_merchant_validation:false');expect(s).not.toMatch(/paymentIntents\.create|charges\.create|capture\(/)});
 it('founder center limits attention to governance surfaces',()=>{const s=r('base44/functions/getFounderControlCenter/entry.ts');for(const x of ['Approval','AutonomyIncident','OperatingHealthAssessment','RealWorldGapReport'])expect(s).toContain(x);expect(s).toMatch(/Routine operations stay in[\s\S]*Admin\/digests/)});
 it('health score is advisory not source of truth',()=>{expect(r('base44/entities/OperatingHealthAssessment.jsonc')).toContain('Advisory only');expect(r('base44/functions/operatingHealthWorker/entry.ts')).toContain('never replaces underlying domain metrics')});
 it('shadow routing remains shadow after revenue seal',()=>{const s=r('base44/shared/shadowRoutingCore.ts');expect(s).toContain('REAL_ROUTING_ALLOWED=false')});
 it('billing autopilot still cannot approve verified savings',()=>{const s=r('base44/functions/recoverAutopilotWorker/entry.ts');expect(s).not.toContain('approveRecoverReportForInvoicing')});

 it('aggregate procurement is a canonical communication engine',()=>{const c=JSON.parse(r('base44/entities/CommunicationThread.jsonc'));expect(c.properties.engine.enum).toContain('aggregate_procurement');expect(c.properties.meeting_classification).toBeTruthy();expect(c.properties.meeting_brief_json).toBeTruthy()});
 it('agent authority is default-deny and no agent can approve sign spend or charge',async()=>{const m=await import('../../base44/shared/agentAuthority.ts');expect(m.assertNoMaterialAuthority()).toBe(true);const unknown=m.authorityForAgent('totally_unknown_agent');expect(unknown.CAN_READ).toBe(false);expect(unknown.CAN_APPROVE).toBe(false);expect(unknown.CAN_SIGN).toBe(false);expect(unknown.CAN_SPEND).toBe(false);expect(unknown.CAN_CHARGE).toBe(false)});
 it('collection operations reconcile first and never manually retry a payment intent',()=>{const s=r('base44/functions/collectionOperationsWorker/entry.ts');expect(s).toContain("reconcileRecoverBilling");expect(s).toContain('No manual PaymentIntent retry');expect(s).not.toMatch(/paymentIntents\.create|paymentIntents\.confirm|charges\.create/)});
 it('sales prioritization refuses to fabricate revenue',()=>{const s=r('base44/functions/salesPipelineWorker/entry.ts');expect(s).toContain('Unknown monetary value remains unknown');expect(s).toContain('expected=collected');expect(s).not.toContain('estimated_gmv')});
 it('unit economics exposes missing inputs rather than synthetic CAC or LTV',()=>{const s=r('base44/functions/unitEconomicsWorker/entry.ts');expect(s).toContain("missing.push('cac')");expect(s).toContain('merchant_side_ltv_requires_retention_history');expect(s).toContain('provider_side_ltv_requires_provider_retention_history');expect(s).toContain('LTV remains null until real retention/payment history exists')});
 it('developer incident bridge cannot auto-patch or cut over production',()=>{const s=r('base44/functions/developerSignalWorker/entry.ts');expect(s).toContain('investigate_and_prepare_fix_plan');expect(s).toContain('approval-gated');expect(s).not.toContain("functions.invoke('developerMigrationEngine'")});
 it('exception operations have explicit workflow and impact dimensions',()=>{const p=JSON.parse(r('base44/entities/AutonomyIncident.jsonc')).properties;for(const x of ['workflow_state','owner_type','automation_eligibility','financial_impact_minor','customer_impact','legal_risk','root_cause','actions_taken_json','recovery_json','prevention_json'])expect(p[x]).toBeTruthy()});
 it('executive digest is deterministic and not LLM financial truth',()=>{const s=r('base44/functions/executiveDigestWorker/entry.ts');expect(s).toContain('Invoice');expect(s).not.toMatch(/Claude|OpenAI|anthropic|callCambraClaude/)});
 it('financial forecasting refuses an unsupported 12-month number',()=>{const s=r('base44/functions/getFinancialControlTower/entry.ts');expect(s).toContain("expected_cash:null");expect(s).toContain('insufficient_real_merchant_and_provider_settlement_history_for_defensible_12m_forecast');expect(s).toContain('requires_formal_accounting_recognition_policy')});
});
