import{describe,it,expect}from'vitest';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';const R=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');const r=p=>fs.readFileSync(path.join(R,p),'utf8');const j=p=>JSON.parse(r(p));
describe('Final Autonomous Revenue Engine Seal',()=>{
 it('has explicit deterministic revenue lifecycle states',()=>{const p=j('base44/entities/RevenueLifecycle.jsonc').properties.state.enum;for(const x of ['opportunity','savings_identified','savings_accepted','implementation_pending','implemented','verification_pending','savings_verified','billable','invoiced','payment_pending','paid','partially_paid','disputed','failed','written_off','cancelled'])expect(p).toContain(x)});
 it('revenue lifecycle projects from authoritative truth instead of rewriting it',()=>{const s=r('base44/functions/revenueLifecycleWorker/entry.ts');for(const x of ['MonthlySavingsReport','Invoice','DealActivation'])expect(s).toContain(x);expect(s).toContain('Projection only');expect(s).not.toContain('MonthlySavingsReport.update');expect(s).not.toContain('Invoice.update')});
 it('estimated verified billable invoiced and collected remain distinct',()=>{const s=r('base44/functions/getFinancialControlTower/entry.ts');for(const x of ['estimated_savings','verified_savings','billable_savings','invoiced_revenue','collected_cash'])expect(s).toContain(x);expect(s).toContain("measurement_mode==='fully_verified'");expect(s).toContain("verification_status==='realized'")});
 it('real-world pilot excludes internal test data',()=>{const s=r('base44/functions/realWorldValidationWorker/entry.ts');expect(s).toContain("data_classification:'production',learning_eligible:true");expect(s).toContain('Only explicitly production-classified payment evidence')});
 it('golden path self-test never moves external money',()=>{const s=r('base44/functions/revenueGoldenPathSelfTest/entry.ts');expect(s).toContain('external_money_movement:false');expect(s).toContain('real_merchant_validation:false');expect(s).not.toMatch(/paymentIntents\.create|charges\.create|capture\(/)});
 it('founder center limits attention to governance surfaces',()=>{const s=r('base44/functions/getFounderControlCenter/entry.ts');for(const x of ['Approval','AutonomyIncident','OperatingHealthAssessment','RealWorldGapReport'])expect(s).toContain(x);expect(s).toContain('Routine operations stay in Admin/digests')});
 it('health score is advisory not source of truth',()=>{expect(r('base44/entities/OperatingHealthAssessment.jsonc')).toContain('Advisory only');expect(r('base44/functions/operatingHealthWorker/entry.ts')).toContain('never replaces underlying domain metrics')});
 it('shadow routing remains shadow after revenue seal',()=>{const s=r('base44/shared/shadowRoutingCore.ts');expect(s).toContain('REAL_ROUTING_ALLOWED=false')});
 it('billing autopilot still cannot approve verified savings',()=>{const s=r('base44/functions/recoverAutopilotWorker/entry.ts');expect(s).not.toContain('approveRecoverReportForInvoicing')});
});
