import { describe, expect, it } from "vitest";
import fs from "node:fs";
import {
  ACTIVE_LAUNCH_MARKETS,
  CANONICAL_MARKET_CODES,
  MARKET_SCOPE_BY_ISO2,
  MARKET_SCOPE_COUNTS,
  MARKET_SCOPE_DECISION_STATUS,
  PROTECTED_MARKETS,
} from "./generated/europeMarkets.js";
import {
  REGULATED_CAPABILITIES,
  evaluateMarketLaunchScope,
  marketSeedLaunchProjection,
  validatePaymentsLaunchMarketInput,
} from "../../base44/shared/marketLaunchScope.ts";

const EXPECTED_CANONICAL = [
  "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE",
  "GR", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT",
  "RO", "SK", "SI", "ES", "SE", "NO", "IS", "LI", "CH", "GB", "AD",
];
const EXPECTED_ACTIVE = [
  "AT", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "DE", "GR", "HU",
  "IE", "IT", "LV", "LT", "LU", "MT", "PL", "PT", "RO", "SK", "SI",
  "ES", "SE", "NO", "IS", "LI", "CH", "GB", "AD",
];

describe("founder market launch authority", () => {
  it("defines the exact canonical 33 and exact 30/3 partition", () => {
    expect(CANONICAL_MARKET_CODES).toEqual(EXPECTED_CANONICAL);
    expect(ACTIVE_LAUNCH_MARKETS).toEqual(EXPECTED_ACTIVE);
    expect(PROTECTED_MARKETS).toEqual(["FR", "BE", "NL"]);
    expect(MARKET_SCOPE_COUNTS).toEqual({
      canonical_market_count: 33,
      active_launch_count: 30,
      protected_market_count: 3,
    });
    expect(MARKET_SCOPE_DECISION_STATUS).toBe("FOUNDER_DECIDED");
    expect(new Set([...ACTIVE_LAUNCH_MARKETS, ...PROTECTED_MARKETS])).toEqual(
      new Set(EXPECTED_CANONICAL),
    );
    expect(ACTIVE_LAUNCH_MARKETS).toContain("ES");
  });

  it("keeps frontend and backend projections aligned from generated bytes", () => {
    expect(fs.readFileSync("src/lib/generated/europeMarkets.js", "utf8")).toBe(
      fs.readFileSync("base44/shared/generated/europeMarkets.ts", "utf8"),
    );
    for (const market of EXPECTED_CANONICAL) {
      expect(evaluateMarketLaunchScope(market)).toMatchObject(MARKET_SCOPE_BY_ISO2[market]);
    }
    const generator = fs.readFileSync("scripts/generate-europe-markets.mjs", "utf8");
    expect(generator).toContain("src/lib/generated/europeMarkets.js");
    expect(generator).toContain("base44/shared/generated/europeMarkets.ts");
    expect(generator).toContain("market registry drift:");
  });

  it("blocks unknown and protected countries on the backend", () => {
    expect(validatePaymentsLaunchMarketInput({ country: "ZZ" })).toEqual({
      ok: false,
      failure: { field: "country", reason: "not_canonical_market" },
    });
    for (const market of PROTECTED_MARKETS) {
      expect(validatePaymentsLaunchMarketInput({ country: market })).toEqual({
        ok: false,
        failure: { field: "country", reason: "protected_research_only" },
      });
      expect(marketSeedLaunchProjection(market)).toMatchObject({
        iso2: market,
        launch_status: "REGULATORY_HOLD",
        research_mode: "RESEARCH_ONLY",
        outbound_capacity: 0,
      });
    }
  });

  it("rejects a caller-supplied region and derives region server-side", () => {
    expect(validatePaymentsLaunchMarketInput({ country: "ES", region: "UK" })).toEqual({
      ok: false,
      failure: { field: "region", reason: "manual_region_forbidden" },
    });
    expect(validatePaymentsLaunchMarketInput({ country: "ES", channels: [{ region: "UK" }] })).toEqual({
      ok: false,
      failure: { field: "region", reason: "manual_region_forbidden" },
    });
    expect(validatePaymentsLaunchMarketInput({ country: "GB" })).toMatchObject({
      ok: true,
      country: "GB",
      region: "UK",
    });
    expect(validatePaymentsLaunchMarketInput({ country: "ES" })).toMatchObject({
      ok: true,
      country: "ES",
      region: "EU",
    });
    expect(validatePaymentsLaunchMarketInput({ country: "AD" })).toMatchObject({
      ok: true,
      country: "AD",
      region: "RoW",
    });
  });

  it("never grants outbound or regulated capability through market membership", () => {
    expect(REGULATED_CAPABILITIES).toEqual([
      "ACCESS_BANK_ACCOUNT_DATA",
      "INITIATE_PAYMENT",
      "HOLD_FUNDS",
      "ACT_AS_PSP",
      "ACT_AS_PSP_AGENT",
    ]);
    for (const market of EXPECTED_CANONICAL) {
      expect(evaluateMarketLaunchScope(market)).toMatchObject({
        outbound_allowed: false,
        outbound_capacity: 0,
        regulated_capabilities_authorized: false,
      });
    }
  });

  it("wires the authority into submit, seed and Analyzer without FR/ES scope hardcodes", () => {
    const submit = fs.readFileSync("base44/functions/submitPaymentsAnalysis/entry.ts", "utf8");
    const seed = fs.readFileSync("base44/functions/seedEuropeMarketFoundation/entry.ts", "utf8");
    const analyzer = fs.readFileSync("src/pages/PaymentsAnalyzer.jsx", "utf8");
    expect(submit).toContain("validatePaymentsLaunchMarketInput(raw)");
    expect(submit.indexOf("validatePaymentsLaunchMarketInput(raw)")).toBeLessThan(
      submit.indexOf("consumePublicRequestRateLimit("),
    );
    expect(submit).not.toContain("countryToRegion");
    expect(seed).toContain("marketSeedLaunchProjection(market.iso2)");
    expect(seed).toContain("outbound_globally_paused_zero");
    expect(seed).toContain("regulated_activity_not_authorized");
    expect(seed).toContain("launch_status: launch.launch_status");
    expect(analyzer).toContain("ACTIVE_LAUNCH_MARKETS.includes(country)");
    for (const source of [submit, seed, analyzer]) {
      expect(source).not.toMatch(/\[\s*["']FR["']\s*,\s*["']ES["']\s*\]/);
    }
  });
});
