import { describe, expect, it } from "vitest";
import fs from "node:fs";
import {
  ACTIVE_LAUNCH_MARKETS,
  CANONICAL_MARKET_CODES,
  MARKET_SCOPE_BY_ISO2,
  MARKET_SCOPE_COUNTS,
  MARKET_SCOPE_DECISION_STATUS,
  NOT_LAUNCH_MARKETS,
  OUTSIDE_LAUNCH_PERIMETER,
  PROTECTED_MARKETS,
} from "./generated/europeMarkets.js";
import {
  RATE_FRESHNESS_MAX_AGE_DAYS,
  REGULATED_CAPABILITIES,
  evaluateMarketLaunchScope,
  marketSeedLaunchProjection,
  rateFreshnessDecision,
  validatePaymentsLaunchMarketInput,
} from "../../base44/shared/marketLaunchScope.ts";
import { planDiscoveryQuery } from "../../base44/shared/discoveryV2Planner.ts";
import {
  DISCOVERY_ACTIVE_LAUNCH_COUNTRY_OPTIONS,
  getDiscoveryFilterDefinition,
} from "./discoveryFilterOptions.js";

const EXPECTED_CANONICAL = [
  "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE",
  "GR", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT",
  "RO", "SK", "SI", "ES", "SE", "NO", "IS", "LI", "CH", "GB", "AD",
];
const EXPECTED_ACTIVE = ["ES", "IT", "PT", "GB", "GR", "HR", "DE", "PL", "CZ", "CY"];
const EXPECTED_NOT_LAUNCH = ["AT", "BG", "CH", "DK", "EE", "FI", "HU", "IE", "LT", "LU", "LV", "MT", "NO", "RO", "SE", "SI", "SK"];
const EXPECTED_OUTSIDE = ["IS", "LI", "AD"];

describe("founder market launch authority", () => {
  it("defines the exact canonical 33 and exact 10/3/17 launch decision", () => {
    expect(CANONICAL_MARKET_CODES).toEqual(EXPECTED_CANONICAL);
    expect(ACTIVE_LAUNCH_MARKETS).toEqual(EXPECTED_ACTIVE);
    expect(PROTECTED_MARKETS).toEqual(["FR", "BE", "NL"]);
    expect(NOT_LAUNCH_MARKETS).toEqual(EXPECTED_NOT_LAUNCH);
    expect(OUTSIDE_LAUNCH_PERIMETER).toEqual(EXPECTED_OUTSIDE);
    expect(MARKET_SCOPE_COUNTS).toEqual({
      canonical_market_count: 33,
      launch_perimeter_count: 30,
      active_launch_count: 10,
      licensing_blocked_count: 3,
      not_launch_market_count: 17,
      outside_launch_perimeter_count: 3,
    });
    expect(MARKET_SCOPE_DECISION_STATUS).toBe("FOUNDER_DECIDED");
    expect(new Set([...ACTIVE_LAUNCH_MARKETS, ...PROTECTED_MARKETS, ...NOT_LAUNCH_MARKETS])).toEqual(
      new Set(EXPECTED_CANONICAL.filter((code) => !EXPECTED_OUTSIDE.includes(code))),
    );
    expect(new Set([...ACTIVE_LAUNCH_MARKETS, ...PROTECTED_MARKETS, ...NOT_LAUNCH_MARKETS, ...OUTSIDE_LAUNCH_PERIMETER])).toEqual(new Set(EXPECTED_CANONICAL));
    expect(ACTIVE_LAUNCH_MARKETS).toContain("ES");
  });

  it("keeps frontend and backend projections aligned from generated bytes", () => {
    expect(fs.readFileSync("src/lib/generated/europeMarkets.js", "utf8")).toBe(
      fs.readFileSync("base44/shared/generated/europeMarkets.ts", "utf8"),
    );
    for (const market of EXPECTED_CANONICAL) {
      expect(evaluateMarketLaunchScope(market)).toMatchObject(MARKET_SCOPE_BY_ISO2[market]);
    }
    const generator = fs.readFileSync("scripts/generate-europe-markets.mjs", "utf8");
    expect(generator).toContain("src/lib/generated/europeMarkets.js");
    expect(generator).toContain("base44/shared/generated/europeMarkets.ts");
    expect(generator).toContain("market registry drift:");
  });

  it("blocks unknown and protected countries on the backend", () => {
    expect(validatePaymentsLaunchMarketInput({ country: "ZZ" })).toEqual({
      ok: false,
      failure: { field: "country", reason: "not_canonical_market" },
    });
    for (const market of PROTECTED_MARKETS) {
      expect(validatePaymentsLaunchMarketInput({ country: market })).toEqual({
        ok: false,
        failure: { field: "country", reason: "protected_research_only" },
      });
      expect(marketSeedLaunchProjection(market)).toMatchObject({
        iso2: market,
        launch_status: "REGULATORY_HOLD",
        commercial_eligibility: "BLOCKED",
        blocked_reason: "licensing",
        research_mode: "RESEARCH_ONLY",
        outbound_capacity: 0,
      });
    }
  });

  it("blocks exactly 17 not-launch markets without degrading research access", () => {
    expect(NOT_LAUNCH_MARKETS).toHaveLength(17);
    for (const market of NOT_LAUNCH_MARKETS) {
      expect(evaluateMarketLaunchScope(market)).toMatchObject({
        launch_active: false,
        research_allowed: true,
        commercial_eligibility: "BLOCKED",
        blocked_reason: "not_launch_market",
      });
      expect(validatePaymentsLaunchMarketInput({ country: market })).toEqual({
        ok: false,
        failure: { field: "country", reason: "not_launch_market" },
      });
    }
  });

  it("keeps IS/LI/AD outside the 30-market launch perimeter and commercially inactive", () => {
    for (const market of OUTSIDE_LAUNCH_PERIMETER) {
      expect(evaluateMarketLaunchScope(market)).toMatchObject({
        launch_active: false,
        research_allowed: true,
        commercial_scope_eligible: false,
        commercial_eligibility: null,
      });
    }
  });

  it("treats Austria reactivation as launch-state only and never mutates rate data", () => {
    const rateSchemaBefore = fs.readFileSync("base44/entities/PaymentsRateTable.jsonc", "utf8");
    const rateSeederBefore = fs.readFileSync("base44/functions/seedPaymentsRateTable/entry.ts", "utf8");
    const austria = marketSeedLaunchProjection("AT");
    expect(austria).toMatchObject({ commercial_eligibility: "BLOCKED", blocked_reason: "not_launch_market" });
    const hypotheticalReactivated = { ...austria, commercial_eligibility: "ELIGIBLE", blocked_reason: null, launch_status: "ANALYZER_READY" };
    expect(hypotheticalReactivated.commercial_eligibility).toBe("ELIGIBLE");
    expect(fs.readFileSync("base44/entities/PaymentsRateTable.jsonc", "utf8")).toBe(rateSchemaBefore);
    expect(fs.readFileSync("base44/functions/seedPaymentsRateTable/entry.ts", "utf8")).toBe(rateSeederBefore);
  });

  it("rejects a caller-supplied region and derives region server-side", () => {
    expect(validatePaymentsLaunchMarketInput({ country: "ES", region: "UK" })).toEqual({
      ok: false,
      failure: { field: "region", reason: "manual_region_forbidden" },
    });
    expect(validatePaymentsLaunchMarketInput({ country: "ES", channels: [{ region: "UK" }] })).toEqual({
      ok: false,
      failure: { field: "region", reason: "manual_region_forbidden" },
    });
    expect(validatePaymentsLaunchMarketInput({ country: "GB" })).toMatchObject({
      ok: true,
      country: "GB",
      region: "UK",
    });
    expect(validatePaymentsLaunchMarketInput({ country: "ES" })).toMatchObject({
      ok: true,
      country: "ES",
      region: "EU",
    });
    expect(validatePaymentsLaunchMarketInput({ country: "AD" })).toEqual({
      ok: false,
      failure: { field: "country", reason: "protected_research_only" },
    });
  });

  it("never grants outbound or regulated capability through market membership", () => {
    expect(REGULATED_CAPABILITIES).toEqual([
      "ACCESS_BANK_ACCOUNT_DATA",
      "INITIATE_PAYMENT",
      "HOLD_FUNDS",
      "ACT_AS_PSP",
      "ACT_AS_PSP_AGENT",
    ]);
    for (const market of EXPECTED_CANONICAL) {
      expect(evaluateMarketLaunchScope(market)).toMatchObject({
        outbound_allowed: false,
        outbound_capacity: 0,
        regulated_capabilities_authorized: false,
      });
    }
  });

  it("enforces a non-reducible 90-day rate freshness gate without deleting inactive-market history", () => {
    expect(RATE_FRESHNESS_MAX_AGE_DAYS).toBe(90);
    const now = "2026-08-22T00:00:00.000Z";
    expect(rateFreshnessDecision({
      verified_at: "2026-05-24T00:00:00.000Z",
      launch_active: true,
      now,
    })).toMatchObject({
      status: "CURRENT",
      commercial_use_allowed: true,
      reactivation_allowed: true,
    });
    expect(rateFreshnessDecision({
      verified_at: "2026-05-23T23:59:59.999Z",
      launch_active: true,
      now,
    })).toMatchObject({
      status: "STALE_BLOCKED",
      commercial_use_allowed: false,
      reactivation_allowed: false,
      reason: "verification_older_than_90_days",
    });
    expect(rateFreshnessDecision({
      verified_at: "2026-08-01T00:00:00.000Z",
      launch_active: false,
      now,
    })).toMatchObject({
      status: "INFORMATIONAL_INACTIVE_CURRENT",
      commercial_use_allowed: false,
      reactivation_allowed: true,
    });
    expect(rateFreshnessDecision({ launch_active: false, now })).toMatchObject({
      status: "INFORMATIONAL_INACTIVE_STALE",
      commercial_use_allowed: false,
      reactivation_allowed: false,
      reason: "verification_missing_invalid_or_future",
    });
  });

  it("wires the authority into submit, seed and Analyzer without FR/ES scope hardcodes", () => {
    const submit = fs.readFileSync("base44/functions/submitPaymentsAnalysis/entry.ts", "utf8");
    const seed = fs.readFileSync("base44/functions/seedEuropeMarketFoundation/entry.ts", "utf8");
    const analyzer = fs.readFileSync("src/pages/PaymentsAnalyzer.jsx", "utf8");
    expect(submit).toContain("validatePaymentsLaunchMarketInput(raw)");
    expect(submit.indexOf("validatePaymentsLaunchMarketInput(raw)")).toBeLessThan(
      submit.indexOf("consumePublicRequestRateLimit("),
    );
    expect(submit).not.toContain("countryToRegion");
    expect(seed).toContain("marketSeedLaunchProjection(market.iso2)");
    expect(seed).toContain("market_reactivation_requires_rate_reverification");
    expect(seed).toContain("writes_applied: 0");
    expect(seed.indexOf("reactivationBlockers.length > 0")).toBeLessThan(
      seed.indexOf("for (const market of EUROPE_MARKETS as any[]) {", seed.indexOf("reactivationBlockers.length > 0")),
    );
    expect(seed).toContain("outbound_globally_paused_zero");
    expect(seed).toContain("regulated_activity_not_authorized");
    expect(seed).toContain("launch_status: launch.launch_status");
    expect(analyzer).toContain("ACTIVE_LAUNCH_MARKETS.includes(country)");
    for (const source of [submit, seed, analyzer]) {
      expect(source).not.toMatch(/\[\s*["']FR["']\s*,\s*["']ES["']\s*\]/);
    }
  });

  it("limits operational merchant discovery and profile activation to the exact active 10", () => {
    expect(DISCOVERY_ACTIVE_LAUNCH_COUNTRY_OPTIONS.map((option) => option.value).sort())
      .toEqual([...EXPECTED_ACTIVE].sort());
    expect(getDiscoveryFilterDefinition("MERCHANT", "country").options.map((option) => option.value).sort())
      .toEqual([...EXPECTED_ACTIVE].sort());

    const activePlan = planDiscoveryQuery({
      discovery_type: "MERCHANT",
      source_mode: "CAMBRA",
      filters: { country: ["ES", "DE"] },
    });
    expect(activePlan.execution_blockers).toEqual([]);
    expect(activePlan.market_scope).toMatchObject({
      active_launch_markets: EXPECTED_ACTIVE,
      requested_markets: ["ES", "DE"],
      blocked_markets: [],
    });

    const protectedPlan = planDiscoveryQuery({
      discovery_type: "MERCHANT",
      source_mode: "CAMBRA",
      filters: { country: ["FR"] },
    });
    expect(protectedPlan.execution_blockers).toContain("MERCHANT_MARKET_OUTSIDE_ACTIVE_LAUNCH:FR");
    expect(planDiscoveryQuery({ discovery_type: "MERCHANT", source_mode: "CAMBRA", filters: {} }).execution_blockers)
      .toContain("MERCHANT_ACTIVE_LAUNCH_MARKET_REQUIRED");

    const policyAdmin = fs.readFileSync("base44/functions/commercialPolicyAdmin/entry.ts", "utf8");
    const worker = fs.readFileSync("base44/functions/alwaysOnLeadDiscoveryWorker/entry.ts", "utf8");
    const discoveryAdmin = fs.readFileSync("base44/shared/discoveryV2Admin.ts", "utf8");
    expect(policyAdmin).toContain("discovery_market_outside_active_launch");
    expect(worker).toContain("ACTIVE_LAUNCH_MARKET_SET.has(value)");
    expect(discoveryAdmin).not.toContain('native.country || "FR"');
  });
});
