import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
describe('outbound pool safety',()=>{
 it('commercial sender requires master switch and explicit sending profile for acquisition',()=>{const s=read('base44/functions/commercialSendMessage/entry.ts');expect(s).toContain('outbound_master_paused');expect(s).toContain('sending_profile_required');expect(s).toContain('premium_outlook_paused');expect(s).toContain('volume_resend_paused');expect(s).toContain('sending_profile_daily_cap_reached')});
 it('premium workers are hard-gated and use Xavi profile',()=>{const m=read('base44/functions/autonomousCommercialWorker/entry.ts');const p=read('base44/functions/autonomousPartnerWorker/entry.ts');expect(m).toContain("reason:'merchant_volume_only'");expect(p).toContain('premium_outlook_enabled');expect(p).toContain("outlook:xavi@cambra.global");expect(p).toContain("reason:'daily_limit'")});
 it('volume worker cannot run unless both switches are enabled',()=>{const s=read('base44/functions/outboundVolumeWorker/entry.ts');expect(s).toContain('!control?.acquisition_enabled||!control?.volume_resend_enabled');expect(s).toContain("profile_key:'resend:contact.cambra.global'");expect(s).toContain('Math.ceil(Number(profile.current_daily_cap||50)/11)');expect(s).toContain('relatedDomain');expect(s).not.toContain('PartnerProspect.filter')});
 it('deliverability manager pauses and only ramps in 50-step evidence-gated intervals',()=>{const s=read('base44/functions/outboundDeliverabilityManager/entry.ts');expect(s).toContain('deliverability_threshold_exceeded');expect(s).toContain('complaint_slow_threshold_pct');expect(s).toContain('ramp_min_days');expect(s).toContain('ramp_step')});
 it('control admin is explicit and never self-starts',()=>{const s=read('base44/functions/outboundControlAdmin/entry.ts');expect(s).toContain("action==='start_volume'");expect(s).toContain("action==='pause_all'");expect(s).toContain("admin_required")});
 it('Resend lifecycle events feed deliverability evidence',()=>{const s=read('base44/functions/resendInboundWebhook/entry.ts');expect(s).toContain("email.complained");expect(s).toContain('last_resend_event');expect(s).toContain("send_status:status")});
});
