import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
describe('outbound pool safety',()=>{
 it('commercial sender requires master switch and explicit sending profile for acquisition',()=>{const s=read('base44/functions/commercialSendMessage/entry.ts');expect(s).toContain('outbound_master_paused');expect(s).toContain('sending_profile_required');expect(s).toContain('premium_outlook_paused');expect(s).toContain('volume_resend_paused');expect(s).toContain('sending_profile_daily_cap_reached')});
 it('legacy premium merchant scheduler is disabled and partner worker resolves its allowlisted Outlook profile',()=>{const mc=read('base44/functions/autonomousCommercialWorker/function.jsonc');const m=read('base44/functions/autonomousCommercialWorker/entry.ts');const p=read('base44/functions/autonomousPartnerWorker/entry.ts');expect(mc).toContain('"is_active": false');expect(m).toContain("reason:'merchant_volume_only'");expect(p).toContain('premium_outlook_enabled');expect(p).toContain('policy.sending_profile_keys||[]');expect(p).toContain("provider==='outlook'");expect(p).toContain('sendingProfileIsValid');expect(p).toContain("reason:'daily_limit'")});
 it('volume worker consumes only READY_FOR_CONTACT leads through an allowlisted enabled provider profile',()=>{const s=read('base44/functions/outboundVolumeWorker/entry.ts');expect(s).toContain('!control?.acquisition_enabled');expect(s).toMatch(/policy\.sending_profile_keys\s*\|\|\s*\[\]/);expect(s).toMatch(/candidate\?\.provider\s*===\s*["']resend["']/);expect(s).toMatch(/candidate\?\.provider\s*===\s*["']instantly["']/);expect(s).toMatch(/control\.instantly_enabled\s*===\s*true/);expect(s).toContain('sendingProfileIsValid');expect(s).toMatch(/["']OutboundLead["'],\s*\{ reservoir_state: ["']ready["'] \}/);expect(s).toMatch(/x\.revenue_stage\s*!==\s*["']outreach_ready["']/);expect(s).toContain('policyAlready');expect(s).toMatch(/Number\(policy\.daily_send_limit\)\s*-\s*policyAlready\.length/);expect(s).toMatch(/Math\.ceil\(Number\(profile\.current_daily_cap\s*\|\|\s*15\)\s*\/\s*11\)/);expect(s).toContain('relatedDomain');expect(s).not.toContain('PartnerProspect.filter')});
 it('deliverability manager pauses and only ramps in 50-step evidence-gated intervals',()=>{const s=read('base44/functions/outboundDeliverabilityManager/entry.ts');expect(s).toContain('deliverability_threshold_exceeded');expect(s).toContain('complaint_slow_threshold_pct');expect(s).toContain('ramp_min_days');expect(s).toContain('ramp_step')});
 it('control admin is explicit and never self-starts',()=>{const s=read('base44/functions/outboundControlAdmin/entry.ts');expect(s).toContain('start_volume: "resend"');expect(s).toMatch(/action\s*===\s*["']pause_all["']/);expect(s).toContain("admin_required")});
 it('Resend lifecycle events feed deliverability evidence',()=>{const s=read('base44/functions/resendInboundWebhook/entry.ts');expect(s).toContain("email.complained");expect(s).toContain('last_resend_event');expect(s).toContain("send_status:status")});
});
