import{describe,it,expect}from'vitest';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{committedVolumeFromExplicitCommitments,aggregationPowerScore,tierProgress,materialAggregateTerms,truthfulDemandSnapshot}from'../../base44/shared/aggregateCore.ts';const R=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');const read=p=>fs.readFileSync(path.join(R,p),'utf8');const json=p=>JSON.parse(read(p));
describe('P14 Aggregate',()=>{
 it('models aggregate primitives without duplicating provider intelligence',()=>{for(const n of ['DemandUnit','AggregatePool','AggregatePoolMember','AggregateCommitment','AggregateRFP','AggregateBid','DynamicAgreement','AgreementTier','PrivateRateCard','MerchantRateEligibility'])expect(fs.existsSync(path.join(R,'base44/entities',`${n}.jsonc`))).toBe(true);expect(read('base44/entities/PrivateRateCard.jsonc')).toContain('Distinct from public ProviderPricingVersion')});
 it('committed volume comes only from explicit live commitments',()=>{const rows=[{status:'active',committed_annual_volume_minor:100},{status:'explicitly_authorized',committed_annual_volume_minor:50},{status:'draft',committed_annual_volume_minor:999},{status:'revoked',committed_annual_volume_minor:999}];expect(committedVolumeFromExplicitCommitments(rows)).toBe(150)});
 it('truth snapshot separates observed addressable committed',()=>{const x=truthfulDemandSnapshot({merchant_count:2,observed_annual_volume_minor:100,addressable_annual_volume_minor:60,committed_annual_volume_minor:10,probable_annual_volume_minor:40,currency:'EUR'});expect(x.observed_annual_volume_minor).toBe(100);expect(x.addressable_annual_volume_minor).toBe(60);expect(x.committed_annual_volume_minor).toBe(10);expect(x.claim_rule).toContain('distinct')});
 it('APS rewards leverage but penalizes concentration',()=>{const a=aggregationPowerScore({addressable_annual_volume_minor:10000000000,committed_annual_volume_minor:1000000000,merchant_count:20,migration_readiness:.8,confidence:.8,concentration:.1,growth_rate:.2});const b=aggregationPowerScore({addressable_annual_volume_minor:10000000000,committed_annual_volume_minor:1000000000,merchant_count:20,migration_readiness:.8,confidence:.8,concentration:.95,growth_rate:.2});expect(a).toBeGreaterThan(b)});
 it('tier progress is deterministic and machine readable',()=>{expect(tierProgress({addressable_annual_volume_minor:90},{metric:'addressable_volume',threshold_value:100})).toMatchObject({qualified:false,progress_pct:90,amount_remaining:10});expect(tierProgress({addressable_annual_volume_minor:110},{metric:'addressable_volume',threshold_value:100}).qualified).toBe(true)});
 it('material terms include exclusivity guarantees liabilities and long contracts',()=>{expect(materialAggregateTerms({legal_terms_json:{exclusivity:true}})).toBe(true);expect(materialAggregateTerms({legal_terms_json:{volume_guarantee:true}})).toBe(true);expect(materialAggregateTerms({legal_terms_json:{financial_liability:true}})).toBe(true);expect(materialAggregateTerms({legal_terms_json:{contract_term_months:24}})).toBe(true)});
 it('collective negotiation reuses canonical communication and approval surfaces',()=>{const s=read('base44/functions/collectiveNegotiationAgent/entry.ts');for(const x of ['NegotiationCase','NegotiationOffer','CommunicationThread','commercialSendMessage','Approval','AggregateBid'])expect(s).toContain(x);expect(s).toContain('Never call observed or addressable volume committed/guaranteed')});
 it('proposal approval does not execute contract',()=>{const s=read('base44/functions/resolveCommercialApproval/entry.ts');expect(s).toMatch(/action_type\s*===\s*["']aggregate_contract["']/);expect(s).toMatch(/contract_execution\s*:\s*false/);expect(s).toMatch(/action_type\s*===\s*["']aggregate_contract_execution["']/);expect(s).toMatch(/contract_match_status\s*!==\s*["']match["']/)});
 it('routing only consumes active private rates for eligible merchant',()=>{const s=read('base44/functions/shadowRoutingEngine/entry.ts');expect(s).toContain("PrivateRateCard.filter({status:'active'}");expect(s).toContain("MerchantRateEligibility.filter({brand_id:o.brand_id,status:'eligible'}");expect(s).toContain("pricing_source:'cambra_private_rate'")});
 it('recover exposes merchant-only aggregate program with potential not guaranteed',()=>{const s=read('base44/functions/getRecoverAcceptanceContext/entry.ts');expect(s).toContain('aggregate_programs');expect(s).toContain("e.status === 'eligible' ? rate.variable_rate_bps : null");expect(s).toContain('rate_guaranteed')});
 it('aggregate joins moat and supervisor',()=>{expect(read('base44/functions/moatCuratorWorker/entry.ts')).toContain('moat-p14-aggregate-1.0.0');const s=read('base44/functions/autonomousOperationsSupervisor/entry.ts');expect(s).toContain('aggregate_stale_pool');expect(s).toContain('aggregate_tier_confirmation')});
 it('all P14 entities remain admin restricted',()=>{for(const n of ['DemandUnit','AggregatePool','AggregatePoolMember','AggregateCommitment','AggregateRFP','AggregateBid','DynamicAgreement','AgreementTier','PrivateRateCard','MerchantRateEligibility'])expect(json(`base44/entities/${n}.jsonc`).rls.read.user_condition.role).toBe('admin')});
});
