import{describe,it,expect}from'vitest';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{recommendationFirewall,classifyConflict,providerRevenueAmountMinor,compensationTierProgress}from'../../base44/shared/providerEconomicsCore.ts';const R=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..'),r=p=>fs.readFileSync(path.join(R,p),'utf8'),j=p=>JSON.parse(r(p));
describe('P15 provider revenue share and dual-sided economics',()=>{
 it('models a separate provider-side subledger and tiers',()=>{for(const n of ['ProviderCompensationTier','ProviderRevenueAttribution','ProviderRevenueLedger','ProviderRevenueStatement','ProviderRevenueInvoice','ProviderEconomicAssessment'])expect(fs.existsSync(path.join(R,'base44/entities',`${n}.jsonc`))).toBe(true)});
 it('keeps merchant and provider economics structurally separate',()=>{expect(j('base44/entities/DynamicAgreement.jsonc').properties.provider_compensation_terms_json).toBeTruthy();expect(j('base44/entities/AggregateBid.jsonc').properties.provider_economics_json).toBeTruthy();expect(j('base44/entities/AggregateBid.jsonc').properties.compensation_effect_on_ranking.default).toBe(false)});
 it('merchant recommendation firewall ignores provider revenue',()=>{const a={provider_id:'A',merchant_outcome_score:94,provider_expected_revenue_12m_minor:1000000},b={provider_id:'B',merchant_outcome_score:80,provider_expected_revenue_12m_minor:10000000};expect(recommendationFirewall([b,a]).provider_id).toBe('A');expect(classifyConflict({bestMerchantScore:94,candidateMerchantScore:80,candidateProviderRevenue:10000000,bestProviderRevenue:1000000})).toBe('conflict_critical')});
 it('negotiation order is merchant first then provider monetization',()=>{const s=r('base44/functions/collectiveNegotiationAgent/entry.ts');expect(s).toMatch(/merchant_terms_established\s*:\s*true/);expect(s).toContain("providerMonetizationAgent");expect(r('base44/functions/providerMonetizationAgent/entry.ts')).toContain('merchant_suitability_gate_failed')});
 it('provider compensation cannot activate before explicit legal review',()=>{const s=r('base44/functions/providerRevenueLifecycleWorker/entry.ts');expect(s).toContain("provider_compensation_legal_status==='approved'");expect(s).toContain('provider_compensation_activation_allowed===true');const a=r('base44/functions/approveProviderMonetizationLegalReview/entry.ts');for(const x of ['legal_opinion_reference','disclosure_status','tax_treatment_reference','settlement_mode'])expect(a).toContain(x)});
 it('dynamic revenue-share tiers upgrade only on measured basis',()=>{expect(compensationTierProgress({volume_minor:105_000_00000},{metric:'processed_volume',threshold_value:100_000_00000}).qualified).toBe(true);expect(providerRevenueAmountMinor(100_000_00000,{rate_bps:5})).toBe(5_000_000)});
 it('reconciliation and recovery are evidence based',()=>{const q=r('base44/functions/providerRevenueReconciliationWorker/entry.ts');expect(q).toContain('PROVIDER_REVENUE_MISMATCH');const x=r('base44/functions/providerRevenueRecoveryAgent/entry.ts');expect(x).toContain('provider_compensation_legal_authority_required')});
 it('provider billing never invents invoice numbers',()=>{const s=r('base44/functions/providerRevenueBillingWorker/entry.ts');expect(s).toContain('no_invented_invoice_number:true');expect(s).toMatch(/mode\s*===\s*'provider_self_billing'/);const i=r('base44/functions/recordProviderRevenueInvoiceIssued/entry.ts');expect(i).toContain('externally_valid_invoice_number_and_document_required')});
 it('financial control tower reports two sides and total without double-counting',()=>{const s=r('base44/functions/getFinancialControlTower/entry.ts');for(const x of ['merchant_side_collected_revenue','provider_side_collected_revenue','total_cambra_collected_revenue','double_counting'])expect(s).toContain(x)});
 it('unit economics keeps merchant/provider/total LTV separate and unknown when unsupported',()=>{const s=r('base44/functions/unitEconomicsWorker/entry.ts');for(const x of ['merchant_side_revenue','provider_side_revenue','total_cambra_revenue','merchant_side_ltv:undefined','provider_side_ltv:undefined','total_ltv:undefined'])expect(s).toContain(x)});
 it('provider economics feeds confidential moat intelligence',()=>{const s=r('base44/functions/providerEconomicsIntelligenceWorker/entry.ts');expect(s).toContain('MoatMetric');expect(s).toContain('provider_compensation');expect(s).toContain('never changes merchant recommendation ranking')});
 it('new P15 entities are admin-only',()=>{for(const n of ['ProviderCompensationTier','ProviderRevenueAttribution','ProviderRevenueLedger','ProviderRevenueStatement','ProviderRevenueInvoice','ProviderEconomicAssessment'])expect(j(`base44/entities/${n}.jsonc`).rls.read.user_condition.role).toBe('admin')});
 it('new autonomous agents still cannot approve sign spend or charge',()=>{const s=r('base44/shared/agentAuthority.ts');for(const n of ['provider_monetization','provider_revenue_recovery','provider_revenue_lifecycle','provider_revenue_reconciliation'])expect(s).toContain(n);expect(s).not.toMatch(/provider_monetization:A\([^\n]*CAN_APPROVE:true/)});
});
