import{describe,it,expect}from'vitest';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';const R=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');const r=p=>fs.readFileSync(path.join(R,p),'utf8');const j=p=>JSON.parse(r(p));
describe('P16 Founder OS & Autonomous Company Command Center',()=>{
 it('models governed founder OS primitives with admin reads and service-bound authoritative writes',()=>{for(const n of ['FounderDecision','FounderSimulation','StrategyDirective','FounderCommandAudit','FounderSavedView']){const x=j(`base44/entities/${n}.jsonc`);expect(x.rls.read.user_condition.role).toBe('admin');expect(x.rls.write.user_condition.role).toBe(['FounderCommandAudit','FounderSavedView'].includes(n)?'__service_role_only__':'admin')}});
 it('keeps simulations structurally non-production',()=>{const s=r('base44/functions/founderOSSimulation/entry.ts');expect(s).toContain('production_effect:false');expect(s).toContain('simulation_only:true');expect(s).not.toMatch(/PaymentIntent|charges\.create|capture\(|DynamicAgreement\.update/)});
 it('has canonical deterministic company snapshot and metric catalog',()=>{const s=r('base44/shared/founderOSCore.ts');for(const x of ['collected_revenue','verified_savings','aggregate_addressable','aggregate_committed','company_health','founder_attention'])expect(s).toContain(x);expect(s).toContain('Merchant-side collected cash plus provider-side evidenced paid revenue')});
 it('supports why, scheduler health, 360, graph, war room and search through governed query layer',()=>{const s=r('base44/functions/founderOSQuery/entry.ts');for(const x of ['why_metric','scheduler_health','merchant_360','provider_360','company_graph','negotiation_war_room','search'])expect(s).toContain(x);expect(s).toContain('causal claims are operational hypotheses unless directly evidenced');expect(s).not.toContain("functions.invoke('commercialSendMessage'")});
 it('command gateway previews before material approval execution and audits it',()=>{const s=r('base44/functions/founderOSCommand/entry.ts');expect(s).toMatch(/action\s*===\s*["']resolve_approval["']/);expect(s).toMatch(/requires_confirmation\s*:\s*true/);expect(s).toContain('FounderCommandAudit.create');expect(s).toMatch(/functions\.invoke\(\s*["']resolveCommercialApproval["']/);expect(s).toContain('aggregate_contract_execution')});
 it('chat routes WHY and DO IT through founder OS rather than prose authority',()=>{const s=r('base44/functions/chatChiefOrchestrator/entry.ts');for(const x of ['founder_os_query','founder_command','founder_simulation','founder_chief_of_staff'])expect(s).toContain(x);expect(s).toContain('Financial state is deterministic');expect(s).toContain('Do not claim execution before confirmation');expect(s).toContain('material_action_preview')});
 it('chat never stores an empty no-response placeholder after a tool failure',()=>{const s=r('base44/functions/chatChiefOrchestrator/entry.ts');expect(s).toContain('commandLoopFallback');expect(s).toContain('No se ejecutó ninguna acción externa.');expect(s).not.toContain('"(no response)"')});
 it('chat stores structured evidence for rich rendering',()=>{expect(j('base44/entities/ChatMessage.jsonc').properties.tool_result_json).toBeTruthy();const s=r('src/components/admin/chat/ChatMessageBubble.jsx');expect(s).toContain('EvidenceResult');expect(s).toContain('Confirm — do it');expect(s).toContain('Simulation only')});
 it('admin home is Founder OS with Ask CAMBRA and why links',()=>{const s=r('src/pages/admin/AdminCommand.jsx');expect(s).toContain('getFounderOSCommandCenter');expect(s).toContain('founderChiefOfStaff');expect(s).toContain('What needs you');expect(s).toContain('Why?');expect(s).toContain('Ask CAMBRA')});
 it('admin approval UI never mutates Approval directly and the gateway routes aggregate contracts canonically',()=>{const ui=r('src/pages/admin/AdminApprovals.jsx');const gateway=r('base44/functions/founderOSCommand/entry.ts');expect(ui).toContain('founderOSCommand');expect(ui).toContain('confirmed: false');expect(ui).toContain('confirmed: true');expect(ui).not.toContain('entities.Approval.update');expect(gateway).toContain('aggregate_contract');expect(gateway).toContain('aggregate_contract_execution');expect(gateway).toContain('APPROVAL_RESOLUTION_REGISTRY');expect(gateway).toMatch(/functions\.invoke\(\s*["']resolveCommercialApproval["']/)});
 it('top bar includes global ask/command entry and mobile Ask CAMBRA',()=>{const s=r('src/pages/admin/AdminLayout.jsx');expect(s).toContain('Search or ask CAMBRA');expect(s).toContain("navigate('/admin/chat')");expect(s).toContain('Provider Economics')});
 it('Chief of Staff cannot invent comparison/trend and degrades to deterministic evidence',()=>{const s=r('base44/functions/founderChiefOfStaff/entry.ts');expect(s).toContain('ONLY supplied internal evidence');expect(s).toContain('Never invent a metric, trend, target, forecast or causal claim');expect(s).toContain('all authoritative values come from evidence_snapshot');expect(s).toContain("generated_by:'deterministic_fallback'");expect(s).toContain('performs no action')});
 it('company search truthfully labels itself bounded substring rather than semantic',()=>{const s=r('base44/shared/founderOSData.ts');expect(s).toContain("search_mode:'bounded_exact_substring'");expect(s).toContain('semantic_search:false')});
 it('agent authority still forbids approve sign spend and charge for every agent',async()=>{const m=await import('../../base44/shared/agentAuthority.ts');expect(m.assertNoMaterialAuthority()).toBe(true)});
});
