import{describe,it,expect}from'vitest';import fs from'node:fs';import{remediationFor,isAutomatic,requiresHuman,healthScore}from'../../base44/shared/maintenanceCore.ts';
const r=p=>fs.readFileSync(p,'utf8');
describe('P17 autonomous maintenance & self-healing',()=>{
 it('expired OAuth is safe-refresh eligible, not material authority',()=>{const s={key:'x',domain:'integration',type:'oauth_token_expired',severity:'warning',summary:'x'};const a=remediationFor(s);expect(a).toBe('refresh_oauth');expect(isAutomatic(a)).toBe(true);expect(requiresHuman(s,a)).toBe(false)});
 it('failed webhooks use bounded existing replay worker',()=>expect(remediationFor({key:'x',domain:'webhook',type:'webhook_retry_backlog',severity:'warning',summary:'x'})).toBe('replay_webhooks'));
 it('stuck jobs are terminated as stale rather than silently left running',()=>expect(remediationFor({key:'x',domain:'worker',type:'agent_task_stuck',severity:'warning',summary:'x'})).toBe('close_stale_task'));
 it('stale provider rates invoke the governed intelligence refresh path',()=>expect(remediationFor({key:'x',domain:'intelligence',type:'provider_pricing_stale',severity:'warning',summary:'x'})).toBe('refresh_provider_intelligence'));
 it('billing reconciliation can auto-run only the existing convergent reconciler',()=>{const s={key:'x',domain:'billing',type:'billing_reconciliation_error',severity:'critical',summary:'x'};expect(remediationFor(s)).toBe('reconcile_billing');expect(isAutomatic(remediationFor(s))).toBe(true)});
 it('degraded agent / external critical technical outage escalates to Developer investigation, not code mutation',()=>{const s={key:'x',domain:'worker',type:'agent_degraded',severity:'critical',summary:'x'};expect(remediationFor(s)).toBe('developer_investigation');expect(requiresHuman(s,remediationFor(s))).toBe(true);expect(r('base44/functions/developerSignalWorker/entry.ts')).toContain('no automatic patch')});
 it('security and material domains can never self-heal',()=>{for(const d of['security','contracts','permissions','authentication_policy','production_database','money_movement']){const s={key:d,domain:d,type:'issue',severity:'critical',summary:d};expect(remediationFor(s)).toBe('human_review');expect(requiresHuman(s,'human_review')).toBe(true)}});
 it('health score is deterministic and worsens with material incidents',()=>{expect(healthScore({critical:0,warning:0,stale:0,failedRepairs:0})).toBe(100);expect(healthScore({critical:2,warning:3,stale:1,failedRepairs:1})).toBeLessThan(30)});
 it('engine resolves incidents only after repair verification and records learning',()=>{const s=r('base44/functions/maintenanceEngine/entry.ts');expect(s).toContain("if(repair.verified)");expect(s).toContain('RemediationKnowledge');expect(s).toContain("status:'resolved'");expect(s).toContain("workflow_state:'human_review'");expect(s).toContain('repairs_verified');expect(s).toContain('repairs_failed')});
 it('OAuth internal authority is refresh-only and uses canonical secret verification',()=>{const s=r('base44/functions/oauthConnector/entry.ts');expect(s).toContain('mode === "refresh" && isInternalCaller(req, body)');expect(s).toContain('if (!user) return Response.json')});
 it('maintenance schedule and dependency security watch are active and bounded',()=>{const a=r('base44/functions/maintenanceEngine/function.jsonc'),d=r('base44/functions/dependencySecurityWorker/function.jsonc');expect(a).toContain('repeat_interval":10');expect(d).toContain('Dependabot');expect(r('base44/functions/dependencySecurityWorker/entry.ts')).toContain("domain:'security'");expect(r('base44/functions/dependencySecurityWorker/entry.ts')).toContain("automation_eligibility:'human_required'")});
 it('Founder OS exposes the Maintenance Center',()=>{expect(r('src/App.jsx')).toContain('/admin/maintenance');expect(r('src/pages/admin/AdminLayout.jsx')).toContain('Maintenance');expect(r('src/pages/admin/AdminCommand.jsx')).toContain("to:'/admin/maintenance'");expect(r('src/pages/admin/AdminMaintenance.jsx')).toContain('MONITOR → DETECT → DIAGNOSE → SAFE FIX → VERIFY → LOG → LEARN')});
 it('maintenance agent has no material authority',()=>{const s=r('base44/shared/agentAuthority.ts');expect(s).toContain('maintenance_engine:A({CAN_READ:true,CAN_WRITE:true,CAN_EXECUTE:true})');expect(s).toContain('assertNoMaterialAuthority')});
 it('P17 evidence entities are admin-only and track attempted/verified/failed learning',()=>{for(const p of['base44/entities/MaintenanceRun.jsonc','base44/entities/RemediationKnowledge.jsonc']){const j=JSON.parse(r(p));expect(j.rls.read.user_condition.role).toBe('admin');expect(j.rls.write.user_condition.role).toBe('admin')}const m=r('base44/entities/MaintenanceRun.jsonc');for(const x of['automatic_repairs','repairs_verified','repairs_failed','escalations','learning_updates'])expect(m).toContain(x)});
});