import{describe,it,expect}from'vitest';import fs from'node:fs';
const r=p=>fs.readFileSync(p,'utf8');
const packageVersion=JSON.parse(r('package.json')).version;
const exists=p=>fs.existsSync(p);

describe('P18 Operating Bible, Founder Handbook & Living Documentation',()=>{
 it('ships canonical Bible, founder handbook, source-derived agent catalog and actual failure playbooks',()=>{for(const p of['src/docs/CAMBRA_OPERATING_BIBLE.md','src/docs/CAMBRA_FOUNDER_HANDBOOK.md','src/docs/CAMBRA_AGENT_OPERATING_CATALOG.md','src/docs/P18_TROUBLESHOOTING_PLAYBOOKS.md','src/docs/P18_INCIDENT_PLAYBOOKS.md','src/docs/P18_EMERGENCY_CONTROLS.md'])expect(exists(p)).toBe(true);expect(r('src/docs/CAMBRA_OPERATING_BIBLE.md')).toContain('Routing Intelligence — PARTIALLY_IMPLEMENTED');expect(r('src/docs/CAMBRA_OPERATING_BIBLE.md')).toContain('Security and privacy — PARTIALLY_IMPLEMENTED');expect(r('src/docs/CAMBRA_AGENT_OPERATING_CATALOG.md')).toContain('SOURCE-DERIVED OPERATING CATALOG');expect(r('src/docs/CAMBRA_AGENT_OPERATING_CATALOG.md')).toContain('`documentation_maintenance`')});
 it('founder handbook is practical and available EN FR ES',()=>{const s=r('src/docs/CAMBRA_FOUNDER_HANDBOOK.md');for(const x of['## EN','## FR','## ES','What do I do every morning?','Que dois-je faire chaque matin ?','¿Qué hago cada mañana?','SAFE MODE'])expect(s).toContain(x)});
 it('registry classifies real systems and carries EN/FR/ES contextual help',()=>{const s=r('base44/shared/documentationRegistry.ts');for(const k of['founder_os','product','acquisition','recover','aggregate','provider_intelligence','moat','provider_economics','maintenance','billing','developer','security_privacy','routing','emergency_controls','ai_workforce','markets','documentation'])expect(s).toContain(`key:'${k}'`);expect(s).toContain(`DOCUMENTATION_SYSTEM_VERSION='${packageVersion}'`);expect(s).toContain('PARTIALLY_IMPLEMENTED');expect(s).toMatch(/Localized=\{en:string[,;]fr:string[,;]es:string\}/)});
 it('documentation query explicitly separates system documentation from live state',()=>{const s=r('base44/functions/documentationQuery/entry.ts');expect(s).toContain("live_state:false");expect(s).toContain('current operational state');expect(s).toContain('Founder OS live-state tools')});
 it('Ask CAMBRA routes how-does-this-work questions to documentation and live questions to Founder OS',()=>{const s=r('base44/functions/chatChiefOrchestrator/entry.ts')+'\n'+r('base44/shared/commandToolCatalog.ts');expect(s).toContain('name: "documentation_query"');expect(s).toContain('PRIMARY SYSTEM-BEHAVIOR DOCUMENTATION TOOL');expect(s).toContain('LIVE company questions');expect(s).toContain('Never answer a live-state question from documentation')});
 it('living documentation versions changes, learns from incidents and does not silently rewrite canonical prose',()=>{const s=r('base44/functions/documentationMaintenanceWorker/entry.ts');expect(s).toContain('DocumentationVersion.create');expect(s).toContain('DocumentationChangeProposal.create');expect(s).toContain("trigger_type:'incident'");expect(s).toContain("trigger_type:'remediation'");expect(s).toContain('Incident proposals never auto-edit canonical source documentation');expect(r('base44/functions/maintenanceEngine/entry.ts')).toContain("documentationMaintenanceWorker");expect(r('base44/functions/documentationMaintenanceWorker/function.jsonc')).toContain('Living Documentation Maintenance — daily')});
 it('P18 documentation evidence entities are admin-only',()=>{for(const p of['base44/entities/DocumentationObject.jsonc','base44/entities/DocumentationVersion.jsonc','base44/entities/DocumentationHealthAssessment.jsonc','base44/entities/DocumentationChangeProposal.jsonc']){const j=JSON.parse(r(p));expect(j.rls.read.user_condition.role).toBe('admin');expect(j.rls.write.user_condition.role).toBe('admin')}});
 it('release documentation drift gate hashes actual implementation paths and canonical docs',()=>{const g=r('scripts/generate-documentation-manifest.mjs'),c=r('scripts/check-documentation-drift.mjs');expect(g).toContain('documentation-drift-manifest.json');expect(g).toContain('CAMBRA_OPERATING_BIBLE.md');expect(c).toContain('documented behavior source changed without documentation closure');expect(c).toContain('zero drift')});
 it('Founder OS exposes contextual help and emergency controls',()=>{const a=r('src/App.jsx'),l=r('src/pages/admin/AdminLayout.jsx'),c=r('src/pages/admin/AdminCommand.jsx');expect(a).toContain('/admin/documentation');expect(l).toContain('How does this work?');expect(l).toContain('documentationTopic');expect(c).toContain('emergency_controls')});
 it('Maintenance Center includes Documentation Health from the P18 assessment',()=>{const api=r('base44/functions/getMaintenanceCenter/entry.ts'),ui=r('src/pages/admin/AdminMaintenance.jsx');expect(api).toContain('DocumentationHealthAssessment');expect(api).toContain('documentation_health_score');expect(ui).toContain('Documentation Health');expect(ui).toContain('documentation_drift')});
 it('SAFE MODE is explicit, confirmed and does not falsify financial truth',()=>{const s=r('base44/functions/emergencyControlAdmin/entry.ts')+r('base44/shared/emergencyControlAdminCore.ts'),d=r('src/docs/P18_EMERGENCY_CONTROLS.md');expect(s).toContain('ACTIVATE_CAMBRA_SAFE_MODE');expect(s).toContain('RESTORE_CAMBRA_AUTONOMY');expect(s).toContain('billing_issuance_paused:true');expect(d).toContain('Reconciliation');expect(d.toLowerCase()).toContain('does not automatically reactivate commercial policies')});
 it('SAFE MODE blocks material execution boundaries before side effects',()=>{const checks=[['base44/functions/commercialSendMessage/entry.ts','emergency_control_paused:communications'],['base44/functions/startPaymentsMigration/entry.ts','emergency_control_paused:migrations'],['base44/functions/createEligibleRecoverInvoices/entry.ts','emergency_control_paused:billing_issuance'],['base44/functions/startProviderNegotiation/entry.ts','emergency_control_paused:negotiations'],['base44/functions/providerNegotiationAgent/entry.ts','emergency_control_paused:negotiations'],['base44/functions/aggregateProcurementWorker/entry.ts','emergency_control_paused:negotiations'],['base44/functions/collectiveNegotiationAgent/entry.ts','emergency_control_paused:negotiations'],['base44/functions/providerMonetizationAgent/entry.ts','emergency_control_paused:negotiations']];for(const[p,x]of checks)expect(r(p)).toContain(x)});
 it('major user-facing email execution paths obey communications pause while internal alerts can remain observable',()=>{for(const p of['base44/functions/sendRecoverContractEmail/entry.ts','base44/functions/sendMonthlySavingsSummary/entry.ts','base44/functions/newsletterAgent/entry.ts','base44/functions/outreachAgent/entry.ts','base44/functions/onBrandCreated/entry.ts','base44/functions/joinCollective/entry.ts','base44/functions/submitCallRequest/entry.ts'])expect(r(p)).toMatch(/captureEmergencyEpoch\s*\([^)]*,\s*["']communications["']\s*,?\s*\)/s)});
 it('P18 never claims a universal agent kill switch that does not exist',()=>{const d=r('src/docs/P18_EMERGENCY_CONTROLS.md'),reg=r('base44/shared/documentationRegistry.ts');expect(d).toContain('There is no universal persisted kill switch for every internal/read-only agent');expect(reg).toContain('There is not yet one universal pause switch for every internal/read-only agent')});
 it('documentation maintenance has no approve/sign/spend/charge authority',()=>{const a=r('base44/shared/agentAuthority.ts');expect(a).toContain('documentation_maintenance:A({CAN_READ:true,CAN_WRITE:true,CAN_EXECUTE:true})');expect(a).toContain('assertNoMaterialAuthority')});
 it('production function census includes all P18 backend surfaces',()=>{const s=r('src/lib/productionFunctions.static.test.js');for(const x of['documentationQuery','documentationMaintenanceWorker','emergencyControlAdmin'])expect(s).toContain(`"${x}"`)});
 it('48h founder-return acceptance is structurally supported across P16/P17/P18',()=>{expect(r('src/pages/admin/AdminCommand.jsx')).toContain('What needs you');expect(r('base44/functions/maintenanceEngine/entry.ts')).toContain('repair_failed_escalated');expect(r('base44/functions/maintenanceEngine/entry.ts')).toContain('oauth_token_expired');expect(r('base44/functions/maintenanceEngine/entry.ts')).toContain('webhook_retry_backlog');expect(r('base44/functions/maintenanceEngine/entry.ts')).toContain('provider_pricing_stale');expect(r('base44/functions/maintenanceEngine/entry.ts')).toContain('agent_degraded');expect(r('base44/functions/documentationQuery/entry.ts')).toContain("mode:'documentation'");expect(r('base44/functions/chatChiefOrchestrator/entry.ts')).toContain('founder_command')});
});
