import {describe,it,expect} from 'vitest';
import {P2_MARKETS,assertP2MarketUniverse,availabilityKey,presenceKey,currencySupportKey,eligibilityKey,authorizationKey,assertionKey,canPromoteUnavailable,canPromoteMarketUnavailable,verifiedAtFor,canUseForVerifiedEconomics,canInheritAcrossMarkets,currencyEvidenceConsistent,resolveIdentity,regulatorySystemForMarket,researchOutcome,productAvailabilityDoesNotImplyEligibility} from './p2ProviderIntelligence.js';
describe('P2 provider intelligence invariants',()=>{
 it('keeps exactly 33 markets incl FR and independent LI/CH with BG EUR',()=>{expect(assertP2MarketUniverse()).toBe(true);expect(P2_MARKETS).toHaveLength(33);expect(P2_MARKETS.indexOf('LI')).not.toBe(P2_MARKETS.indexOf('CH'));});
 it('separates regulatory systems without changing market universe',()=>{expect(regulatorySystemForMarket('FR')).toBe('EU_EEA_PSD2');expect(regulatorySystemForMarket('LI')).toBe('EU_EEA_PSD2');expect(regulatorySystemForMarket('GB')).toBe('UK_PSR');expect(regulatorySystemForMarket('CH')).toBe('SWISS');expect(regulatorySystemForMarket('AD')).toBe('ANDORRAN');});
 it('separates market presence, product availability and merchant eligibility keys',()=>{expect(presenceKey({provider_id:'stripe',market:'LI'})).toBe('stripe|LI');expect(availabilityKey({provider_id:'stripe',product_id:'terminal',market:'LI',channel:'IN_PERSON'})).toBe('stripe|terminal|LI|IN_PERSON');expect(eligibilityKey({provider_product_id:'stripe-terminal',market:'LI',segment:'SMB'})).toBe('stripe-terminal|LI|SMB');});
 it('types currency support by product, market and usage',()=>{expect(currencySupportKey({provider_product_id:'stripe-terminal',market:'LI',currency:'CHF',usage_type:'PRESENTMENT'})).toBe('stripe-terminal|LI|CHF|PRESENTMENT');expect(()=>currencySupportKey({provider_product_id:'x',market:'LI',currency:'CHF',usage_type:'MAGIC'})).toThrow();});
 it('creates stable authorization and evidence assertion identities',()=>{expect(authorizationKey({provider_legal_entity_id:'le1',jurisdiction:'IE',authorization_number:'123'})).toBe('le1|IE|123');expect(assertionKey({subject_type:'ProviderProduct',subject_id:'terminal',predicate:'AVAILABLE_IN',market:'LI',evidence_id:'ev1'})).toBe('ProviderProduct|terminal|AVAILABLE_IN|LI|ev1');});
 it('requires explicit evidence for negative availability/presence',()=>{expect(canPromoteUnavailable({availability:'UNAVAILABLE',research_state:'RESOLVED',evidence_refs:[]})).toBe(false);expect(canPromoteUnavailable({availability:'UNAVAILABLE',research_state:'RESOLVED',evidence_refs:['official']})).toBe(true);expect(canPromoteMarketUnavailable({presence_state:'UNAVAILABLE',research_state:'RESOLVED',evidence_refs:[]})).toBe(false);});
 it('does not fake verified_at',()=>{expect(verifiedAtFor('LOW','2026-01-01')).toBeNull();expect(verifiedAtFor('VERIFIED','2026-01-01')).toBe('2026-01-01');});
 it('isolates estimates from verified economics',()=>{expect(canUseForVerifiedEconomics({provenance:'ESTIMATED'})).toBe(false);expect(canUseForVerifiedEconomics({provenance:'CONTRACT_OBSERVED'})).toBe(true);});
 it('prohibits cross-market inheritance absent explicit scope',()=>{expect(canInheritAcrossMarkets({applicable_markets:['DE']},'IT')).toBe(false);expect(canInheritAcrossMarkets({applicable_markets:['DE','IT']},'IT')).toBe(true);});
 it('surfaces currency/evidence mismatch without equating market currency',()=>{expect(currencyEvidenceConsistent({currency:'EUR',evidence_currency:'PLN'})).toBe(false);expect(currencyEvidenceConsistent({currency:'USD',evidence_currency:'USD',market:'PL'})).toBe(true);});
 it('never fuzzy-merges similar names',()=>{expect(resolveIdentity({name:'Stripee'},[{name:'Stripe',aliases:[],domains:[]}]).outcome).toBe('UNCERTAIN');});
 it('allows researched-none-found as a valid auditable result',()=>{expect(researchOutcome({attempted:true})).toBe('RESEARCHED_NONE_FOUND');expect(researchOutcome({attempted:true,candidates:2})).toBe('CANDIDATES_FOUND');expect(researchOutcome({attempted:true,verified:1})).toBe('VERIFIED');expect(researchOutcome({attempted:true,conflicts:1})).toBe('CONFLICT');});
 it('never equates product availability with merchant eligibility',()=>{expect(productAvailabilityDoesNotImplyEligibility({availability:'AVAILABLE',eligibility:'UNKNOWN'})).toBe(true);expect(productAvailabilityDoesNotImplyEligibility({availability:'AVAILABLE',eligibility:'ELIGIBLE'})).toBe(false);});
});
