import{describe,it,expect}from'vitest';
import{assertP3MarketUniverse,P3_MARKETS,bpsToPpm,percentToPpm,ppmToPercent,validateRateComponent,validateObservation,semanticFingerprint,resolvePricing,evaluateComponents,canAutoPromote,classifyLegacyRate,migrateLegacyToP3,researchStateClosed,p2P3Consistency}from'./p3RateIntelligence.js';

describe('P3 European Rate Intelligence invariants',()=>{
 it('has exactly 33 markets, FR, independent LI/CH and BG EUR',()=>{expect(assertP3MarketUniverse()).toBe(true);expect(P3_MARKETS).toHaveLength(33);expect(P3_MARKETS).toContain('FR');expect(P3_MARKETS).toContain('LI');expect(P3_MARKETS).toContain('CH');expect(P3_MARKETS.indexOf('LI')).not.toBe(P3_MARKETS.indexOf('CH'));});
 it('uses ppm as exact canonical percentage storage',()=>{expect(bpsToPpm(149)).toBe(14900);expect(percentToPpm(0.015)).toBe(150);expect(ppmToPercent(150)).toBe(.015);});
 it('rejects fractional canonical ppm',()=>expect(validateRateComponent({component_type:'PROCESSING_FEE',percentage_ppm:14900.5,value_mode:'KNOWN'}).ok).toBe(false));
 it('requires currency for fixed money',()=>expect(validateRateComponent({component_type:'FIXED_TRANSACTION_FEE',amount_minor:25,value_mode:'KNOWN'}).errors).toContain('money_component_requires_currency'));
 it('allows percentage without currency',()=>expect(validateRateComponent({component_type:'PROCESSING_FEE',percentage_ppm:15000,value_mode:'KNOWN'}).ok).toBe(true));
 it('allows mixed-currency components',()=>{const a=validateRateComponent({component_type:'PROCESSING_FEE',amount_minor:13,currency:'USD',value_mode:'KNOWN'}),b=validateRateComponent({component_type:'PAYMENT_METHOD_FEE',amount_minor:22,currency:'EUR',value_mode:'KNOWN'});expect(a.ok&&b.ok).toBe(true)});
 it('supports caps/minimums without floats',()=>expect(validateRateComponent({component_type:'PAYMENT_METHOD_FEE',percentage_ppm:10000,maximum_amount_minor:50,currency:'EUR',value_mode:'KNOWN'}).ok).toBe(true));
 it('forbids numeric value on UNKNOWN/PASS_THROUGH components',()=>expect(validateRateComponent({component_type:'ACQUIRER_MARGIN',percentage_ppm:1000,value_mode:'UNKNOWN'}).ok).toBe(false));
 it('allows IC++ partial structure with pass-through and unknown margin',()=>{const cs=[{component_type:'INTERCHANGE',value_mode:'PASS_THROUGH'},{component_type:'SCHEME_FEE',value_mode:'PASS_THROUGH'},{component_type:'ACQUIRER_MARGIN',value_mode:'UNKNOWN'}];expect(cs.every(c=>validateRateComponent(c).ok)).toBe(true)});
 it('unknown is never zero',()=>expect(validateRateComponent({component_type:'ACQUIRER_MARGIN',value_mode:'UNKNOWN'}).ok).toBe(true));
 it('custom quote never requires/invents numeric public rate',()=>{const o={provider_slug:'adyen',market:'FR',pricing_model:'INTERCHANGE_PLUS_PLUS',pricing_visibility:'CUSTOM_QUOTE',observation_type:'UNKNOWN',verification_status:'RESEARCHED',scope_type:'MARKET'};expect(validateObservation(o,[]).ok).toBe(true)});
 it('forbids verified_at on unverified status',()=>expect(validateObservation({provider_slug:'x',market:'FR',pricing_model:'CUSTOM',pricing_visibility:'UNKNOWN',verification_status:'RESEARCHED',verified_at:'2026-08-10T00:00:00Z',scope_type:'MARKET'},[]).errors).toContain('verified_at_without_verification'));
 it('requires verified_at for verified primary',()=>expect(validateObservation({provider_slug:'x',market:'FR',pricing_model:'CUSTOM',pricing_visibility:'UNKNOWN',verification_status:'VERIFIED_PRIMARY',scope_type:'MARKET'},[]).errors).toContain('verified_status_requires_verified_at'));
 it('does not turn retrieved_at into effective_from when effective date is unknown',()=>expect(validateObservation({provider_slug:'x',market:'FR',pricing_model:'CUSTOM',pricing_visibility:'UNKNOWN',verification_status:'RESEARCHED',scope_type:'MARKET',retrieved_at:'2026-08-10T00:00:00Z',effective_from:'2026-08-10T00:00:00Z',effective_date_certainty:'UNKNOWN'},[]).errors).toContain('retrieved_at_must_not_be_invented_effective_from'));
 it('empty country never means global',()=>expect(validateObservation({provider_slug:'x',market:'',country:'',pricing_model:'CUSTOM',pricing_visibility:'UNKNOWN',verification_status:'RESEARCHED',scope_type:'GLOBAL'},[]).errors).toContain('empty_market_never_global'));
 it('generic bank pseudo-provider cannot be verified',()=>expect(validateObservation({provider_slug:'bank_tpv_es_generic',market:'ES',pricing_model:'BLENDED',pricing_visibility:'PUBLIC_COMPLETE',verification_status:'VERIFIED_PRIMARY',verified_at:'2026-08-10T00:00:00Z',scope_type:'MARKET'},[]).errors).toContain('generic_bank_placeholder_cannot_be_verified'));
 it('legacy estimates cannot be verified',()=>expect(validateObservation({provider_slug:'sumup',market:'ES',pricing_model:'BLENDED',pricing_visibility:'PUBLIC_COMPLETE',observation_type:'LEGACY_ESTIMATE',verification_status:'VERIFIED_PRIMARY',verified_at:'2026-08-10T00:00:00Z',scope_type:'MARKET'},[]).errors).toContain('legacy_estimate_cannot_be_verified'));
 it('achievable rate is forbidden in P3 truth',()=>expect(validateObservation({provider_slug:'x',market:'FR',pricing_model:'BLENDED',pricing_visibility:'PUBLIC_COMPLETE',verification_status:'RESEARCHED',scope_type:'MARKET',achievable_percent_bps:100},[]).errors).toContain('achievable_rate_forbidden_in_p3'));
 it('market scope cannot silently inherit another market',()=>expect(validateObservation({provider_slug:'sumup',market:'ES',pricing_model:'BLENDED',pricing_visibility:'PUBLIC_COMPLETE',verification_status:'RESEARCHED',scope_type:'MARKET',applicable_markets:['ES','FR']},[]).ok).toBe(false));
 it('semantic fingerprint is deterministic and order-stable',()=>{const o={provider_slug:'stripe',market:'ES',channel:'IN_PERSON',pricing_model:'FIXED_PLUS_PERCENT',pricing_visibility:'PUBLIC_COMPLETE',scope_type:'MARKET'};const a=[{component_type:'PROCESSING_FEE',percentage_ppm:14000,value_mode:'KNOWN'},{component_type:'FIXED_TRANSACTION_FEE',amount_minor:10,currency:'EUR',value_mode:'KNOWN'}];expect(semanticFingerprint({observation:o,components:a})).toBe(semanticFingerprint({observation:o,components:[...a].reverse()}));});
});

describe('P3 deterministic resolver',()=>{
 const base={status:'CURRENT',verification_status:'VERIFIED_PRIMARY',verified_at:'2026-08-10T00:00:00Z',pricing_visibility:'PUBLIC_COMPLETE',pricing_model:'FIXED_PLUS_PERCENT',scope_type:'MARKET',observation_type:'PUBLIC_PUBLISHED',recorded_at:'2026-08-10T00:00:00Z'};
 it('never matches ES rate to FR',()=>{const r=resolvePricing([{...base,provider_slug:'sumup',market:'ES',channel:'IN_PERSON',semantic_fingerprint:'es'}],{provider_slug:'sumup',market:'FR',channel:'IN_PERSON',date:'2026-08-10T12:00:00Z'});expect(r.outcome).toBe('UNKNOWN')});
 it('never matches CH to LI',()=>{const r=resolvePricing([{...base,provider_slug:'worldline',market:'CH',semantic_fingerprint:'ch'}],{provider_slug:'worldline',market:'LI',date:'2026-08-10T12:00:00Z'});expect(r.outcome).toBe('UNKNOWN')});
 it('allows explicit evidenced multi-market scope only through applicable_markets',()=>{const o={...base,provider_slug:'worldline',market:'CH',scope_type:'EEA',applicable_markets:['DE','BE'],semantic_fingerprint:'eea'};expect(resolvePricing([o],{provider_slug:'worldline',market:'DE',date:'2026-08-10T12:00:00Z'}).outcome).toBe('EXACT_MATCH');expect(resolvePricing([o],{provider_slug:'worldline',market:'IT',date:'2026-08-10T12:00:00Z'}).outcome).toBe('UNKNOWN')});
 it('distinguishes Stripe Terminal from ecommerce',()=>{const obs=[{...base,provider_slug:'stripe',market:'ES',channel:'IN_PERSON',provider_product_id:'terminal',semantic_fingerprint:'t'},{...base,provider_slug:'stripe',market:'ES',channel:'ECOMMERCE',provider_product_id:'payments',semantic_fingerprint:'e'}];expect(resolvePricing(obs,{provider_slug:'stripe',market:'ES',channel:'IN_PERSON',provider_product_id:'terminal',date:'2026-08-10T12:00:00Z'}).match.semantic_fingerprint).toBe('t')});
 it('returns MULTIPLE_MATCHES for equally specific conflicting semantics',()=>{const obs=[{...base,provider_slug:'x',market:'FR',semantic_fingerprint:'a'},{...base,provider_slug:'x',market:'FR',semantic_fingerprint:'b'}];expect(resolvePricing(obs,{provider_slug:'x',market:'FR',date:'2026-08-10T12:00:00Z'}).outcome).toBe('MULTIPLE_MATCHES')});
 it('returns custom quote instead of a fake number',()=>{const r=resolvePricing([{...base,provider_slug:'adyen',market:'FR',pricing_visibility:'CUSTOM_QUOTE',semantic_fingerprint:'c'}],{provider_slug:'adyen',market:'FR',date:'2026-08-10T12:00:00Z'});expect(r.outcome).toBe('CUSTOM_QUOTE')});
 it('resolves historical effective periods',()=>{const obs=[{...base,provider_slug:'x',market:'FR',effective_from:'2026-01-01T00:00:00Z',effective_to:'2026-06-30T23:59:59Z',semantic_fingerprint:'old'},{...base,provider_slug:'x',market:'FR',effective_from:'2026-07-01T00:00:00Z',semantic_fingerprint:'new'}];expect(resolvePricing(obs,{provider_slug:'x',market:'FR',date:'2026-03-01T00:00:00Z'}).match.semantic_fingerprint).toBe('old');expect(resolvePricing(obs,{provider_slug:'x',market:'FR',date:'2026-08-01T00:00:00Z'}).match.semantic_fingerprint).toBe('new')});
 it('supports knowledge-time queries separately from valid time',()=>{const obs=[{...base,provider_slug:'x',market:'FR',recorded_at:'2026-08-10T00:00:00Z',semantic_fingerprint:'seen-later'}];expect(resolvePricing(obs,{provider_slug:'x',market:'FR',date:'2026-07-01T00:00:00Z',known_as_of:'2026-08-01T00:00:00Z'}).outcome).toBe('UNKNOWN');expect(resolvePricing(obs,{provider_slug:'x',market:'FR',date:'2026-07-01T00:00:00Z',known_as_of:'2026-08-11T00:00:00Z'}).outcome).toBe('EXACT_MATCH')});
 it('returns stale explicitly',()=>expect(resolvePricing([{...base,provider_slug:'x',market:'FR',verification_status:'STALE',status:'STALE',semantic_fingerprint:'s'}],{provider_slug:'x',market:'FR',date:'2026-08-10T12:00:00Z'}).outcome).toBe('STALE'));
 it('returns partial match and missing dimensions rather than guessing',()=>{const r=resolvePricing([{...base,provider_slug:'x',market:'FR',semantic_fingerprint:'broad'}],{provider_slug:'x',market:'FR',channel:'ECOMMERCE',date:'2026-08-10T12:00:00Z'});expect(r.outcome).toBe('PARTIAL_MATCH');expect(r.missing_dimensions).toContain('channel')});
});

describe('P3 component evaluation',()=>{
 it('applies percentage and fixed fee',()=>{const r=evaluateComponents([{component_type:'PROCESSING_FEE',percentage_ppm:14000,value_mode:'KNOWN',unit_basis:'PER_TRANSACTION'},{component_type:'FIXED_TRANSACTION_FEE',amount_minor:10,currency:'EUR',value_mode:'KNOWN',unit_basis:'PER_TRANSACTION'}],{transaction_amount_minor:10000});expect(r.calculated_amount_minor).toBe(150);expect(r.calculation_status).toBe('COMPLETE')});
 it('applies Paysera-style maximum cap',()=>{const c=[{component_type:'PAYMENT_METHOD_FEE',percentage_ppm:10000,maximum_amount_minor:50,currency:'EUR',value_mode:'KNOWN',unit_basis:'PER_TRANSACTION'}];expect(evaluateComponents(c,{transaction_amount_minor:1000}).calculated_amount_minor).toBe(10);expect(evaluateComponents(c,{transaction_amount_minor:10000}).calculated_amount_minor).toBe(50)});
 it('does not add monthly fee per transaction',()=>{const r=evaluateComponents([{component_type:'MONTHLY_FEE',amount_minor:995,currency:'EUR',value_mode:'KNOWN',unit_basis:'PER_MONTH'}],{transaction_amount_minor:10000});expect(r.calculated_amount_minor).toBe(0);expect(r.excluded_components).toHaveLength(1)});
 it('returns PARTIAL when IC++ margin is unknown',()=>{const r=evaluateComponents([{component_type:'INTERCHANGE',value_mode:'PASS_THROUGH'},{component_type:'SCHEME_FEE',value_mode:'PASS_THROUGH'},{component_type:'ACQUIRER_MARGIN',value_mode:'UNKNOWN'}],{transaction_amount_minor:10000});expect(r.calculation_status).toBe('PARTIAL');expect(r.unknown_components).toHaveLength(3)});
});

describe('P3 promotion and legacy migration',()=>{
 it('only auto-promotes unambiguous high-confidence primary evidence',()=>{expect(canAutoPromote({source_authority:'PRIMARY',market_unambiguous:true,product_unambiguous:true,channel_unambiguous:true,currency_valid:true,temporal_valid:true,parser_confidence:.99,no_conflict:true,invariants_ok:true})).toBe(true);expect(canAutoPromote({source_authority:'SECONDARY',market_unambiguous:true,product_unambiguous:true,channel_unambiguous:true,currency_valid:true,temporal_valid:true,parser_confidence:.99,no_conflict:true,invariants_ok:true})).toBe(false)});
 it('classifies generic pseudo-provider as placeholder',()=>expect(classifyLegacyRate({provider_slug:'bank_tpv_fr_generic',country:'FR'}).classification).toBe('GENERIC_PLACEHOLDER'));
 it('classifies unverified SumUp as legacy estimate',()=>expect(classifyLegacyRate({provider_slug:'sumup',country:'ES',verified:false}).classification).toBe('LEGACY_ESTIMATE'));
 it('does not treat empty country as global',()=>expect(classifyLegacyRate({provider_slug:'stripe',country:'',verified:false}).classification).toBe('INVALID_SCOPE'));
 it('flags unevidenced international uplift',()=>expect(classifyLegacyRate({provider_slug:'stripe',country:'FR',verified:true,source_url:'x',source_quote:'y',intl_uplift_bps:175}).reasons).toContain('unevidenced_international_uplift'));
 it('quarantines achievable fields for downstream P5',()=>expect(classifyLegacyRate({provider_slug:'stripe',country:'FR',achievable_percent_bps:100}).reasons).toContain('achievable_fields_quarantine_for_p5'));
 it('migrates verified fixed+percent into ppm without copying achievable rate',()=>{const m=migrateLegacyToP3({id:'1',cohort_key:'stripe|ANY|EU-FR',provider_slug:'stripe',country:'FR',channel:'online',percent_bps:150,fixed_fee_minor_units:25,fixed_fee_currency:'EUR',verified:true,source_url:'https://stripe.com/fr/pricing',source_quote:'1.5% + 0.25',verified_at:'2026-08-10T00:00:00Z',achievable_percent_bps:100});expect(m.observation.verification_status).toBe('VERIFIED_PRIMARY');expect(m.components[0].percentage_ppm).toBe(15000);expect(m.observation.achievable_percent_bps).toBeUndefined()});
 it('does not create verified timestamp for legacy estimate',()=>{const m=migrateLegacyToP3({id:'1',cohort_key:'sumup|ANY|EU',provider_slug:'sumup',country:'ES',channel:'in_store',percent_bps:175,fixed_fee_minor_units:0,fixed_fee_currency:'EUR',verified:false});expect(m.observation.verified_at).toBeNull();expect(m.observation.status).toBe('QUARANTINED')});
 it('recognizes honest terminal research states',()=>{expect(researchStateClosed('UNKNOWN_AFTER_RESEARCH')).toBe(true);expect(researchStateClosed('NOT_RESEARCHED')).toBe(false)});
 it('routes P3/P2 identity contradictions to review instead of mutating P2',()=>expect(p2P3Consistency({p2_availability:'UNAVAILABLE',p2_market:'FR',p3_market:'FR',p2_product_id:'x',p3_product_id:'x'}).event).toBe('PROVIDER_TRUTH_CONSISTENCY_REVIEW_REQUIRED'));
});
