import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
describe('partner acquisition autonomy',()=>{
 it('has a separate partner prospect entity and engine',()=>{expect(read('base44/entities/PartnerProspect.jsonc')).toContain('accounting_firm');expect(read('base44/entities/CommunicationThread.jsonc')).toContain('partner_acquisition');expect(read('base44/entities/CommercialPolicy.jsonc')).toContain('partner_acquisition')});
 it('worker is really registered hourly and fail-closed without active policy',()=>{const cfg=read('base44/functions/autonomousPartnerWorker/function.jsonc');const src=read('base44/functions/autonomousPartnerWorker/entry.ts');expect(cfg).toContain('"repeat_interval": 1');expect(cfg).toContain('"is_active": true');expect(src).toContain('partner_policy_missing');expect(src).toContain('outside_business_hours')});
 it('discovers partners through Apollo with GDPR provenance and suppression',()=>{const s=read('base44/functions/autonomousPartnerWorker/entry.ts');expect(s).toContain('mixed_people/api_search');expect(s).toContain("legal_basis:'legitimate_interest'");expect(s).toContain('ContactSuppression');expect(s).toContain('PartnerProspect')});
 it('scores distribution multipliers separately from merchant leads',()=>{const s=read('base44/functions/autonomousPartnerWorker/entry.ts');expect(s).toContain('decision_maker');expect(s).toContain('target_partner_type');expect(s).toContain('commerce_relevance');expect(s).toContain('business_domain')});
 it('uses canonical sender, thread, follow-up and Outlook meeting stack',()=>{const s=read('base44/functions/autonomousPartnerWorker/entry.ts');const r=read('base44/functions/commercialReplyAgent/entry.ts');const m=read('base44/functions/outlookMeetingCoordinator/entry.ts');expect(s).toContain("engine:'partner_acquisition'");expect(s).toContain("commercialSendMessage");expect(r).toContain("['merchant_acquisition','partner_acquisition','aggregate_procurement']");expect(m).toContain("['merchant_acquisition','partner_acquisition','aggregate_procurement']")});

 it('uses Claude Sonnet 4.5 for the first partner email and never hardcodes a signature in the draft',()=>{const s=read('base44/functions/autonomousPartnerWorker/entry.ts');expect(s).toContain("model:'claude-sonnet-4-5'");expect(s).toContain('claudeDraft');expect(s).toContain('Do NOT add a signature');expect(s).not.toContain('CAMBRA Partnerships`:');});
 it('deduplicates partner outreach at organization-domain level',()=>{const s=read('base44/functions/autonomousPartnerWorker/entry.ts');expect(s).toContain('contactedOrgDomains');expect(s).toContain('seenOrgDomains');});
 it('does not auto-activate partner policy in code',()=>{const s=read('base44/functions/commercialPolicyAdmin/entry.ts');expect(s).toContain("status: 'draft'");expect(s).toContain('APPROVE_AUTONOMY_POLICY')});
});
