import { safeBestEffort } from '../../shared/bestEffort.ts';
import{createClientFromRequest}from'npm:@base44/sdk@0.8.41';
Deno.serve(async req=>{try{const b=createClientFromRequest(req),u=await b.auth.me().catch((error:any)=>safeBestEffort(error,{operation:'intelligenceAdmin',fallback:null,severity:'secondary'}));if(!u)return Response.json({ok:false,error:'Unauthorized'},{status:401});if(u.role!=='admin')return Response.json({ok:false,error:'Forbidden'},{status:403});const body=await req.json().catch(()=>({})),s=b.asServiceRole,a=String(body.action||''),reason=String(body.reason||'').trim();if(!reason)return Response.json({ok:false,error:'reason_required'},{status:400});let before:any=null,after:any=null,subject='';
if(a==='quarantine_evidence'){before=await s.entities.IntelligenceEvidence.get(String(body.id||'')).catch((error:any)=>safeBestEffort(error,{operation:'intelligenceAdmin',fallback:null,severity:'secondary'}));if(!before)return Response.json({ok:false,error:'not_found'},{status:404});await s.entities.IntelligenceEvidence.update(before.id,{quarantined:true,quarantine_reason:reason});after={...before,quarantined:true,quarantine_reason:reason};subject=`IntelligenceEvidence:${before.id}`}
else if(a==='set_claim_state'){before=await s.entities.KnowledgeClaim.get(String(body.id||'')).catch((error:any)=>safeBestEffort(error,{operation:'intelligenceAdmin',fallback:null,severity:'secondary'}));if(!before)return Response.json({ok:false,error:'not_found'},{status:404});const state=String(body.state||'');if(!['candidate','observed','corroborated','verified','active','stale','superseded','archived','quarantined'].includes(state))return Response.json({ok:false,error:'invalid_state'},{status:400});if(['verified','active'].includes(state)&&String(before.truth_level||'')==='inferred')return Response.json({ok:false,error:'inferred_claim_cannot_be_admin_promoted_to_verified_without_new_evidence'},{status:409});await s.entities.KnowledgeClaim.update(before.id,{knowledge_state:state});after={...before,knowledge_state:state};subject=`KnowledgeClaim:${before.id}`}
else if(a==='resolve_conflict'){before=await s.entities.KnowledgeConflict.get(String(body.id||'')).catch((error:any)=>safeBestEffort(error,{operation:'intelligenceAdmin',fallback:null,severity:'secondary'}));if(!before)return Response.json({ok:false,error:'not_found'},{status:404});const state=String(body.state||'resolved');if(!['resolved','expected_variation','data_error'].includes(state))return Response.json({ok:false,error:'invalid_state'},{status:400});after={...before,status:state,resolution_json:{reason,notes:body.notes||''},resolved_at:new Date().toISOString(),resolved_by:u.email};await s.entities.KnowledgeConflict.update(before.id,{status:after.status,resolution_json:after.resolution_json,resolved_at:after.resolved_at,resolved_by:u.email});subject=`KnowledgeConflict:${before.id}`}
else if(a==='recalculate_moat'){const internal=Deno.env.get('INTERNAL_CALL_SECRET')||'';const r=await s.functions.invoke('moatCuratorWorker',{internal_secret:internal});before={};after=r?.data||r;subject='MoatMetric:recalculation'}
else return Response.json({ok:false,error:'unknown_action'},{status:400});
await s.entities.OperationalLog.create({event_type:'intelligence_override',message:a,data_json:{subject,reason,before,after},actor_email:u.email,created_at:new Date().toISOString()}).catch((error:any)=>safeBestEffort(error,{operation:'intelligenceAdmin',fallback:null,severity:'secondary'}));return Response.json({ok:true,action:a,subject})}catch(e){console.error(e);return Response.json({ok:false,error:'intelligence_admin_failed'},{status:500})}});
