import { safeBestEffort } from '../../shared/bestEffort.ts';
import{createClientFromRequest}from'npm:@base44/sdk@0.8.41';import{FOUNDER_OS_VERSION,safeNumber}from'../../shared/founderOSCore.ts';import{handleFounderMeetingAdmin}from'../founderMeetingAdmin/entry.ts';
import { internalErrorResponse } from '../../shared/publicErrors.ts';
const commercial=new Set(['final_provider_deal','aggregate_contract','aggregate_contract_execution','commercial_reply_exception','provider_negotiation_review','aggregate_procurement_review','contract_mismatch','contract_exception','post_meeting_commitment_review']);
const founderMeetingActions=new Set(['status','configure_policy','command','record_outcome','mark_no_show','cancel_meeting']);
const executableAgents:Record<string,string>=Object.freeze({outreach:'outreachAgent',follow_up:'followUpAgent',meeting:'meetingAgent',founder_meeting:'outlookMeetingCoordinator',blog:'blogAgent',linkedin:'linkedinAgent',x_twitter:'xTwitterAgent',newsletter:'newsletterAgent'});
const key=()=>`founder-command:${crypto.randomUUID()}`;
Deno.serve(async req=>{const routedAction=String((await req.clone().json().catch(()=>({})))?.action||'');if(founderMeetingActions.has(routedAction))return handleFounderMeetingAdmin(req);try{const b=createClientFromRequest(req),u=await b.auth.me().catch((error:any)=>safeBestEffort(error,{operation:'founderOSCommand',fallback:null,severity:'secondary'}));if(!u||u.role!=='admin')return Response.json({ok:false,error:'Forbidden'},{status:403});const body=await req.json().catch(()=>({})),action=String(body.action||''),confirmed=body.confirmed===true,s=b.asServiceRole,created_at=new Date().toISOString(),commandKey=String(body.command_key||key());if(!action)return Response.json({ok:false,error:'action_required'},{status:400});
 let preview:any={action,version:FOUNDER_OS_VERSION},risk=2,material=false,requires=true,result:any=null,status='previewed';
 if(action==='resolve_approval'){
  const id=String(body.approval_id||'');const a=await s.entities.Approval.get(id).catch((error:any)=>safeBestEffort(error,{operation:'founderOSCommand',fallback:null,severity:'secondary'}));if(!a)return Response.json({ok:false,error:'approval_not_found'},{status:404});const task=a.agent_task_id?await s.entities.AgentTask.get(a.agent_task_id).catch((error:any)=>safeBestEffort(error,{operation:'founderOSCommand',fallback:null,severity:'secondary'})):null;risk=safeNumber(a.risk_level);material=risk>=4;requires=true;preview={action:'resolve_approval',decision:String(body.decision||'approve'),approval_id:a.id,action_type:a.action_type,risk_level:risk,material,related_entity_type:a.related_entity_type,related_entity_id:a.related_entity_id,expires_at:a.expires_at,summary:String(a.draft_content||'').slice(0,1500),financial_impact:a.draft_payload_json?.estimated_financial_impact??a.draft_payload_json?.expected_provider_revenue_12m_minor??null,reversible:material?'partially_or_not_reversible':'generally_reversible',resolver:commercial.has(a.action_type)?'resolveCommercialApproval':task?.agent_name&&executableAgents[String(task.agent_name)]?executableAgents[String(task.agent_name)]:'approval_state_only'};
  if(!confirmed){await s.entities.FounderCommandAudit.create({command_key:commandKey,conversation_id:body.conversation_id||'',actor_email:u.email,intent:'approval',action,scope_json:{approval_id:id},risk_level:risk,material,requires_confirmation:true,confirmed:false,preview_json:preview,status:'previewed',result_json:{},policy_json:{founder_os_version:FOUNDER_OS_VERSION},created_at});return Response.json({ok:true,requires_confirmation:true,command_key:commandKey,preview});}
  const decision=String(body.decision||'approve');if(!['approve','reject'].includes(decision))return Response.json({ok:false,error:'decision_must_be_approve_or_reject'},{status:400});if(a.status!=='pending')return Response.json({ok:false,error:'approval_not_pending',status:a.status},{status:409});
  if(commercial.has(a.action_type)){const r=await b.functions.invoke('resolveCommercialApproval',{approval_id:a.id,decision,reason:body.reason||''});result=r?.data||r;if(result?.ok===false)throw new Error(result.error||'commercial_approval_failed');}
  else if(decision==='reject'){await s.entities.Approval.update(a.id,{status:'rejected',approved_by:u.email,approved_at:new Date().toISOString(),rejected_reason:String(body.reason||'')});result={ok:true,status:'rejected',execution:false};}
  else if(task?.agent_name&&executableAgents[String(task.agent_name)]){await s.entities.Approval.update(a.id,{status:'approved',approved_by:u.email,approved_at:new Date().toISOString()});const fn=executableAgents[String(task.agent_name)];const r=await b.functions.invoke(fn,{mode:'execute',approval_id:a.id});result=r?.data||r;if(result?.ok===false)throw new Error(result.error||`${fn}_execute_failed`);}
  else {await s.entities.Approval.update(a.id,{status:'approved',approved_by:u.email,approved_at:new Date().toISOString()});result={ok:true,status:'approved',execution:false,note:'Approval state recorded. Domain execution remains a separate canonical operation because no safe resolver is registered for this approval type.'};}
  status='executed';
 }
 else if(action==='run_provider_revenue_recovery'){risk=3;material=false;const providerId=String(body.provider_id||'');preview={action,provider_id:providerId||null,impact:'Contacts provider only through existing policy-gated recovery agent; no settlement or contract acceptance.',reversible:true};if(!confirmed){await s.entities.FounderCommandAudit.create({command_key:commandKey,conversation_id:body.conversation_id||'',actor_email:u.email,intent:'provider_revenue_recovery',action,scope_json:{provider_id:providerId},risk_level:risk,material,requires_confirmation:true,confirmed:false,preview_json:preview,status:'previewed',result_json:{},policy_json:{founder_os_version:FOUNDER_OS_VERSION},created_at});return Response.json({ok:true,requires_confirmation:true,command_key:commandKey,preview});}const r=await b.functions.invoke('providerRevenueRecoveryAgent',{provider_id:providerId||undefined});result=r?.data||r;status='executed';}
 else if(action==='run_system_health'){risk=1;requires=false;preview={action,material:false,reversible:true};const r=await b.functions.invoke('systemHealthAgent',{});result=r?.data||r;status='executed';}
 else if(action==='investigate_developer'){risk=1;requires=false;preview={action,incident_id:body.incident_id||null,material:false,reversible:true};const r=await b.functions.invoke('developerSignalWorker',{incident_id:body.incident_id||undefined});result=r?.data||r;status='executed';}
 else if(action==='save_strategy_directive'){risk=2;material=false;const directive=String(body.directive||'').trim(),scope=String(body.scope||'company');if(!directive)return Response.json({ok:false,error:'directive_required'},{status:400});preview={action,scope,directive,warning:'Strategic context only. This does not override domain authority, billing, security or contract policies.'};if(!confirmed){await s.entities.FounderCommandAudit.create({command_key:commandKey,conversation_id:body.conversation_id||'',actor_email:u.email,intent:'strategy',action,scope_json:{scope},risk_level:risk,material:false,requires_confirmation:true,confirmed:false,preview_json:preview,status:'previewed',result_json:{},policy_json:{founder_os_version:FOUNDER_OS_VERSION},created_at});return Response.json({ok:true,requires_confirmation:true,command_key:commandKey,preview});}const row=await s.entities.StrategyDirective.create({directive_key:`strategy:${scope}:${Date.now()}`,scope,directive,status:'active',priority:safeNumber(body.priority)||50,effective_from:new Date().toISOString(),evidence_json:{source:'founder_os',conversation_id:body.conversation_id||null},created_by:u.email,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});result={ok:true,directive_id:row.id};status='executed';}
 else return Response.json({ok:false,error:'unsupported_action',actions:['resolve_approval','run_provider_revenue_recovery','run_system_health','investigate_developer','save_strategy_directive']},{status:400});
 await s.entities.FounderCommandAudit.create({command_key:commandKey,conversation_id:body.conversation_id||'',actor_email:u.email,intent:String(body.intent||action),action,scope_json:body.scope||{},risk_level:risk,material,requires_confirmation:requires,confirmed,preview_json:preview,status,result_json:result||{},policy_json:{founder_os_version:FOUNDER_OS_VERSION},created_at});
 await s.entities.OperationalLog.create({event_type:'founder_os_command',message:action,data_json:{command_key:commandKey,risk_level:risk,material,preview,result},actor_email:u.email,created_at}).catch((error:any)=>safeBestEffort(error,{operation:'founderOSCommand',fallback:null,severity:'secondary'}));
 return Response.json({ok:true,command_key:commandKey,preview,result,status});
}catch(e){console.error(e);return internalErrorResponse(error, 'founderOSCommand');}});
