import{createClientFromRequest}from'npm:@base44/sdk@0.8.41';
import{requireAdminOrInternal}from'../../shared/internalGate.ts';
import{legacyClassification}from'../../shared/p3RateIntelligence.ts';

// P3 cutover semantics:
// - ProviderPricingVersion + RateComponent is the canonical factual pricing ledger.
// - PaymentsRateTable is a temporary legacy Analyzer compatibility projection only.
// - Legacy estimates/placeholders never promote into canonical P3 truth.
// - Exact verified P3 facts may project DOWN into an existing exact-country legacy row.
// - Achievable/P4/P5 inference fields are never copied into P3 factual truth.
Deno.serve(async req=>{try{const b=createClientFromRequest(req),body=await req.json().catch(()=>({})),g=await requireAdminOrInternal(req,b,body);if(!g.ok)return g.response;const s=b.asServiceRole,at=new Date().toISOString();const [legacy,p3]=await Promise.all([s.entities.PaymentsRateTable.list('-updated_date',1000).catch(()=>[]),s.entities.ProviderPricingVersion.filter({vertical:'payments',status:'CURRENT'},'-recorded_at',2000).catch(()=>[])]);
const classifications:any={};let quarantinedLegacy=0,projected=0,unchanged=0,noTarget=0,precisionBlocked=0,currencyBlocked=0,unknownStructure=0;
for(const r of legacy as any[]){if(r.is_demo)continue;const c=legacyClassification(r);classifications[c.classification]=(classifications[c.classification]||0)+1;const unsafe=c.classification!=='VERIFIED_MIGRATABLE'||r.verified!==true||(r.region==='EU'&&!r.country);if(unsafe&&r.active===true){await s.entities.PaymentsRateTable.update(r.id,{active:false,source_notes:`${String(r.source_notes||'')}\n[P3 LEGACY QUARANTINE ${at}] ${c.classification}: ${c.reasons.join(',')||'not exact verified market truth'}`.trim()}).catch(()=>null);quarantinedLegacy++;}}
for(const o of p3 as any[]){if(o.is_demo)continue;if(o.verification_status!=='VERIFIED_PRIMARY'||o.pricing_visibility!=='PUBLIC_COMPLETE'||!o.market||!o.provider_slug||o.access_scope==='TENANT_PRIVATE')continue;const components=await s.entities.RateComponent.filter({pricing_observation_id:o.id},'component_sequence',200).catch(()=>[]);if(components.some((c:any)=>c.value_mode!=='KNOWN')){unknownStructure++;continue}const pct=components.filter((c:any)=>['PROCESSING_FEE','ACQUIRER_MARGIN'].includes(c.component_type)&&c.percentage_ppm!=null);const fixed=components.filter((c:any)=>c.component_type==='FIXED_TRANSACTION_FEE'&&c.amount_minor!=null);if(pct.length!==1||pct[0].percentage_ppm%100!==0){precisionBlocked++;continue}const currencies=new Set(fixed.map((c:any)=>c.currency).filter(Boolean));if(currencies.size>1){currencyBlocked++;continue}const channel=o.channel==='IN_PERSON'?'in_store':o.channel==='ECOMMERCE'?'online':null;if(!channel)continue;const slug=o.provider_slug==='stripe'&&o.product_key==='stripe:terminal'?'stripe_terminal':o.provider_slug;const target=(legacy as any[]).find(r=>r.provider_slug===slug&&r.country===o.market&&(r.channel||'online')===channel&&r.tier==='ANY');if(!target){noTarget++;continue}const patch:any={active:true,verified:true,verified_at:o.verified_at||at,percent_bps:pct[0].percentage_ppm/100,fixed_fee_minor_units:fixed[0]?.amount_minor||0,fixed_fee_currency:fixed[0]?.currency||target.fixed_fee_currency,source_url:o.source_reference||target.source_url,source_quote:`P3 compatibility projection from ${o.pricing_key}`,intl_uplift_bps:null,achievable_percent_bps:null,achievable_fixed_fee_minor_units:null,achievable_intl_uplift_bps:null,source_notes:`P3 COMPATIBILITY PROJECTION ${at}. Canonical truth: ProviderPricingVersion ${o.id}. Legacy achievable fields intentionally cleared; P5 owns achievable inference.`};const same=Number(target.percent_bps)===Number(patch.percent_bps)&&Number(target.fixed_fee_minor_units||0)===Number(patch.fixed_fee_minor_units||0)&&target.fixed_fee_currency===patch.fixed_fee_currency&&target.active===true&&target.verified===true;if(same){unchanged++;continue}await s.entities.PaymentsRateTable.update(target.id,patch);projected++;}
await s.entities.Event.create({brand_id:'_platform',event_type:'P3_LEGACY_COMPATIBILITY_RECONCILED',source:'intelligenceMaintenanceWorker',entity_type:'PaymentsRateTable',entity_id:'legacy-adapter',payload_json:{classifications,quarantined_legacy:quarantinedLegacy,projected,unchanged,no_target:noTarget,precision_blocked:precisionBlocked,currency_blocked:currencyBlocked,unknown_structure:unknownStructure,canonical_truth:'ProviderPricingVersion+RateComponent',legacy_is_projection_only:true},status:'processed',processed_at:at}).catch(()=>null);
return Response.json({ok:true,canonical_truth:'ProviderPricingVersion+RateComponent',legacy_projection_only:true,classifications,quarantined_legacy:quarantinedLegacy,projected,unchanged,no_target:noTarget,precision_blocked:precisionBlocked,currency_blocked:currencyBlocked,unknown_structure:unknownStructure})}catch(e){console.error(e);return Response.json({ok:false,error:'intelligence_maintenance_failed'},{status:500})}});
