// DPA-1 (2026-08-16) — traduction du texte maître anglais (en/dpa.js), de sens
// juridique identique (même convention LEGAL-1 que terms.js / privacy.js).
//
// Valeurs fixées à la publication (le master les portait entre crochets) :
// 30 jours de préavis pour les sous-traitants ultérieurs · 48 heures pour la
// notification des violations · 15 jours ouvrés de préavis d'audit · une fois
// par année civile · 90 jours pour l'effacement. Voir src/docs/Decision_Log_DPA.md.

export default {
  badge: "Légal",
  title: "Accord de sous-traitance des données.",
  version: "1.0",
  lastUpdated: "Version 1.0 — 16 août 2026",
  back: "Retour",
  sections: [
    { title: "Parties", content: "Le présent Accord de sous-traitance des données (l'« Accord ») est conclu entre vous, le client, agissant en qualité de Responsable du traitement (« le Responsable »), et CAMBRA Global SASU, société par actions simplifiée de droit français, SIREN 105 452 916, TVA intracommunautaire FR50105452916, dont le siège social est situé 47 rue Vivienne, 75002 Paris, France, agissant en qualité de Sous-traitant (« CAMBRA »). Le présent Accord fait partie intégrante des Conditions générales et du contrat principal de services entre les parties, et est accepté conjointement avec ceux-ci." },
    { title: "1. Objet et finalité", content: "1.1. Le présent Accord régit le traitement de données à caractère personnel effectué par CAMBRA pour le compte du Responsable dans le cadre de la fourniture des services décrits au contrat principal (analyse des coûts de paiement, audit des commissions, services de récupération et fonctionnalités connexes de la plateforme). 1.2. Le présent Accord est conclu en application de l'article 28 du Règlement (UE) 2016/679 (« RGPD ») ou, lorsque l'Annexe de juridiction le prévoit, de la législation nationale équivalente qui y est identifiée." },
    { title: "2. Définitions", content: "Les termes « données à caractère personnel », « traitement », « responsable du traitement », « sous-traitant », « personne concernée », « violation de données à caractère personnel » et les autres termes définis ont le sens que leur donne l'article 4 du RGPD, ou la disposition équivalente applicable au titre de l'Annexe de juridiction." },
    { title: "3. Description du traitement", content: "3.1. La nature, la finalité et la durée du traitement, les types de données à caractère personnel et les catégories de personnes concernées sont détaillés à l'Annexe I. 3.2. Résumé indicatif : NATURE — collecte, conservation, analyse, comparaison et production de rapports sur des données de transactions de paiement et de facturation. FINALITÉ — fourniture des services souscrits d'analyse et d'audit des coûts de paiement. DURÉE — la durée du contrat principal, augmentée du délai d'effacement prévu à l'article 12. CATÉGORIES DE PERSONNES CONCERNÉES — le personnel du Responsable ; les clients finaux du Responsable dans la mesure où ils apparaissent dans les données transactionnelles. TYPES DE DONNÉES — données d'identification et de contact professionnelles ; données de transactions (montants, commissions, références) ; données de facturation. CATÉGORIES PARTICULIÈRES (art. 9 RGPD) — non traitées de manière délibérée ; si elles apparaissaient de manière incidente, l'article 6.4 s'applique." },
    { title: "4. Instructions du Responsable", content: "4.1. CAMBRA ne traitera les données à caractère personnel que sur instructions documentées du Responsable, y compris en ce qui concerne les transferts internationaux, sauf obligation contraire résultant du droit de l'Union ou de l'État membre applicable à CAMBRA ; dans ce cas, CAMBRA informera le Responsable de cette obligation juridique avant le traitement, sauf si ce droit l'interdit pour des motifs importants d'intérêt public. 4.2. Le contrat principal, le présent Accord et les instructions données par les fonctionnalités de configuration de la plateforme constituent les instructions documentées initiales. 4.3. CAMBRA informera immédiatement le Responsable si, selon elle, une instruction constitue une violation du RGPD ou d'une autre disposition applicable en matière de protection des données." },
    { title: "5. Confidentialité", content: "5.1. CAMBRA veille à ce que les personnes autorisées à traiter les données à caractère personnel s'engagent à respecter la confidentialité ou soient soumises à une obligation légale appropriée de confidentialité. 5.2. CAMBRA limite l'accès aux données au personnel qui en a besoin pour la fourniture des services." },
    { title: "6. Sécurité du traitement", content: "6.1. CAMBRA met en œuvre les mesures techniques et organisationnelles appropriées afin de garantir un niveau de sécurité adapté au risque, conformément à l'article 32 du RGPD, y compris celles décrites à l'Annexe II. 6.2. Ces mesures comprennent, selon les besoins : la pseudonymisation et le chiffrement ; la capacité de garantir la confidentialité, l'intégrité, la disponibilité et la résilience constantes ; la capacité de rétablir la disponibilité et l'accès après un incident ; ainsi qu'une procédure de test et d'évaluation réguliers de l'efficacité des mesures. 6.3. CAMBRA évalue le niveau de sécurité en tenant compte des risques du traitement, en particulier la destruction, la perte, l'altération, la divulgation ou l'accès non autorisés, de manière accidentelle ou illicite. 6.4. Si CAMBRA détecte des catégories particulières de données traitées de manière incidente hors du périmètre de l'Annexe I, elle en informera le Responsable et appliquera ses instructions, en s'abstenant entre-temps de toute utilisation de ces données." },
    { title: "7. Sous-traitants ultérieurs", content: "7.1. Le Responsable donne une autorisation écrite générale permettant à CAMBRA de recourir aux sous-traitants ultérieurs listés sur la page Sous-traitants (/Subprocessors), laquelle constitue l'Annexe III du présent Accord. 7.2. CAMBRA informera le Responsable de tout ajout ou remplacement envisagé de sous-traitants ultérieurs avec un préavis d'au moins 30 jours, en donnant au Responsable la possibilité de s'y opposer pour des motifs raisonnables liés à la protection des données. Si l'opposition ne peut être résolue, chacune des parties pourra résilier la partie du service concernée. 7.3. CAMBRA imposera contractuellement à chaque sous-traitant ultérieur les mêmes obligations de protection des données que celles prévues au présent Accord, en particulier des garanties suffisantes quant à la mise en œuvre de mesures techniques et organisationnelles appropriées. 7.4. CAMBRA demeure pleinement responsable envers le Responsable de l'exécution des obligations du sous-traitant ultérieur." },
    { title: "8. Assistance — droits des personnes concernées", content: "8.1. Compte tenu de la nature du traitement, CAMBRA aidera le Responsable, par des mesures techniques et organisationnelles appropriées, à s'acquitter de son obligation de donner suite aux demandes d'exercice des droits des personnes concernées (accès, rectification, effacement, limitation, portabilité, opposition et décision automatisée). 8.2. Si une personne concernée s'adresse directement à CAMBRA, CAMBRA transmettra la demande au Responsable sans retard injustifié et n'y répondra pas elle-même, sauf instruction du Responsable ou obligation légale." },
    { title: "9. Assistance — sécurité, violations et analyses", content: "9.1. CAMBRA aidera le Responsable à respecter les obligations des articles 32 à 36 du RGPD (sécurité, notification des violations, analyses d'impact et consultation préalable), compte tenu de la nature du traitement et des informations à la disposition de CAMBRA. 9.2. NOTIFICATION DES VIOLATIONS DE DONNÉES : CAMBRA notifiera au Responsable, sans retard injustifié après en avoir pris connaissance, toute violation de données à caractère personnel traitées pour le compte du Responsable, et en tout état de cause dans un délai maximal de 48 heures à compter de cette prise de connaissance. La notification comprendra, dans la mesure disponible : la nature de la violation, les catégories et le nombre approximatif de personnes concernées et d'enregistrements concernés, les conséquences probables, ainsi que les mesures prises ou proposées. 9.3. CAMBRA documentera toute violation et coopérera avec le Responsable dans sa gestion. La notification à l'autorité de contrôle et aux personnes concernées incombe au Responsable." },
    { title: "10. Audits", content: "10.1. CAMBRA mettra à la disposition du Responsable toutes les informations nécessaires pour démontrer le respect des obligations de l'article 28 du RGPD. 10.2. CAMBRA permettra la réalisation d'audits, y compris d'inspections, par le Responsable ou par un auditeur qu'il a mandaté, et y contribuera, moyennant un préavis raisonnable d'au moins 15 jours ouvrés, pendant les heures ouvrables, sans perturber de manière disproportionnée les opérations de CAMBRA, et au maximum une fois par année civile, sauf à la suite d'une violation de données ou d'une demande d'une autorité de contrôle. 10.3. CAMBRA pourra satisfaire tout ou partie du droit d'audit par la remise de certifications ou de rapports d'audit indépendants récents (par exemple ISO 27001, SOC 2), sans préjudice du droit du Responsable à une inspection si ces rapports s'avèrent insuffisants de manière motivée." },
    { title: "11. Transferts internationaux", content: "11.1. CAMBRA ne transférera pas de données à caractère personnel en dehors de l'Espace économique européen (ou du territoire indiqué à l'Annexe de juridiction) sans garantir un mécanisme de transfert valable : décision d'adéquation, clauses contractuelles types approuvées par la Commission européenne (ou l'instrument équivalent applicable au titre de l'Annexe de juridiction), ou une autre garantie appropriée au titre du chapitre V du RGPD. 11.2. Les transferts existants et leurs mécanismes sont documentés sur la page Sous-traitants (/Subprocessors), avec la liste des sous-traitants ultérieurs." },
    { title: "12. Effacement et restitution", content: "12.1. Au choix du Responsable, CAMBRA effacera ou restituera toutes les données à caractère personnel au terme de la fourniture des services, et effacera les copies existantes, sauf si le droit de l'Union ou national applicable en exige la conservation. 12.2. Sauf instruction contraire, l'effacement sera achevé dans un délai de 90 jours à compter de la résiliation, avec certification écrite à la demande du Responsable." },
    { title: "13. Responsabilité", content: "13.1. Chaque partie est responsable conformément aux articles 82 et suivants du RGPD et au régime de responsabilité convenu au contrat principal. 13.2. Aucune stipulation du présent Accord ne limite la responsabilité d'une partie envers les personnes concernées ni envers les autorités de contrôle pour ce qui n'est pas juridiquement susceptible de limitation." },
    { title: "14. Durée, droit applicable et juridiction", content: "14.1. Le présent Accord entre en vigueur à la date de son acceptation et demeure en vigueur tant que CAMBRA traite des données à caractère personnel pour le compte du Responsable. 14.2. DROIT APPLICABLE ET JURIDICTION : ceux indiqués à l'Annexe de juridiction correspondant au pays du Responsable. À défaut d'annexe applicable, le présent Accord est régi par le droit français et soumis aux tribunaux de commerce compétents de Paris (France) — en cohérence avec les Conditions générales de la plateforme, l'entité contractante étant CAMBRA Global SASU, société de droit français. 14.3. En cas de conflit entre le présent Accord et le contrat principal en matière de protection des données, le présent Accord prévaut. En cas de conflit entre le présent Accord et des clauses contractuelles types applicables à un transfert, ces dernières prévalent." },
    { title: "Annexe I — Description du traitement", content: "La nature, la finalité, la durée, les catégories de personnes concernées et les types de données à caractère personnel sont ceux résumés à l'article 3.2 pour le service standard. Lorsqu'une opération particulière s'écarte de cette description, elle est documentée dans la commande ou l'enregistrement de configuration correspondant et fait partie de la présente Annexe." },
    { title: "Annexe II — Mesures techniques et organisationnelles", content: "Chiffrement en transit et au repos ; contrôle des accès avec authentification et moindre privilège ; journalisation de l'activité ; sauvegardes ; gestion des vulnérabilités ; effacement sécurisé ; continuité d'activité ; et pseudonymisation lorsque cela est pertinent. L'état détaillé et à jour de ces mesures est disponible sur demande à privacy@cambra.global." },
    { title: "Annexe III — Sous-traitants autorisés et transferts", content: "La liste à jour des sous-traitants ultérieurs autorisés, leur pays, le service fourni et le mécanisme de transfert applicable sont publiés et tenus à jour sur la page Sous-traitants (/Subprocessors). Cette page porte sa propre date de dernière mise à jour, qui constitue la référence du préavis de 30 jours prévu à l'article 7.2." },
    { title: "Annexe IV — Annexe de juridiction", content: "Lorsque le Responsable est établi hors de France, la fiche pays de l'annexe de juridiction de CAMBRA s'applique et est fournie sur demande à privacy@cambra.global. Pour les États membres de l'UE et les pays de l'EEE, le fond du présent Accord est inchangé (le RGPD s'applique directement) ; seuls changent la loi nationale complémentaire, l'autorité de contrôle, le droit applicable et la langue faisant foi. Pour les pays dotés de leur propre législation adéquate (Suisse, Andorre), la clause d'inclusion correspondante s'applique et remplace les références au RGPD." },
    { title: "Statut du présent document", content: "Il s'agit de la version 1.0 de l'Accord. Son statut de revue juridique est suivi en interne et ce texte peut être modifié ; les changements substantiels sont notifiés avec un préavis d'au moins 30 jours conformément aux Conditions générales. Pour toute question relative au présent Accord : privacy@cambra.global." },
  ],
};
