// LEGAL-1 — Traduction française du texte maître anglais (en/privacy.js).
// Sens juridique identique, vouvoiement, terminologie RGPD.

export default {
  badge: "Légal · Confidentialité",
  title: "Politique de confidentialité.",
  lastUpdated: "Dernière mise à jour : 24 juillet 2026",
  back: "Retour",
  sections: [
    { title: "1. Responsable du traitement", content: "Le responsable du traitement est CAMBRA Global SASU, société par actions simplifiée de droit français, immatriculée sous le SIREN 105 452 916 et le SIRET 105 452 916 00015, TVA intracommunautaire FR50105452916, dont le siège social est situé 47 rue Vivienne, Chez Vivienne Domiciliation, 75002 Paris, France. Pour toute demande relative à vos données, contactez-nous à privacy@cambra.global." },
    { title: "2. Données collectées", content: "Nous collectons les informations que vous nous fournissez directement : nom, e-mail professionnel, informations sur votre marque, données de coûts de paiement et d'infrastructure, relevés téléversés et indicateurs opérationnels saisis dans l'Analyzer. Lorsque vous connectez un compte tiers (par ex. Stripe), nous collectons les données autorisées par votre périmètre OAuth — en lecture seule. Nous traitons également les journaux techniques générés par le fonctionnement normal de la plateforme (requêtes, erreurs, événements de sécurité). Si vous nous découvrez via le lien de recommandation d'un autre commerce, nous enregistrons également ce code de recommandation : un code aléatoire opaque généré par CAMBRA, non dérivé de données personnelles. Il sert uniquement à identifier le commerce qui vous a recommandé et à appliquer la réduction de commission correspondante à ce commerce ; il est conservé avec votre session d'analyse. Il est stocké dans votre navigateur (sessionStorage) entre l'ouverture du lien et l'exécution de votre analyse — voir notre Politique de cookies." },
    { title: "3. Utilisation de vos données", content: "Vos données sont utilisées pour fournir l'intelligence d'infrastructure de CAMBRA — génération d'audits, calcul de benchmarks, identification d'opportunités d'optimisation et personnalisation de votre tableau de bord. Base juridique : exécution du contrat (art. 6(1)(b) RGPD) et intérêt légitime pour le benchmarking (art. 6(1)(f) RGPD). Nous ne vendons jamais vos données. L’intelligence inter-clients est séparée des données opérationnelles des marchands. Nous ne pouvons conserver que des statistiques agrégées et entièrement anonymisées, sans identifiant marchand ni pseudonyme stable, produites uniquement lorsqu’un seuil minimal de diversité est atteint ; les données identifiables ou seulement pseudonymisées restent soumises aux règles ordinaires de conservation et d’effacement." },
    { title: "4. Téléversement de fichiers et traitement par IA", content: "Lorsque vous téléversez des relevés ou des factures (PDF, Excel, CSV), ils sont traités par de grands modèles de langage afin d'en extraire des données structurées de coûts et d'exploitation. Le contenu transmis à nos fournisseurs d'IA est limité aux données commerciales nécessaires à l'analyse — montants, commissions, dates et noms de prestataires ; nous ne transmettons pas, à cette fin, de données personnelles de vos clients finaux. Nos fournisseurs d'IA traitent ce contenu dans le cadre de leurs accords de traitement des données standard, dont les conditions prévoient que les données soumises via leurs API ne sont pas utilisées pour entraîner leurs modèles. Les fichiers téléversés sont stockés en s'appuyant sur les contrôles de sécurité de notre hébergeur et prestataire de stockage, et restent votre propriété." },
    { title: "5. Sous-traitants", content: "Pour exploiter le service, CAMBRA fait appel aux sous-traitants suivants, chacun dans le cadre de son accord de traitement des données respectif : Base44 (hébergement applicatif et base de données) ; Anthropic PBC (traitement IA — extraction documentaire, intelligence produit et Copilot intégré) ; OpenAI (contre-vérification d'extraction IA) ; Resend, Inc. (envoi d'e-mails transactionnels) ; Stripe Payments Europe Ltd. (traitement des paiements le cas échéant) ; Microsoft Ireland Operations Limited (sauvegarde de reprise après sinistre chiffrée et hors plateforme des données de la plateforme et des pièces jointes des marchands dans un locataire SharePoint, données au repos hébergées en France). Une liste complète et à jour est disponible sur demande à privacy@cambra.global et à l'Annexe III de notre DPA (page Sous-traitants)." },
    { title: "6. Stockage et sécurité", content: "Vos données sont chiffrées en transit et au repos conformément aux standards de notre fournisseur d'infrastructure. En complément, les identifiants tiers que vous connectez (jetons OAuth, clés API) sont chiffrés au niveau applicatif en AES-256-GCM, avec une clé dédiée jamais exposée au code client. L'accès à vos données est restreint aux systèmes et aux personnes qui en ont besoin pour exploiter le service, et les opérations sensibles sont journalisées." },
    { title: "7. Vos droits (RGPD)", content: "Si vous résidez dans l'Espace économique européen, au Royaume-Uni ou en Suisse, vous disposez des droits d'accès, de rectification, d'effacement, de limitation, de portabilité et d'opposition au traitement de vos données. Vous pouvez également retirer votre consentement à tout moment. Pour exercer ces droits, contactez privacy@cambra.global — nous répondons dans un délai d'un mois, conformément à l'art. 12 du RGPD." },
    { title: "8. Conservation des données", content: "Nous conservons les données personnelles et opérationnelles uniquement pendant la durée d'activité de votre compte ou le temps nécessaire à la fourniture du service. Lorsque vous demandez la suppression de votre compte, nous supprimons ou anonymisons les données identifiantes dans les meilleurs délais. Les données de facturation sont conservées 10 ans conformément au droit commercial et fiscal français (Code de commerce, art. L123-22). Les benchmarks agrégés et anonymisés, ne permettant plus de vous identifier, peuvent être conservés." },
    { title: "9. Cookies et stockage local", content: "Nous utilisons un ensemble restreint de cookies internes (first-party) et de stockage navigateur (localStorage / sessionStorage), strictement pour faire fonctionner la plateforme — authentification, continuité de session et vos préférences. Nous n'utilisons ni cookies publicitaires ni traceurs tiers. La liste complète, vérifiée sur le code, figure dans notre Politique de cookies." },
    { title: "10. Transferts internationaux", content: "Certains de nos sous-traitants traitent des données en dehors de l'EEE (par ex. inférence IA par Anthropic PBC ou OpenAI, envoi d'e-mails par Resend, Inc.). Ces transferts sont encadrés par les mécanismes de transfert prévus dans l'accord de traitement des données de chaque fournisseur, tels que les clauses contractuelles types approuvées par la Commission européenne. Microsoft Ireland Operations Limited (sauvegarde SharePoint de reprise après sinistre) héberge les données au repos en France ; les services annexes (support, télémétrie), le cas échéant, sont couverts par les Clauses contractuelles types signées dans le Microsoft Products and Services Data Protection Addendum." },
    { title: "11. Notification des violations de données", content: "En cas de violation de données personnelles susceptible d'engendrer un risque pour vos droits et libertés, CAMBRA notifiera l'autorité de contrôle compétente (CNIL) dans les 72 heures et, si le risque est élevé, informera les utilisateurs concernés dans les meilleurs délais, conformément aux art. 33-34 du RGPD." },
    { title: "12. Contact et autorité de contrôle", content: "Pour toute question, demande ou réclamation relative à la confidentialité : privacy@cambra.global. Vous avez également le droit d'introduire une réclamation auprès de la Commission Nationale de l'Informatique et des Libertés (CNIL, www.cnil.fr) ou de votre autorité locale de protection des données." },
  ],
};
