// LEGAL-1 — Traduction française du texte maître anglais (en/terms.js).
// Sens juridique identique, vouvoiement.

export default {
  badge: "Légal",
  title: "Conditions générales.",
  lastUpdated: "Dernière mise à jour : 3 août 2026",
  back: "Retour",
  sections: [
    { title: "1. Éditeur et identité légale", content: "La plateforme CAMBRA est éditée par CAMBRA GLOBAL SASU, société par actions simplifiée unipersonnelle de droit français, immatriculée sous le SIREN 105 452 916, dont le siège social est situé 42 rue Vivienne, 75002 Paris, France. Contact : support@cambra.global. Directeur de la publication : le représentant légal de CAMBRA GLOBAL SASU. L'hébergement est assuré par Base44." },
    { title: "2. Acceptation", content: "En accédant à la plateforme CAMBRA ou en l'utilisant, vous acceptez d'être lié par les présentes Conditions générales. Si vous n'êtes pas d'accord, n'utilisez pas la plateforme. CAMBRA se réserve le droit de mettre à jour ces conditions moyennant un préavis raisonnable (au moins 30 jours pour les modifications substantielles), communiqué par e-mail et par notification dans l'application." },
    { title: "3. Objet de la plateforme", content: "CAMBRA fournit des services d'analyse des coûts de paiement, de benchmarking et de récupération pour les marques du commerce indépendant, couvrant les paiements par carte en ligne et en magasin. La plateforme est destinée à un usage exclusivement professionnel (B2B). Vous devez avoir au moins 18 ans et être dûment habilité à représenter la marque ou l'entité que vous inscrivez." },
    { title: "4. Résultats d'audit et estimations", content: "Tous les résultats de l'Analyzer, les estimations d'économies de paiement et les comparaisons de benchmarks sont des estimations dérivées de vos saisies et du jeu de données du réseau CAMBRA. Il s'agit d'orientations opérationnelles — et non de conseils financiers, juridiques, comptables ou fiscaux. CAMBRA ne garantit aucun résultat d'économies spécifique. Consultez toujours des conseillers qualifiés avant toute décision importante." },
    { title: "5. Propriété des données et licence", content: "Vous conservez la pleine propriété de toutes les données que vous soumettez. En utilisant la plateforme, vous accordez à CAMBRA une licence limitée, mondiale, non exclusive et révocable pour traiter ces données dans le seul but de fournir le service. Les données agrégées et entièrement anonymisées (à partir desquelles aucune marque individuelle ne peut être ré-identifiée) peuvent être utilisées pour améliorer les benchmarks. Nous ne partagerons jamais de données identifiantes avec des tiers sans votre consentement explicite, sauf obligation légale." },
    { title: "6. Tarification — audit gratuit", content: "L'accès à l'Analyzer, aux benchmarks, au scoring et au tableau de bord est actuellement proposé gratuitement aux marques partenaires de la première heure. Aucune carte bancaire n'est requise. CAMBRA pourra introduire des offres payantes à l'avenir moyennant un préavis d'au moins 30 jours ; les premiers partenaires conserveront leurs conditions commerciales d'origine pendant une période de transition raisonnable." },
    { title: "7. Service de récupération — commission au succès", content: "Si vous optez pour le service de récupération, CAMBRA agit en votre nom pour renégocier vos taux de paiement par carte — en ligne (PSP) et en magasin (TPE / terminal physique) — auprès de votre prestataire actuel, ou pour vous faire migrer vers un meilleur prestataire le cas échéant. La commission est de 25 % des économies de paiement vérifiées, calculée sur un accord de 24 mois à compter du moment où les économies deviennent mesurables sur vos relevés réels de PSP ou de prestataire. Règles clés : (a) aucun frais initial, aucun abonnement, aucun minimum ; (b) si aucune économie vérifiée n'est récupérée, vous ne devez rien ; (c) « économies vérifiées » désigne l'écart entre votre taux effectif de référence et votre nouveau taux effectif, attesté par les relevés réels de votre PSP ou prestataire de TPE et rapprochés par CAMBRA ; (d) au terme de l'accord de 24 mois, 100 % des économies futures vous restent acquises ; (e) les conditions spécifiques de chaque mandat de récupération sont formalisées dans un mandat écrit distinct, signé avant toute négociation." },
    { title: "8. Programme de recommandation — réduction de commission", content: "CAMBRA opère un programme de recommandation qui réduit la commission de résultat définie à l'article 7. Mécanisme : (a) la commission de résultat standard est de 25% des économies vérifiées ; (b) pour chaque commerce recommandé qui devient une recommandation activée, votre propre commission est réduite de 5 points de pourcentage, sans limite du nombre de commerces que vous pouvez recommander ; (c) la réduction est cumulative entre recommandations activées, dans la limite d'un plancher absolu de 5% — votre commission ne descendra jamais en dessous de 5% des économies vérifiées ; (d) un commerce recommandé via votre lien entre à 20% au lieu de 25% — une réduction d'entrée à palier unique, non renouvelée par ses propres recommandations, lesquelles relèvent pour lui du point (b). Définition — « recommandation activée » : un commerce recommandé ayant atteint des économies vérifiées au sens de l'article 7(c), c'est-à-dire des économies mesurables et attestées par ses relevés de prestataire réels tels que rapprochés par CAMBRA, et dont la récupération a été activée. L'inscription, la réalisation d'une analyse, l'ouverture d'un compte ou le clic sur un lien de recommandation ne constituent, isolément ou ensemble, pas une recommandation activée. Persistance : une fois obtenue, la réduction est définitive pour la durée restante de votre propre engagement de 24 mois, y compris si le commerce recommandé met fin par la suite à son service, révoque son mandat ou cesse son activité pour quelque motif que ce soit ; une réduction déjà acquise n'est jamais reprise. Portée temporelle : chaque réduction s'applique aux commissions facturées à compter du mois suivant l'activation vérifiée de la recommandation correspondante. Elle n'est pas rétroactive et n'ouvre droit à aucun avoir, remise ou recalcul des commissions déjà facturées. Non-cumul avec d'autres remises : les réductions de recommandation ne se cumulent avec aucune autre remise commerciale, promotion ou commission négociée, à l'exception des réductions du présent programme, qui se cumulent entre elles jusqu'au plancher de 5%. Absence de contrepartie financière : CAMBRA ne verse aucune somme, commission, partage de revenus ni avantage en nature au titre d'une recommandation. Le seul bénéfice du programme est la réduction de votre propre commission. Par conséquent, recommander un commerce dans ce cadre ne vous confère pas la qualité d'agent, de courtier, d'intermédiaire ou d'apporteur d'affaires rémunéré de CAMBRA, et n'ouvre droit à aucune rémunération de quelque nature que ce soit. CAMBRA peut modifier ou interrompre le programme pour les recommandations futures moyennant un préavis de 30 jours ; les réductions déjà acquises restent régies par la règle de persistance ci-dessus." },
    { title: "9. Programme prestataires", content: "CAMBRA opère un programme prestataires à deux niveaux, décrit sur notre page For Providers (/ForProviders). Le niveau 1 (Listed) couvre les prestataires de paiement dont la tarification publique entre dans notre benchmark atteignable — sans frais, sans exclusivité, sans aucun flux de rémunération dans un sens ou dans l'autre. Le niveau 2 (Partner) couvre les prestataires de paiement qui offrent un tarif exclusif aux commerçants présentés par CAMBRA en échange d'un accord d'apport d'affaires ; lorsque nous présentons une offre Partner à un commerçant, elle est signalée comme offre exclusive CAMBRA, visuellement et sémantiquement distincte de notre benchmark public. Notre benchmark public n'est jamais influencé par les accords Partner : CAMBRA recommande toujours l'option qui fait économiser le plus à la marque, que l'ancre gagnante soit Listed, Partner ou le prestataire actuel du commerçant. Les conditions commerciales spécifiques de chaque partenariat sont formalisées dans un accord signé et communiquées à tout prestataire intéressé sur demande écrite à support@cambra.global." },
    { title: "10. Usage acceptable", content: "Vous vous engagez à ne pas : rétro-concevoir la plateforme, extraire massivement les données de benchmark, présenter faussement votre marque, téléverser des contenus illicites, tenter d'accéder aux données d'un autre utilisateur, ou utiliser CAMBRA pour créer un service directement concurrent. Toute violation peut entraîner une suspension immédiate sans remboursement." },
    { title: "11. Propriété intellectuelle", content: "La plateforme CAMBRA, la marque, la méthodologie, les benchmarks et le logiciel sont la propriété exclusive de CAMBRA GLOBAL SASU. Aucune disposition des présentes Conditions ne vous transfère de droit de propriété intellectuelle, à l'exception de la licence limitée d'utilisation du service." },
    { title: "12. Limitation de responsabilité", content: "Dans toute la mesure permise par le droit français, CAMBRA n'est pas responsable des dommages indirects, accessoires, spéciaux ou consécutifs résultant de l'utilisation de la plateforme. La responsabilité totale cumulée est plafonnée au plus élevé de (a) les montants que vous avez versés à CAMBRA au cours des douze mois précédant la réclamation, ou (b) 5 000 €. Aucune disposition des présentes Conditions ne limite la responsabilité en cas de faute lourde, de faute intentionnelle ou de décès/dommage corporel." },
    { title: "13. Rétractation (B2B)", content: "La plateforme est un service professionnel B2B. Le droit de rétractation de 14 jours du Code de la consommation ne s'applique pas. Vous pouvez néanmoins résilier votre compte à tout moment depuis les paramètres du compte, conformément à la section 13 ci-dessous." },
    { title: "14. Résiliation", content: "Vous pouvez résilier votre compte à tout moment depuis les paramètres du compte. Les mandats de récupération en cours se poursuivent selon leurs conditions existantes, sauf révocation écrite du mandat lui-même. CAMBRA peut suspendre ou résilier l'accès en cas de violation substantielle des présentes conditions ou d'inactivité prolongée (plus de 24 mois). En cas de résiliation, vos données sont traitées conformément à notre Politique de confidentialité." },
    { title: "15. Droit applicable et juridiction", content: "Les présentes Conditions sont régies par le droit français. Tout litige fera d'abord l'objet d'une négociation de bonne foi. À défaut de résolution dans les 60 jours, les parties pourront recourir à la médiation (CMAP, Paris). À défaut de résolution amiable, la compétence exclusive revient aux tribunaux de commerce compétents de Paris, France." },
    { title: "16. Contact", content: "Pour toute question contractuelle : support@cambra.global. Pour les notifications légales : 42 rue Vivienne, 75002 Paris, France." },
  ],
};