import { safeBestEffort } from '../../shared/bestEffort.ts';
import{createClientFromRequest}from'npm:@base44/sdk@0.8.41';
import{requireAdminOrInternal}from'../../shared/internalGate.ts';
import{sha256,P3_PROMOTION_POLICY_VERSION}from'../../shared/p3RateIntelligence.ts';
import { guardedScheduledServe } from '../../shared/schedulerRun.ts';
import { fetchPublicHttps } from '../../shared/publicHttpEgress.ts';
import { requireCriticalOperation } from '../../shared/criticalExecution.ts';

const now=()=>new Date().toISOString();
function cleanHtml(s:string){return s.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<!--([\s\S]*?)-->/g,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim().slice(0,250000)}
async function first(s:any,e:string,q:any){return(await requireCriticalOperation(`rate_watch_read_${e}`,()=>s.entities[e].filter(q,'-created_date',2)))[0]||null}
guardedScheduledServe({"worker_key":"rateIntelligenceWatchWorker","cadence_seconds":21600},createClientFromRequest,async req=>{try{const b=createClientFromRequest(req),body=await req.json().catch(()=>({})),g=await requireAdminOrInternal(req,b,body);if(!g.ok)return g.response||Response.json({error:'authorization_failed'},{status:503});const s=b.asServiceRole,start=Date.now(),at=now(),limit=Math.max(1,Math.min(Number(body.limit||20),20));const due=(await requireCriticalOperation('rate_watch_due_targets',()=>s.entities.PricingWatchTarget.filter({status:{$in:['ACTIVE','STALE','FAILED']},next_check_at:{$lte:at}},'next_check_at',limit)));let checked=0,unchanged=0,changed=0,failed=0,candidates=0;
for(const w of due as any[]){checked++;const cadence=Math.max(24,Number(w.cadence_hours||168)),next=new Date(Date.now()+cadence*3600000).toISOString(),fresh=new Date(Date.now()+Math.max(cadence*2,Number(w.freshness_sla_hours||cadence*2))*3600000).toISOString();try{const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),10000);let res;try{({response:res}=await fetchPublicHttps(w.source_url,{signal:ctl.signal,headers:{'accept':'text/html,application/xhtml+xml,application/pdf;q=0.8,*/*;q=0.5','user-agent':'CAMBRA-RateIntelligence/1.0 (+responsible rate verification)'}},{maxRedirects:4}))}finally{clearTimeout(timer)}if(!res.ok)throw new Error(`http_${res.status}`);const ct=String(res.headers.get('content-type')||'');if(!/text|html|json|xml/i.test(ct)){await requireCriticalOperation('rate_watch_mark_access_restricted',()=>s.entities.PricingWatchTarget.update(w.id,{last_checked_at:at,next_check_at:next,fresh_until:fresh,status:'ACCESS_RESTRICTED',stale_reason:`unsupported_content_type:${ct.slice(0,80)}`,failure_count:Number(w.failure_count||0)+1}));failed++;continue}const raw=(await res.text()).slice(0,500000),normalized=cleanHtml(raw),content_hash=await sha256(raw),normalized_hash=await sha256(normalized);const prev=w.last_snapshot_id?await requireCriticalOperation('rate_watch_previous_snapshot',()=>s.entities.RateSourceSnapshot.get(w.last_snapshot_id)):null;if(prev?.normalized_content_hash===normalized_hash){await requireCriticalOperation('rate_watch_mark_unchanged',()=>s.entities.PricingWatchTarget.update(w.id,{last_checked_at:at,next_check_at:next,fresh_until:fresh,status:'ACTIVE',failure_count:0,stale_reason:null}));unchanged++;continue}
const snapshot_key=`p3-watch-snapshot:${w.id}:${normalized_hash}`;let snap=await first(s,'RateSourceSnapshot',{snapshot_key});if(!snap)snap=await s.entities.RateSourceSnapshot.create({snapshot_key,source_url:w.source_url,source_type:w.source_type||'OFFICIAL_PROVIDER_PRICING',provider_id:w.provider_id,market:w.market,language:'source',retrieved_at:at,http_status:res.status,etag:res.headers.get('etag')||undefined,last_modified:res.headers.get('last-modified')||undefined,content_hash,normalized_content_hash:normalized_hash,pricing_section_hash:normalized_hash,normalized_extract_json:{normalized_text:normalized.slice(0,50000),note:'Change-detection snapshot only. No numeric pricing fact is promoted from unstructured text without deterministic extraction and evidence validation.'},parser_version:'p3-watch-text-normalizer-1',extractor_version:'p3-watch-1',status:prev?'CHANGED':'HEALTHY'});
if(prev){const candidate_key=`p3-change:${w.id}:${normalized_hash}`;let c=await first(s,'RateChangeCandidate',{candidate_key});if(!c){c=await s.entities.RateChangeCandidate.create({candidate_key,provider_id:w.provider_id,market:w.market,source_snapshot_id:snap.id,current_observation_id:null,candidate_observation_json:{source_url:w.source_url,previous_snapshot_id:prev.id,new_snapshot_id:snap.id,semantic_extraction_status:'UNSTRUCTURED_CHANGE_ONLY'},semantic_fingerprint:normalized_hash,state:'REVIEW_REQUIRED',reason_codes:['SOURCE_CONTENT_CHANGED','NO_DETERMINISTIC_RATE_EXTRACTION_PROMOTION'],detected_at:at,promotion_policy_version:P3_PROMOTION_POLICY_VERSION});candidates++;}changed++;await s.entities.Event.create({brand_id:'_platform',event_type:'RATE_SOURCE_CHANGED',source:'rateIntelligenceWatchWorker',entity_type:'RateChangeCandidate',entity_id:c.id,payload_json:{provider_id:w.provider_id,provider_slug:w.provider_slug,market:w.market,watch_key:w.watch_key,auto_promoted:false},status:'processed',processed_at:at}).catch((error:any)=>safeBestEffort(error,{operation:'rateIntelligenceWatchWorker',fallback:null,severity:'secondary'}))}else unchanged++;
await s.entities.PricingWatchTarget.update(w.id,{last_checked_at:at,last_changed_at:prev?at:w.last_changed_at||at,next_check_at:next,fresh_until:fresh,status:'ACTIVE',failure_count:0,stale_reason:null,last_snapshot_id:snap.id});
}catch(e:any){failed++;const n=Number(w.failure_count||0)+1,backoff=Math.min(Math.max(Number(w.cadence_hours||168),24)*Math.min(2**Math.min(n,4),16),24*30),nextRetry=new Date(Date.now()+backoff*3600000).toISOString();await requireCriticalOperation('rate_watch_mark_failure',()=>s.entities.PricingWatchTarget.update(w.id,{last_checked_at:at,next_check_at:nextRetry,status:n>=3?'STALE':'FAILED',stale_reason:String(e?.message||e).slice(0,200),failure_count:n}));await s.entities.Event.create({brand_id:'_platform',event_type:'RATE_RESEARCH_FAILED',source:'rateIntelligenceWatchWorker',entity_type:'PricingWatchTarget',entity_id:w.id,payload_json:{market:w.market,provider_slug:w.provider_slug,error:String(e?.message||e).slice(0,200),old_truth_preserved:true},status:'processed',processed_at:at}).catch((error:any)=>safeBestEffort(error,{operation:'rateIntelligenceWatchWorker',fallback:null,severity:'secondary'}))}}
await requireCriticalOperation('rate_watch_agent_task',()=>s.entities.AgentTask.create({brand_id:'_platform',agent_name:'rate_intelligence_watch',task_type:'p3_rate_watch',status:failed?'failed':'completed',input_summary:`P3 rate watch checked ${checked}; changed ${changed}; candidates ${candidates}; failed ${failed}. limit=${limit}`,output_summary:`checked=${checked} unchanged=${unchanged} changed=${changed} failed=${failed} candidates=${candidates}`,output_payload_json:{checked,unchanged,changed,failed,candidates,duration_ms:Date.now()-start},started_at:at,completed_at:now()}));const payload={ok:failed===0,checked,unchanged,changed,failed,candidates,duration_ms:Date.now()-start,policy:'No unstructured page change is auto-promoted into canonical pricing.'};return failed?Response.json({...payload,error:'rate_watch_partial_or_failed'},{status:503}):Response.json(payload)}catch(e){console.error(e);return Response.json({ok:false,error:'rate_intelligence_watch_failed'},{status:500})}});