import { safeBestEffort } from '../../shared/bestEffort.ts';
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
import { ACTION_POLICIES, EUROPE_33, LEGAL_EXECUTION_VERSION } from '../../shared/legalExecution.ts';

const POLICY_STATUSES=new Set(['ALLOW','ALLOW_WITH_CONDITIONS','BLOCK','LEGAL_REVIEW_REQUIRED']);
const APPROVED_REVIEWS=new Set(['APPROVED_FOR_POLICY','COUNSEL_APPROVED']);
const APPROVED_CONFIDENCE=new Set(['VERIFIED_PRIMARY','VERIFIED_MULTIPLE_PRIMARY','COUNSEL_APPROVED']);
const AUTHORITY_SCOPES=new Set(Object.values(ACTION_POLICIES).map((x:any)=>x.authority_scope).filter(Boolean));
const KILL_SWITCH_SCOPES=new Set(['global','jurisdiction','action','jurisdiction_action','merchant','provider']);

export async function handleManageLegalExecution(req: Request) {
  try{
    const base44=createClientFromRequest(req);const user=await base44.auth.me().catch((error:any)=>safeBestEffort(error,{operation:'manageLegalExecution',fallback:null,severity:'secondary'}));
    if(user?.role!=='admin')return Response.json({ok:false,error:'admin_required'},{status:403});
    const body=await req.json().catch(()=>({}));const svc=base44.asServiceRole;const action=String(body.action||'');const now=new Date().toISOString();
    if(action==='publish_policy'){
      const jurisdiction=String(body.jurisdiction||'').toUpperCase();const requestedAction=String(body.requested_action||'').toUpperCase();const status=String(body.status||'').toUpperCase();const reviewStatus=String(body.review_status||'').toUpperCase();const confidence=String(body.confidence||'').toUpperCase();const evidenceRefs=Array.isArray(body.evidence_refs)?body.evidence_refs.map(String).filter(Boolean):[];
      if(!EUROPE_33.includes(jurisdiction)||!ACTION_POLICIES[requestedAction])return Response.json({ok:false,error:'canonical_jurisdiction_and_action_required'},{status:400});
      if(!POLICY_STATUSES.has(status))return Response.json({ok:false,error:'invalid_policy_status'},{status:400});
      if(['ALLOW','ALLOW_WITH_CONDITIONS'].includes(status)&&(!APPROVED_REVIEWS.has(reviewStatus)||!APPROVED_CONFIDENCE.has(confidence)||!evidenceRefs.length))return Response.json({ok:false,error:'allow_requires_approved_review_confidence_and_evidence'},{status:409});
      const previous=await svc.entities.LegalExecutionPolicy.filter({jurisdiction,requested_action:requestedAction,active:true},'-effective_from',100).catch((error:any)=>safeBestEffort(error,{operation:'manageLegalExecution',fallback:[],severity:'secondary'}));
      for(const row of previous)await svc.entities.LegalExecutionPolicy.update(row.id,{active:false,effective_to:now}).catch((error:any)=>safeBestEffort(error,{operation:'manageLegalExecution',fallback:null,severity:'secondary'}));
      const version=String(body.version||`${LEGAL_EXECUTION_VERSION}:${now}`);const row=await svc.entities.LegalExecutionPolicy.create({policy_key:`${jurisdiction}:${requestedAction}:${version}`,jurisdiction,requested_action:requestedAction,status,confidence:confidence||'COUNSEL_REQUIRED',review_status:reviewStatus||'DRAFT',version,evidence_refs:evidenceRefs,conditions:Array.isArray(body.conditions)?body.conditions.map(String):[],merchant_approval_required:body.merchant_approval_required!==false,signature_requirement:String(body.signature_requirement||ACTION_POLICIES[requestedAction].minimum_signature),signer_capacity_requirement:String(body.signer_capacity_requirement||'VERIFIED'),counsel_required:body.counsel_required!==false,effective_from:String(body.effective_from||now),effective_to:body.effective_to||undefined,next_review_at:body.next_review_at||undefined,active:true,approved_by:user.email,approved_at:now});
      await svc.entities.Event.create({brand_id:'_platform',event_type:'LEGAL_EXECUTION_POLICY_PUBLISHED',source:'manage_legal_execution',entity_type:'LegalExecutionPolicy',entity_id:row.id,payload_json:{jurisdiction,requested_action:requestedAction,status,version,evidence_refs:evidenceRefs},status:'processed',processed_at:now}).catch((error:any)=>safeBestEffort(error,{operation:'manageLegalExecution',fallback:null,severity:'secondary'}));
      return Response.json({ok:true,policy:row,superseded:previous.length});
    }
    if(action==='activate_kill_switch'){
      const scope=String(body.scope_type||'global').toLowerCase();if(!KILL_SWITCH_SCOPES.has(scope))return Response.json({ok:false,error:'invalid_kill_switch_scope'},{status:400});if(scope.includes('jurisdiction')&&!EUROPE_33.includes(String(body.jurisdiction||'').toUpperCase()))return Response.json({ok:false,error:'canonical_jurisdiction_required'},{status:400});if(scope.includes('action')&&!ACTION_POLICIES[String(body.requested_action||'').toUpperCase()])return Response.json({ok:false,error:'known_action_required'},{status:400});if(scope==='merchant'&&!body.merchant_id)return Response.json({ok:false,error:'merchant_id_required'},{status:400});if(scope==='provider'&&!body.provider_id)return Response.json({ok:false,error:'provider_id_required'},{status:400});const key=String(body.switch_key||`legal-kill:${scope}:${body.jurisdiction||'*'}:${body.requested_action||'*'}:${now}`);const row=await svc.entities.LegalKillSwitch.create({switch_key:key,scope_type:scope,jurisdiction:String(body.jurisdiction||'').toUpperCase(),requested_action:String(body.requested_action||'').toUpperCase(),merchant_id:String(body.merchant_id||''),provider_id:String(body.provider_id||''),reason:String(body.reason||'admin_legal_containment'),active:true,activated_by:user.email,activated_at:now});return Response.json({ok:true,kill_switch:row});
    }
    if(action==='deactivate_kill_switch'){
      const row=await svc.entities.LegalKillSwitch.get(String(body.id||'')).catch((error:any)=>safeBestEffort(error,{operation:'manageLegalExecution',fallback:null,severity:'secondary'}));if(!row)return Response.json({ok:false,error:'kill_switch_not_found'},{status:404});const updated=await svc.entities.LegalKillSwitch.update(row.id,{active:false,deactivated_by:user.email,deactivated_at:now});return Response.json({ok:true,kill_switch:updated});
    }
    if(action==='verify_signer_capacity'){
      const mandate=await svc.entities.Mandate.get(String(body.mandate_id||'')).catch((error:any)=>safeBestEffort(error,{operation:'manageLegalExecution',fallback:null,severity:'secondary'}));const evidenceRefs=Array.isArray(body.evidence_refs)?body.evidence_refs.map(String).filter(Boolean):[];if(!mandate||mandate.status!=='active'||!mandate.signed_at||!mandate.signed_by_email)return Response.json({ok:false,error:'active_signed_mandate_required'},{status:409});if(!evidenceRefs.length)return Response.json({ok:false,error:'signer_capacity_evidence_required'},{status:409});const updated=await svc.entities.Mandate.update(mandate.id,{signer_capacity_status:'verified',signer_capacity_verified_by:user.email,signer_capacity_verified_at:now,signer_capacity_evidence_refs:evidenceRefs});return Response.json({ok:true,mandate_id:mandate.id,signer_capacity_status:updated.signer_capacity_status});
    }
    if(['grant_authority','restrict_authority'].includes(action)){
      const mandate=await svc.entities.Mandate.get(String(body.mandate_id||'')).catch((error:any)=>safeBestEffort(error,{operation:'manageLegalExecution',fallback:null,severity:'secondary'}));const scope=String(body.scope||'').toUpperCase();if(!mandate||mandate.status!=='active')return Response.json({ok:false,error:'active_mandate_required'},{status:409});if(!AUTHORITY_SCOPES.has(scope))return Response.json({ok:false,error:'known_authority_scope_required'},{status:400});
      if(action==='grant_authority'){const evidenceRefs=Array.isArray(body.evidence_refs)?body.evidence_refs.map(String).filter(Boolean):[];if(!mandate.acceptance_snapshot_hash||!mandate.signed_at||!evidenceRefs.length)return Response.json({ok:false,error:'signed_mandate_and_authority_evidence_required'},{status:409});const row=await svc.entities.MandateAuthorityGrant.create({grant_key:String(body.grant_key||`${mandate.id}:${scope}:${body.provider_id||'*'}:${body.case_id||'*'}:${now}`),mandate_id:mandate.id,merchant_id:String(mandate.brand_id||body.merchant_id||''),scope,provider_id:String(body.provider_id||''),case_id:String(body.case_id||''),evidence_refs:evidenceRefs,effective_from:String(body.effective_from||now),effective_to:body.effective_to||undefined,active:true,created_by:user.email});return Response.json({ok:true,grant:row});}
      const row=await svc.entities.MandateAuthorityRestriction.create({restriction_key:String(body.restriction_key||`${mandate.id}:${scope}:${now}`),mandate_id:mandate.id,merchant_id:String(mandate.brand_id||body.merchant_id||''),scope,reason:String(body.reason||'admin_restriction'),effective_from:String(body.effective_from||now),effective_to:body.effective_to||undefined,active:true,created_by:user.email});return Response.json({ok:true,restriction:row});
    }
    return Response.json({ok:false,error:'unsupported_action',actions:['publish_policy','activate_kill_switch','deactivate_kill_switch','verify_signer_capacity','grant_authority','restrict_authority']},{status:400});
  }catch(error){console.error('manageLegalExecution failed',error);return Response.json({ok:false,error:'manage_legal_execution_failed'},{status:500});}
}
