import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
import { requireAdminOrInternal } from '../../shared/internalGate.ts';
import { isBusinessHour, normalizeEmail, policyIsActive, sanitizeExternalText } from '../../shared/commercialAutonomy.ts';

async function claude(prompt:string){const key=Deno.env.get('ANTHROPIC_API_KEY');if(!key)throw new Error('anthropic_not_configured');const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-sonnet-4-5',max_tokens:1600,messages:[{role:'user',content:prompt}]})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`anthropic_failed:${r.status}`);return String(d?.content?.[0]?.text||'')}
function parse(text:string){const c=text.replace(/```json\s*/gi,'').replace(/```/g,'').trim();try{return JSON.parse(c)}catch{}const m=c.match(/\{[\s\S]*\}/);if(m){try{return JSON.parse(m[0])}catch{}}return null}
function isoDayStart(){const d=new Date();d.setUTCHours(0,0,0,0);return d.toISOString()}

Deno.serve(async(req)=>{let task:any=null;try{
 const base44=createClientFromRequest(req);const body=await req.json().catch(()=>({}));const gate=await requireAdminOrInternal(req,base44,body);if(!gate.ok)return gate.response;const svc=base44.asServiceRole;
 const policies=await svc.entities.CommercialPolicy.filter({engine:'merchant_acquisition',status:'active'},'-approved_at',10).catch(()=>[]);const policy=policies.find((p:any)=>policyIsActive(p))||null;
 task=await svc.entities.AgentTask.create({brand_id:'_platform',agent_name:'autonomous_commercial',task_type:'merchant_acquisition_loop',status:'running',requires_approval:false,risk_level:3,input_summary:'Policy-gated acquisition sweep',started_at:new Date().toISOString()});
 if(!policy){await svc.entities.AgentTask.update(task.id,{status:'waiting_input',output_summary:'No active founder-approved merchant acquisition policy',completed_at:new Date().toISOString()});return Response.json({ok:true,task_id:task.id,status:'waiting_input',blocker:'acquisition_policy_missing'});}
 const controls=await svc.entities.OutboundControl.filter({control_key:'global'},'-created_date',1).catch(()=>[]);const control=controls[0]||null;if(true){await svc.entities.AgentTask.update(task.id,{status:'completed',output_summary:'Premium merchant acquisition disabled by routing policy; cold merchants use Resend volume pool',completed_at:new Date().toISOString()});return Response.json({ok:true,task_id:task.id,sent:0,reason:'merchant_volume_only'});}
 const manualOverride=gate.isAdmin&&body?.manual_override===true;
 if(!isBusinessHour(policy,new Date())&&!manualOverride){await svc.entities.AgentTask.update(task.id,{status:'completed',output_summary:'Outside approved business-hours window; no sends',completed_at:new Date().toISOString()});return Response.json({ok:true,task_id:task.id,sent:0,reason:'outside_business_hours'});}
 const sentToday=await svc.entities.CommunicationMessage.filter({direction:'outbound',policy_key:policy.policy_key,sent_at:{$gte:isoDayStart()}},'-sent_at',Math.min(Number(policy.daily_send_limit||30)+5,250)).catch(()=>[]);let remaining=Math.max(0,Number(policy.daily_send_limit||30)-sentToday.length);if(!remaining){await svc.entities.AgentTask.update(task.id,{status:'completed',output_summary:'Daily send limit reached',output_payload_json:{sent_today:sentToday.length,limit:policy.daily_send_limit},completed_at:new Date().toISOString()});return Response.json({ok:true,task_id:task.id,sent:0,reason:'daily_limit'});}
 const internal=Deno.env.get('INTERNAL_CALL_SECRET')||'';const icp=policy.icp_json||{};let discovery:any=null;
 if(icp?.enabled!==false){discovery=await svc.functions.invoke('leadOrchestrator',{icp:{industry:icp.industry||'ecommerce',titles:Array.isArray(icp.titles)?icp.titles:['founder','CEO','co-founder'],country:(policy.countries||[])[0]||'France',limit:Math.max(1,Math.min(Number(icp.per_run||25),50))},internal_secret:internal}).catch((e:any)=>({data:{ok:false,error:String(e?.message||e)}}));}
 const candidates=await svc.entities.OutboundLead.filter({stage:'scored'},'-score',Math.min(remaining*4,100)).catch(()=>[]);let sent=0,skipped=0;const errors:any[]=[];const excluded=new Set((policy.excluded_domains||[]).map((x:any)=>String(x).trim().toLowerCase()).filter(Boolean));
 for(const lead of candidates){if(sent>=remaining)break;const email=normalizeEmail(lead.contact_email);const domain=String(lead.company_domain||email.split('@')[1]||'').trim().toLowerCase();if(!email||excluded.has(domain)||Number(lead.score||0)<Number(policy.min_lead_score||70)||!lead.legal_basis){skipped++;continue;}const country=String(lead.country||'').toUpperCase();const allowed=(policy.countries||[]).map((x:any)=>String(x).toUpperCase());if(allowed.length&&!allowed.some((x:string)=>country.includes(x)||x.includes(country))){skipped++;continue;}
  const sup=await svc.entities.ContactSuppression.filter({email,active:true},'-created_date',1).catch(()=>[]);if(sup.length){skipped++;continue;}const existing=await svc.entities.CommunicationThread.filter({lead_id:lead.id,engine:'merchant_acquisition'},'-created_date',1).catch(()=>[]);if(existing.length){skipped++;continue;}
  const prompt=['Write the first CAMBRA B2B outreach email using ONLY the supplied facts.','CAMBRA currently focuses on card-payment cost analysis and Recover. Do not claim you know their PSP, fees, GMV, overpayment or savings unless supplied.','No fake employee identity. Sign simply as CAMBRA. Natural, concise, specific, max 85 words. No formulaic opener, no hype, no em-dash-heavy prose. Include a plain opt-out line.','Return ONLY JSON {"subject":"...","body":"...","language":"en|fr|es"}.','LEAD:',JSON.stringify({name:lead.contact_full_name,title:lead.contact_title,company:lead.company_name,domain:lead.company_domain,country:lead.country,industry:lead.industry,score_reason:lead.score_breakdown_json?.reasoning||lead.score_breakdown_json?.breakdown||null})].join('\n');const draft=parse(await claude(prompt));if(!draft?.subject||!draft?.body){errors.push({lead_id:lead.id,error:'draft_unparseable'});continue;}
  const thread=await svc.entities.CommunicationThread.create({thread_key:`lead:${lead.id}`,engine:'merchant_acquisition',related_entity_type:'OutboundLead',related_entity_id:lead.id,lead_id:lead.id,counterparty_email:email,counterparty_name:lead.contact_full_name||'',language:['en','fr','es'].includes(draft.language)?draft.language:'en',status:'open',policy_key:policy.policy_key,policy_version:policy.version,automation_paused:false,summary:`Outbound lead ${lead.company_name||lead.company_domain||email}`,sending_profile_key:'outlook:xavi@cambra.global'});
  const internal=Deno.env.get('INTERNAL_CALL_SECRET')||'';const next=new Date(Date.now()+Number(policy.followup_intervals_hours?.[0]||72)*3600000).toISOString();const r=await svc.functions.invoke('commercialSendMessage',{thread_id:thread.id,action:'initial_outreach',classification:'interested',subject:sanitizeExternalText(draft.subject,300),text:sanitizeExternalText(draft.body,5000),agent_name:'autonomous_commercial',idempotency_key:`initial:${lead.id}:${policy.version}`,sending_profile_key:'outlook:xavi@cambra.global',next_action_at:next,internal_secret:internal}).catch((e:any)=>({data:{ok:false,error:String(e?.message||e)}}));const rd=r?.data||r||{};if(rd.ok===false){errors.push({lead_id:lead.id,error:rd.error});await svc.entities.CommunicationThread.update(thread.id,{automation_paused:true,pause_reason:rd.error||'send_failed'}).catch(()=>null);continue;}await svc.entities.OutboundLead.update(lead.id,{stage:'contacted',next_action:`Await reply; follow-up due ${next}`}).catch(()=>null);sent++;
 }
 await svc.entities.AgentTask.update(task.id,{status:'completed',output_summary:`Acquisition sweep sent ${sent}; skipped ${skipped}; ${errors.length} errors`,output_payload_json:{policy:policy.version,discovery:discovery?.data||discovery||null,sent,skipped,errors:errors.slice(0,20),remaining_after:Math.max(0,remaining-sent)},completed_at:new Date().toISOString()});return Response.json({ok:true,task_id:task.id,discovery:discovery?.data||discovery||null,sent,skipped,errors:errors.length});
}catch(error){console.error('autonomousCommercialWorker failed',error);if(task?.id){try{const b=createClientFromRequest(req);await b.asServiceRole.entities.AgentTask.update(task.id,{status:'failed',error:'autonomous_commercial_failed',completed_at:new Date().toISOString()})}catch{}}return Response.json({ok:false,error:'autonomous_commercial_failed',task_id:task?.id||null},{status:500})}});
