// AUDIT 2026-08-18 — moved out of base44/functions/getEuropeanGrowthCommandCenter/entry.ts. Host functions
// import this module directly: a relative import into another function's tree
// cannot be bundled, so every host of this logical route silently failed to
// deploy and kept serving stale code.
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
import { requireAdminOrInternal } from '../internalGate.ts';
import { claimSchedulerRun, finishSchedulerRunOrThrow, markSchedulerEffectStarted, schedulerClaimDeniedResponse } from '../schedulerRun.ts';
import { applyScenarioChanges, GROWTH_PATH_ENGINE_VERSION } from '../growthPath.ts';
import { computeGrowthPath, ensureGrowthPathRegistry, loadGrowthPathInputs, persistGrowthPathSnapshot, recomputeEuropeanMarketPortfolio, validateGrowthAssumption, validateGrowthTarget } from '../growthPathRuntime.ts';

const safe = async (fn:()=>Promise<any>, fallback:any = []) => { try { return await fn(); } catch { return fallback; } };
const clean = (value:any, max = 300) => String(value || '').trim().slice(0,max);

async function persistRecommendation(service:any, result:any) {
  const top = result.recommendations?.[0]; if (!top) return null; const day = result.as_of.slice(0,10); const decisionKey = `growth-path:${top.recommendation_key}:${day}`;
  const row:any = { decision_key:decisionKey,market_code:'EUROPE',segment_key:'ALL',decision_type:'GROWTH_PATH_ALLOCATION',recommendation:top.action,reason:top.why,evidence_refs:result.lineage.flatMap((line:any) => line.sources || []).slice(0,100),expected_effect_json:{ expected_impact:top.expected_impact,cost_eur:top.cost_eur,time_to_value:top.time_to_value,marginal_allocation:result.marginal_allocation?.[0] || null },confidence:Number(top.confidence || 0),risks:top.risks || [],constraints:top.constraints || [],alternatives:result.recommendations.slice(1).map((item:any) => ({ action:item.action,reason:item.why })),required_authority:top.authority || 'FOUNDER_APPROVAL_REQUIRED',mode:'SHADOW',status:'OPEN',growth_policy_version:GROWTH_PATH_ENGINE_VERSION,commercial_policy_version:'canonical-active-policy-at-runtime',regulatory_policy_version:'canonical-p10-at-runtime',security_policy_version:'canonical-p11-at-runtime',model_version:GROWTH_PATH_ENGINE_VERSION,expires_at:new Date(Date.now()+7*86400000).toISOString(),created_at:result.as_of,updated_at:result.as_of };
  const old = await safe(() => service.entities.GrowthDecision.filter({ decision_key:decisionKey },'-created_at',1),[]); return old[0] ? service.entities.GrowthDecision.update(old[0].id,row) : service.entities.GrowthDecision.create(row);
}

async function configureTarget(service:any, body:any, actor:string) {
  if (body.confirmation !== 'SAVE_GROWTH_TARGET') return Response.json({ ok:false,error:'confirmation_required',expected:'SAVE_GROWTH_TARGET' },{ status:409 }); const validation = validateGrowthTarget(body); if (!validation.ok) return Response.json(validation,{ status:400 });
  const now = new Date().toISOString(); const version = clean(body.version,100) || `founder-${now}`; const scope = { period_key:clean(body.period_key,30),metric_key:body.metric_key,business_line:body.business_line || 'ALL' }; const active = await safe(() => service.entities.GrowthTargetRegistry.filter({ ...scope,status:'ACTIVE' },'-effective_at',100),[]); for (const row of active) await service.entities.GrowthTargetRegistry.update(row.id,{ status:'SUPERSEDED' });
  const saved = await service.entities.GrowthTargetRegistry.create({ target_key:`${version}:${scope.period_key}:${scope.metric_key}:${scope.business_line}`,version,status:'ACTIVE',period_key:scope.period_key,period_start:body.period_start,period_end:body.period_end,metric_key:scope.metric_key,business_line:scope.business_line,geography:clean(body.geography,100) || 'GLOBAL',channel:clean(body.channel,100) || 'ALL',target_value:validation.value,currency:clean(body.currency,10) || 'EUR',target_kind:body.target_kind || 'STRATEGIC_TARGET',milestones_json:Array.isArray(body.milestones_json) ? body.milestones_json.slice(0,50) : [],source_note:clean(body.source_note,1000) || 'Founder-edited strategic target; not a forecast.',approved_by:actor,approved_at:now,effective_at:now,created_at:now });
  return Response.json({ ok:true,target:saved,execution:false,note:'Target saved as a plan; no forecast or runtime policy was changed.' });
}

async function configureAssumption(service:any, body:any, actor:string) {
  if (body.confirmation !== 'SAVE_GROWTH_ASSUMPTION') return Response.json({ ok:false,error:'confirmation_required',expected:'SAVE_GROWTH_ASSUMPTION' },{ status:409 }); const validation = validateGrowthAssumption(body); if (!validation.ok) return Response.json(validation,{ status:400 });
  const now = new Date().toISOString(); const version = clean(body.version,100) || `founder-${now}`; const scope = { metric_key:clean(body.metric_key,100),period_key:clean(body.period_key,30) || 'ALL',business_line:clean(body.business_line,50) || 'PAYMENTS_EUROPE',channel:clean(body.channel,50) || 'ALL',geography:clean(body.geography,100) || 'GLOBAL',segment_key:clean(body.segment_key,100) || 'ALL' }; const active = await safe(() => service.entities.GrowthAssumptionRegistry.filter({ ...scope,status:'ACTIVE' },'-effective_at',100),[]); for (const row of active) await service.entities.GrowthAssumptionRegistry.update(row.id,{ status:'SUPERSEDED' });
  const saved = await service.entities.GrowthAssumptionRegistry.create({ assumption_key:`${version}:${scope.channel}:${scope.metric_key}:${scope.period_key}`,version,status:'ACTIVE',...scope,value:validation.value,low_value:Number.isFinite(Number(body.low_value)) ? Number(body.low_value) : validation.value,high_value:Number.isFinite(Number(body.high_value)) ? Number(body.high_value) : validation.value,unit:clean(body.unit,50),provenance:body.provenance,source_ref:clean(body.source_ref,500) || `Founder:${actor}`,source_note:clean(body.source_note,1000),confidence:validation.confidence,effective_at:now,created_by:actor,created_at:now });
  return Response.json({ ok:true,assumption:saved,execution:false,note:'Assumption version saved. No commercial, spend or execution policy was changed.' });
}

export async function handleEuropeanGrowthCommandCenter(req:Request) {
  let schedulerService:any = null; let schedulerClaim:any = null; let schedulerOk = true;
  try {
    const base44 = createClientFromRequest(req); const body = await req.clone().json().catch(() => ({})); const gate = await requireAdminOrInternal(req,base44,body); if (!gate.ok) return gate.response; const service = base44.asServiceRole; const action = clean(body.action,50) || 'status'; const actor = gate.user?.email || 'internal';
    if (action === 'configure_target') { if (!gate.isAdmin) return Response.json({ ok:false,error:'admin_required' },{ status:403 }); return configureTarget(service,body,actor); }
    if (action === 'configure_assumption') { if (!gate.isAdmin) return Response.json({ ok:false,error:'admin_required' },{ status:403 }); return configureAssumption(service,body,actor); }

    let seed:any = null; let portfolio:any = null; let savedSnapshot:any = null; let decision:any = null; let computed:any;
    if (action === 'recompute') {
      if (!gate.isInternal && body.confirmation !== 'RECOMPUTE_GROWTH_PATH') return Response.json({ ok:false,error:'confirmation_required',expected:'RECOMPUTE_GROWTH_PATH' },{ status:409 });
      if (body.source === 'scheduled') { let claim = await claimSchedulerRun(service,req,{ worker_key:'getEuropeMarketsCommandCenter',cadence_seconds:21600 }); let denied=schedulerClaimDeniedResponse(claim);if(denied)return denied; claim=await markSchedulerEffectStarted(service,claim);denied=schedulerClaimDeniedResponse(claim);if(denied)return denied;schedulerService = service; schedulerClaim = claim; }
      seed = await ensureGrowthPathRegistry(service); portfolio = await recomputeEuropeanMarketPortfolio(service); computed = await computeGrowthPath(service,{ scenario_key:'BASE' }); savedSnapshot = await persistGrowthPathSnapshot(service,computed.result); decision = await persistRecommendation(service,computed.result);
    } else if (action === 'run_scenario') {
      const inputs = await loadGrowthPathInputs(service); const changes = Array.isArray(body.changes) ? body.changes.slice(0,50) : []; const scenarioKey = clean(body.scenario_key,100) || `CUSTOM:${Date.now()}`; computed = await computeGrowthPath(service,{ scenario_key:scenarioKey,assumptions:applyScenarioChanges(inputs.assumptions,changes) });
      if (body.save === true) {
        if (!gate.isAdmin || body.confirmation !== 'SAVE_GROWTH_SCENARIO') return Response.json({ ok:false,error:'confirmation_required',expected:'SAVE_GROWTH_SCENARIO' },{ status:409 }); const now = new Date().toISOString(); const row = { scenario_key:scenarioKey,name:clean(body.name,120) || scenarioKey,scenario_type:['BASE','INTERNAL_EXECUTION_TARGET','BREAKOUT','CUSTOM'].includes(body.scenario_type) ? body.scenario_type : 'CUSTOM',status:'ACTIVE',changes_json:changes,result_json:{ target_gaps:computed.result.target_gaps,binding_constraint:computed.result.binding_constraint,recommendations:computed.result.recommendations,confidence:computed.result.confidence },target_version:computed.result.forecasts?.[0]?.target_key || '',assumption_versions:[...new Set(computed.inputs.assumptions.map((item:any) => item.version).filter(Boolean))],created_by:actor,created_at:now,updated_at:now }; const old = await safe(() => service.entities.GrowthScenario.filter({ scenario_key:scenarioKey },'-updated_at',1),[]); await (old[0] ? service.entities.GrowthScenario.update(old[0].id,row) : service.entities.GrowthScenario.create(row));
      }
    } else if (action === 'status') computed = await computeGrowthPath(service,{ scenario_key:'BASE' });
    else return Response.json({ ok:false,error:'unsupported_growth_action' },{ status:400 });

    const [snapshots,decisions,outcomes,briefs,experiments,costs,touches,approvals,production] = await Promise.all([safe(() => service.entities.MarketGrowthSnapshot.list('-calculated_at',500)),safe(() => service.entities.GrowthDecision.list('-created_at',200)),safe(() => service.entities.GrowthDecisionOutcome.list('-evaluated_at',200)),safe(() => service.entities.FounderGrowthBrief.list('-generated_at',20)),safe(() => service.entities.GrowthExperiment.list('-created_at',200)),safe(() => service.entities.GrowthCostLedger.list('-occurred_at',5000)),safe(() => service.entities.AcquisitionTouch.list('-occurred_at',5000)),safe(() => service.entities.Approval.filter({ status:'pending' },'-created_date',500)),safe(() => service.entities.ProductionReadinessSnapshot.list('-calculated_at',1))]);
    const latestByMarket = new Map(); for (const row of snapshots) if (!latestByMarket.has(row.market_code)) latestByMarket.set(row.market_code,row); const markets = [...latestByMarket.values()].sort((a:any,b:any) => (b.attractiveness_score ?? -1)-(a.attractiveness_score ?? -1) || String(a.market_code).localeCompare(String(b.market_code)));
    return Response.json({ ok:true,engine_version:GROWTH_PATH_ENGINE_VERSION,action,seed,portfolio,snapshot_id:savedSnapshot?.id || null,decision_id:decision?.id || null,growth_path:computed.result,target_registry:computed.inputs.targets,assumption_registry:computed.inputs.assumptions,scenarios:computed.inputs.scenarios,markets,brief:briefs[0] || null,decisions:decisions.slice(0,100),decision_outcomes:outcomes.slice(0,100),experiments:experiments.slice(0,100),approval_inbox:approvals.slice(0,100),production_readiness:production[0] || null,metrics:{ markets:markets.length,scored_markets:markets.filter((x:any) => x.attractiveness_status === 'SCORED').length,launch_ready:markets.filter((x:any) => x.launch_state === 'READY').length,hard_blocked:markets.filter((x:any) => ['TECHNICAL_BLOCKED','REGULATORY_BLOCKED'].includes(x.launch_state)).length,open_decisions:decisions.filter((x:any) => x.status === 'OPEN').length,running_experiments:experiments.filter((x:any) => x.status === 'RUNNING').length,cost_rows:costs.length,attribution_touches:touches.length,pending_approvals:approvals.length },truth_boundary:{ ...computed.result.truth_boundary,ranking:'Only evidence-backed dimensions are scored; insufficient markets remain unranked.',cac:'Unknown until all required cost categories and attributed customers are evidenced.',experiments:'Underpowered or non-significant tests remain NO_CONCLUSIVE_RESULT.' } });
  } catch (error) { schedulerOk = false; console.error(error); return Response.json({ ok:false,error:'european_growth_command_center_failed' },{ status:500 }); }
  finally { if (schedulerService && schedulerClaim?.allowed === true) await finishSchedulerRunOrThrow(schedulerService,schedulerClaim,{ worker_key:'getEuropeMarketsCommandCenter',engine_version:GROWTH_PATH_ENGINE_VERSION },schedulerOk); }
}
