// AUDIT 2026-08-18 — moved out of base44/functions/instantlyReconciliationWorker/entry.ts so hosts of this
// logical route can import it without a relative import escaping their bundle.
import { safeBestEffort } from '../bestEffort.ts';
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
import { operationErrorResponse } from '../publicErrors.ts';
import { requireAdminOrInternal } from '../internalGate.ts';
import { claimSchedulerRun, finishSchedulerRunOrThrow, markSchedulerEffectStarted, schedulerClaimDeniedResponse } from '../schedulerRun.ts';
import { InstantlyOutboundProvider, instantlyTransportProfile } from '../outboundProvider.ts';
import { processInstantlyProviderEvent } from '../outboundProviderEventProcessing.ts';
import { upsertInstantlyProviderState } from '../instantlyRuntime.ts';
import { normalizeEmail } from '../commercialAutonomy.ts';
import { reservePaidOperation, settlePaidOperation } from '../costGovernance.ts';

const addresses=(value:any)=>String(value||'').split(',').map(normalizeEmail).filter(Boolean);
const accountEvidence=(account:any)=>({email:normalizeEmail(account?.email),status:account?.status??null,warmup_status:account?.warmup_status??null,warmup_score:account?.stat_warmup_score??null,setup_pending:account?.setup_pending??null,tracking_domain_status:account?.tracking_domain_status??null,daily_limit:account?.daily_limit??null,status_message_code:account?.status_message?.code??null});
// Reconciliation consumes the already-paid Instantly subscription rather than
// a metered provider charge. Keep a positive one-cent control-plane reservation
// so the global governor, anomaly alert and kill-switch still see every cycle.
export const INSTANTLY_RECONCILIATION_COST_FLOOR_MINOR=1;

export async function handleInstantlyReconciliationWorker(req:Request){let svc:any=null,claim:any=null,success=true,reservation:any=null;try{
  const base44=createClientFromRequest(req);const body=await req.clone().json().catch(()=>({}));const gate=await requireAdminOrInternal(req,base44,body);if(!gate.ok)return gate.response;svc=base44.asServiceRole;claim=await claimSchedulerRun(svc,req,{worker_key:'instantlyReconciliationWorker',cadence_seconds:900});{const denied=schedulerClaimDeniedResponse(claim);if(denied)return denied;}claim=await markSchedulerEffectStarted(svc,claim);{const denied=schedulerClaimDeniedResponse(claim);if(denied)return denied;}
  const apiKey=Deno.env.get('INSTANTLY_API_KEY')||'';if(!apiKey){await upsertInstantlyProviderState(svc,{status:'NOT_CONFIGURED',auth_test_pass:false,last_checked_at:new Date().toISOString(),last_error_code:'SECRET_MISSING'}).catch((error:any)=>safeBestEffort(error,{operation:'instantlyReconciliationWorker',fallback:null,severity:'secondary'}));return Response.json({ok:true,status:'NOT_CONFIGURED',reconciled:0});}
  reservation=await reservePaidOperation(svc,{event_key:`api:instantly:reconcile:${claim.run_key}`,category:'api',provider:'instantly',source:'instantlyReconciliationWorker',emergency_effect_mode:'read_only_reconciliation',related_entity_type:'CommercialProviderState',related_entity_id:'instantly',amount_minor:INSTANTLY_RECONCILIATION_COST_FLOOR_MINOR});
  const provider=new InstantlyOutboundProvider(apiKey);let diagnostic:any,emailPage:any;try{[diagnostic,emailPage]=await Promise.all([provider.diagnose(),provider.listEmails(100)])}catch(error:any){if(String(error?.code||'')!=='INSTANTLY_PLAN_REQUIRED')throw error;await settlePaidOperation(svc,reservation,{ok:false,usage_json:{error_code:'INSTANTLY_PLAN_REQUIRED',provider_request_completed:true,plan_upgrade_required:true}});const state=await upsertInstantlyProviderState(svc,{status:'DEGRADED',auth_test_pass:false,last_checked_at:new Date().toISOString(),configuration_json:{transport_role_only:true,mailbox_protocol_access:false,supersearch_enabled:false,reconciliation_available:false,plan_upgrade_required:true},metrics_json:{bounded_email_scan:0,recovered_inbound:0,recovered_sent:0},last_error_code:'INSTANTLY_PLAN_REQUIRED'});return Response.json({ok:true,status:state.status,reconciled:0,reason:'INSTANTLY_PLAN_REQUIRED',plan_upgrade_required:true})}const accounts=(diagnostic.accounts||[]).map(accountEvidence),campaigns=diagnostic.campaigns||[],webhooks=diagnostic.webhooks||[],emails=Array.isArray(emailPage?.items)?emailPage.items:[];
  const profiles=await svc.entities.OutboundSendingProfile.filter({provider:'instantly'},'-created_date',100).catch((error:any)=>safeBestEffort(error,{operation:'instantlyReconciliationWorker',fallback:[],severity:'secondary'}));const transportProfiles=profiles.filter(instantlyTransportProfile);let readinessBlocked=false,nativeAiConflict=false;
  for(const profile of transportProfiles){const accountEmails=(profile.provider_config_json?.account_emails||[]).map((value:any)=>normalizeEmail(value)).filter(Boolean);const matched=accounts.filter((account:any)=>accountEmails.includes(account.email));const minimumScore=Math.max(1,Math.min(100,Number(profile.provider_config_json?.minimum_warmup_score||80)));const senderReady=accountEmails.length>0&&matched.length===accountEmails.length&&matched.every((account:any)=>account.status===1&&account.warmup_status===1&&account.setup_pending===false&&Number(account.warmup_score)>=minimumScore);const remoteCampaign=campaigns.find((campaign:any)=>String(campaign.id)===String(profile.external_campaign_id||''));const conflict=Boolean(remoteCampaign?.ai_sdr_id);const webhook=webhooks.find((row:any)=>String(row.campaign||'')===String(profile.external_campaign_id||'')&&row.event_type==='all_events');const webhookActive=Number(webhook?.status)===1;readinessBlocked ||= !senderReady||!webhookActive||!remoteCampaign;nativeAiConflict ||= conflict;await svc.entities.OutboundSendingProfile.update(profile.id,{webhook_status:webhookActive?'ACTIVE':webhook?'ERROR':'NOT_CONFIGURED',last_provider_health_at:new Date().toISOString(),provider_config_json:{...(profile.provider_config_json||{}),minimum_warmup_score:minimumScore,sender_ready:senderReady,sender_health_evidence:matched,native_ai_conflict:conflict,native_ai_reply_enabled:false,remote_campaign_status:remoteCampaign?.status??null,remote_not_sending_status:remoteCampaign?.not_sending_status??null},...(!senderReady||!webhookActive||conflict?{status:'paused',notes:conflict?'Provider-native AI conflict; CAMBRA replies remain blocked.':'Provider reconciliation has not proven sender/webhook readiness.'}:{})}).catch((error:any)=>safeBestEffort(error,{operation:'instantlyReconciliationWorker',fallback:null,severity:'secondary'}));}
  const threads=await svc.entities.CommunicationThread.filter({external_provider:'instantly'},'-last_message_at',200).catch((error:any)=>safeBestEffort(error,{operation:'instantlyReconciliationWorker',fallback:[],severity:'secondary'}));let recoveredInbound=0,recoveredSent=0;
  for(const email of emails){const id=String(email?.id||'');const timestamp=String(email?.timestamp_email||email?.timestamp_created||'');if(!id||!timestamp)continue;const from=normalizeEmail(email?.from_address_email);const to=addresses(email?.to_address_email_list);const eaccount=normalizeEmail(email?.eaccount);const thread=threads.find((row:any)=>normalizeEmail(row.counterparty_email)===from&&(to.includes(eaccount)||(row.sending_profile_key&&profiles.some((profile:any)=>profile.profile_key===row.sending_profile_key&&normalizeEmail(profile.from_address)===eaccount))));if(thread){const result=await processInstantlyProviderEvent(svc,{event_type:'reply_received',timestamp,workspace:email?.organization_id||'',campaign_id:thread.external_campaign_id||'',lead_email:from,email_account:eaccount,email_id:id,reply_subject:String(email?.subject||''),reply_text:String(email?.body?.text||''),reply_html:String(email?.body?.html||'')});if(result.ok&&!result.duplicate)recoveredInbound++;continue;}const outboundThread=threads.find((row:any)=>to.includes(normalizeEmail(row.counterparty_email))&&profiles.some((profile:any)=>profile.profile_key===row.sending_profile_key&&normalizeEmail(profile.from_address)===from));if(outboundThread){const pending=await svc.entities.CommunicationMessage.filter({thread_id:outboundThread.id,direction:'outbound',provider:'instantly',send_status:'scheduled'},'-created_date',20).catch((error:any)=>safeBestEffort(error,{operation:'instantlyReconciliationWorker',fallback:[],severity:'secondary'}));const message=pending.find((row:any)=>String(row.subject||'')===String(email?.subject||''));if(message){const result=await processInstantlyProviderEvent(svc,{event_type:'email_sent',timestamp,workspace:email?.organization_id||'',campaign_id:outboundThread.external_campaign_id||'',lead_email:normalizeEmail(outboundThread.counterparty_email),email_account:from,email_id:id,email_subject:String(email?.subject||''),email_text:String(email?.body?.text||''),email_html:String(email?.body?.html||'')});if(result.ok&&!result.duplicate)recoveredSent++;}}
  }
  const state=await upsertInstantlyProviderState(svc,{status:nativeAiConflict||readinessBlocked?'DEGRADED':'AUTHENTICATED',auth_test_pass:true,last_checked_at:new Date().toISOString(),last_success_at:new Date().toISOString(),accounts_json:{items:accounts,count:accounts.length},campaigns_json:{count:campaigns.length},webhook_json:{count:webhooks.length},metrics_json:{bounded_email_scan:emails.length,recovered_inbound:recoveredInbound,recovered_sent:recoveredSent},configuration_json:{transport_role_only:true,mailbox_protocol_access:false,supersearch_enabled:false,native_ai_conflict:nativeAiConflict,sender_readiness_blocked:readinessBlocked,transport_profile_keys:transportProfiles.map((profile:any)=>profile.profile_key)},last_error_code:nativeAiConflict?'NATIVE_AI_REPLY_CONFLICT':readinessBlocked?'PROVIDER_READINESS_NOT_PROVEN':''});
  await settlePaidOperation(svc,reservation,{ok:true,usage_json:{accounts:accounts.length,campaigns:campaigns.length,webhooks:webhooks.length,emails_scanned:emails.length,recovered_inbound:recoveredInbound,recovered_sent:recoveredSent}});return Response.json({ok:true,status:state.status,emails_scanned:emails.length,recovered_inbound:recoveredInbound,recovered_sent:recoveredSent,readiness_blocked:readinessBlocked,native_ai_conflict:nativeAiConflict});
}catch(error:any){success=false;if(svc&&reservation)await settlePaidOperation(svc,reservation,{ok:false,usage_json:{error_code:String(error?.code||'FAILED').slice(0,160)}}).catch((error:any)=>safeBestEffort(error,{operation:'instantlyReconciliationWorker',fallback:null,severity:'secondary'}));if(svc)await upsertInstantlyProviderState(svc,{status:'DEGRADED',auth_test_pass:false,last_checked_at:new Date().toISOString(),last_error_code:String(error?.code||'RECONCILIATION_FAILED').slice(0,160)}).catch((error:any)=>safeBestEffort(error,{operation:'instantlyReconciliationWorker',fallback:null,severity:'secondary'}));console.error('instantlyReconciliationWorker failed',error);return operationErrorResponse(error,'instantlyReconciliationWorker','instantly_reconciliation_failed');}finally{if(svc&&claim?.allowed)await finishSchedulerRunOrThrow(svc,claim,{worker_key:'instantlyReconciliationWorker'},success)}}
