import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req); const user = await base44.auth.me().catch(() => null); if (!user || user.role !== 'admin') return Response.json({ ok:false,error:'Forbidden' }, { status:403 }); const svc = base44.asServiceRole;
    const [snapshots,decisions,outcomes,briefs,experiments,costs,touches,approvals,production] = await Promise.all([svc.entities.MarketGrowthSnapshot.list('-calculated_at', 500).catch(() => []),svc.entities.GrowthDecision.list('-created_at', 200).catch(() => []),svc.entities.GrowthDecisionOutcome.list('-evaluated_at', 200).catch(() => []),svc.entities.FounderGrowthBrief.list('-generated_at', 20).catch(() => []),svc.entities.GrowthExperiment.list('-created_at', 200).catch(() => []),svc.entities.GrowthCostLedger.list('-occurred_at', 5000).catch(() => []),svc.entities.AcquisitionTouch.list('-occurred_at', 5000).catch(() => []),svc.entities.Approval.filter({ status:'pending' }, '-created_date', 500).catch(() => []),svc.entities.ProductionReadinessSnapshot.list('-calculated_at', 1).catch(() => [])]);
    const latestByMarket = new Map(); for (const row of snapshots) if (!latestByMarket.has(row.market_code)) latestByMarket.set(row.market_code,row); const markets = [...latestByMarket.values()].sort((a:any,b:any) => (b.attractiveness_score ?? -1) - (a.attractiveness_score ?? -1) || String(a.market_code).localeCompare(String(b.market_code)));
    return Response.json({ ok:true,markets,brief:briefs[0] || null,decisions:decisions.slice(0,100),decision_outcomes:outcomes.slice(0,100),experiments:experiments.slice(0,100),approval_inbox:approvals.slice(0,100),production_readiness:production[0] || null,metrics:{ markets:markets.length,scored_markets:markets.filter((x:any) => x.attractiveness_status === 'SCORED').length,launch_ready:markets.filter((x:any) => x.launch_state === 'READY').length,hard_blocked:markets.filter((x:any) => ['TECHNICAL_BLOCKED','REGULATORY_BLOCKED'].includes(x.launch_state)).length,open_decisions:decisions.filter((x:any) => x.status === 'OPEN').length,running_experiments:experiments.filter((x:any) => x.status === 'RUNNING').length,cost_rows:costs.length,attribution_touches:touches.length,pending_approvals:approvals.length },truth_boundary:{ ranking:'Only evidence-backed dimensions are scored; insufficient markets remain unranked.',revenue:'Founder OS canonical revenue definitions; growth never treats TAM or pipeline as cash.',cac:'Unknown until all cost categories and attributed customers are evidenced.',experiments:'Underpowered or non-significant tests are NO_CONCLUSIVE_RESULT.',authority:'Shadow/recommend-only. P10, P11, EmergencyControl and founder authority cannot be overridden.' } });
  } catch (error) { console.error(error); return Response.json({ ok:false,error:'european_growth_command_center_failed' }, { status:500 }); }
});
