export const AGGREGATE_ENGINE_VERSION='p14-aggregate-1.0.0';
export const AGGREGATE_MIN_APS_TO_PREPARE=50;
export const AGGREGATE_MIN_APS_TO_NEGOTIATE=65;
export type DemandVolumeKind='observed'|'addressable'|'committed'|'probable';
export function clamp01(n:number){return Math.max(0,Math.min(1,Number.isFinite(n)?n:0))}
export function annualize(valueMinor:number,windowDays:number){const d=Math.max(1,Number(windowDays||0));return Math.round(Math.max(0,Number(valueMinor||0))*365/d)}
export function committedVolumeFromExplicitCommitments(rows:any[],now=Date.now()){return rows.filter(r=>['explicitly_authorized','active'].includes(String(r.status||''))).filter(r=>!r.effective_at||Date.parse(r.effective_at)<=now).filter(r=>!r.expires_at||Date.parse(r.expires_at)>now).reduce((a,r)=>a+Math.max(0,Number(r.committed_annual_volume_minor||0)),0)}
export function aggregationPowerScore(x:any){const addressable=Math.max(0,Number(x.addressable_annual_volume_minor||0));const committed=Math.max(0,Number(x.committed_annual_volume_minor||0));const merchants=Math.max(0,Number(x.merchant_count||0));const readiness=clamp01(Number(x.migration_readiness||0));const confidence=clamp01(Number(x.confidence||0));const concentration=clamp01(Number(x.concentration||0));const growth=Math.max(-1,Math.min(2,Number(x.growth_rate||0)));const vol=Math.min(1,Math.log10(1+addressable/100)/8);const com=Math.min(1,Math.log10(1+committed/100)/8);const merchantDepth=Math.min(1,Math.log10(1+merchants)/2);const score=100*(.30*vol+.24*com+.12*merchantDepth+.14*readiness+.12*confidence+.08*Math.max(0,growth/2))*(1-.30*concentration);return Number(Math.max(0,Math.min(100,score)).toFixed(1))}
export function apsLabel(score:number){const s=Number(score||0);if(s>=90)return'STRATEGIC_PROCUREMENT';if(s>=80)return'HIGH_LEVERAGE';if(s>=65)return'NEGOTIATION_READY';if(s>=50)return'PREPARE_MARKET';if(s>=30)return'BUILD_POOL';return'OBSERVE'}
export function poolStatusFromAPS(score:number,current?:string){if(['rfp_open','negotiating','final_offer','human_approval','contracting','active','tier_upgrade_pending','renegotiating','expiring'].includes(String(current||'')))return current;return score>=65?'negotiation_ready':score>=30?'threshold_waiting':'pool_forming'}
export function metricValue(pool:any,metric:string){if(metric==='observed_volume')return Number(pool.observed_annual_volume_minor||0);if(metric==='addressable_volume')return Number(pool.addressable_annual_volume_minor||0);if(metric==='committed_volume')return Number(pool.committed_annual_volume_minor||0);if(metric==='active_merchant_count')return Number(pool.merchant_count||0);if(metric==='transaction_count')return Number(pool.transaction_count_annualized||0);return 0}
export function tierProgress(pool:any,tier:any){const value=Math.max(0,metricValue(pool,String(tier.metric||''))),threshold=Math.max(0,Number(tier.threshold_value||0));const qualified=threshold===0||value>=threshold;return{value,threshold,qualified,progress_pct:threshold?Number(Math.min(100,value/threshold*100).toFixed(1)):100,amount_remaining:Math.max(0,threshold-value)}}
export function pricingCostMinor(volumeMinor:number,txCount:number,pricing:any){const volume=Math.max(0,Number(volumeMinor||0)),tx=Math.max(0,Number(txCount||0));return Math.round(volume*Math.max(0,Number(pricing?.variable_rate_bps||0))/10000+tx*Math.max(0,Number(pricing?.fixed_fee_minor||0))+Math.max(0,Number(pricing?.monthly_fee_minor||0))*12)}
export function normalizeBidForPool(pool:any,bid:any){const volume=Math.max(0,Number(pool.addressable_annual_volume_minor||0)),tx=Math.max(0,Number(pool.transaction_count_annualized||0));const cost=pricingCostMinor(volume,tx,bid);const bps=volume?Number((cost/volume*10000).toFixed(2)):null;return{normalized_annual_cost_minor:cost,estimated_effective_bps:bps}}
export function materialAggregateTerms(x:any){const l=x?.legal_terms_json||x?.conditions_json||{};return Boolean(l.exclusivity===true||l.volume_guarantee===true||l.minimum_spend!=null||l.minimum_volume!=null||l.financial_liability===true||Number(l.contract_term_months||x?.contract_term_months||0)>12||l.brand_usage_material===true||l.regulatory_exposure===true)}
export function truthfulDemandSnapshot(pool:any){return{merchant_count:Number(pool.merchant_count||0),observed_annual_volume_minor:Number(pool.observed_annual_volume_minor||0),addressable_annual_volume_minor:Number(pool.addressable_annual_volume_minor||0),committed_annual_volume_minor:Number(pool.committed_annual_volume_minor||0),probable_annual_volume_minor:Number(pool.probable_annual_volume_minor||0),currency:String(pool.currency||'EUR'),aggregation_power_score:Number(pool.aggregation_power_score||0),claim_rule:'observed/addressable/committed are distinct; committed comes only from explicit AggregateCommitment evidence'}}
export function canOpenRFP(pool:any){return Number(pool.aggregation_power_score||0)>=AGGREGATE_MIN_APS_TO_NEGOTIATE&&Number(pool.addressable_annual_volume_minor||0)>0&&Number(pool.merchant_count||0)>0}
