import{safeNumber,ageMinutes,riskRank,attentionPriority,FOUNDER_OS_VERSION}from'./founderOSCore.ts';
// COMMAND-C3 (2026-08-17) — this helper used to swallow every read failure and
// return [] with no trace. Every metric below is computed from those arrays and
// was then stamped with a HARDCODED confidence literal, so a failed Invoice read
// produced `collected_revenue: 0` labelled `verified` on the founder's home page.
// A failed read is now recorded, and `metric()` refuses to attach a confidence
// to a value whose sources did not load.
type SourceFailures=Set<string>;
const safeTracked=async<T>(failures:SourceFailures,source:string,fn:()=>Promise<T>,fallback:any=[]):Promise<any>=>{
 try{return await fn()}catch(error){
  failures.add(source);
  console.error(JSON.stringify({event:'founder_os_source_unavailable',source,message:error instanceof Error?error.message:String(error)}));
  return fallback;
 }
};
const sum=(a:any[],f:string)=>a.reduce((x:number,y:any)=>x+safeNumber(y?.[f]),0);
const unique=(a:any[])=>new Set(a.filter(Boolean)).size;
export async function buildFounderSnapshot(s:any){
 const failures:SourceFailures=new Set<string>();
 const safe=<T>(source:string,fn:()=>Promise<T>,fallback:any=[])=>safeTracked(failures,source,fn,fallback);
 const now=new Date(),since24=new Date(now.getTime()-86400000).toISOString(),since7=new Date(now.getTime()-7*86400000).toISOString();
 const [brands,leads,life,reports,invoices,providerLedger,pools,approvals,incidents,meetings,tasks,agentPerf,health,gaps,cases,migrations,integrations,cs,attrs,digest,commercial,decisions,legalDecisions,legalPolicies,legalSwitches]=await Promise.all([
  safe('Brand',()=>s.entities.Brand.list('-created_date',2000)),safe('OutboundLead',()=>s.entities.OutboundLead.list('-created_date',5000)),safe('RevenueLifecycle',()=>s.entities.RevenueLifecycle.list('-updated_at',5000)),safe('MonthlySavingsReport',()=>s.entities.MonthlySavingsReport.list('-month',5000)),safe('Invoice',()=>s.entities.Invoice.list('-issued_at',5000)),safe('ProviderRevenueLedger',()=>s.entities.ProviderRevenueLedger.list('-updated_at',5000)),safe('AggregatePool',()=>s.entities.AggregatePool.list('-updated_at',2000)),safe('Approval',()=>s.entities.Approval.filter({status:'pending'},'-created_date',1000)),safe('AutonomyIncident',()=>s.entities.AutonomyIncident.filter({status:'open'},'-last_seen_at',1000)),safe('CommunicationThread',()=>s.entities.CommunicationThread.filter({meeting_start_at:{$ne:null}},'meeting_start_at',500)),safe('AgentTask',()=>s.entities.AgentTask.list('-created_date',5000)),safe('AgentPerformanceMetric',()=>s.entities.AgentPerformanceMetric.list('-calculated_at',1000)),safe('OperatingHealthAssessment',()=>s.entities.OperatingHealthAssessment.list('-calculated_at',5)),safe('RealWorldGapReport',()=>s.entities.RealWorldGapReport.filter({status:{$in:['open','investigating']}},'-created_at',500)),safe('NegotiationCase',()=>s.entities.NegotiationCase.list('-started_at',2000)),safe('MigrationTask',()=>s.entities.MigrationTask.list('-updated_at',3000)),safe('Integration',()=>s.entities.Integration.list('-last_sync_at',4000)),safe('CustomerSuccessSignal',()=>s.entities.CustomerSuccessSignal.filter({status:'open'},'-updated_at',1000)),safe('ProviderRevenueAttribution',()=>s.entities.ProviderRevenueAttribution.filter({status:'active'},'-updated_at',5000)),safe('ExecutiveDigest',()=>s.entities.ExecutiveDigest.list('-generated_at',1)),safe('CommercialIntelligenceSnapshot',()=>s.entities.CommercialIntelligenceSnapshot.list('-generated_at',1)),safe('FounderDecision',()=>s.entities.FounderDecision.filter({status:'open'},'-created_at',100)),safe('LegalExecutionDecision',()=>s.entities.LegalExecutionDecision.filter({allowed:false},'-evaluated_at',1000)),safe('LegalExecutionPolicy',()=>s.entities.LegalExecutionPolicy.filter({active:true},'-effective_from',2000)),safe('LegalKillSwitch',()=>s.entities.LegalKillSwitch.filter({active:true},'-activated_at',250))
 ]);
 const productionBrands=brands.filter((b:any)=>!b.is_demo),activeBrandIds=new Set<string>();
 for(const x of life)if(['savings_accepted','implementation_pending','implemented','verification_pending','savings_verified','billable','invoiced','payment_pending','paid','partially_paid'].includes(String(x.state)))activeBrandIds.add(String(x.brand_id));
 for(const i of integrations)if(i.status==='connected'&&i.brand_id)activeBrandIds.add(String(i.brand_id));
 const verified=reports.filter((r:any)=>r.measurement_mode==='fully_verified'&&r.verification_status==='realized');
 const merchantCollected=sum(invoices,'amount_paid'),providerPaid=sum(providerLedger.filter((x:any)=>x.state==='paid'),'paid_amount_minor')/100,providerAccrued=sum(providerLedger,'accrued_amount_minor')/100;
 const totalCollected=merchantCollected+providerPaid;
 const addressable=sum(pools.filter((p:any)=>!['archived','terminated'].includes(String(p.status))),'addressable_annual_volume_minor')/100;
 const committed=sum(pools.filter((p:any)=>!['archived','terminated'].includes(String(p.status))),'committed_annual_volume_minor')/100;
 const pendingL4=approvals.filter((a:any)=>safeNumber(a.risk_level)>=4),criticalInc=incidents.filter((i:any)=>String(i.severity).toLowerCase()==='critical');
 const futureMeetings=meetings.filter((m:any)=>Date.parse(m.meeting_start_at||'')>=Date.now()-3600000&&m.founder_required===true);
 const failed7=tasks.filter((t:any)=>String(t.status)==='failed'&&String(t.created_date||t.started_at||'')>=since7),running=tasks.filter((t:any)=>String(t.status)==='running');
 const attention:any[]=[];
 for(const a of pendingL4){const fin=safeNumber(a.draft_payload_json?.estimated_financial_impact||a.draft_payload_json?.expected_provider_revenue_12m_minor)/100;attention.push({id:`approval:${a.id}`,type:'approval_required',title:a.action_type,summary:String(a.draft_content||'Material approval required').slice(0,320),related_entity_type:a.related_entity_type,related_entity_id:a.related_entity_id,approval_id:a.id,financial_impact:fin||null,risk:'high',deadline:a.expires_at||null,ai_recommendation:a.draft_payload_json?.ai_recommendation||null,confidence:a.draft_payload_json?.confidence??null,financial_impact_score:fin?Math.min(100,20+Math.log10(Math.max(1,fin))*18):30,risk_score:85,urgency_score:a.expires_at?Math.max(20,100-Math.max(0,Date.parse(a.expires_at)-Date.now())/86400000*10):55,strategic_score:60})}
 for(const i of criticalInc){attention.push({id:`incident:${i.id}`,type:'critical_exception',title:i.summary||i.incident_type,summary:i.details_json?.message||i.summary||'Critical incident',related_entity_type:i.subject_type,related_entity_id:i.subject_id,financial_impact:safeNumber(i.financial_impact_minor)/100||null,risk:'critical',deadline:null,ai_recommendation:i.recovery_json?.recommended_action||null,confidence:null,financial_impact_score:i.financial_impact_minor?75:40,risk_score:100,urgency_score:95,strategic_score:60})}
 for(const m of futureMeetings.slice(0,20)){attention.push({id:`meeting:${m.id}`,type:'meeting',title:m.counterparty_name||m.summary||'Founder meeting',summary:m.summary||m.meeting_classification||'',related_entity_type:m.related_entity_type,related_entity_id:m.related_entity_id,financial_impact:null,risk:'notice',deadline:m.meeting_start_at,ai_recommendation:'Review meeting brief and desired outcome',confidence:null,financial_impact_score:20,risk_score:30,urgency_score:Date.parse(m.meeting_start_at||'')-Date.now()<86400000?90:50,strategic_score:m.meeting_classification==='strategic'||m.meeting_classification==='executive'?90:55})}
 for(const g of gaps.filter((x:any)=>safeNumber(x.financial_impact_minor)>0||String(x.severity||'').toLowerCase()==='critical').slice(0,20)){attention.push({id:`gap:${g.id}`,type:'real_world_gap',title:g.title||g.category||'Real-world gap',summary:g.summary||g.actual_flow||'',related_entity_type:g.related_entity_type,related_entity_id:g.related_entity_id,financial_impact:safeNumber(g.financial_impact_minor)/100||null,risk:g.severity||'high',deadline:null,ai_recommendation:g.recommended_action||null,confidence:g.confidence??null,financial_impact_score:g.financial_impact_minor?70:35,risk_score:riskRank(g.severity),urgency_score:65,strategic_score:70})}
 for(const d of decisions.slice(0,30)){attention.push({id:`decision:${d.id}`,type:'founder_decision',title:d.title||d.decision_type,summary:d.summary||'Evidence-backed decision proposal',related_entity_type:d.related_entity_type,related_entity_id:d.related_entity_id,financial_impact:d.financial_impact_json?.expected_eur??null,risk:d.risk_json?.level||'notice',deadline:d.expires_at||null,ai_recommendation:d.recommended_option||null,confidence:d.confidence??null,financial_impact_score:d.financial_impact_json?.expected_eur?60:20,risk_score:riskRank(d.risk_json?.level),urgency_score:45,strategic_score:80})}
 for(const d of legalDecisions.slice(0,20)){attention.push({id:`legal:${d.id}`,type:'legal_execution_blocker',title:`${d.requested_action} · ${d.jurisdiction}`,summary:(d.reason_codes||[]).join(', ')||d.decision,related_entity_type:'LegalExecutionDecision',related_entity_id:d.id,financial_impact:null,risk:d.decision==='BLOCK'?'high':'notice',deadline:null,ai_recommendation:'Review P10/P11 evidence, contract, mandate and exact authority; never override through AI.',confidence:null,financial_impact_score:20,risk_score:d.decision==='BLOCK'?90:70,urgency_score:60,strategic_score:85})}
 for(const x of attention)x.priority=attentionPriority(x);attention.sort((a,b)=>b.priority-a.priority);
 const recentLeads=leads.filter((x:any)=>String(x.created_date||'')>=since24),newBrands=productionBrands.filter((x:any)=>String(x.created_date||'')>=since24),recentPaid=invoices.filter((x:any)=>String(x.updated_date||x.issued_at||'')>=since24&&safeNumber(x.amount_paid)>0),recentVerified=verified.filter((x:any)=>String(x.updated_date||x.created_date||x.month||'')>=since24);
 const conversions={lead_to_engaged:{numerator:leads.filter((x:any)=>['engaged','discovery','analysis_pending','analyzed','proposal','recover','won','meeting'].includes(String(x.revenue_stage||x.stage))).length,denominator:leads.length},lead_to_won:{numerator:leads.filter((x:any)=>String(x.revenue_stage||x.stage)==='won').length,denominator:leads.length}};
 const blockedMigrations=migrations.filter((m:any)=>['blocked','failed'].includes(String(m.status))||['blocked','failed'].includes(String(m.step_status))),delayedMigrations=migrations.filter((m:any)=>{const t=Date.parse(m.next_action_at||m.updated_at||'');return ['pending','in_progress','waiting_external','waiting_merchant'].includes(String(m.status))&&Number.isFinite(t)&&t<Date.now()-5*86400000});
 const providerOutstanding=providerLedger.filter((x:any)=>['accrued','validation_pending','invoiced','payment_pending','partially_paid','disputed'].includes(String(x.state))).reduce((a:number,x:any)=>a+Math.max(0,safeNumber(x.accrued_amount_minor)-safeNumber(x.paid_amount_minor)),0)/100;
 const hasObserved=(value:any)=>value!==null&&value!==undefined&&value!=='';const hasForecastInputs=(lead:any)=>{const value=Number(lead.expected_revenue_value),probability=Number(lead.close_probability);return hasObserved(lead.expected_revenue_value)&&hasObserved(lead.close_probability)&&Number.isFinite(value)&&value>=0&&Number.isFinite(probability)&&probability>=0&&probability<=1};const weightedPipeline=leads.reduce((total:number,lead:any)=>total+(hasForecastInputs(lead)?Number(lead.expected_revenue_value)*Number(lead.close_probability):0),0),weightedPipelineKnown=leads.filter(hasForecastInputs).length;
 // COMMAND-C3 (2026-08-17) — a metric may only carry a confidence label if the
 // canonical sources it was computed from actually loaded. If any did not, the
 // value is null (NOT zero) and the confidence is 'unknown', with the failed
 // sources named. Callers and the UI must treat null as "not proven", never 0.
 //
 // `extra` is spread FIRST on purpose: the authoritative fields below must win.
 // Spreading it last would let a caller's key silently overwrite the verdict.
 const metric=(value:any,unit:string,sources:string[],confidence:string,extra:any={})=>{
  const missing=sources.filter((source)=>failures.has(source));
  if(missing.length)return{...extra,value:null,unit,as_of:now.toISOString(),confidence:'unknown',unavailable_sources:missing};
  return{...extra,value,unit,as_of:now.toISOString(),confidence};
 };
 const metrics:any={
  collected_revenue:metric(totalCollected,'EUR',['Invoice','ProviderRevenueLedger'],'verified',{merchant:merchantCollected,provider:providerPaid}),
  provider_accrued:metric(providerAccrued,'EUR',['ProviderRevenueLedger'],'contractual'),verified_savings:metric(sum(verified,'savings'),'EUR',['MonthlySavingsReport'],'verified'),
  merchants:metric(productionBrands.length,'count',['Brand'],'observed'),active_merchants:metric(activeBrandIds.size,'count',['Brand','RevenueLifecycle','Integration'],'observed'),new_merchants_24h:metric(newBrands.length,'count',['Brand'],'observed'),
  leads_24h:metric(recentLeads.length,'count',['OutboundLead'],'observed'),weighted_pipeline:metric(weightedPipeline,'EUR',['OutboundLead'],weightedPipelineKnown?'estimated':'unknown',{known_value_count:weightedPipelineKnown,unknown_value_count:leads.length-weightedPipelineKnown}),aggregate_addressable:metric(addressable,'EUR_annual_volume',['AggregatePool'],'estimated'),aggregate_committed:metric(committed,'EUR_annual_volume',['AggregatePool'],'contractual'),
  company_health:{...metric(health[0]?.score??null,'score_0_100',['OperatingHealthAssessment'],'observed'),as_of:health[0]?.calculated_at||null},founder_attention:metric(attention.length,'count',['Approval','AutonomyIncident','CommunicationThread'],'observed'),provider_outstanding:metric(providerOutstanding,'EUR',['ProviderRevenueLedger'],'contractual')
 };
 const opportunities:any[]=[];
 for(const p of pools.filter((x:any)=>safeNumber(x.aggregation_power_score)>=65).slice(0,20))opportunities.push({type:'aggregate',title:`${p.pool_key} is negotiation-ready`,expected_value:null,probability:null,time_to_value:'near_term',effort:'low',risk:'low',evidence:[{entity:'AggregatePool',id:p.id}],recommended_action:'Review/open competitive procurement if not already active'});
 for(const x of cs.filter((x:any)=>x.type==='expansion_opportunity').slice(0,20))opportunities.push({type:'expansion',title:x.summary||`Expansion opportunity · ${x.brand_id}`,expected_value:x.expected_value||null,probability:safeNumber(x.score)/100||null,time_to_value:'unknown',effort:'unknown',risk:'low',evidence:[{entity:'CustomerSuccessSignal',id:x.id}],recommended_action:x.recommended_action||'Review expansion path'});
 const risks:any[]=[];
 if(blockedMigrations.length)risks.push({type:'operational',title:`${blockedMigrations.length} migration(s) blocked/failed`,probability:1,impact:'merchant/revenue delay',velocity:'current',mitigation:'Open Migration/Operations and resolve highest-value blockers',evidence:blockedMigrations.slice(0,10).map((x:any)=>({entity:'MigrationTask',id:x.id}))});
 if(delayedMigrations.length)risks.push({type:'operational',title:`${delayedMigrations.length} migration(s) delayed >5d`,probability:1,impact:'time-to-revenue',velocity:'current',mitigation:'Escalate provider/merchant waits where policy allows',evidence:delayedMigrations.slice(0,10).map((x:any)=>({entity:'MigrationTask',id:x.id}))});
 if(providerOutstanding>0)risks.push({type:'financial',title:`Provider revenue outstanding`,amount:providerOutstanding,probability:1,impact:'cash timing',velocity:'current',mitigation:'Run provider revenue reconciliation/recovery',evidence:providerLedger.filter((x:any)=>!['paid','expected','eligible'].includes(String(x.state))).slice(0,10).map((x:any)=>({entity:'ProviderRevenueLedger',id:x.id}))});
 if(failed7.length)risks.push({type:'technical',title:`${failed7.length} agent/task failure(s) in 7d`,probability:1,impact:'automation reliability',velocity:'current',mitigation:'Review Developer/System Health',evidence:failed7.slice(0,10).map((x:any)=>({entity:'AgentTask',id:x.id}))});
 // COMMAND-C3: coverage travels with the snapshot. Every consumer — the home
 // page, the Chief of Staff brief, founderOSQuery and founderOSSimulation —
 // can now tell a real zero from a read that never happened.
 const degradedSources=[...failures].sort();
 return {ok:true,version:FOUNDER_OS_VERSION,generated_at:now.toISOString(),data_complete:degradedSources.length===0,degraded_sources:degradedSources,last_digest:digest[0]||null,commercial_intelligence:commercial[0]||null,open_founder_decisions:decisions.slice(0,100),legal_execution:{recent_blockers:legalDecisions.slice(0,100),active_policy_count:legalPolicies.length,review_required_policy_count:legalPolicies.filter((x:any)=>!['ALLOW','ALLOW_WITH_CONDITIONS'].includes(String(x.status))).length,active_kill_switches:legalSwitches},metrics,conversions,attention:attention.slice(0,100),opportunities:opportunities.slice(0,50),risks:risks.slice(0,50),operations:{blocked_migrations:blockedMigrations.length,delayed_migrations_gt_5d:delayedMigrations.length,running_tasks:running.length,failed_tasks_7d:failed7.length,open_incidents:incidents.length,active_negotiations:cases.filter((x:any)=>!['approved','rejected','closed','expired'].includes(String(x.status))).length,legal_execution_blockers:legalDecisions.length},ai_workforce:{latest_metrics:agentPerf.slice(0,100),task_count_7d:tasks.filter((x:any)=>String(x.created_date||x.started_at||'')>=since7).length,failed_7d:failed7.length},freshness:{health_age_minutes:ageMinutes(health[0]?.calculated_at),digest_age_minutes:ageMinutes(digest[0]?.generated_at),commercial_intelligence_age_minutes:ageMinutes(commercial[0]?.generated_at)},counts:{brands:productionBrands.length,leads:leads.length,pools:pools.length,provider_attributions:attrs.length}};
}
export async function merchant360(s:any,brandId:string){
 // COMMAND-C3: a merchant 360 built on unread sources is a partial picture,
 // and it must say which parts are missing rather than look complete.
 const failures:SourceFailures=new Set<string>();
 const safe=<T>(source:string,fn:()=>Promise<T>,fallback:any=[])=>safeTracked(failures,source,fn,fallback);
 const [brand,integrations,analyzer,life,recover,mandates,poolMembers,cases,migrations,reports,invoices,providerAttrs,incidents,threads,events,unit,cs]=await Promise.all([safe('Brand',()=>s.entities.Brand.get(brandId),null),safe('Integration',()=>s.entities.Integration.filter({brand_id:brandId},'-last_sync_at',100)),safe('AnalyzerResult',()=>s.entities.AnalyzerResult.filter({brand_id:brandId},'-created_date',50)),safe('RevenueLifecycle',()=>s.entities.RevenueLifecycle.filter({brand_id:brandId},'-updated_at',100)),safe('DealActivation',()=>s.entities.DealActivation.filter({brand_id:brandId},'-last_updated',100)),safe('Mandate',()=>s.entities.Mandate.filter({brand_id:brandId},'-signed_at',50)),safe('AggregatePoolMember',()=>s.entities.AggregatePoolMember.filter({brand_id:brandId},'-updated_at',100)),safe('NegotiationCase',()=>s.entities.NegotiationCase.filter({brand_id:brandId},'-started_at',100)),safe('MigrationTask',()=>s.entities.MigrationTask.filter({brand_id:brandId},'-updated_at',100)),safe('MonthlySavingsReport',()=>s.entities.MonthlySavingsReport.filter({brand_id:brandId},'-month',100)),safe('Invoice',()=>s.entities.Invoice.filter({brand_id:brandId},'-issued_at',100)),safe('ProviderRevenueAttribution',()=>s.entities.ProviderRevenueAttribution.filter({brand_id:brandId},'-updated_at',100)),safe('AutonomyIncident',()=>s.entities.AutonomyIncident.filter({subject_id:brandId},'-last_seen_at',100)),safe('CommunicationThread',()=>s.entities.CommunicationThread.filter({brand_id:brandId},'-last_message_at',100)),safe('Event',()=>s.entities.Event.filter({brand_id:brandId},'-created_date',200)),safe('MerchantUnitEconomics',()=>s.entities.MerchantUnitEconomics.filter({brand_id:brandId},'-calculated_at',5)),safe('CustomerSuccessSignal',()=>s.entities.CustomerSuccessSignal.filter({brand_id:brandId,status:'open'},'-updated_at',100))]);return{ok:!!brand,brand,health:{retention_risk:Math.max(0,...cs.filter((x:any)=>x.type==='retention_risk').map((x:any)=>safeNumber(x.score))),open_incidents:incidents.length,integration_disconnects:integrations.filter((x:any)=>x.status!=='connected').length},integrations,analyzer:analyzer.slice(0,10),revenue_lifecycle:life[0]||null,recover:recover.slice(0,20),mandates:mandates.slice(0,10),aggregate_membership:poolMembers,cases,migrations,reports:reports.slice(0,24),invoices:invoices.slice(0,50),provider_revenue_attribution:providerAttrs,unit_economics:unit[0]||null,customer_success:cs,timeline:[...events.map((e:any)=>({at:e.created_date||e.processed_at,type:e.event_type,source:e.source,entity_type:e.entity_type,entity_id:e.entity_id})),...threads.map((t:any)=>({at:t.last_message_at||t.created_date,type:'communication',source:t.engine,entity_type:'CommunicationThread',entity_id:t.id}))].filter(x=>x.at).sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)).slice(0,200),data_complete:failures.size===0,degraded_sources:[...failures].sort()};}
export async function provider360(s:any,providerId:string){
 // COMMAND-C3: same rule as merchant360 — a partial provider picture must
 // declare which canonical sources it could not read.
 const failures:SourceFailures=new Set<string>();
 const safe=<T>(source:string,fn:()=>Promise<T>,fallback:any=[])=>safeTracked(failures,source,fn,fallback);
 const [provider,agreements,ledger,cases,pricing,rates,statements,incidents,contacts,assessments,tiers]=await Promise.all([safe('Provider',()=>s.entities.Provider.get(providerId),null),safe('DynamicAgreement',()=>s.entities.DynamicAgreement.filter({provider_id:providerId},'-created_at',100)),safe('ProviderRevenueLedger',()=>s.entities.ProviderRevenueLedger.filter({provider_id:providerId},'-updated_at',500)),safe('NegotiationCase',()=>s.entities.NegotiationCase.filter({provider_id:providerId},'-started_at',200)),safe('ProviderPricingVersion',()=>s.entities.ProviderPricingVersion.filter({provider_id:providerId},'-effective_at',200)),safe('PrivateRateCard',()=>s.entities.PrivateRateCard.filter({provider_id:providerId},'-effective_at',200)),safe('ProviderRevenueStatement',()=>s.entities.ProviderRevenueStatement.filter({provider_id:providerId},'-received_at',100)),safe('AutonomyIncident',()=>s.entities.AutonomyIncident.filter({subject_id:providerId},'-last_seen_at',100)),safe('ProviderContact',()=>s.entities.ProviderContact.filter({provider_id:providerId,active:true},'-last_verified_at',50)),safe('ProviderEconomicAssessment',()=>s.entities.ProviderEconomicAssessment.filter({provider_id:providerId},'-calculated_at',200)),safe('ProviderCompensationTier',()=>s.entities.ProviderCompensationTier.list('-updated_at',500))]);const merchantIds=new Set(ledger.map((x:any)=>x.brand_id).filter(Boolean));return{ok:!!provider,provider,relationship:{merchant_count:merchantIds.size,active_agreements:agreements.filter((x:any)=>x.status==='active').length,open_negotiations:cases.filter((x:any)=>!['approved','closed','expired','rejected'].includes(String(x.status))).length,provider_revenue_paid_minor:sum(ledger.filter((x:any)=>x.state==='paid'),'paid_amount_minor'),provider_revenue_outstanding_minor:ledger.reduce((a:number,x:any)=>a+Math.max(0,safeNumber(x.accrued_amount_minor)-safeNumber(x.paid_amount_minor)),0)},agreements,provider_revenue:ledger,negotiations:cases,public_observed_pricing:pricing,private_rates:rates,statements,incidents,contacts:contacts.map((x:any)=>({id:x.id,name:x.name,title:x.title,department:x.department,source:x.source,confidence:x.confidence,last_verified_at:x.last_verified_at})),assessments,compensation_tiers:tiers.filter((t:any)=>agreements.some((a:any)=>a.id===t.agreement_id)),data_complete:failures.size===0,degraded_sources:[...failures].sort()};}
export async function searchCompany(s:any,qRaw:string){const q=String(qRaw||'').trim().toLowerCase();if(!q)return{ok:false,error:'query_required'};
 // COMMAND-C3: a search that cannot read an entity must say so. "No results"
 // and "could not look" are different answers to the founder.
 const failures:SourceFailures=new Set<string>();
 const safe=<T>(source:string,fn:()=>Promise<T>,fallback:any=[])=>safeTracked(failures,source,fn,fallback);
 const out:any[]=[];const configs:any[]=[['Brand',['name'],'merchant',1000],['Provider',['name'],'provider',1000],['OutboundLead',['company_name'],'lead',2000],['DynamicAgreement',['provider_name','program_name','agreement_key'],'contract',1000],['Invoice',['invoice_number'],'invoice',1000],['NegotiationCase',['provider_name'],'negotiation',1500],['AggregatePool',['pool_key'],'aggregate_pool',500]];for(const[c,fields,type,limit]of configs){const rows=await safe(String(c),()=>s.entities[c].list('-created_date',Number(limit)));for(const r of rows){const hay=(fields as string[]).map((f:string)=>String(r?.[f]||'').toLowerCase()).join(' · ');if(hay.includes(q)&&!out.some(x=>x.entity===c&&x.id===r.id))out.push({type,entity:c,id:r.id,label:r.name||r.company_name||r.provider_name||r.program_name||r.agreement_key||r.invoice_number||r.pool_key||r.id,secondary:r.country||r.status||r.vertical||''});if(out.length>=50)break}if(out.length>=50)break}return{ok:true,query:q,results:out.slice(0,50),search_mode:'bounded_exact_substring',semantic_search:false,searched_complete:failures.size===0,unavailable_sources:[...failures].sort()};}
