import{safeNumber,ageMinutes,riskRank,attentionPriority,FOUNDER_OS_VERSION}from'./founderOSCore.ts';
const safe=async<T>(fn:()=>Promise<T>,fallback:any=[]):Promise<any>=>{try{return await fn()}catch{return fallback}};
const sum=(a:any[],f:string)=>a.reduce((x:number,y:any)=>x+safeNumber(y?.[f]),0);
const unique=(a:any[])=>new Set(a.filter(Boolean)).size;
export async function buildFounderSnapshot(s:any){
 const now=new Date(),since24=new Date(now.getTime()-86400000).toISOString(),since7=new Date(now.getTime()-7*86400000).toISOString();
 const [brands,leads,life,reports,invoices,providerLedger,pools,approvals,incidents,meetings,tasks,agentPerf,health,gaps,cases,migrations,integrations,cs,attrs,digest]=await Promise.all([
  safe(()=>s.entities.Brand.list('-created_date',2000)),safe(()=>s.entities.OutboundLead.list('-created_date',5000)),safe(()=>s.entities.RevenueLifecycle.list('-updated_at',5000)),safe(()=>s.entities.MonthlySavingsReport.list('-month',5000)),safe(()=>s.entities.Invoice.list('-issued_at',5000)),safe(()=>s.entities.ProviderRevenueLedger.list('-updated_at',5000)),safe(()=>s.entities.AggregatePool.list('-updated_at',2000)),safe(()=>s.entities.Approval.filter({status:'pending'},'-created_date',1000)),safe(()=>s.entities.AutonomyIncident.filter({status:'open'},'-last_seen_at',1000)),safe(()=>s.entities.CommunicationThread.filter({meeting_start_at:{$ne:null}},'meeting_start_at',500)),safe(()=>s.entities.AgentTask.list('-created_date',5000)),safe(()=>s.entities.AgentPerformanceMetric.list('-calculated_at',1000)),safe(()=>s.entities.OperatingHealthAssessment.list('-calculated_at',5)),safe(()=>s.entities.RealWorldGapReport.filter({status:{$in:['open','investigating']}},'-created_at',500)),safe(()=>s.entities.NegotiationCase.list('-started_at',2000)),safe(()=>s.entities.MigrationTask.list('-updated_at',3000)),safe(()=>s.entities.Integration.list('-last_sync_at',4000)),safe(()=>s.entities.CustomerSuccessSignal.filter({status:'open'},'-updated_at',1000)),safe(()=>s.entities.ProviderRevenueAttribution.filter({status:'active'},'-updated_at',5000)),safe(()=>s.entities.ExecutiveDigest.list('-generated_at',1))
 ]);
 const productionBrands=brands.filter((b:any)=>!b.is_demo),activeBrandIds=new Set<string>();
 for(const x of life)if(['savings_accepted','implementation_pending','implemented','verification_pending','savings_verified','billable','invoiced','payment_pending','paid','partially_paid'].includes(String(x.state)))activeBrandIds.add(String(x.brand_id));
 for(const i of integrations)if(i.status==='connected'&&i.brand_id)activeBrandIds.add(String(i.brand_id));
 const verified=reports.filter((r:any)=>r.measurement_mode==='fully_verified'&&r.verification_status==='realized');
 const merchantCollected=sum(invoices,'amount_paid'),providerPaid=sum(providerLedger.filter((x:any)=>x.state==='paid'),'paid_amount_minor')/100,providerAccrued=sum(providerLedger,'accrued_amount_minor')/100;
 const totalCollected=merchantCollected+providerPaid;
 const addressable=sum(pools.filter((p:any)=>!['archived','terminated'].includes(String(p.status))),'addressable_annual_volume_minor')/100;
 const committed=sum(pools.filter((p:any)=>!['archived','terminated'].includes(String(p.status))),'committed_annual_volume_minor')/100;
 const pendingL4=approvals.filter((a:any)=>safeNumber(a.risk_level)>=4),criticalInc=incidents.filter((i:any)=>String(i.severity).toLowerCase()==='critical');
 const futureMeetings=meetings.filter((m:any)=>Date.parse(m.meeting_start_at||'')>=Date.now()-3600000&&m.founder_required===true);
 const failed7=tasks.filter((t:any)=>String(t.status)==='failed'&&String(t.created_date||t.started_at||'')>=since7),running=tasks.filter((t:any)=>String(t.status)==='running');
 const attention:any[]=[];
 for(const a of pendingL4){const fin=safeNumber(a.draft_payload_json?.estimated_financial_impact||a.draft_payload_json?.expected_provider_revenue_12m_minor)/100;attention.push({id:`approval:${a.id}`,type:'approval_required',title:a.action_type,summary:String(a.draft_content||'Material approval required').slice(0,320),related_entity_type:a.related_entity_type,related_entity_id:a.related_entity_id,approval_id:a.id,financial_impact:fin||null,risk:'high',deadline:a.expires_at||null,ai_recommendation:a.draft_payload_json?.ai_recommendation||null,confidence:a.draft_payload_json?.confidence??null,financial_impact_score:fin?Math.min(100,20+Math.log10(Math.max(1,fin))*18):30,risk_score:85,urgency_score:a.expires_at?Math.max(20,100-Math.max(0,Date.parse(a.expires_at)-Date.now())/86400000*10):55,strategic_score:60})}
 for(const i of criticalInc){attention.push({id:`incident:${i.id}`,type:'critical_exception',title:i.summary||i.incident_type,summary:i.details_json?.message||i.summary||'Critical incident',related_entity_type:i.subject_type,related_entity_id:i.subject_id,financial_impact:safeNumber(i.financial_impact_minor)/100||null,risk:'critical',deadline:null,ai_recommendation:i.recovery_json?.recommended_action||null,confidence:null,financial_impact_score:i.financial_impact_minor?75:40,risk_score:100,urgency_score:95,strategic_score:60})}
 for(const m of futureMeetings.slice(0,20)){attention.push({id:`meeting:${m.id}`,type:'meeting',title:m.counterparty_name||m.summary||'Founder meeting',summary:m.summary||m.meeting_classification||'',related_entity_type:m.related_entity_type,related_entity_id:m.related_entity_id,financial_impact:null,risk:'notice',deadline:m.meeting_start_at,ai_recommendation:'Review meeting brief and desired outcome',confidence:null,financial_impact_score:20,risk_score:30,urgency_score:Date.parse(m.meeting_start_at||'')-Date.now()<86400000?90:50,strategic_score:m.meeting_classification==='strategic'||m.meeting_classification==='executive'?90:55})}
 for(const g of gaps.filter((x:any)=>safeNumber(x.financial_impact_minor)>0||String(x.severity||'').toLowerCase()==='critical').slice(0,20)){attention.push({id:`gap:${g.id}`,type:'real_world_gap',title:g.title||g.category||'Real-world gap',summary:g.summary||g.actual_flow||'',related_entity_type:g.related_entity_type,related_entity_id:g.related_entity_id,financial_impact:safeNumber(g.financial_impact_minor)/100||null,risk:g.severity||'high',deadline:null,ai_recommendation:g.recommended_action||null,confidence:g.confidence??null,financial_impact_score:g.financial_impact_minor?70:35,risk_score:riskRank(g.severity),urgency_score:65,strategic_score:70})}
 for(const x of attention)x.priority=attentionPriority(x);attention.sort((a,b)=>b.priority-a.priority);
 const recentLeads=leads.filter((x:any)=>String(x.created_date||'')>=since24),newBrands=productionBrands.filter((x:any)=>String(x.created_date||'')>=since24),recentPaid=invoices.filter((x:any)=>String(x.updated_date||x.issued_at||'')>=since24&&safeNumber(x.amount_paid)>0),recentVerified=verified.filter((x:any)=>String(x.updated_date||x.created_date||x.month||'')>=since24);
 const conversions={lead_to_engaged:{numerator:leads.filter((x:any)=>['engaged','discovery','analysis_pending','analyzed','proposal','recover','won'].includes(String(x.status))).length,denominator:leads.length},lead_to_won:{numerator:leads.filter((x:any)=>String(x.status)==='won').length,denominator:leads.length}};
 const blockedMigrations=migrations.filter((m:any)=>['blocked','failed'].includes(String(m.status))||['blocked','failed'].includes(String(m.step_status))),delayedMigrations=migrations.filter((m:any)=>{const t=Date.parse(m.next_action_at||m.updated_at||'');return ['pending','in_progress','waiting_external','waiting_merchant'].includes(String(m.status))&&Number.isFinite(t)&&t<Date.now()-5*86400000});
 const providerOutstanding=providerLedger.filter((x:any)=>['accrued','validation_pending','invoiced','payment_pending','partially_paid','disputed'].includes(String(x.state))).reduce((a:number,x:any)=>a+Math.max(0,safeNumber(x.accrued_amount_minor)-safeNumber(x.paid_amount_minor)),0)/100;
 const metrics:any={
  collected_revenue:{value:totalCollected,merchant:merchantCollected,provider:providerPaid,unit:'EUR',as_of:now.toISOString(),confidence:'verified'},
  provider_accrued:{value:providerAccrued,unit:'EUR',as_of:now.toISOString(),confidence:'contractual'},verified_savings:{value:sum(verified,'savings'),unit:'EUR',as_of:now.toISOString(),confidence:'verified'},
  merchants:{value:productionBrands.length,unit:'count',as_of:now.toISOString(),confidence:'observed'},active_merchants:{value:activeBrandIds.size,unit:'count',as_of:now.toISOString(),confidence:'observed'},new_merchants_24h:{value:newBrands.length,unit:'count',as_of:now.toISOString(),confidence:'observed'},
  leads_24h:{value:recentLeads.length,unit:'count',as_of:now.toISOString(),confidence:'observed'},aggregate_addressable:{value:addressable,unit:'EUR_annual_volume',as_of:now.toISOString(),confidence:'estimated'},aggregate_committed:{value:committed,unit:'EUR_annual_volume',as_of:now.toISOString(),confidence:'contractual'},
  company_health:{value:health[0]?.score??null,unit:'score_0_100',as_of:health[0]?.calculated_at||null,confidence:'observed'},founder_attention:{value:attention.length,unit:'count',as_of:now.toISOString(),confidence:'observed'},provider_outstanding:{value:providerOutstanding,unit:'EUR',as_of:now.toISOString(),confidence:'contractual'}
 };
 const opportunities:any[]=[];
 for(const p of pools.filter((x:any)=>safeNumber(x.aggregation_power_score)>=65).slice(0,20))opportunities.push({type:'aggregate',title:`${p.pool_key} is negotiation-ready`,expected_value:null,probability:null,time_to_value:'near_term',effort:'low',risk:'low',evidence:[{entity:'AggregatePool',id:p.id}],recommended_action:'Review/open competitive procurement if not already active'});
 for(const x of cs.filter((x:any)=>x.type==='expansion_opportunity').slice(0,20))opportunities.push({type:'expansion',title:x.summary||`Expansion opportunity · ${x.brand_id}`,expected_value:x.expected_value||null,probability:safeNumber(x.score)/100||null,time_to_value:'unknown',effort:'unknown',risk:'low',evidence:[{entity:'CustomerSuccessSignal',id:x.id}],recommended_action:x.recommended_action||'Review expansion path'});
 const risks:any[]=[];
 if(blockedMigrations.length)risks.push({type:'operational',title:`${blockedMigrations.length} migration(s) blocked/failed`,probability:1,impact:'merchant/revenue delay',velocity:'current',mitigation:'Open Migration/Operations and resolve highest-value blockers',evidence:blockedMigrations.slice(0,10).map((x:any)=>({entity:'MigrationTask',id:x.id}))});
 if(delayedMigrations.length)risks.push({type:'operational',title:`${delayedMigrations.length} migration(s) delayed >5d`,probability:1,impact:'time-to-revenue',velocity:'current',mitigation:'Escalate provider/merchant waits where policy allows',evidence:delayedMigrations.slice(0,10).map((x:any)=>({entity:'MigrationTask',id:x.id}))});
 if(providerOutstanding>0)risks.push({type:'financial',title:`Provider revenue outstanding`,amount:providerOutstanding,probability:1,impact:'cash timing',velocity:'current',mitigation:'Run provider revenue reconciliation/recovery',evidence:providerLedger.filter((x:any)=>!['paid','expected','eligible'].includes(String(x.state))).slice(0,10).map((x:any)=>({entity:'ProviderRevenueLedger',id:x.id}))});
 if(failed7.length)risks.push({type:'technical',title:`${failed7.length} agent/task failure(s) in 7d`,probability:1,impact:'automation reliability',velocity:'current',mitigation:'Review Developer/System Health',evidence:failed7.slice(0,10).map((x:any)=>({entity:'AgentTask',id:x.id}))});
 return {ok:true,version:FOUNDER_OS_VERSION,generated_at:now.toISOString(),last_digest:digest[0]||null,metrics,conversions,attention:attention.slice(0,100),opportunities:opportunities.slice(0,50),risks:risks.slice(0,50),operations:{blocked_migrations:blockedMigrations.length,delayed_migrations_gt_5d:delayedMigrations.length,running_tasks:running.length,failed_tasks_7d:failed7.length,open_incidents:incidents.length,active_negotiations:cases.filter((x:any)=>!['approved','rejected','closed','expired'].includes(String(x.status))).length},ai_workforce:{latest_metrics:agentPerf.slice(0,100),task_count_7d:tasks.filter((x:any)=>String(x.created_date||x.started_at||'')>=since7).length,failed_7d:failed7.length},freshness:{health_age_minutes:ageMinutes(health[0]?.calculated_at),digest_age_minutes:ageMinutes(digest[0]?.generated_at)},counts:{brands:productionBrands.length,leads:leads.length,pools:pools.length,provider_attributions:attrs.length}};
}
export async function merchant360(s:any,brandId:string){const [brand,integrations,analyzer,life,recover,mandates,poolMembers,cases,migrations,reports,invoices,providerAttrs,incidents,threads,events,unit,cs]=await Promise.all([safe(()=>s.entities.Brand.get(brandId),null),safe(()=>s.entities.Integration.filter({brand_id:brandId},'-last_sync_at',100)),safe(()=>s.entities.AnalyzerResult.filter({brand_id:brandId},'-created_date',50)),safe(()=>s.entities.RevenueLifecycle.filter({brand_id:brandId},'-updated_at',100)),safe(()=>s.entities.DealActivation.filter({brand_id:brandId},'-last_updated',100)),safe(()=>s.entities.Mandate.filter({brand_id:brandId},'-signed_at',50)),safe(()=>s.entities.AggregatePoolMember.filter({brand_id:brandId},'-updated_at',100)),safe(()=>s.entities.NegotiationCase.filter({brand_id:brandId},'-started_at',100)),safe(()=>s.entities.MigrationTask.filter({brand_id:brandId},'-updated_at',100)),safe(()=>s.entities.MonthlySavingsReport.filter({brand_id:brandId},'-month',100)),safe(()=>s.entities.Invoice.filter({brand_id:brandId},'-issued_at',100)),safe(()=>s.entities.ProviderRevenueAttribution.filter({brand_id:brandId},'-updated_at',100)),safe(()=>s.entities.AutonomyIncident.filter({subject_id:brandId},'-last_seen_at',100)),safe(()=>s.entities.CommunicationThread.filter({brand_id:brandId},'-last_message_at',100)),safe(()=>s.entities.Event.filter({brand_id:brandId},'-created_date',200)),safe(()=>s.entities.MerchantUnitEconomics.filter({brand_id:brandId},'-calculated_at',5)),safe(()=>s.entities.CustomerSuccessSignal.filter({brand_id:brandId,status:'open'},'-updated_at',100))]);return{ok:!!brand,brand,health:{retention_risk:Math.max(0,...cs.filter((x:any)=>x.type==='retention_risk').map((x:any)=>safeNumber(x.score))),open_incidents:incidents.length,integration_disconnects:integrations.filter((x:any)=>x.status!=='connected').length},integrations,analyzer:analyzer.slice(0,10),revenue_lifecycle:life[0]||null,recover:recover.slice(0,20),mandates:mandates.slice(0,10),aggregate_membership:poolMembers,cases,migrations,reports:reports.slice(0,24),invoices:invoices.slice(0,50),provider_revenue_attribution:providerAttrs,unit_economics:unit[0]||null,customer_success:cs,timeline:[...events.map((e:any)=>({at:e.created_date||e.processed_at,type:e.event_type,source:e.source,entity_type:e.entity_type,entity_id:e.entity_id})),...threads.map((t:any)=>({at:t.last_message_at||t.created_date,type:'communication',source:t.engine,entity_type:'CommunicationThread',entity_id:t.id}))].filter(x=>x.at).sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)).slice(0,200)};}
export async function provider360(s:any,providerId:string){const [provider,agreements,ledger,cases,pricing,rates,statements,incidents,contacts,assessments,tiers]=await Promise.all([safe(()=>s.entities.Provider.get(providerId),null),safe(()=>s.entities.DynamicAgreement.filter({provider_id:providerId},'-created_at',100)),safe(()=>s.entities.ProviderRevenueLedger.filter({provider_id:providerId},'-updated_at',500)),safe(()=>s.entities.NegotiationCase.filter({provider_id:providerId},'-started_at',200)),safe(()=>s.entities.ProviderPricingVersion.filter({provider_id:providerId},'-effective_at',200)),safe(()=>s.entities.PrivateRateCard.filter({provider_id:providerId},'-effective_at',200)),safe(()=>s.entities.ProviderRevenueStatement.filter({provider_id:providerId},'-received_at',100)),safe(()=>s.entities.AutonomyIncident.filter({subject_id:providerId},'-last_seen_at',100)),safe(()=>s.entities.ProviderContact.filter({provider_id:providerId,active:true},'-last_verified_at',50)),safe(()=>s.entities.ProviderEconomicAssessment.filter({provider_id:providerId},'-calculated_at',200)),safe(()=>s.entities.ProviderCompensationTier.list('-updated_at',500))]);const merchantIds=new Set(ledger.map((x:any)=>x.brand_id).filter(Boolean));return{ok:!!provider,provider,relationship:{merchant_count:merchantIds.size,active_agreements:agreements.filter((x:any)=>x.status==='active').length,open_negotiations:cases.filter((x:any)=>!['approved','closed','expired','rejected'].includes(String(x.status))).length,provider_revenue_paid_minor:sum(ledger.filter((x:any)=>x.state==='paid'),'paid_amount_minor'),provider_revenue_outstanding_minor:ledger.reduce((a:number,x:any)=>a+Math.max(0,safeNumber(x.accrued_amount_minor)-safeNumber(x.paid_amount_minor)),0)},agreements,provider_revenue:ledger,negotiations:cases,public_observed_pricing:pricing,private_rates:rates,statements,incidents,contacts:contacts.map((x:any)=>({id:x.id,name:x.name,title:x.title,department:x.department,source:x.source,confidence:x.confidence,last_verified_at:x.last_verified_at})),assessments,compensation_tiers:tiers.filter((t:any)=>agreements.some((a:any)=>a.id===t.agreement_id))};}
export async function searchCompany(s:any,qRaw:string){const q=String(qRaw||'').trim();if(!q)return{ok:false,error:'query_required'};const rx={$regex:q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),$options:'i'};const out:any[]=[];const configs=[['Brand',['name'],'merchant'],['Provider',['name'],'provider'],['OutboundLead',['company_name'],'lead'],['DynamicAgreement',['provider_name','program_name','agreement_key'],'contract'],['Invoice',['invoice_number'],'invoice'],['NegotiationCase',['provider_name'],'negotiation'],['AggregatePool',['pool_key'],'aggregate_pool']];for(const[c,fields,type]of configs){for(const f of fields){const rows=await safe(()=>s.entities[c].filter({[f]:rx},'-created_date',10));for(const r of rows)if(!out.some(x=>x.entity===c&&x.id===r.id))out.push({type,entity:c,id:r.id,label:r.name||r.company_name||r.provider_name||r.program_name||r.agreement_key||r.invoice_number||r.pool_key||r.id,secondary:r.country||r.status||r.vertical||''})}}return{ok:true,query:q,results:out.slice(0,50)};}
