// P3 European Rate Intelligence — backend-safe canonical helpers.
// P3 stores observed truth only. Statistical benchmarks/predictions belong to P4/P5.
export const P3_SCHEMA_VERSION='p3-rate-truth-1.0.0';
export const P3_RESOLVER_POLICY_VERSION='p3-resolver-1.0.0';
export const P3_PROMOTION_POLICY_VERSION='p3-promotion-1.0.0';
export const P3_MARKETS=['AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE','NO','IS','LI','CH','GB','AD'] as const;
export const VERIFIED_STATUSES=['VERIFIED_PRIMARY','VERIFIED_SECONDARY','VERIFIED_MULTI_SOURCE','CONTRACT_VERIFIED','NEGOTIATED_VERIFIED'] as const;

export function stableSerialize(v:any):string{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stableSerialize).join(',')}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stableSerialize(v[k])}`).join(',')}}`;}
export async function sha256(v:any){const bytes=new TextEncoder().encode(typeof v==='string'?v:stableSerialize(v));const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('');}
export function bpsToPpm(bps:number){if(!Number.isInteger(bps))throw new Error('bps_must_be_integer');return bps*100;}
export function isIsoCurrency(x:any){return typeof x==='string'&&/^[A-Z]{3}$/.test(x);}
export function valueMode(c:any){return String(c?.value_mode||'KNOWN');}
export function validateComponent(c:any){const e:string[]=[];if(!c?.component_type)e.push('component_type_required');for(const k of ['percentage_ppm','amount_minor','minimum_amount_minor','maximum_amount_minor'])if(c?.[k]!=null&&!Number.isInteger(c[k]))e.push(`${k}_must_be_integer`);if((c?.amount_minor!=null||c?.minimum_amount_minor!=null||c?.maximum_amount_minor!=null)&&!isIsoCurrency(c?.currency))e.push('money_component_requires_currency');const has=c?.percentage_ppm!=null||c?.amount_minor!=null||c?.minimum_amount_minor!=null||c?.maximum_amount_minor!=null;if(valueMode(c)!=='KNOWN'&&has)e.push('non_known_component_cannot_have_numeric_value');if(valueMode(c)==='KNOWN'&&!has)e.push('known_component_requires_value');return{ok:e.length===0,errors:e};}
export function validateObservation(o:any,components:any[]=[]){const e:string[]=[];const market=String(o?.market||o?.country||'');if(!(P3_MARKETS as readonly string[]).includes(market))e.push('market_invalid');if(o?.verified_at&&!VERIFIED_STATUSES.includes(o.verification_status))e.push('verified_at_without_verification');if((VERIFIED_STATUSES as readonly string[]).includes(o?.verification_status)&&!o?.verified_at)e.push('verified_status_requires_verified_at');if((o?.country===''||o?.market===''))e.push('empty_market_never_global');if(/^bank_tpv_[a-z]{2}_generic$/i.test(String(o?.provider_slug||''))&&(VERIFIED_STATUSES as readonly string[]).includes(o?.verification_status))e.push('generic_bank_placeholder_cannot_be_verified');if(o?.observation_type==='LEGACY_ESTIMATE'&&(VERIFIED_STATUSES as readonly string[]).includes(o?.verification_status))e.push('legacy_estimate_cannot_be_verified');if(o?.achievable_percent_bps!=null||o?.achievable_percent_ppm!=null)e.push('achievable_rate_forbidden_in_p3');if(o?.effective_from&&o?.retrieved_at&&o.effective_from===o.retrieved_at&&o?.effective_date_certainty==='UNKNOWN')e.push('retrieved_at_must_not_be_invented_effective_from');for(const c of components)for(const x of validateComponent(c).errors)e.push(`component:${x}`);return{ok:e.length===0,errors:e};}
function within(o:any,at:string){const t=Date.parse(at);if(Number.isNaN(t))return false;if(o.effective_from&&t<Date.parse(o.effective_from))return false;if(o.effective_to&&t>Date.parse(o.effective_to))return false;return true;}
function knownAt(o:any,asOf?:string){if(!asOf)return true;const t=Date.parse(asOf),r=Date.parse(o.recorded_at||o.first_seen_at||o.observed_at||'1970-01-01');return r<=t&&(!o.retired_at||Date.parse(o.retired_at)>t);}
function marketMatch(o:any,m:string){if((o.market||o.country)===m)return true;return ['EU','EEA','EUROZONE','MARKET_GROUP','GLOBAL','CUSTOM_SCOPE'].includes(o.scope_type)&&(o.applicable_markets||[]).includes(m)&&!(o.excluded_markets||[]).includes(m);}
function fieldMatch(o:any,k:string,v:any){return v==null||v===''||o[k]==null||o[k]===''||o[k]===v;}
function score(o:any,q:any){let n=(o.market||o.country)===q.market?20:5;for(const k of ['provider_id','provider_legal_entity_id','provider_product_id','channel','pricing_plan_id','payment_method_id','card_scope_id','merchant_segment_scope_id'])if(q[k]!=null&&o[k]===q[k])n+=10;if((VERIFIED_STATUSES as readonly string[]).includes(o.verification_status))n+=4;if(['VERIFIED_PRIMARY','VERIFIED_MULTI_SOURCE'].includes(o.verification_status))n+=2;return n;}
export function resolvePricing(rows:any[],q:any){if(!q?.market||!(P3_MARKETS as readonly string[]).includes(q.market))return{outcome:'UNKNOWN',reason:'market_required',matches:[]};const at=q.date||new Date().toISOString();const c=(rows||[]).filter(o=>!['REJECTED','QUARANTINED'].includes(o.status)&&marketMatch(o,q.market)&&fieldMatch(o,'provider_id',q.provider_id)&&fieldMatch(o,'provider_slug',q.provider_slug)&&fieldMatch(o,'provider_legal_entity_id',q.provider_legal_entity_id)&&fieldMatch(o,'provider_product_id',q.provider_product_id)&&fieldMatch(o,'channel',q.channel)&&fieldMatch(o,'pricing_plan_id',q.pricing_plan_id)&&fieldMatch(o,'payment_method_id',q.payment_method_id)&&fieldMatch(o,'card_scope_id',q.card_scope_id)&&within(o,at)&&knownAt(o,q.known_as_of));if(!c.length)return{outcome:'UNKNOWN',reason:'no_applicable_observation',matches:[]};if(c.some(o=>o.status==='CONFLICT'||o.verification_status==='CONFLICT'))return{outcome:'CONFLICT',matches:c};const custom=c.filter(o=>['CUSTOM_QUOTE','NEGOTIATED_ONLY','NOT_PUBLIC'].includes(o.pricing_visibility));if(custom.length===c.length)return{outcome:custom.some(o=>o.pricing_visibility==='CUSTOM_QUOTE')?'CUSTOM_QUOTE':'NOT_PUBLIC',matches:custom};const ranked=c.map(o=>({o,s:score(o,q)})).sort((a,b)=>b.s-a.s||String(b.o.verified_at||'').localeCompare(String(a.o.verified_at||'')));const best=ranked.filter(x=>x.s===ranked[0].s).map(x=>x.o);if(best.length>1&&new Set(best.map(x=>x.semantic_fingerprint||x.content_hash||x.pricing_key)).size>1)return{outcome:'MULTIPLE_MATCHES',matches:best};const o=best[0];const missing:string[]=[];for(const k of ['provider_legal_entity_id','provider_product_id','channel','pricing_plan_id','payment_method_id','card_scope_id'])if(q[k]!=null&&(o[k]==null||o[k]===''))missing.push(k);if(o.status==='STALE'||o.verification_status==='STALE')return{outcome:'STALE',match:o,matches:[o],missing_dimensions:missing};if(missing.length)return{outcome:'PARTIAL_MATCH',match:o,matches:[o],missing_dimensions:missing,reason_for_partial_match:'observation broader than requested context'};return{outcome:'EXACT_MATCH',match:o,matches:[o],missing_dimensions:[]};}
export function evaluateComponents(components:any[],q:any={}){let total=0;const included:any[]=[],excluded:any[]=[],unknown:any[]=[];for(const c of components||[]){if(valueMode(c)!=='KNOWN'){unknown.push(c);continue}if(['PER_MONTH','PER_TERMINAL','PER_ACCOUNT'].includes(c.unit_basis)){excluded.push(c);continue}let f=0;if(c.percentage_ppm!=null){if(!Number.isInteger(q.transaction_amount_minor)){unknown.push(c);continue}f+=Math.round(q.transaction_amount_minor*c.percentage_ppm/1_000_000)}if(c.amount_minor!=null)f+=c.amount_minor;if(c.minimum_amount_minor!=null)f=Math.max(f,c.minimum_amount_minor);if(c.maximum_amount_minor!=null)f=Math.min(f,c.maximum_amount_minor);total+=f;included.push({...c,calculated_amount_minor:f})}return{calculation_status:unknown.length?'PARTIAL':'COMPLETE',calculated_amount_minor:total,included_components:included,excluded_components:excluded,unknown_components:unknown};}
export function canAutoPromote(x:any){return x?.source_authority==='PRIMARY'&&x.market_unambiguous===true&&x.product_unambiguous===true&&x.channel_unambiguous===true&&x.currency_valid===true&&x.temporal_valid===true&&Number(x.parser_confidence)>=Number(x.threshold??.95)&&x.no_conflict===true&&x.invariants_ok===true;}
export function legacyClassification(r:any){const reasons:string[]=[];let classification='PARTIAL_MIGRATABLE';const slug=String(r?.provider_slug||'');if(/^bank_tpv_[a-z]{2}_generic$/i.test(slug)||slug==='ANY'){classification='GENERIC_PLACEHOLDER';reasons.push('generic_pseudo_provider')}if((r?.country??null)===''){if(classification!=='GENERIC_PLACEHOLDER')classification='INVALID_SCOPE';reasons.push('empty_country_not_global')}if(slug==='sumup'&&r?.verified!==true){classification='LEGACY_ESTIMATE';reasons.push('sumup_unverified_or_extrapolated')}if(r?.verified===true&&r?.source_url&&r?.source_quote&&classification==='PARTIAL_MIGRATABLE')classification='VERIFIED_MIGRATABLE';if(r?.intl_uplift_bps!=null&&!r?.intl_uplift_source_url){reasons.push('unevidenced_international_uplift');if(classification==='VERIFIED_MIGRATABLE')classification='PARTIAL_MIGRATABLE'}if(r?.achievable_percent_bps!=null||r?.achievable_fixed_fee_minor_units!=null||r?.achievable_intl_uplift_bps!=null)reasons.push('achievable_fields_quarantine_for_p5');return{classification,reasons};}
