export const PROVIDER_ECONOMICS_VERSION='p15-provider-economics-1.0.0';
export const PROVIDER_MONETIZATION_PRODUCTION_ALLOWED=false; // legal review gate; technical negotiation/reconciliation may be tested without activating revenue entitlement.
export const MERCHANT_SUITABILITY_MIN_SCORE=70;
export function clamp01(n:number){return Math.max(0,Math.min(1,Number.isFinite(n)?n:0))}
export function merchantSuitability(score:number){return Number(score||0)>=MERCHANT_SUITABILITY_MIN_SCORE}
export function providerExpectedRevenueMinor(e:any,horizonMonths=12){const months=Math.max(0,Number(horizonMonths||0));const volume=Math.max(0,Number(e?.expected_annual_volume_minor||0))*months/12;const bps=Math.max(0,Number(e?.rate_bps||0));const pct=Math.max(0,Number(e?.percentage||0));const fixed=Math.max(0,Number(e?.fixed_fee_minor||0));const merchants=Math.max(0,Number(e?.expected_activated_merchants||0));const recurring=Math.max(0,Number(e?.recurring_monthly_minor||0))*months;return Math.round(volume*bps/10000 + volume*pct/100 + fixed*merchants + recurring)}
export function providerEconomicsScore(e:any){const r12=providerExpectedRevenueMinor(e,12),r36=providerExpectedRevenueMinor(e,36),reliability=clamp01(Number(e?.payment_reliability??.5)),activation=clamp01(Number(e?.activation_probability??.5)),claw=Math.max(0,Math.min(1,Number(e?.clawback_risk??0)));return Number(Math.min(100,(Math.log10(1+r12/100)/6*55)+(Math.log10(1+r36/100)/7*20)+reliability*10+activation*10+(1-claw)*5).toFixed(1))}
export function classifyConflict(input:{bestMerchantScore:number;candidateMerchantScore:number;candidateProviderRevenue:number;bestProviderRevenue:number}){const gap=Math.max(0,input.bestMerchantScore-input.candidateMerchantScore),revGain=input.candidateProviderRevenue-input.bestProviderRevenue;if(revGain<=0||gap<=0)return'conflict_none';if(gap<3)return'conflict_minor';if(gap<10)return'conflict_material';return'conflict_critical'}
export function recommendationFirewall(options:any[]){const eligible=options.filter(x=>merchantSuitability(Number(x.merchant_outcome_score||0)));const ranked=[...eligible].sort((a,b)=>Number(b.merchant_outcome_score||0)-Number(a.merchant_outcome_score||0));return ranked[0]||null}
export function compensationMetricValue(ctx:any,metric:string){if(metric==='activated_volume'||metric==='processed_volume')return Number(ctx?.volume_minor||0);if(metric==='transaction_count')return Number(ctx?.transaction_count||0);if(metric==='activated_merchants')return Number(ctx?.merchant_count||0);if(metric==='provider_net_revenue')return Number(ctx?.provider_net_revenue_minor||0);if(metric==='product_adoption')return Number(ctx?.product_adoption||0);if(metric==='retention')return Number(ctx?.retention||0);if(metric==='growth_rate')return Number(ctx?.growth_rate||0);return 0}
export function compensationTierProgress(ctx:any,tier:any){const value=Math.max(0,compensationMetricValue(ctx,String(tier.metric||''))),threshold=Math.max(0,Number(tier.threshold_value||0));return{value,threshold,qualified:threshold===0||value>=threshold,progress_pct:threshold?Number(Math.min(100,value/threshold*100).toFixed(1)):100,amount_remaining:Math.max(0,threshold-value)}}
export function providerRevenueAmountMinor(basisValue:number,terms:any){const basis=Math.max(0,Number(basisValue||0));return Math.round(basis*Math.max(0,Number(terms?.rate_bps||0))/10000 + basis*Math.max(0,Number(terms?.percentage||0))/100 + Math.max(0,Number(terms?.fixed_fee_minor||0)))}
