export const RECOVERY_ECONOMICS_COPY_VERSION='recover-economics-copy-v2-draft-legal-review';
const COPY:any={
 en:{title:'24-month Recovery Term',y1:'Months 1–12',y2:'Months 13–24',after:'After month 24',cambra:'CAMBRA fee',keep:'You keep',referrals:'Successful referrals reduce the CAMBRA fee by 5 percentage points each, down to a minimum 5% fee during the Recovery Term.',verified:'Only positive Verified Savings are fee-bearing. No verified savings, no fee.',survival:'Ending other CAMBRA services does not by itself end an activated Recovery Term. The success fee continues only on positive savings attributable to that Recover that can be verified during the remaining term.',data:'During an active Recovery Term, reasonably necessary evidence may be required to verify savings. CAMBRA will not invoice estimated savings as verified savings.'},
 fr:{title:'Période Recover de 24 mois',y1:'Mois 1 à 12',y2:'Mois 13 à 24',after:'Après le 24e mois',cambra:'Commission CAMBRA',keep:'Vous conservez',referrals:'Chaque parrainage réussi réduit la commission CAMBRA de 5 points de pourcentage, jusqu’à un minimum de 5 % pendant la période Recover.',verified:'Seules les économies vérifiées positives donnent lieu à une commission. Sans économie vérifiée, aucune commission.',survival:'La fin des autres services CAMBRA ne met pas, à elle seule, fin à une période Recover déjà activée. La commission ne continue que sur les économies positives attribuables à ce Recover et vérifiables pendant la durée restante.',data:'Pendant une période Recover active, les éléments raisonnablement nécessaires à la vérification des économies peuvent être requis. CAMBRA ne facture pas des économies estimées comme si elles étaient vérifiées.'},
 es:{title:'Recovery Term de 24 meses',y1:'Meses 1–12',y2:'Meses 13–24',after:'Después del mes 24',cambra:'Comisión CAMBRA',keep:'Tú conservas',referrals:'Cada referral exitoso reduce la comisión de CAMBRA en 5 puntos porcentuales, hasta un mínimo del 5% durante el Recovery Term.',verified:'Solo el ahorro positivo realmente verificado genera comisión. Sin ahorro verificado, no hay comisión.',survival:'Cancelar otros servicios de CAMBRA no extingue por sí solo un Recovery Term ya activado. La comisión solo continúa sobre ahorro positivo atribuible a ese Recover que pueda verificarse durante el plazo restante.',data:'Durante un Recovery Term activo podrá solicitarse la evidencia razonablemente necesaria para verificar el ahorro. CAMBRA no facturará ahorro estimado como si fuera ahorro verificado.'}
};
export function recoveryEconomicsCopy(locale:string){return COPY[locale]||COPY.en;}

export function recoveryEconomicsAcceptanceText(locale:string, entity:string){
 const name=String(entity||'').trim() || ({fr:'mon entreprise',es:'mi empresa',en:'my business'} as any)[locale] || 'my business';
 if(locale==='fr') return `Je déclare être habilité(e) à engager ${name}. J’accepte la période Recover de 24 mois présentée ci-dessus : 25 % des économies vérifiées positives pendant les mois 1 à 12, 15 % pendant les mois 13 à 24, puis 0 %, sous réserve des réductions de parrainage applicables avec un plancher de 5 % pendant la période Recover. Je comprends que la fin des autres services CAMBRA ne met pas, à elle seule, fin à une période Recover déjà activée et qu’aucune commission n’est due sans économie positive vérifiée.`;
 if(locale==='es') return `Declaro que estoy autorizado/a para vincular jurídicamente a ${name}. Acepto el Recovery Term de 24 meses mostrado anteriormente: 25% del ahorro positivo verificado durante los meses 1–12, 15% durante los meses 13–24 y 0% después, sujeto a los descuentos por referrals aplicables con un suelo del 5% durante el Recovery Term. Entiendo que cancelar otros servicios de CAMBRA no extingue por sí solo un Recovery Term ya activado y que no existe comisión sin ahorro positivo verificado.`;
 return `I confirm I can legally bind ${name}. I accept the 24-month Recovery Term shown above: 25% of positive Verified Savings in months 1–12, 15% in months 13–24, then 0%, subject to applicable referral reductions with a 5% floor during the Recovery Term. I understand that ending other CAMBRA services does not by itself end an already activated Recovery Term and that no fee is due without positive Verified Savings.`;
}
