export const SHADOW_ROUTING_MODEL_VERSION='p13-shadow-routing-1.0.0';
export const ROUTING_FEATURES_VERSION='routing-features-1.0.0';
export const REAL_ROUTING_ALLOWED=false;
export const MIN_APPROVAL_SAMPLE=50;
export const MIN_OPPORTUNITY_ANNUAL_EUR=1000;
export const MIN_OPPORTUNITY_CONFIDENCE=.6;
export function clamp01(n:number){return Math.max(0,Math.min(1,Number.isFinite(n)?n:0))}
export function validCurrency(v:any){return /^[A-Z]{3}$/.test(String(v||''))}
export function validateObservation(x:any){const errors:string[]=[];if(!x?.brand_id)errors.push('brand_id_required');if(!x?.provider_slug)errors.push('provider_required');if(x?.currency&&!validCurrency(x.currency))errors.push('invalid_currency');if(x?.granularity==='transaction'&&!(Number(x.amount_minor)>0))errors.push('amount_must_be_positive');if(x?.transaction_count!=null&&Number(x.transaction_count)<0)errors.push('invalid_transaction_count');if(x?.occurred_at&&Date.parse(x.occurred_at)>Date.now()+300000)errors.push('future_timestamp');for(const k of ['pan','card_number','cvv','cvc','track_data'])if(x?.feature_json&&k in x.feature_json)errors.push(`sensitive_card_data_forbidden:${k}`);return errors}
export function amountBucket(minor:number){const eur=Math.abs(Number(minor||0))/100;return eur<25?'lt25':eur<100?'25_100':eur<500?'100_500':eur<2000?'500_2000':'gte2000'}
export function estimatedCostMinor(input:{volumeMinor:number;txCount:number;variableBps?:number;fixedFeeMinor?:number;monthlyFeeMinor?:number;windowDays?:number}){const volume=Math.max(0,Number(input.volumeMinor||0)),tx=Math.max(0,Number(input.txCount||0));const variable=volume*Math.max(0,Number(input.variableBps||0))/10000;const fixed=tx*Math.max(0,Number(input.fixedFeeMinor||0));const months=Math.max(0,Number(input.windowDays||30))/30.4375;const monthly=Math.max(0,Number(input.monthlyFeeMinor||0))*months;return Math.round(variable+fixed+monthly)}
export function approvalEstimate(rows:any[],provider:string){const candidates=rows.filter(r=>r.provider_slug===provider&&Number(r.sample_size||0)>=MIN_APPROVAL_SAMPLE).sort((a,b)=>Number(b.specificity||0)-Number(a.specificity||0)||Number(b.sample_size||0)-Number(a.sample_size||0));const r=candidates[0];if(!r)return {available:false,probability:null,sample_size:0,confidence:0};return {available:true,probability:clamp01(Number(r.approval_rate||0)),sample_size:Number(r.sample_size||0),confidence:clamp01(Number(r.confidence||0))}}
export function chooseShadowRoute(candidates:any[],mode='cost_only'){const eligible=candidates.filter(c=>c.eligible!==false&&Number.isFinite(c.estimated_cost_minor));if(!eligible.length)return null;return [...eligible].sort((a,b)=>{if(mode!=='cost_only'&&a.approval?.available&&b.approval?.available){const av=(Number(a.approval.probability)-Number(b.approval.probability))*100000;const cost=Number(b.estimated_cost_minor)-Number(a.estimated_cost_minor);if(Math.abs(av)>Math.abs(cost))return -av}return Number(a.estimated_cost_minor)-Number(b.estimated_cost_minor)})[0]}
export function routingConfidence(x:{pricingConfidence:number;dataQuality:number;approvalConfidence?:number;counterfactual:boolean}){const approval=x.approvalConfidence==null?.5:clamp01(x.approvalConfidence);return Number((clamp01(x.pricingConfidence)*.45+clamp01(x.dataQuality)*.35+approval*.2-(x.counterfactual?.05:0)).toFixed(3))}
export function canCreateOpportunity(annualValue:number,confidence:number){return Math.abs(Number(annualValue||0))>=MIN_OPPORTUNITY_ANNUAL_EUR&&Number(confidence||0)>=MIN_OPPORTUNITY_CONFIDENCE}
export function readinessLevel(x:{observations:number;decisions:number;realtime:boolean;validatedRecommendations:boolean}){if(x.validatedRecommendations)return 'R3';if(x.realtime&&x.decisions>0)return 'R2';if(x.observations>0&&x.decisions>0)return 'R1';return 'R0'}