// DPA-1 (2026-08-16) — traducción del texto maestro inglés (en/dpa.js) con
// sentido jurídico idéntico. Este idioma es además el del documento fuente
// original (DPA_MAESTRO_CAMBRA_ENCARGADO_ES.md v1.0).
//
// Valores fijados en publicación (el maestro los traía entre corchetes):
// 30 días de preaviso de subencargados · 48 horas de notificación de brechas ·
// 15 días laborables de preaviso de auditoría · una vez por año natural ·
// 90 días de supresión. Ver src/docs/Decision_Log_DPA.md.

export default {
  badge: "Legal",
  title: "Acuerdo de Encargo de Tratamiento.",
  version: "1.0",
  lastUpdated: "Versión 1.0 — 16 de agosto de 2026",
  back: "Volver",
  sections: [
    { title: "Partes", content: "El presente Acuerdo de Encargo de Tratamiento (el «Acuerdo») se celebra entre usted, el cliente, en calidad de Responsable del Tratamiento («el Responsable»), y CAMBRA Global SASU, sociedad por acciones simplificada de derecho francés, SIREN 105 452 916, IVA intracomunitario FR50105452916, con domicilio social en 47 rue Vivienne, 75002 París, Francia, en calidad de Encargado del Tratamiento («CAMBRA»). Este Acuerdo forma parte integrante de los Términos y Condiciones y del contrato principal de servicios entre las partes, y se acepta junto con ellos." },
    { title: "1. Objeto y finalidad", content: "1.1. El presente Acuerdo regula el tratamiento de datos personales que CAMBRA realiza por cuenta del Responsable en el marco de la prestación de los servicios descritos en el contrato principal (análisis de costes de pagos, auditoría de comisiones, servicios de recuperación y funcionalidades conexas de la plataforma). 1.2. Este Acuerdo se celebra en cumplimiento del artículo 28 del Reglamento (UE) 2016/679 («RGPD») o, cuando resulte aplicable según el Anexo de Jurisdicción, de la normativa nacional equivalente indicada en dicho anexo." },
    { title: "2. Definiciones", content: "Los términos «datos personales», «tratamiento», «responsable», «encargado», «interesado», «violación de la seguridad de los datos personales» y demás términos definidos tendrán el significado que les atribuye el artículo 4 del RGPD o la norma equivalente aplicable según el Anexo de Jurisdicción." },
    { title: "3. Descripción del tratamiento", content: "3.1. La naturaleza, finalidad y duración del tratamiento, los tipos de datos personales y las categorías de interesados se detallan en el Anexo I. 3.2. Resumen orientativo: NATURALEZA — recogida, almacenamiento, análisis, comparación y elaboración de informes sobre datos de transacciones de pago y facturación. FINALIDAD — prestación de los servicios contratados de análisis y auditoría de costes de pago. DURACIÓN — la vigencia del contrato principal más el periodo de supresión del apartado 12. CATEGORÍAS DE INTERESADOS — personal del Responsable; clientes finales del Responsable en la medida en que aparezcan en datos transaccionales. TIPOS DE DATOS — datos identificativos y de contacto profesionales; datos de transacciones (importes, comisiones, referencias); datos de facturación. CATEGORÍAS ESPECIALES (art. 9 RGPD) — no se tratan de forma deliberada; si aparecieran incidentalmente, se aplicará el apartado 6.4." },
    { title: "4. Instrucciones del Responsable", content: "4.1. CAMBRA tratará los datos personales únicamente siguiendo instrucciones documentadas del Responsable, incluidas las relativas a transferencias internacionales, salvo que el Derecho de la Unión o del Estado miembro aplicable exija otro tratamiento; en tal caso, CAMBRA informará al Responsable de esa exigencia legal antes del tratamiento, salvo que dicho Derecho lo prohíba por razones importantes de interés público. 4.2. El contrato principal, este Acuerdo y las instrucciones cursadas a través de las funcionalidades de configuración de la plataforma constituyen las instrucciones documentadas iniciales. 4.3. CAMBRA informará inmediatamente al Responsable si, en su opinión, una instrucción infringe el RGPD u otra disposición aplicable en materia de protección de datos." },
    { title: "5. Confidencialidad", content: "5.1. CAMBRA garantiza que las personas autorizadas para tratar datos personales se han comprometido a respetar la confidencialidad o están sujetas a una obligación de confidencialidad de naturaleza estatutaria. 5.2. CAMBRA limitará el acceso a los datos al personal que lo necesite para la prestación de los servicios." },
    { title: "6. Seguridad del tratamiento", content: "6.1. CAMBRA aplicará las medidas técnicas y organizativas apropiadas para garantizar un nivel de seguridad adecuado al riesgo, conforme al artículo 32 del RGPD, incluidas las descritas en el Anexo II. 6.2. Dichas medidas incluirán, según proceda: seudonimización y cifrado; capacidad de garantizar confidencialidad, integridad, disponibilidad y resiliencia permanentes; capacidad de restaurar la disponibilidad y el acceso tras un incidente; y un proceso de verificación y evaluación regulares de la eficacia de las medidas. 6.3. CAMBRA evaluará el nivel de seguridad teniendo en cuenta los riesgos del tratamiento, en particular la destrucción, pérdida, alteración o comunicación o acceso no autorizados, accidentales o ilícitos. 6.4. Si CAMBRA detectara categorías especiales de datos tratadas de forma incidental fuera del alcance del Anexo I, lo notificará al Responsable y aplicará las instrucciones que éste curse, absteniéndose entre tanto de cualquier uso de dichos datos." },
    { title: "7. Subencargados", content: "7.1. El Responsable otorga una autorización general por escrito para que CAMBRA recurra a los subencargados listados en la página de Subencargados (/Subprocessors), que constituye el Anexo III de este Acuerdo. 7.2. CAMBRA informará al Responsable de cualquier adición o sustitución prevista de subencargados con una antelación mínima de 30 días, dando al Responsable la posibilidad de oponerse por motivos razonables relacionados con la protección de datos. Si la oposición no puede resolverse, cualquiera de las partes podrá resolver la parte del servicio afectada. 7.3. CAMBRA impondrá a cada subencargado, mediante contrato, las mismas obligaciones de protección de datos que las estipuladas en este Acuerdo, en particular garantías suficientes de aplicar medidas técnicas y organizativas apropiadas. 7.4. CAMBRA seguirá siendo plenamente responsable ante el Responsable del cumplimiento de las obligaciones del subencargado." },
    { title: "8. Asistencia — derechos de los interesados", content: "8.1. Teniendo en cuenta la naturaleza del tratamiento, CAMBRA asistirá al Responsable, mediante medidas técnicas y organizativas apropiadas, en el cumplimiento de su obligación de responder a las solicitudes de ejercicio de los derechos de los interesados (acceso, rectificación, supresión, limitación, portabilidad, oposición y decisiones automatizadas). 8.2. Si un interesado se dirige directamente a CAMBRA, CAMBRA remitirá la solicitud al Responsable sin dilación indebida y no responderá por sí misma salvo instrucción del Responsable o exigencia legal." },
    { title: "9. Asistencia — seguridad, brechas y evaluaciones", content: "9.1. CAMBRA asistirá al Responsable en el cumplimiento de las obligaciones de los artículos 32 a 36 del RGPD (seguridad, notificación de violaciones, evaluaciones de impacto y consultas previas), teniendo en cuenta la naturaleza del tratamiento y la información a disposición de CAMBRA. 9.2. NOTIFICACIÓN DE VIOLACIONES DE SEGURIDAD: CAMBRA notificará al Responsable sin dilación indebida tras tener conocimiento de una violación de la seguridad de los datos personales tratados por cuenta del Responsable, y en cualquier caso en un plazo no superior a 48 horas desde dicho conocimiento. La notificación incluirá, en la medida disponible: naturaleza de la violación, categorías y número aproximado de interesados y registros afectados, consecuencias probables, y medidas adoptadas o propuestas. 9.3. CAMBRA documentará toda violación y cooperará con el Responsable en la gestión de la misma. La notificación a la autoridad de control y a los interesados corresponde al Responsable." },
    { title: "10. Auditorías", content: "10.1. CAMBRA pondrá a disposición del Responsable toda la información necesaria para demostrar el cumplimiento de las obligaciones del artículo 28 del RGPD. 10.2. CAMBRA permitirá y contribuirá a la realización de auditorías, incluidas inspecciones, por parte del Responsable o de un auditor autorizado por éste, con un preaviso razonable de al menos 15 días laborables, durante horario laboral, sin interrumpir de forma desproporcionada las operaciones de CAMBRA, y como máximo una vez por año natural, salvo tras una violación de seguridad o requerimiento de una autoridad de control. 10.3. CAMBRA podrá satisfacer total o parcialmente el derecho de auditoría mediante la entrega de certificaciones o informes de auditoría independientes recientes (p. ej. ISO 27001, SOC 2), sin perjuicio del derecho del Responsable a una inspección si dichos informes resultaran insuficientes de forma motivada." },
    { title: "11. Transferencias internacionales", content: "11.1. CAMBRA no transferirá datos personales fuera del Espacio Económico Europeo (o del territorio indicado en el Anexo de Jurisdicción) sin garantizar un mecanismo de transferencia válido: decisión de adecuación, cláusulas contractuales tipo aprobadas por la Comisión Europea (o el instrumento equivalente aplicable según el Anexo de Jurisdicción), u otra garantía adecuada del Capítulo V del RGPD. 11.2. Las transferencias existentes y sus mecanismos se documentan en la página de Subencargados (/Subprocessors) junto a la lista de subencargados." },
    { title: "12. Supresión y devolución", content: "12.1. A elección del Responsable, CAMBRA suprimirá o devolverá todos los datos personales una vez finalizada la prestación de los servicios, y suprimirá las copias existentes, salvo que el Derecho de la Unión o nacional aplicable exija su conservación. 12.2. Salvo instrucción en contrario, la supresión se completará en un plazo de 90 días desde la terminación, con certificación escrita a solicitud del Responsable." },
    { title: "13. Responsabilidad", content: "13.1. Cada parte responderá conforme a los artículos 82 y siguientes del RGPD y al régimen de responsabilidad pactado en el contrato principal. 13.2. Nada en este Acuerdo limita la responsabilidad de una parte frente a los interesados ni frente a las autoridades de control en aquello que no sea legalmente disponible." },
    { title: "14. Duración, ley aplicable y jurisdicción", content: "14.1. Este Acuerdo entra en vigor en la fecha de su aceptación y permanecerá vigente mientras CAMBRA trate datos personales por cuenta del Responsable. 14.2. LEY APLICABLE Y JURISDICCIÓN: las indicadas en el Anexo de Jurisdicción correspondiente al país del Responsable. En defecto de anexo aplicable, este Acuerdo se rige por el derecho francés y se somete a los tribunales de comercio competentes de París (Francia) — en coherencia con los Términos y Condiciones de la plataforma, dado que la entidad contratante es CAMBRA Global SASU, sociedad de derecho francés. 14.3. En caso de conflicto entre este Acuerdo y el contrato principal en materia de protección de datos, prevalecerá este Acuerdo. En caso de conflicto entre este Acuerdo y cláusulas contractuales tipo aplicables a una transferencia, prevalecerán estas últimas." },
    { title: "Anexo I — Descripción del tratamiento", content: "La naturaleza, finalidad, duración, categorías de interesados y tipos de datos personales son las resumidas en el apartado 3.2 para el servicio estándar. Cuando una operación concreta se aparte de esa descripción, quedará documentada en el pedido o registro de configuración correspondiente y formará parte de este Anexo." },
    { title: "Anexo II — Medidas técnicas y organizativas", content: "Cifrado en tránsito y en reposo; control de accesos con autenticación y mínimo privilegio; registro de actividad; copias de seguridad; gestión de vulnerabilidades; borrado seguro; continuidad de negocio; y seudonimización cuando proceda. La declaración detallada y vigente de estas medidas está disponible a solicitud en privacy@cambra.global." },
    { title: "Anexo III — Subencargados autorizados y transferencias", content: "La lista vigente de subencargados autorizados, su país, el servicio que prestan y el mecanismo de transferencia aplicable se publica y mantiene actualizada en la página de Subencargados (/Subprocessors). Dicha página lleva su propia fecha de última actualización, que es la referencia del preaviso de 30 días del apartado 7.2." },
    { title: "Anexo IV — Anexo de Jurisdicción", content: "Cuando el Responsable esté establecido fuera de Francia, se aplica la ficha del país correspondiente del anexo de jurisdicción de CAMBRA, disponible a solicitud en privacy@cambra.global. Para los Estados miembros de la UE y los países del EEE el fondo de este Acuerdo no cambia (el RGPD es de aplicación directa); solo cambian la ley nacional complementaria, la autoridad de control, la ley aplicable y el idioma vinculante. Para los países con ley propia adecuada (Suiza, Andorra) se aplica la cláusula de inclusión correspondiente, que sustituye las referencias al RGPD." },
    { title: "Estado de este documento", content: "Esta es la versión 1.0 del Acuerdo. Su estado de revisión jurídica se controla internamente y este texto puede ser modificado; los cambios sustanciales se notifican con al menos 30 días de antelación conforme a los Términos y Condiciones. Para cualquier consulta sobre este Acuerdo: privacy@cambra.global." },
  ],
};
