// LEGAL-1 — Traducción española del texto maestro inglés (en/privacy.js).
// Sentido jurídico idéntico, tuteo, terminología RGPD.

export default {
  badge: "Legal · Privacidad",
  title: "Política de privacidad.",
  lastUpdated: "Última actualización: 24 de julio de 2026",
  back: "Volver",
  sections: [
    { title: "1. Responsable del tratamiento", content: "El responsable del tratamiento es CAMBRA Global SASU, sociedad por acciones simplificada de derecho francés, inscrita con SIREN 105 452 916 y SIRET 105 452 916 00015, IVA intracomunitario FR50105452916, con domicilio social en 47 rue Vivienne, Chez Vivienne Domiciliation, 75002 París, Francia. Para cualquier solicitud relativa a tus datos, escríbenos a privacy@cambra.global." },
    { title: "2. Qué datos recogemos", content: "Recogemos la información que nos facilitas directamente: nombre, email profesional, información de tu marca, datos de costes de pagos e infraestructura, extractos subidos y métricas operativas introducidas en el Analyzer. Cuando conectas una cuenta de terceros (p. ej. Stripe), recogemos los datos autorizados por tu alcance OAuth — solo lectura. También tratamos los registros técnicos generados por el funcionamiento normal de la plataforma (peticiones, errores, eventos de seguridad). Si llegas a nosotros mediante el enlace de referido de otro comercio, también registramos ese código de referido: un código aleatorio opaco generado por CAMBRA, no derivado de datos personales. Se usa únicamente para identificar qué comercio te ha referido y aplicarle a ese comercio la reducción de comisión correspondiente, y se conserva junto a tu sesión de análisis. Se guarda en tu navegador (sessionStorage) entre el momento en que abres el enlace y el momento en que ejecutas tu análisis — consulta nuestra Política de cookies." },
    { title: "3. Cómo usamos tus datos", content: "Tus datos se usan para ofrecer la inteligencia de infraestructura de CAMBRA: generar auditorías, calcular benchmarks, identificar oportunidades de optimización y personalizar tu panel. Base jurídica: ejecución del contrato (art. 6.1.b RGPD) e interés legítimo para el benchmarking (art. 6.1.f RGPD). Nunca vendemos tus datos. La inteligencia entre clientes se mantiene separada de los datos operativos de cada merchant. Solo podremos conservar estadísticas agregadas y totalmente anonimizadas, sin identificador del merchant ni pseudónimo estable y producidas únicamente cuando se alcance un umbral mínimo de diversidad; los datos identificables o meramente seudonimizados siguen sujetos a las reglas ordinarias de conservación y supresión." },
    { title: "4. Subida de archivos y procesamiento con IA", content: "Cuando subes extractos o facturas (PDF, Excel, CSV), se procesan con grandes modelos de lenguaje para extraer datos estructurados de costes y operaciones. El contenido enviado a nuestros proveedores de IA se limita a los datos comerciales necesarios para el análisis — importes, comisiones, fechas y nombres de proveedores; no enviamos con este fin datos personales de tus clientes finales. Nuestros proveedores de IA tratan este contenido bajo sus acuerdos estándar de tratamiento de datos, cuyas condiciones establecen que los datos enviados a través de sus API no se usan para entrenar sus modelos. Los archivos subidos se almacenan bajo los controles de seguridad de nuestro proveedor de alojamiento y almacenamiento, y siguen siendo de tu propiedad." },
    { title: "5. Encargados del tratamiento", content: "Para operar el servicio, CAMBRA se apoya en los siguientes encargados del tratamiento, cada uno bajo su respectivo acuerdo de tratamiento de datos: Base44 (alojamiento de la aplicación y base de datos); Anthropic PBC (procesamiento con IA — extracción documental, inteligencia de producto y el Copilot integrado); OpenAI (contraste de extracción con IA); Resend, Inc. (envío de emails transaccionales); Stripe Payments Europe Ltd. (procesamiento de pagos cuando aplique); Microsoft Ireland Operations Limited (copia de recuperación ante desastres cifrada y fuera de plataforma de los datos de la plataforma y adjuntos del comercio en un tenant de SharePoint, datos en reposo alojados en Francia). Hay una lista completa y actualizada disponible bajo petición en privacy@cambra.global y en el Anexo III del DPA (página de subencargados)." },
    { title: "6. Almacenamiento y seguridad", content: "Tus datos se cifran en tránsito y en reposo conforme a los estándares de nuestro proveedor de infraestructura. Además, las credenciales de terceros que conectas (tokens OAuth, claves API) se cifran a nivel de aplicación con AES-256-GCM, usando una clave dedicada que nunca se expone al código cliente. El acceso a tus datos está restringido a los sistemas y personas que lo necesitan para operar el servicio, y las operaciones sensibles quedan registradas." },
    { title: "7. Tus derechos (RGPD)", content: "Si resides en el Espacio Económico Europeo, Reino Unido o Suiza, tienes derecho a acceder, rectificar, suprimir, limitar, portar y oponerte al tratamiento de tus datos. También puedes retirar tu consentimiento en cualquier momento. Para ejercer estos derechos, escribe a privacy@cambra.global — respondemos en el plazo de un mes, conforme al art. 12 del RGPD." },
    { title: "8. Conservación de los datos", content: "Conservamos los datos personales y operativos solo mientras tu cuenta esté activa o sea necesario para prestar el servicio. Cuando solicitas la eliminación de tu cuenta, suprimimos o anonimizamos los datos identificables sin dilación indebida. Los datos de facturación se conservan 10 años conforme al derecho mercantil y fiscal francés (Code de commerce, art. L123-22). Los benchmarks agregados y anonimizados, que ya no permiten identificarte, pueden conservarse." },
    { title: "9. Cookies y almacenamiento local", content: "Usamos un conjunto reducido de cookies propias y almacenamiento del navegador (localStorage / sessionStorage), estrictamente para que la plataforma funcione: autenticación, continuidad de sesión y tus preferencias. No usamos cookies publicitarias ni rastreadores de terceros. La lista completa, verificada sobre el código, está en nuestra Política de cookies." },
    { title: "10. Transferencias internacionales", content: "Algunos de nuestros encargados tratan datos fuera del EEE (p. ej. inferencia de IA de Anthropic PBC u OpenAI, envío de emails de Resend, Inc.). Estas transferencias se rigen por los mecanismos de transferencia previstos en el acuerdo de tratamiento de datos de cada proveedor, como las cláusulas contractuales tipo aprobadas por la Comisión Europea. Microsoft Ireland Operations Limited (copia de recuperación en SharePoint) aloja los datos en reposo en Francia; los servicios auxiliares (soporte, telemetría), cuando apliquen, quedan cubiertos por las Cláusulas Contractuales Tipo firmadas en el Microsoft Products and Services Data Protection Addendum." },
    { title: "11. Notificación de brechas de datos", content: "En caso de violación de datos personales que pueda suponer un riesgo para tus derechos y libertades, CAMBRA lo notificará a la autoridad de control competente (CNIL) en un plazo de 72 horas y, si el riesgo es alto, informará a los usuarios afectados sin dilación indebida, conforme a los arts. 33-34 del RGPD." },
    { title: "12. Contacto y autoridad de control", content: "Para cualquier cuestión, solicitud o reclamación sobre privacidad: privacy@cambra.global. También tienes derecho a presentar una reclamación ante la Commission Nationale de l'Informatique et des Libertés (CNIL, www.cnil.fr) o ante tu autoridad local de protección de datos." },
  ],
};
