// LEGAL-1 — Traducción española del texto maestro inglés (en/terms.js).
// Sentido jurídico idéntico, tuteo.

export default {
  badge: "Legal",
  title: "Términos y condiciones.",
  lastUpdated: "Última actualización: 24 de julio de 2026",
  back: "Volver",
  sections: [
    { title: "1. Editor e identidad legal", content: "La plataforma CAMBRA está editada por CAMBRA GLOBAL SASU, sociedad por acciones simplificada unipersonal de derecho francés, inscrita con el SIREN 105 452 916, con domicilio social en 42 rue Vivienne, 75002 París, Francia. Contacto: support@cambra.global. Director de la publicación: el representante legal de CAMBRA GLOBAL SASU. El alojamiento lo proporciona Base44." },
    { title: "2. Aceptación", content: "Al acceder a la plataforma CAMBRA o usarla, aceptas quedar vinculado por estos Términos y condiciones. Si no estás de acuerdo, no uses la plataforma. CAMBRA se reserva el derecho de actualizar estos términos con un preaviso razonable (al menos 30 días para cambios sustanciales), comunicado por email y mediante notificación en la aplicación." },
    { title: "3. Objeto de la plataforma", content: "CAMBRA ofrece servicios de análisis de costes de pago, benchmarking y recuperación para marcas de comercio independiente, cubriendo los pagos con tarjeta tanto online como en tienda. La plataforma está destinada exclusivamente a uso profesional (B2B). Debes tener al menos 18 años y estar debidamente autorizado para representar a la marca o entidad que registras." },
    { title: "4. Resultados de auditoría y estimaciones", content: "Todos los resultados del Analyzer, las estimaciones de ahorro en pagos y las comparativas de benchmarks son estimaciones derivadas de tus datos y del conjunto de datos de la red CAMBRA. Son orientación operativa — no asesoramiento financiero, jurídico, contable ni fiscal. CAMBRA no garantiza ningún resultado de ahorro concreto. Consulta siempre a asesores cualificados antes de decisiones importantes." },
    { title: "5. Propiedad de los datos y licencia", content: "Conservas la plena propiedad de todos los datos que envías. Al usar la plataforma, concedes a CAMBRA una licencia limitada, mundial, no exclusiva y revocable para tratar esos datos con el único fin de prestar el servicio. Los datos agregados y totalmente anonimizados (a partir de los cuales no puede reidentificarse ninguna marca individual) pueden usarse para mejorar los benchmarks. Nunca compartiremos datos identificables con terceros sin tu consentimiento explícito, salvo obligación legal." },
    { title: "6. Precio — auditoría gratuita", content: "El acceso al Analyzer, los benchmarks, el scoring y el panel se ofrece actualmente de forma gratuita a las marcas early partner. No se requiere tarjeta de crédito. CAMBRA podrá introducir niveles de pago en el futuro con al menos 30 días de preaviso; los early partners mantendrán sus condiciones comerciales originales durante un periodo de transición razonable." },
    { title: "7. Servicio de recuperación — comisión de éxito", content: "Si optas por el servicio de recuperación, CAMBRA actúa en tu nombre para renegociar tus tasas de pago con tarjeta — online (PSP) y en tienda (TPV / terminal físico) — con tu proveedor actual, o para migrarte a uno mejor cuando proceda. La comisión es del 25% del ahorro en pagos verificado, calculada sobre un acuerdo de 24 meses desde el momento en que el ahorro sea medible en tus extractos reales del PSP o proveedor. Reglas clave: (a) sin coste inicial, sin suscripción, sin mínimo; (b) si no se recupera ahorro verificado, no debes nada; (c) «ahorro verificado» significa la diferencia entre tu tasa efectiva de referencia y tu nueva tasa efectiva, acreditada con extractos reales del PSP o proveedor de TPV conciliados por CAMBRA; (d) al terminar el acuerdo de 24 meses, el 100% del ahorro futuro queda para ti; (e) las condiciones específicas de cada mandato de recuperación se formalizan en un mandato escrito independiente, firmado antes de emprender cualquier negociación." },
    { title: "8. Programa de proveedores", content: "CAMBRA opera un programa de proveedores de dos niveles, descrito en nuestra página For Providers (/ForProviders). El nivel 1 (Listed) cubre a los proveedores de pago cuya tarificación pública entra en nuestro benchmark alcanzable — sin coste, sin exclusividad y sin flujos de compensación en ningún sentido. El nivel 2 (Partner) cubre a los proveedores de pago que ofrecen una tarifa exclusiva a los comercios presentados a través de CAMBRA a cambio de un acuerdo de referidos; cuando presentamos una oferta Partner a un comercio, se etiqueta como oferta exclusiva de CAMBRA, separada visual y semánticamente de nuestro benchmark público. Nuestro benchmark público nunca está influido por los acuerdos Partner: CAMBRA siempre recomienda la opción que más ahorra a la marca, ya sea el ancla ganadora Listed, Partner o el proveedor actual del comercio. Las condiciones comerciales específicas de cada acuerdo se formalizan en un contrato firmado y se comunican a cualquier proveedor interesado previa solicitud escrita a support@cambra.global." },
    { title: "9. Uso aceptable", content: "Te comprometes a no: hacer ingeniería inversa de la plataforma, extraer masivamente los datos de benchmark, tergiversar tu marca, subir contenido ilícito, intentar acceder a los datos de otro usuario, ni usar CAMBRA para construir un servicio directamente competidor. Las infracciones pueden conllevar la suspensión inmediata sin reembolso." },
    { title: "10. Propiedad intelectual", content: "La plataforma CAMBRA, la marca, la metodología, los benchmarks y el software son propiedad exclusiva de CAMBRA GLOBAL SASU. Ninguna disposición de estos Términos te transfiere derecho alguno de propiedad intelectual, salvo la licencia limitada de uso del servicio." },
    { title: "11. Limitación de responsabilidad", content: "En la máxima medida permitida por el derecho francés, CAMBRA no es responsable de los daños indirectos, incidentales, especiales o consecuentes derivados del uso de la plataforma. La responsabilidad total agregada queda limitada a la mayor de estas cantidades: (a) los importes que hayas pagado a CAMBRA en los doce meses anteriores a la reclamación, o (b) 5.000 €. Nada en estos Términos limita la responsabilidad por negligencia grave, dolo o muerte/daños personales." },
    { title: "12. Desistimiento (B2B)", content: "La plataforma es un servicio profesional B2B. El derecho de desistimiento de 14 días del Código de consumo francés no es aplicable. No obstante, puedes cancelar tu cuenta en cualquier momento desde los ajustes de la cuenta, conforme a la sección 13 siguiente." },
    { title: "13. Cancelación", content: "Puedes cancelar tu cuenta en cualquier momento desde los ajustes de la cuenta. Los mandatos de recuperación en curso continúan según sus condiciones vigentes, salvo que el propio mandato se revoque por escrito. CAMBRA puede suspender o cancelar el acceso por infracciones sustanciales de estos términos o por inactividad prolongada (más de 24 meses). Tras la cancelación, tus datos se tratan conforme a nuestra Política de privacidad." },
    { title: "14. Ley aplicable y jurisdicción", content: "Estos Términos se rigen por el derecho francés. Cualquier controversia se abordará primero mediante negociación de buena fe. Si no se resuelve en 60 días, las partes podrán recurrir a mediación (CMAP, París). A falta de resolución amistosa, la jurisdicción exclusiva corresponde a los tribunales de comercio competentes de París, Francia." },
    { title: "15. Contacto", content: "Para cualquier cuestión contractual: support@cambra.global. Para notificaciones legales: 42 rue Vivienne, 75002 París, Francia." },
  ],
};