import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
import { requireAdminOrInternal } from '../../shared/internalGate.ts';
import { offerHasMaterialCommitment, OFFER_EXTRACTION_VERSION, sanitizeExternalText } from '../../shared/commercialAutonomy.ts';
import { negotiationCohort, safeMemorySummary } from '../../shared/negotiationMemory.ts';
import { callCambraClaude } from '../../shared/commercialModelRouter.ts';

async function claude(prompt:string){return (await callCambraClaude(prompt,{tier:'high_reasoning',maxTokens:2600})).text}
function parse(t:string){const c=t.replace(/```json\s*/gi,'').replace(/```/g,'').trim();try{return JSON.parse(c)}catch{}const m=c.match(/\{[\s\S]*\}/);if(m){try{return JSON.parse(m[0])}catch{}}return null}

Deno.serve(async(req)=>{let task:any=null;try{
 const base44=createClientFromRequest(req);const body=await req.json().catch(()=>({}));const gate=await requireAdminOrInternal(req,base44,body);if(!gate.ok)return gate.response;const svc=base44.asServiceRole;
 const c=await svc.entities.NegotiationCase.get(String(body?.case_id||'')).catch(()=>null);if(!c)return Response.json({ok:false,error:'negotiation_case_not_found'},{status:404});if(['approved','rejected','closed','expired'].includes(c.status))return Response.json({ok:false,error:'negotiation_case_closed'},{status:409});
 const thread=await svc.entities.CommunicationThread.get(c.thread_id).catch(()=>null);if(!thread)return Response.json({ok:false,error:'negotiation_thread_missing'},{status:409});
 task=await svc.entities.AgentTask.create({brand_id:c.brand_id,agent_name:'provider_negotiation',task_type:String(body?.action||'negotiate'),related_entity_type:'NegotiationCase',related_entity_id:c.id,status:'running',requires_approval:false,risk_level:3,input_summary:`${c.provider_name} · round ${Number(c.round||0)+1}`,started_at:new Date().toISOString()});
 const internal=Deno.env.get('INTERNAL_CALL_SECRET')||'';const memories=await svc.entities.NegotiationMemoryCohort.filter({cohort_key:negotiationCohort(c)},'-updated_at',1).catch(()=>[]);const memory=safeMemorySummary(memories[0]);
 if(body?.action==='initial_contact'){
   const current=c.current_economics_json||{};const target=c.target_economics_json||{};
   const prompt=['Write CAMBRA\'s initial B2B pricing-review email to a payment provider.','CAMBRA is authorized by the merchant to manage payment infrastructure optimization. Do not claim authority beyond the stored mandate.','Use only facts supplied. Do not mention other merchants or confidential competitor offers. Request the best available commercial terms and the components needed to compare them.','Natural, concise, professional. No fake employee identity. Sign CAMBRA Payments. Return ONLY JSON {"subject":"...","body":"..."}.',JSON.stringify({provider:c.provider_name,current_economics:current,target_economics:target,authority:c.authority_snapshot_json?.disclosable||[],historical_memory:memory})].join('\n');
   const draft=parse(await claude(prompt));if(!draft?.subject||!draft?.body)throw new Error('initial_provider_draft_unparseable');
   const send=await svc.functions.invoke('commercialSendMessage',{thread_id:thread.id,action:'provider_contact',classification:'acknowledgement',subject:sanitizeExternalText(draft.subject,300),text:sanitizeExternalText(draft.body,5000),agent_name:'provider_negotiation',idempotency_key:`provider-initial:${c.id}:${String(thread.counterparty_email||'').toLowerCase()}`,next_action_at:new Date(Date.now()+72*3600000).toISOString(),internal_secret:internal});const sd=send?.data||send||{};if(sd.ok===false)throw new Error(`provider_send_rejected:${sd.error}`);
   await svc.entities.NegotiationCase.update(c.id,{status:'awaiting_provider',round:1,next_action:'await_provider_response',next_action_at:new Date(Date.now()+72*3600000).toISOString()});
   await svc.entities.AgentTask.update(task.id,{status:'completed',output_summary:`Initial provider contact sent to ${c.provider_name}`,output_payload_json:{send:sd},completed_at:new Date().toISOString()});return Response.json({ok:true,task_id:task.id,sent:true});
 }
 const message=await svc.entities.CommunicationMessage.get(String(body?.message_id||'')).catch(()=>null);if(!message||message.thread_id!==thread.id||message.direction!=='inbound')return Response.json({ok:false,error:'provider_message_required'},{status:400});
 const extractionPrompt=['Extract the provider offer from this real email. Do not invent absent terms. Numbers must be null when absent.','Return ONLY JSON {"currency":"EUR|GBP|USD|null","variable_fee_bps":number|null,"fixed_fee_minor":number|null,"pricing_model":"...|unknown","interchange_treatment":"...|unknown","scheme_fee_treatment":"...|unknown","settlement_terms":"...","reserve_terms":"...","minimum_commitment":"...","contract_term_months":number|null,"termination_terms":"...","setup_terms":"...","hardware_terms":"...","conditions_json":{"lock_in":true|false|null,"minimum_volume":number|null,"termination_fee":number|null},"valid_until":null,"confidence":0-1,"is_final":true|false,"requires_contract":true|false}.','EMAIL:',String(message.text_body||'').slice(0,12000)].join('\n');const ex=parse(await claude(extractionPrompt));if(!ex)throw new Error('offer_extraction_unparseable');
 const offer={negotiation_case_id:c.id,round:Number(c.round||0)+1,source_message_id:message.id,currency:String(ex.currency||c.currency||'EUR'),variable_fee_bps:ex.variable_fee_bps==null?null:Number(ex.variable_fee_bps),fixed_fee_minor:ex.fixed_fee_minor==null?null:Number(ex.fixed_fee_minor),pricing_model:String(ex.pricing_model||'unknown'),interchange_treatment:String(ex.interchange_treatment||'unknown'),scheme_fee_treatment:String(ex.scheme_fee_treatment||'unknown'),settlement_terms:String(ex.settlement_terms||''),reserve_terms:String(ex.reserve_terms||''),minimum_commitment:String(ex.minimum_commitment||''),contract_term_months:ex.contract_term_months==null?null:Number(ex.contract_term_months),termination_terms:String(ex.termination_terms||''),setup_terms:String(ex.setup_terms||''),hardware_terms:String(ex.hardware_terms||''),conditions_json:ex.conditions_json||{},valid_until:ex.valid_until||null,extraction_confidence:Math.max(0,Math.min(1,Number(ex.confidence)||0)),extraction_version:OFFER_EXTRACTION_VERSION,material_commitment:false,raw_extraction_json:ex};offer.material_commitment=offerHasMaterialCommitment(offer);
 const row=await svc.entities.NegotiationOffer.create(offer);const targetBps=Number(c.target_economics_json?.variable_fee_bps);const offeredBps=Number(offer.variable_fee_bps);const hasTarget=Number.isFinite(targetBps)&&targetBps>0;const hasOffer=Number.isFinite(offeredBps)&&offeredBps>0;const maxRounds=Math.max(1,Number(c.authority_snapshot_json?.max_rounds||5));const final=ex.is_final===true||offer.material_commitment||Number(c.round||0)+1>=maxRounds||(hasTarget&&hasOffer&&offeredBps<=targetBps);
 await svc.entities.NegotiationCase.update(c.id,{round:Number(c.round||0)+1,best_offer_json:hasOffer&&(!c.best_offer_json?.variable_fee_bps||offeredBps<Number(c.best_offer_json.variable_fee_bps))?{offer_id:row.id,...offer}:c.best_offer_json||{offer_id:row.id,...offer},status:final?'awaiting_final_approval':'negotiating',next_action:final?'founder_final_approval':'counter_provider'});
 if(final){const approval=await svc.entities.Approval.create({brand_id:c.brand_id,agent_task_id:task.id,action_type:'final_provider_deal',related_entity_type:'NegotiationCase',related_entity_id:c.id,risk_level:4,draft_content:`FINAL PROVIDER DEAL\nMerchant Recover: ${c.recover_id}\nProvider: ${c.provider_name}\nCurrent: ${JSON.stringify(c.current_economics_json||{})}\nTarget: ${JSON.stringify(c.target_economics_json||{})}\nOffer: ${JSON.stringify(offer)}\nMaterial commitment: ${offer.material_commitment?'YES':'NO'}`,draft_payload_json:{case_id:c.id,offer_id:row.id,recover_id:c.recover_id,provider_id:c.provider_id,current:c.current_economics_json||{},target:c.target_economics_json||{},offer,requires_revalidation:true},status:'pending',expires_at:new Date(Date.now()+7*86400000).toISOString()});await svc.entities.NegotiationCase.update(c.id,{final_approval_id:approval.id});await svc.entities.CommunicationThread.update(thread.id,{status:'awaiting_approval',automation_paused:true,pause_reason:'final_provider_deal'});await svc.entities.AgentTask.update(task.id,{status:'waiting_approval',requires_approval:true,risk_level:4,approval_id:approval.id,output_summary:'Final/material provider offer ready for founder approval',output_payload_json:{offer_id:row.id,approval_id:approval.id},completed_at:new Date().toISOString()});return Response.json({ok:true,task_id:task.id,offer_id:row.id,approval_id:approval.id,final:true});}
 const prompt=['Write CAMBRA\'s next provider counteroffer. We are authorized to negotiate but NOT to accept a binding commitment.','Do not disclose competitor confidential quotes. If an explicit target exists, push toward it. If NO explicit target exists, DO NOT invent a percentage, price or numerical anchor: ask for a stronger best-and-final improvement and clarify missing commercial components. Keep it concise and natural. Return ONLY JSON {"subject":"...","body":"..."}.',JSON.stringify({provider:c.provider_name,round:Number(c.round||0)+1,current:c.current_economics_json||{},target_bps:hasTarget?targetBps:null,provider_offer:offer,unresolved:c.unresolved_items||[],historical_memory:memory})].join('\n');const draft=parse(await claude(prompt));if(!draft?.subject||!draft?.body)throw new Error('counter_draft_unparseable');const send=await svc.functions.invoke('commercialSendMessage',{thread_id:thread.id,action:'counterproposal',classification:'clarification',subject:sanitizeExternalText(draft.subject,300),text:sanitizeExternalText(draft.body,5000),agent_name:'provider_negotiation',idempotency_key:`provider-counter:${row.id}`,next_action_at:new Date(Date.now()+72*3600000).toISOString(),internal_secret:internal});const sd=send?.data||send||{};if(sd.ok===false)throw new Error(`counter_send_rejected:${sd.error}`);await svc.entities.NegotiationCase.update(c.id,{status:'awaiting_provider',next_action:'await_provider_response',next_action_at:new Date(Date.now()+72*3600000).toISOString()});await svc.entities.AgentTask.update(task.id,{status:'completed',output_summary:`Counteroffer round ${Number(c.round||0)+1} sent`,output_payload_json:{offer_id:row.id,send:sd},completed_at:new Date().toISOString()});return Response.json({ok:true,task_id:task.id,offer_id:row.id,counter_sent:true});
}catch(error){console.error('providerNegotiationAgent failed',error);if(task?.id){try{const b=createClientFromRequest(req);await b.asServiceRole.entities.AgentTask.update(task.id,{status:'failed',error:'provider_negotiation_failed',completed_at:new Date().toISOString()})}catch{}}return Response.json({ok:false,error:'provider_negotiation_failed',task_id:task?.id||null},{status:500})}});
