import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
import { requireAdminOrInternal } from '../../shared/internalGate.ts';
import { sanitizeExternalText } from '../../shared/commercialAutonomy.ts';

async function claude(prompt:string){const k=Deno.env.get('ANTHROPIC_API_KEY');if(!k)throw new Error('anthropic_not_configured');const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':k,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-sonnet-4-5',max_tokens:2200,messages:[{role:'user',content:prompt}]})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`anthropic_failed:${r.status}`);return String(d?.content?.[0]?.text||'')}
function parse(t:string){const c=t.replace(/```json\s*/gi,'').replace(/```/g,'').trim();try{return JSON.parse(c)}catch{}const m=c.match(/\{[\s\S]*\}/);if(m){try{return JSON.parse(m[0])}catch{}}return null}
const eqNum=(a:any,b:any,tol=0.0001)=>a==null&&b==null?true:(a==null||b==null?false:Math.abs(Number(a)-Number(b))<=tol);
const norm=(v:any)=>String(v||'').trim().toLowerCase().replace(/\s+/g,' ');

Deno.serve(async(req)=>{let task:any=null;try{
 const base44=createClientFromRequest(req);const body=await req.json().catch(()=>({}));const gate=await requireAdminOrInternal(req,base44,body);if(!gate.ok)return gate.response;const svc=base44.asServiceRole;
 const caseId=String(body?.case_id||'');const text=sanitizeExternalText(body?.contract_text||'',50000);const documentId=String(body?.document_id||'');if(!caseId||!text)return Response.json({ok:false,error:'case_id_and_contract_text_required'},{status:400});
 const c=await svc.entities.NegotiationCase.get(caseId).catch(()=>null);if(!c)return Response.json({ok:false,error:'negotiation_case_not_found'},{status:404});if(!c.approved_offer_id)return Response.json({ok:false,error:'approved_offer_required_before_contract_review'},{status:409});const offer=await svc.entities.NegotiationOffer.get(c.approved_offer_id).catch(()=>null);if(!offer||offer.negotiation_case_id!==c.id)return Response.json({ok:false,error:'approved_offer_missing'},{status:409});
 task=await svc.entities.AgentTask.create({brand_id:c.brand_id,agent_name:'contract_comparison',task_type:'provider_contract_review',related_entity_type:'NegotiationCase',related_entity_id:c.id,status:'running',requires_approval:false,risk_level:4,input_summary:`Compare provider contract against approved offer for ${c.provider_name}`,started_at:new Date().toISOString()});
 const p=['Extract commercial terms from this provider contract. Never infer a missing number. Return ONLY JSON {"variable_fee_bps":number|null,"fixed_fee_minor":number|null,"currency":"EUR|GBP|USD|null","contract_term_months":number|null,"minimum_commitment":"","termination_terms":"","settlement_terms":"","reserve_terms":"","conditions_json":{"lock_in":true|false|null,"minimum_volume":number|null,"termination_fee":number|null},"confidence":0-1,"unusual_clauses":["..."]}.','CONTRACT TEXT:',text].join('\n');const ex=parse(await claude(p));if(!ex)throw new Error('contract_extraction_unparseable');const confidence=Math.max(0,Math.min(1,Number(ex.confidence)||0));
 const deltas:any[]=[];if(offer.variable_fee_bps!=null&&!eqNum(ex.variable_fee_bps,offer.variable_fee_bps))deltas.push({field:'variable_fee_bps',negotiated:offer.variable_fee_bps,contract:ex.variable_fee_bps});if(offer.fixed_fee_minor!=null&&!eqNum(ex.fixed_fee_minor,offer.fixed_fee_minor))deltas.push({field:'fixed_fee_minor',negotiated:offer.fixed_fee_minor,contract:ex.fixed_fee_minor});if(offer.contract_term_months!=null&&!eqNum(ex.contract_term_months,offer.contract_term_months))deltas.push({field:'contract_term_months',negotiated:offer.contract_term_months,contract:ex.contract_term_months});if(norm(offer.minimum_commitment)&&norm(ex.minimum_commitment)!==norm(offer.minimum_commitment))deltas.push({field:'minimum_commitment',negotiated:offer.minimum_commitment,contract:ex.minimum_commitment});if(norm(offer.termination_terms)&&norm(ex.termination_terms)!==norm(offer.termination_terms))deltas.push({field:'termination_terms',negotiated:offer.termination_terms,contract:ex.termination_terms});if(offer.conditions_json?.lock_in!=null&&ex.conditions_json?.lock_in!==offer.conditions_json.lock_in)deltas.push({field:'lock_in',negotiated:offer.conditions_json.lock_in,contract:ex.conditions_json?.lock_in});
 const status=confidence<0.8?'manual_review':deltas.length?'mismatch':'match';await svc.entities.NegotiationCase.update(c.id,{status:'contract_received',contract_document_id:documentId||c.contract_document_id||null,contract_match_status:status,contract_delta_json:{extraction_version:'provider-contract-1.0.0',confidence,deltas,unusual_clauses:Array.isArray(ex.unusual_clauses)?ex.unusual_clauses.slice(0,20):[],extracted_terms:ex},next_action:status==='match'?'contract_legal_review_and_execution_approval':status==='mismatch'?'resolve_contract_mismatch':'manual_contract_review'});
 let approval:any=null;if(status!=='match'||(Array.isArray(ex.unusual_clauses)&&ex.unusual_clauses.length)){approval=await svc.entities.Approval.create({brand_id:c.brand_id,agent_task_id:task.id,action_type:status==='mismatch'?'contract_mismatch':'contract_exception',related_entity_type:'NegotiationCase',related_entity_id:c.id,risk_level:4,draft_content:`PROVIDER CONTRACT REVIEW\nProvider: ${c.provider_name}\nStatus: ${status}\nDeltas: ${JSON.stringify(deltas)}\nUnusual clauses: ${JSON.stringify(ex.unusual_clauses||[])}`,draft_payload_json:{case_id:c.id,approved_offer_id:offer.id,document_id:documentId||null,contract_match_status:status,deltas,unusual_clauses:ex.unusual_clauses||[],contract_execution:false},status:'pending',expires_at:new Date(Date.now()+7*86400000).toISOString()});}
 await svc.entities.AgentTask.update(task.id,{status:approval?'waiting_approval':'completed',requires_approval:!!approval,approval_id:approval?.id||null,output_summary:`Contract comparison: ${status}${deltas.length?` · ${deltas.length} material delta(s)`:''}`,output_payload_json:{status,confidence,deltas,approval_id:approval?.id||null},completed_at:new Date().toISOString()});return Response.json({ok:true,task_id:task.id,status,confidence,deltas,approval_id:approval?.id||null,contract_execution:false});
}catch(error){console.error('reviewProviderContract failed',error);if(task?.id){try{const b=createClientFromRequest(req);await b.asServiceRole.entities.AgentTask.update(task.id,{status:'failed',error:'provider_contract_review_failed',completed_at:new Date().toISOString()})}catch{}}return Response.json({ok:false,error:'provider_contract_review_failed',task_id:task?.id||null},{status:500})}});