import{createClientFromRequest}from'npm:@base44/sdk@0.8.41';import{buildFounderSnapshot,merchant360,provider360,searchCompany}from'../../shared/founderOSData.ts';import{FOUNDER_METRICS,metricMeta,safeNumber}from'../../shared/founderOSCore.ts';
const safe=async(fn:any,fb:any=[])=>{try{return await fn()}catch{return fb}};
Deno.serve(async req=>{try{const b=createClientFromRequest(req),u=await b.auth.me().catch(()=>null);if(!u||u.role!=='admin')return Response.json({ok:false,error:'Forbidden'},{status:403});const body=await req.json().catch(()=>({})),mode=String(body.mode||'company_summary'),s=b.asServiceRole;
 if(mode==='company_summary'||mode==='recommended_actions'){const snap=await buildFounderSnapshot(s);if(mode==='recommended_actions')return Response.json({ok:true,generated_at:snap.generated_at,actions:[...snap.attention.map((x:any)=>({source:'founder_attention',priority:x.priority,title:x.title,why:x.summary,recommended_action:x.ai_recommendation||'Review and decide',financial_impact:x.financial_impact,risk:x.risk,evidence:[{entity:x.related_entity_type,id:x.related_entity_id},{entity:'Approval',id:x.approval_id}].filter(x=>x.id)})),...snap.opportunities.map((x:any,i:number)=>({source:'opportunity',priority:Math.max(20,70-i),title:x.title,why:x.type,recommended_action:x.recommended_action,financial_impact:x.expected_value,risk:x.risk,evidence:x.evidence}))].slice(0,30)});return Response.json(snap)}
 if(mode==='metric_catalog')return Response.json({ok:true,metrics:FOUNDER_METRICS});
 if(mode==='search')return Response.json(await searchCompany(s,String(body.query||'')));
 if(mode==='merchant_360')return Response.json(await merchant360(s,String(body.brand_id||body.id||'')));
 if(mode==='provider_360')return Response.json(await provider360(s,String(body.provider_id||body.id||'')));
 if(mode==='negotiation_war_room'){const id=String(body.case_id||body.id||'');const c=await safe(()=>s.entities.NegotiationCase.get(id),null);if(!c)return Response.json({ok:false,error:'negotiation_not_found'},{status:404});const [offers,bids,thread,approvals]=await Promise.all([safe(()=>s.entities.NegotiationOffer.filter({negotiation_case_id:id},'round',100)),safe(()=>s.entities.AggregateBid.filter({negotiation_case_id:id},'round',100)),c.thread_id?safe(()=>s.entities.CommunicationThread.get(c.thread_id),null):null,safe(()=>s.entities.Approval.filter({related_entity_id:id},'-created_date',50))]);return Response.json({ok:true,case:{id:c.id,provider_id:c.provider_id,provider_name:c.provider_name,status:c.status,round:c.round,current_economics:c.current_economics_json,target_economics:c.target_economics_json,best_offer:c.best_offer_json,strategy:c.strategy_json,next_action:c.next_action,next_action_at:c.next_action_at,contract_match_status:c.contract_match_status,conflict:c.commercial_conflict_classification},offers,bids,thread:thread?{id:thread.id,status:thread.status,last_message_at:thread.last_message_at,next_action_at:thread.next_action_at,summary:thread.summary,automation_paused:thread.automation_paused,pause_reason:thread.pause_reason}:null,approvals,truth:'Merchant economics and CAMBRA provider economics remain separate. No offer is binding without policy/approval.'});}
 if(mode==='decision'){const approvalId=String(body.approval_id||'');if(!approvalId)return Response.json({ok:false,error:'approval_id_required'},{status:400});const a=await safe(()=>s.entities.Approval.get(approvalId),null);if(!a)return Response.json({ok:false,error:'approval_not_found'},{status:404});let context:any=null;if(a.related_entity_type==='NegotiationCase')context=(await (async()=>{const c=await safe(()=>s.entities.NegotiationCase.get(a.related_entity_id),null);if(!c)return null;const offers=await safe(()=>s.entities.NegotiationOffer.filter({negotiation_case_id:c.id},'round',50));return{case:c,offers}})());if(a.related_entity_type==='DynamicAgreement')context=await safe(()=>s.entities.DynamicAgreement.get(a.related_entity_id),null);const decision={decision:`Resolve ${a.action_type}`,options:[{id:'approve',label:'Approve'},{id:'reject',label:'Reject'},{id:'request_changes',label:'Request changes / keep pending'}],financial_impact:a.draft_payload_json?.estimated_financial_impact??a.draft_payload_json?.expected_provider_revenue_12m_minor??null,risk:{level:a.risk_level,material:safeNumber(a.risk_level)>=4},reversibility:safeNumber(a.risk_level)>=4?'partially_reversible':'reversible',recommendation:a.draft_payload_json?.ai_recommendation||'No deterministic recommendation recorded; inspect evidence before approval.',confidence:a.draft_payload_json?.confidence??null,evidence:[{entity:'Approval',id:a.id},{entity:a.related_entity_type,id:a.related_entity_id}].filter(x=>x.id)};return Response.json({ok:true,approval:a,context,decision});}
 if(mode==='why_metric'){const key=String(body.metric||'').toLowerCase(),snap=await buildFounderSnapshot(s),meta=metricMeta(key);if(!meta)return Response.json({ok:false,error:'unsupported_metric',supported:Object.keys(FOUNDER_METRICS)},{status:400});const causes:any[]=[];if(['collected_revenue','merchant_collected','provider_collected'].includes(key)){const invoices=await safe(()=>s.entities.Invoice.list('-issued_at',5000)),prov=await safe(()=>s.entities.ProviderRevenueLedger.list('-updated_at',5000));const overdue=invoices.filter((x:any)=>['overdue','failed','disputed'].includes(String(x.status))).reduce((a:number,x:any)=>a+Math.max(0,safeNumber(x.total_amount)-safeNumber(x.amount_paid)),0);const providerOutstanding=prov.reduce((a:number,x:any)=>a+Math.max(0,safeNumber(x.accrued_amount_minor)-safeNumber(x.paid_amount_minor)),0)/100;if(overdue>0)causes.push({cause:'Merchant receivables not collected',impact_eur:overdue,evidence:{entity:'Invoice',filter:'overdue/failed/disputed'}});if(providerOutstanding>0)causes.push({cause:'Provider-side revenue not yet collected',impact_eur:providerOutstanding,evidence:{entity:'ProviderRevenueLedger',filter:'accrued minus paid'}});if(snap.operations.delayed_migrations_gt_5d)causes.push({cause:'Delayed migrations may defer verification/billing',count:snap.operations.delayed_migrations_gt_5d,evidence:{entity:'MigrationTask'}});}
 if(key==='company_health'){for(const r of snap.risks)causes.push({cause:r.title,impact:r.impact||r.amount||null,evidence:r.evidence});}
 if(key==='aggregate_addressable'||key==='aggregate_committed'){causes.push({cause:'Aggregate values are sums of active pools; committed includes only explicit commitments.',evidence:{entity:'AggregatePool'}});}
 if(key==='provider_accrued'){causes.push({cause:'Accrual requires an active agreement with provider compensation legal activation allowed and attributable production basis.',evidence:{entity:'ProviderRevenueLedger'}});}
 if(key==='verified_savings'){causes.push({cause:'Only fully_verified + realized savings reports contribute.',evidence:{entity:'MonthlySavingsReport'}});}
 return Response.json({ok:true,metric:key,definition:meta,current:snap.metrics[key]||null,causes,recommendations:causes.map((c:any)=>c.cause.includes('Provider')?'Run provider reconciliation/recovery':c.cause.includes('migration')?'Review delayed migration blockers':'Inspect underlying records'),evidence_boundary:'Explanation is derived from deterministic records; causal claims are operational hypotheses unless directly evidenced.'});}
 return Response.json({ok:false,error:'unsupported_mode',modes:['company_summary','recommended_actions','metric_catalog','search','merchant_360','provider_360','negotiation_war_room','decision','why_metric']},{status:400});
}catch(e){console.error(e);return Response.json({ok:false,error:'founder_os_query_failed'},{status:500})}});
