import{createClientFromRequest}from'npm:@base44/sdk@0.8.41';
import{requireAdminOrInternal}from'../../shared/internalGate.ts';
const VERSION='always-on-lead-discovery-1.0.0';
const normDomain=(x:any)=>String(x||'').toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0].trim();
const now=()=>new Date().toISOString();
Deno.serve(async req=>{try{const b=createClientFromRequest(req),body=await req.json().catch(()=>({})),g=await requireAdminOrInternal(req,b,body);if(!g.ok)return g.response;const s=b.asServiceRole,internal=Deno.env.get('INTERNAL_CALL_SECRET')||'';
 const policies=await s.entities.CommercialPolicy.filter({engine:'merchant_acquisition',status:'active'},'-approved_at',10).catch(()=>[]);const p=policies[0]||null;if(!p)return Response.json({ok:true,status:'waiting_policy',engine_version:VERSION});
 const leads=await s.entities.OutboundLead.list('-created_date',5000).catch(()=>[]),profiles=await s.entities.OutboundSendingProfile.filter({profile_key:'resend:contact.cambra.global'},'-created_date',1).catch(()=>[]),profile=profiles[0]||null;
 const cap=Math.max(0,Number(profile?.current_daily_cap||p.daily_send_limit||0));const target=Math.max(.5,Math.min(30,Number(p?.icp_json?.pipeline_coverage_days||3)));
 const ready=leads.filter((l:any)=>l.stage==='scored'&&Number(l.score||0)>=Number(p.min_lead_score||70)&&Number(l.score_breakdown_json?.evidence_confidence||0)>=.55&&l.contact_email&&l.legal_basis).length;const coverage=cap>0?ready/cap:ready>0?999:0;
 const monthlyBudget=Math.max(0,Number(p?.icp_json?.discovery_monthly_budget||0)),perRun=Math.max(1,Math.min(100,Number(p?.icp_json?.per_run||25)));let action='quality_refresh',discoverN=0;if(coverage<target){action='increase_discovery';discoverN=perRun}else if(coverage>target*2){action='reservoir_healthy_reduce_discovery'}
 const countries=(p.countries||['FR','ES']).slice(0,4);const runs:any[]=[];if(discoverN>0&&p?.icp_json?.enabled!==false){const each=Math.max(1,Math.ceil(discoverN/Math.max(1,countries.length)));for(const cc of countries){const country=String(cc).toUpperCase()==='FR'?'France':String(cc).toUpperCase()==='ES'?'Spain':String(cc);const r=await s.functions.invoke('leadOrchestrator',{icp:{industry:p.icp_json?.industry||'ecommerce',titles:p.icp_json?.titles||['founder','CEO','co-founder','CFO','Head of Ecommerce','Head of Payments'],country,per_page:each,limit:each},internal_secret:internal}).catch((e:any)=>({data:{ok:false,error:String(e?.message||e)}}));runs.push({country,result:r?.data||r})}}
 const fresh=await s.entities.OutboundLead.list('-created_date',5000).catch(()=>[]),seen=new Map<string,string>();let deduped=0,suppressed=0,qualified=0,high=0,readyCount=0,stale=0;const cutoff=Date.now()-30*86400000;for(const l of fresh){const d=normDomain(l.company_domain),email=String(l.contact_email||'').toLowerCase();if(d&&seen.has(d)&&!['contacted','meeting','won'].includes(l.stage)){await s.entities.OutboundLead.update(l.id,{reservoir_state:'disqualified',suppression_reason:`duplicate_company:${seen.get(d)}`,reservoir_updated_at:now()}).catch(()=>null);deduped++;continue}if(d)seen.set(d,l.id);const sup=email?await s.entities.ContactSuppression.filter({email,active:true},'-created_date',1).catch(()=>[]):[];if(sup.length){await s.entities.OutboundLead.update(l.id,{reservoir_state:'suppressed',suppression_reason:'contact_suppression',reservoir_updated_at:now()}).catch(()=>null);suppressed++;continue}const score=Number(l.score||0),conf=Number(l.score_breakdown_json?.evidence_confidence||0),isQ=l.stage==='scored'&&score>=Number(p.min_lead_score||70);if(isQ)qualified++;if(isQ&&conf>=.75)high++;const isReady=isQ&&conf>=.55&&!!l.contact_email&&!!l.legal_basis;if(isReady){readyCount++;await s.entities.OutboundLead.update(l.id,{reservoir_state:'ready',revenue_stage:'outreach_ready',outreach_ready_at:l.outreach_ready_at||now(),last_verified_at:now(),reservoir_updated_at:now()}).catch(()=>null)}else if(['lead','enriched','scored'].includes(l.stage)){await s.entities.OutboundLead.update(l.id,{reservoir_state:l.stage==='lead'?'discovered':l.stage==='enriched'?'enriching':'qualified',reservoir_updated_at:now()}).catch(()=>null)}if(Date.parse(l.last_verified_at||l.updated_date||l.created_date||'')<cutoff)stale++}
 const byCountry:any={};for(const l of fresh){const c=String(l.country||'unknown');byCountry[c]=(byCountry[c]||0)+1}const cov=cap>0?Number((readyCount/cap).toFixed(2)):readyCount>0?999:0,status=cov<target?'LOW':cov>target*2?'EXCESS':'HEALTHY';const snap=await s.entities.LeadReservoirSnapshot.create({snapshot_key:`reservoir:${Date.now()}`,captured_at:now(),discovered:fresh.filter((x:any)=>x.stage==='lead').length,enriching:fresh.filter((x:any)=>x.stage==='enriched').length,qualified,high_confidence:high,outreach_ready:readyCount,queued:0,waiting_window:0,waiting_capacity:Math.max(0,readyCount-cap),suppressed,disqualified:deduped,stale,safe_daily_send_capacity:cap,coverage_days:cov,target_coverage_days:target,coverage_status:status,discovery_action:action,cost_guard_json:{monthly_budget:monthlyBudget,note:'24/7 availability does not imply continuous paid API calls; discovery throttles when coverage is healthy.'},country_breakdown_json:byCountry,engine_version:VERSION});return Response.json({ok:true,engine_version:VERSION,snapshot_id:snap.id,coverage_days:cov,target_coverage_days:target,coverage_status:status,outreach_ready:readyCount,safe_daily_send_capacity:cap,discovery_action:action,discovery_runs:runs.length,deduplicated:deduped,suppressed})}catch(e){console.error(e);return Response.json({ok:false,error:'always_on_lead_discovery_failed',message:String((e as Error)?.message||e).slice(0,300)},{status:500})}});
