import { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useTranslation } from '@/lib/i18n.jsx';
import { ShieldCheck, AlertTriangle } from 'lucide-react';
const COPY={
 en:{title:'CAMBRA service & active Recoveries',active:'Service active',cancelled:'Service cancelled',sub:'Cancelling the general service stops new Recoveries. An already activated Recover keeps its own economic term until the date shown, only on positive Verified Savings.',term:'Recovery Term ends',fee:'Current CAMBRA fee',verify:'Verification access',cancel:'Cancel CAMBRA service',confirm:'I understand that cancelling CAMBRA does not by itself end an already activated Recovery Term.',reason:'Reason (optional)',go:'Confirm service cancellation',warning:'This is not a cancellation fee. Any surviving Recover fee remains based only on positive savings that CAMBRA can verify.',none:'No active Recover commitments.',error:'We could not load or record service cancellation safely.'},
 fr:{title:'Service CAMBRA et Recover actifs',active:'Service actif',cancelled:'Service résilié',sub:'La résiliation du service général bloque les nouveaux Recover. Un Recover déjà activé conserve sa propre durée économique jusqu’à la date indiquée, uniquement sur les économies vérifiées positives.',term:'Fin de la période Recover',fee:'Commission CAMBRA actuelle',verify:'Accès de vérification',cancel:'Résilier le service CAMBRA',confirm:'Je comprends que la résiliation de CAMBRA ne met pas, à elle seule, fin à une période Recover déjà activée.',reason:'Motif (facultatif)',go:'Confirmer la résiliation du service',warning:'Il ne s’agit pas de frais de résiliation. Toute commission Recover survivante reste calculée uniquement sur les économies positives que CAMBRA peut vérifier.',none:'Aucun engagement Recover actif.',error:'Impossible de charger ou enregistrer la résiliation de manière sûre.'},
 es:{title:'Servicio CAMBRA y Recoveries activos',active:'Servicio activo',cancelled:'Servicio cancelado',sub:'Cancelar el servicio general impide nuevos Recoveries. Un Recover ya activado mantiene su propio término económico hasta la fecha indicada, únicamente sobre ahorro positivo verificado.',term:'Fin del Recovery Term',fee:'Comisión CAMBRA actual',verify:'Acceso de verificación',cancel:'Cancelar servicio CAMBRA',confirm:'Entiendo que cancelar CAMBRA no extingue por sí solo un Recovery Term ya activado.',reason:'Motivo (opcional)',go:'Confirmar cancelación del servicio',warning:'No es una penalización por cancelación. Cualquier comisión Recover que sobreviva sigue calculándose solo sobre ahorro positivo que CAMBRA pueda verificar.',none:'No hay compromisos Recover activos.',error:'No hemos podido cargar o registrar la cancelación de forma segura.'}
};
export default function RecoverCommitmentsCard(){
 const {lang}=useTranslation(); const c=COPY[lang]||COPY.en; const [state,setState]=useState(null); const [ack,setAck]=useState(false); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const load=()=>base44.functions.invoke('getMyRecoveryCommitments',{}).then(r=>setState(r?.data||null)).catch(()=>setError(c.error));
 useEffect(()=>{load();},[]);
 if(!state?.exists) return null;
 const cancel=async()=>{if(!ack||busy)return;setBusy(true);setError('');try{const r=await base44.functions.invoke('cancelCambraService',{confirm:true,recovery_terms_acknowledged:true,reason});if(r?.data?.error)throw new Error();await load();}catch{setError(c.error)}finally{setBusy(false)}};
 return <div className="cambra-card p-6"><div className="relative"><div className="flex items-center gap-2 mb-3"><ShieldCheck size={14} className="text-cambra-cyan"/><p className="cc-eyebrow">{c.title}</p></div><p className="text-xs text-white/55 mb-4">{c.sub}</p><p className="text-sm font-bold text-white mb-3">{state.brand?.service_status==='cancelled'?c.cancelled:c.active}</p>
 <div className="space-y-2">{(state.recoveries||[]).length?(state.recoveries||[]).map(r=><div key={r.id} className="rounded-xl border border-white/10 bg-white/[0.03] p-3"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold text-white">{r.name}</p><p className="text-[10px] text-white/45 mt-1">{r.economic_right_status||r.status}</p></div>{r.current_fee_pct!=null&&<p className="text-sm font-black text-white">{r.current_fee_pct}%</p>}</div>{r.recovery_term_end_date&&<p className="text-[11px] text-white/60 mt-2">{c.term}: <b>{r.recovery_term_end_date}</b></p>}<p className="text-[11px] text-white/45 mt-1">{c.verify}: {r.verification_access_status||'—'}</p></div>):<p className="text-xs text-white/45">{c.none}</p>}</div>
 {state.brand?.service_status!=='cancelled'&&<div className="mt-5 pt-4 border-t border-white/10"><p className="text-[11px] text-amber-300/80 flex gap-2"><AlertTriangle size={13} className="shrink-0 mt-0.5"/>{c.warning}</p><label className="mt-3 flex items-start gap-2 text-[11.5px] text-white/65"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} className="mt-0.5"/><span>{c.confirm}</span></label><input value={reason} onChange={e=>setReason(e.target.value)} placeholder={c.reason} className="mt-3 h-9 w-full rounded-lg border border-white/10 bg-white/[0.04] px-3 text-xs text-white"/><button onClick={cancel} disabled={!ack||busy} className="mt-3 h-9 px-4 rounded-full border border-white/15 text-xs font-bold text-white disabled:opacity-40">{busy?'…':c.go}</button></div>}
 {error&&<p role="alert" className="mt-3 text-xs text-red-400">{error}</p>}</div></div>;
}
