import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
import { requireAdminOrInternal } from '../../shared/internalGate.ts';
import { policyIsActive, normalizeEmail } from '../../shared/commercialAutonomy.ts';
import { sha256 } from '../../shared/intelligenceCore.ts';
import { emergencyState } from '../../shared/operationalControl.ts';
import { assertMarketCapabilityAllowed } from '../../shared/marketPolicyRuntime.ts';
import { canonicalMarket } from '../../shared/marketContext.ts';

Deno.serve(async(req)=>{try{
 const base44=createClientFromRequest(req);const body=await req.json().catch(()=>({}));const gate=await requireAdminOrInternal(req,base44,body);if(!gate.ok)return gate.response;const svc=base44.asServiceRole;const emergency=await emergencyState(svc);if(emergency.safe_mode||emergency.negotiations_paused)return Response.json({ok:false,error:'emergency_control_paused:negotiations',safe_mode:emergency.safe_mode,reason:emergency.reason||null},{status:409});
 const recoverId=String(body?.recover_id||'');if(!recoverId)return Response.json({ok:false,error:'recover_id_required'},{status:400});
 const activation=await svc.entities.DealActivation.get(recoverId).catch(()=>null);if(!activation||activation.vertical!=='payments')return Response.json({ok:false,error:'payments_recover_not_found'},{status:404});
 if(!['authorized','migrating','live','monetizing'].includes(String(activation.status)))return Response.json({ok:false,error:'recover_not_authorized'},{status:409});
 const mandates=await svc.entities.Mandate.filter({deal_activation_id:activation.id,status:'active'},'-signed_at',5).catch(()=>[]);const mandate=mandates[0];if(!mandate)return Response.json({ok:false,error:'active_mandate_required'},{status:409});
 const authorized=mandate.authorized_actions_json||{};if(authorized.renegotiate_with_provider!==true)return Response.json({ok:false,error:'mandate_does_not_authorize_provider_negotiation'},{status:409});
 const existing=await svc.entities.NegotiationCase.filter({recover_id:activation.id},'-created_date',20).catch(()=>[]);const open=existing.find((x:any)=>!['closed','rejected','expired'].includes(x.status));if(open)return Response.json({ok:true,case:open,duplicate:true});
 let provider:any=null;const providerId=String(activation.provider_id||'');if(providerId)provider=await svc.entities.Provider.get(providerId).catch(()=>null);
 if(!provider&&gate.isAdmin&&body?.provider_id)provider=await svc.entities.Provider.get(String(body.provider_id)).catch(()=>null);
 if(!provider&&activation.provider_from){const rows=await svc.entities.Provider.filter({name:activation.provider_from},'-created_date',5).catch(()=>[]);provider=rows[0]||null;}
 if(!provider)return Response.json({ok:false,error:'provider_crm_record_required',setup_required:true},{status:409});let contact=normalizeEmail(provider.contact_email);let resolvedContact:any=null;if(!contact){const internal=Deno.env.get('INTERNAL_CALL_SECRET')||'';const rr=await svc.functions.invoke('providerContactResolver',{provider_id:provider.id,brand_id:activation.brand_id,recover_id:activation.id,internal_secret:internal}).catch((e:any)=>({data:{ok:false,error:String(e?.message||e)}}));const rd=rr?.data||rr||{};if(rd.ok===false||!rd?.contact?.email)return Response.json({ok:false,error:'provider_contact_unresolved',provider_id:provider.id,contact_resolution:rd,setup_required:true},{status:409});contact=normalizeEmail(rd.contact.email);resolvedContact=rd.contact;}
 const brand=await svc.entities.Brand.get(activation.brand_id).catch(()=>null);if(brand?.market_context_rollout==='production'){try{await assertMarketCapabilityAllowed(svc,{brand,brand_id:brand.id,capability:'NEGOTIATE',actor_type:'provider_negotiation'})}catch(e:any){return Response.json({ok:false,error:'market_capability_denied:NEGOTIATE',decision:e?.decision||null},{status:409})}}const negotiationLanguage=['en','fr','es'].includes(String(brand?.locale))?String(brand.locale):'en';const policies=await svc.entities.CommercialPolicy.filter({engine:'provider_negotiation',status:'active'},'-approved_at',10).catch(()=>[]);const policy=policies.find((p:any)=>policyIsActive(p))||null;if(!policy)return Response.json({ok:false,error:'provider_negotiation_policy_required',setup_required:true},{status:409});
 const now=new Date().toISOString();const authority={schema_version:'provider-authority-1.0.0',mandate_id:mandate.id,mandate_snapshot_hash:mandate.acceptance_snapshot_hash||null,recover_id:activation.id,provider_id:provider.id,authorized_actions:authorized,disclosable:['merchant_identity','payment_volume_if_verified','transaction_profile_if_verified','current_provider_terms_if_evidenced','benchmark_context_without_cross_merchant_confidentiality'],prohibited:['accept_final_offer','sign_contract','accept_lock_in','accept_minimum_commitment','accept_termination_fee','migration_go_live','send_sensitive_document_without_policy','change_recover_economics'],max_rounds:Math.max(1,Math.min(Number(body?.max_rounds)||5,8)),created_at:now};
 const providerSlug=String(provider.name||'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');const pricingVersions=await svc.entities.ProviderPricingVersion.filter({provider_slug:providerSlug,vertical:'payments',knowledge_state:'active'},'-effective_at',50).catch(()=>[]);const negotiationSnapshotPayload={provider:{id:provider.id,name:provider.name,slug:providerSlug},recover_id:activation.id,authority,policy:{key:policy.policy_key,version:policy.version},pricing_versions:pricingVersions.map((p:any)=>({id:p.id,pricing_key:p.pricing_key,country:p.country,currency:p.currency,variable_rate_bps:p.variable_rate_bps,fixed_fee_minor:p.fixed_fee_minor,truth_level:p.truth_level,effective_at:p.effective_at,observed_at:p.observed_at}))};const negotiationSnapshotHash=await sha256(negotiationSnapshotPayload);const negotiationSnapshot=await svc.entities.IntelligenceSnapshot.create({snapshot_key:`negotiation:${activation.id}:${negotiationSnapshotHash.slice(0,16)}`,snapshot_type:'negotiation_start',related_entity_type:'DealActivation',related_entity_id:activation.id,brand_id:activation.brand_id,vertical:'payments',claim_ids:[],pricing_version_ids:pricingVersions.map((p:any)=>p.id),benchmark_refs_json:{},policy_version:policy.version,model_policy_version:'cambra-model-router',snapshot_json:negotiationSnapshotPayload,snapshot_hash:negotiationSnapshotHash,captured_at:now}).catch(()=>null);
 const caseRow=await svc.entities.NegotiationCase.create({recover_id:activation.id,brand_id:activation.brand_id,provider_id:provider.id,provider_name:provider.name,status:'ready',round:0,currency:'EUR',current_economics_json:body?.current_economics_json||{},target_economics_json:body?.target_economics_json||{},authority_snapshot_json:authority,authority_hash:String(mandate.acceptance_snapshot_hash||''),strategy_json:{policy_key:policy.policy_key,policy_version:policy.version},unresolved_items:[],next_action:'initial_provider_contact',next_action_at:now,contract_match_status:'not_received',started_at:now,intelligence_snapshot_id:negotiationSnapshot?.id||undefined});
 const thread=await svc.entities.CommunicationThread.create({thread_key:`negotiation:${caseRow.id}`,engine:'provider_negotiation',related_entity_type:'NegotiationCase',related_entity_id:caseRow.id,recover_id:activation.id,provider_id:provider.id,counterparty_email:contact,counterparty_name:resolvedContact?.name||provider.account_manager||provider.name,language:negotiationLanguage,market_jurisdiction:canonicalMarket(brand?.billing_country||brand?.country)?.iso2||undefined,market_policy_rollout:brand?.market_context_rollout||'legacy',status:'open',policy_key:policy.policy_key,policy_version:policy.version,automation_paused:false,summary:`${provider.name} negotiation for Recover ${activation.id}`});
 await svc.entities.NegotiationCase.update(caseRow.id,{thread_id:thread.id});
 const internal=Deno.env.get('INTERNAL_CALL_SECRET')||'';const run=await svc.functions.invoke('providerNegotiationAgent',{action:'initial_contact',case_id:caseRow.id,internal_secret:internal}).catch((e:any)=>({data:{ok:false,error:String(e?.message||e)}}));
 return Response.json({ok:true,case_id:caseRow.id,thread_id:thread.id,initial_contact:run?.data||run||null});
}catch(error){console.error('startProviderNegotiation failed',error);return Response.json({ok:false,error:'provider_negotiation_start_failed'},{status:500})}});
