import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { ArrowLeft, Check, Circle, Loader2, ShieldCheck, AlertCircle } from 'lucide-react';
import { useTranslation } from '@/lib/i18n.jsx';

const ORDER = ['preparing','provider_coordination','scheduled','going_live','verifying','completed'];
const COPY = {
  en:{ eyebrow:'Payments migration', title:"We’re handling your migration.", sub:'CAMBRA coordinates the provider, configuration, go-live and savings verification. You only need to step in if we explicitly ask.', back:'Back to reports', savings:'Expected annual savings', progress:'Progress', now:'What CAMBRA is doing now', noMigration:'There is no active payments migration on this account.', errorTitle:"We couldn't load your migration", errorBody:'Your migration data is safe. Try again in a moment.', retry:'Retry', needs:'We need something from you', needsSub:'This action is genuinely required to keep the migration moving. CAMBRA handles everything else.', complete:'Migration completed. The first realized savings have been verified against your locked baseline.', stages:{preparing:'Preparing',provider_coordination:'Provider coordination',scheduled:'Migration scheduled',going_live:'Going live',verifying:'Verifying savings',completed:'Completed'}, stageCopy:{preparing:'We are opening the case, locking scope and assigning operational ownership.',provider_coordination:'We are coordinating onboarding, commercial terms and provider requirements.',scheduled:'We are testing the configuration and preparing a controlled cutover.',going_live:'We are moving the approved payment scope to the new provider or conditions.',verifying:'We are measuring live payment data against your locked baseline. Nothing is billable until savings are verified.',completed:'The migration and first savings verification are complete.'}, blockerTitles:{takeover:'Migration setup',provider_coordination:'Provider coordination',provider_ready:'Provider setup',technical_configuration:'Payment configuration',migration_testing:'Migration testing',cutover_ready:'Go-live preparation',go_live:'Going live',verify_savings:'Savings verification'}},
  fr:{ eyebrow:'Migration des paiements', title:'Nous gérons votre migration.', sub:"CAMBRA coordonne le prestataire, la configuration, la mise en ligne et la vérification des économies. Vous n'intervenez que si nous vous le demandons explicitement.", back:'Retour aux rapports', savings:'Économies annuelles attendues', progress:'Progression', now:'Ce que CAMBRA fait maintenant', noMigration:"Aucune migration de paiements n'est active sur ce compte.", errorTitle:'Impossible de charger votre migration', errorBody:'Vos données de migration sont intactes. Réessayez dans un instant.', retry:'Réessayer', needs:'Nous avons besoin de vous', needsSub:'Cette action est réellement indispensable pour poursuivre la migration. CAMBRA gère tout le reste.', complete:'Migration terminée. Les premières économies réalisées ont été vérifiées par rapport à votre référence verrouillée.', stages:{preparing:'Préparation',provider_coordination:'Coordination prestataire',scheduled:'Migration planifiée',going_live:'Mise en ligne',verifying:'Vérification des économies',completed:'Terminé'}, stageCopy:{preparing:'Nous ouvrons le dossier, verrouillons le périmètre et attribuons la responsabilité opérationnelle.',provider_coordination:'Nous coordonnons l’onboarding, les conditions commerciales et les exigences du prestataire.',scheduled:'Nous testons la configuration et préparons une bascule contrôlée.',going_live:'Nous transférons le périmètre de paiements approuvé vers le nouveau prestataire ou les nouvelles conditions.',verifying:'Nous mesurons les données de paiement réelles par rapport à votre référence verrouillée. Rien n’est facturable avant vérification des économies.',completed:'La migration et la première vérification des économies sont terminées.'}, blockerTitles:{takeover:'Préparation de la migration',provider_coordination:'Coordination prestataire',provider_ready:'Configuration prestataire',technical_configuration:'Configuration des paiements',migration_testing:'Tests de migration',cutover_ready:'Préparation de la mise en ligne',go_live:'Mise en ligne',verify_savings:'Vérification des économies'}},
  es:{ eyebrow:'Migración de pagos', title:'Nos encargamos de tu migración.', sub:'CAMBRA coordina el proveedor, la configuración, el go-live y la verificación del ahorro. Solo tendrás que intervenir si te lo pedimos expresamente.', back:'Volver a informes', savings:'Ahorro anual esperado', progress:'Progreso', now:'Qué está haciendo CAMBRA ahora', noMigration:'No hay ninguna migración de pagos activa en esta cuenta.', errorTitle:'No hemos podido cargar tu migración', errorBody:'Tus datos de migración están a salvo. Inténtalo de nuevo en un momento.', retry:'Reintentar', needs:'Necesitamos algo de ti', needsSub:'Esta acción es realmente imprescindible para que la migración continúe. CAMBRA se encarga de todo lo demás.', complete:'Migración completada. El primer ahorro real ya se ha verificado frente a tu baseline bloqueada.', stages:{preparing:'Preparando',provider_coordination:'Coordinando proveedor',scheduled:'Migración programada',going_live:'Activando',verifying:'Verificando ahorro',completed:'Completado'}, stageCopy:{preparing:'Estamos abriendo el caso, fijando el alcance y asignando la responsabilidad operativa.',provider_coordination:'Estamos coordinando el alta, las condiciones comerciales y los requisitos del proveedor.',scheduled:'Estamos probando la configuración y preparando un cambio controlado.',going_live:'Estamos moviendo el alcance de pagos aprobado al nuevo proveedor o a las nuevas condiciones.',verifying:'Estamos midiendo los datos reales de pago frente a tu baseline bloqueada. Nada se factura hasta que el ahorro esté verificado.',completed:'La migración y la primera verificación del ahorro están completadas.'}, blockerTitles:{takeover:'Preparación de la migración',provider_coordination:'Coordinación con el proveedor',provider_ready:'Alta con el proveedor',technical_configuration:'Configuración de pagos',migration_testing:'Pruebas de migración',cutover_ready:'Preparación del go-live',go_live:'Activación',verify_savings:'Verificación del ahorro'}},
};

export default function PaymentsMigration(){
  const { lang } = useTranslation();
  const c = COPY[lang] || COPY.en;
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState(false);
  const [migration,setMigration]=useState(null);
  const load=useCallback(async()=>{ setLoading(true); setError(false); try{ const r=await base44.functions.invoke('getMyPaymentsMigration',{}); if(r?.data?.error) throw new Error('load_failed'); setMigration(r?.data?.migration||null); }catch{ setError(true); }finally{ setLoading(false); } },[]);
  useEffect(()=>{ load(); },[load]);
  const current=Math.max(0,ORDER.indexOf(migration?.stage||'preparing'));
  const money=useMemo(()=>new Intl.NumberFormat(lang==='fr'?'fr-FR':lang==='es'?'es-ES':'en-GB',{style:'currency',currency:'EUR',maximumFractionDigits:0}),[lang]);

  if(loading) return <div className="py-24 flex justify-center"><Loader2 className="animate-spin text-white/50" size={22}/></div>;
  if(error) return <div className="cambra-card p-8 text-center"><p className="text-white font-bold">{c.errorTitle}</p><p className="text-sm text-white/55 mt-2">{c.errorBody}</p><button onClick={load} className="mt-5 h-10 px-5 rounded-full bg-white text-[#06080F] text-sm font-bold">{c.retry}</button></div>;
  if(!migration) return <div className="cambra-card p-8 text-center"><ShieldCheck className="mx-auto text-white/40" size={22}/><p className="text-white font-bold mt-3">{c.noMigration}</p><Link to="/Reports" className="inline-flex mt-5 text-sm font-semibold text-white/65 hover:text-white"><ArrowLeft size={15} className="mr-2"/>{c.back}</Link></div>;

  return <div className="space-y-6">
    <div className="flex items-center justify-between gap-4"><div><p className="cc-eyebrow mb-1">{c.eyebrow}</p><h1 className="text-2xl sm:text-3xl font-black text-white tracking-tight">{c.title}</h1><p className="text-sm text-white/55 max-w-2xl mt-2">{c.sub}</p></div><Link to="/Reports" className="hidden sm:inline-flex items-center text-sm font-semibold text-white/55 hover:text-white"><ArrowLeft size={15} className="mr-2"/>{c.back}</Link></div>
    <div className="cambra-card p-6 sm:p-8">
      <div className="grid sm:grid-cols-2 gap-5 mb-7"><div><p className="cc-eyebrow mb-1">{c.savings}</p><p className="text-2xl font-black text-white">{money.format(migration.projected_savings_annual||0)}</p></div><div><p className="cc-eyebrow mb-1">{c.progress}</p><p className="text-2xl font-black text-white">{migration.progress_pct||0}%</p></div></div>
      <div className="grid grid-cols-2 sm:grid-cols-6 gap-2">{ORDER.map((s,i)=>{const done=i<current||migration.stage==='completed';const active=i===current&&migration.stage!=='completed';return <div key={s} className={`rounded-xl border px-3 py-3 min-h-[82px] ${active?'border-cambra-cyan/40 bg-cambra-cyan/[.07]':'border-white/[.08] bg-white/[.025]'}`}><div className="mb-2">{done?<Check size={14} className="text-emerald-400"/>:active?<Loader2 size={14} className="text-cambra-cyan animate-spin"/>:<Circle size={12} className="text-white/20"/>}</div><p className={`text-[10.5px] leading-tight font-bold ${active?'text-white':'text-white/55'}`}>{c.stages[s]}</p></div>})}</div>
    </div>
    <div className="cambra-card p-6 sm:p-8"><p className="cc-eyebrow mb-2">{c.now}</p><h2 className="text-lg font-black text-white">{c.stages[migration.stage]||c.stages.preparing}</h2><p className="text-sm text-white/55 leading-relaxed mt-2 max-w-2xl">{c.stageCopy[migration.stage]||c.stageCopy.preparing}</p></div>
    {migration.needs_you && <div className="cambra-card p-5 border-amber-400/20"><div className="flex gap-3"><AlertCircle size={18} className="text-amber-300 shrink-0 mt-0.5"/><div><p className="text-sm font-bold text-white">{c.needs}</p><p className="text-xs text-white/55 mt-1">{c.needsSub}</p>{migration.merchant_blockers.map(b=>{const reason=b?.reason_i18n?.[lang]||b?.reason_i18n?.en||'';return <p key={b.id} className="text-xs text-white/75 mt-3">• {c.blockerTitles[b.step_key]||c.needs}{reason?` — ${reason}`:''}</p>})}</div></div></div>}
    {migration.stage==='completed' && <div className="cambra-card p-5"><div className="flex gap-3"><ShieldCheck size={18} className="text-emerald-400 shrink-0"/><p className="text-sm text-white/65">{c.complete}</p></div></div>}
  </div>;
}
