// DPA-1 (2026-08-16) — English master text. FR/ES are translations with
// identical legal meaning (same LEGAL-1 convention as terms.js / privacy.js).
//
// Source: DPA_MAESTRO_CAMBRA_ENCARGADO_ES.md v1.0 (founder-supplied draft) —
// the version merchants accept, i.e. CAMBRA acting as PROCESSOR on the
// customer's behalf. The companion "CAMBRA as controller" master (for CAMBRA's
// own suppliers) is INTERNAL and deliberately not published here.
//
// Placeholder values fixed at publication (the source carried them in
// brackets; see src/docs/Decision_Log_DPA.md):
//   sub-processor change notice ......... 30 days
//   personal data breach notification ... 48 hours
//   audit prior notice .................. 15 business days
//   audit frequency ..................... once per calendar year
//   deletion after termination .......... 90 days
//
// legal_review status is tracked in config/legal/dpa-status.json — it is
// PENDING until a qualified lawyer signs the text off. Nothing in this file
// asserts that the review has happened.

export default {
  badge: "Legal",
  title: "Data Processing Agreement.",
  version: "1.0",
  lastUpdated: "Version 1.0 — 16 August 2026",
  back: "Back",
  sections: [
    { title: "Parties", content: "This Data Processing Agreement (the \"Agreement\") is entered into between you, the customer, acting as the Controller (\"the Controller\"), and CAMBRA Global SASU, a French société par actions simplifiée registered under SIREN 105 452 916, EU VAT FR50105452916, with registered office at 47 rue Vivienne, 75002 Paris, France, acting as the Processor (\"CAMBRA\"). This Agreement forms an integral part of the Terms & Conditions and of the main services contract between the parties, and is accepted together with them." },
    { title: "1. Subject matter and purpose", content: "1.1. This Agreement governs the processing of personal data that CAMBRA carries out on behalf of the Controller in the provision of the services described in the main contract (payment-cost analysis, fee auditing, recovery services and related platform functionality). 1.2. This Agreement is entered into in performance of Article 28 of Regulation (EU) 2016/679 (\"GDPR\") or, where applicable under the Jurisdiction Annex, of the equivalent national legislation identified in that annex." },
    { title: "2. Definitions", content: "The terms \"personal data\", \"processing\", \"controller\", \"processor\", \"data subject\", \"personal data breach\" and other defined terms have the meaning given to them by Article 4 GDPR, or by the equivalent provision applicable under the Jurisdiction Annex." },
    { title: "3. Description of the processing", content: "3.1. The nature, purpose and duration of the processing, the types of personal data and the categories of data subjects are set out in Annex I. 3.2. Indicative summary: NATURE — collection, storage, analysis, comparison and reporting on payment-transaction and invoicing data. PURPOSE — provision of the contracted payment-cost analysis and audit services. DURATION — the term of the main contract plus the deletion period in Section 12. CATEGORIES OF DATA SUBJECTS — the Controller's personnel; the Controller's end customers to the extent they appear in transactional data. TYPES OF DATA — professional identification and contact data; transaction data (amounts, fees, references); invoicing data. SPECIAL CATEGORIES (Art. 9 GDPR) — not processed deliberately; if they appear incidentally, Section 6.4 applies." },
    { title: "4. Controller's instructions", content: "4.1. CAMBRA will process personal data only on documented instructions from the Controller, including with regard to international transfers, unless required to do otherwise by Union or Member State law applicable to CAMBRA; in that case CAMBRA will inform the Controller of that legal requirement before processing, unless that law prohibits it on important grounds of public interest. 4.2. The main contract, this Agreement and the instructions given through the platform's configuration functionality constitute the initial documented instructions. 4.3. CAMBRA will immediately inform the Controller if, in its opinion, an instruction infringes the GDPR or another applicable data protection provision." },
    { title: "5. Confidentiality", content: "5.1. CAMBRA ensures that persons authorised to process personal data have committed themselves to confidentiality or are under an appropriate statutory obligation of confidentiality. 5.2. CAMBRA limits access to the data to personnel who need it in order to provide the services." },
    { title: "6. Security of processing", content: "6.1. CAMBRA implements appropriate technical and organisational measures to ensure a level of security appropriate to the risk, in accordance with Article 32 GDPR, including those described in Annex II. 6.2. Those measures include, as appropriate: pseudonymisation and encryption; the ability to ensure the ongoing confidentiality, integrity, availability and resilience of processing systems; the ability to restore availability and access following an incident; and a process for regularly testing and evaluating the effectiveness of the measures. 6.3. CAMBRA assesses the level of security having regard to the risks of the processing, in particular accidental or unlawful destruction, loss, alteration, unauthorised disclosure of, or access to, personal data. 6.4. If CAMBRA detects special categories of data processed incidentally outside the scope of Annex I, it will notify the Controller and apply the Controller's instructions, refraining in the meantime from any use of that data." },
    { title: "7. Sub-processors", content: "7.1. The Controller grants a general written authorisation for CAMBRA to engage the sub-processors listed on the Sub-processors page (/Subprocessors), which constitutes Annex III of this Agreement. 7.2. CAMBRA will inform the Controller of any intended addition or replacement of sub-processors at least 30 days in advance, giving the Controller the opportunity to object on reasonable grounds relating to data protection. If the objection cannot be resolved, either party may terminate the affected part of the service. 7.3. CAMBRA will impose on each sub-processor, by contract, the same data protection obligations as those set out in this Agreement, in particular sufficient guarantees to implement appropriate technical and organisational measures. 7.4. CAMBRA remains fully liable to the Controller for the performance of the sub-processor's obligations." },
    { title: "8. Assistance — data subject rights", content: "8.1. Taking into account the nature of the processing, CAMBRA will assist the Controller by appropriate technical and organisational measures in fulfilling its obligation to respond to requests for the exercise of data subject rights (access, rectification, erasure, restriction, portability, objection and automated decision-making). 8.2. If a data subject contacts CAMBRA directly, CAMBRA will forward the request to the Controller without undue delay and will not respond itself unless instructed by the Controller or required by law." },
    { title: "9. Assistance — security, breaches and assessments", content: "9.1. CAMBRA will assist the Controller in complying with the obligations of Articles 32 to 36 GDPR (security, breach notification, data protection impact assessments and prior consultation), taking into account the nature of the processing and the information available to CAMBRA. 9.2. PERSONAL DATA BREACH NOTIFICATION: CAMBRA will notify the Controller without undue delay after becoming aware of a personal data breach affecting data processed on the Controller's behalf, and in any event within 48 hours of becoming aware. The notification will include, to the extent available: the nature of the breach, the categories and approximate number of data subjects and records concerned, the likely consequences, and the measures taken or proposed. 9.3. CAMBRA will document every breach and cooperate with the Controller in handling it. Notification to the supervisory authority and to data subjects is the Controller's responsibility." },
    { title: "10. Audits", content: "10.1. CAMBRA will make available to the Controller all information necessary to demonstrate compliance with the obligations of Article 28 GDPR. 10.2. CAMBRA will allow for and contribute to audits, including inspections, conducted by the Controller or an auditor mandated by it, on reasonable prior notice of at least 15 business days, during business hours, without disproportionately disrupting CAMBRA's operations, and at most once per calendar year, except following a personal data breach or a request from a supervisory authority. 10.3. CAMBRA may satisfy the audit right in whole or in part by providing recent independent certifications or audit reports (e.g. ISO 27001, SOC 2), without prejudice to the Controller's right to an inspection where such reports are shown, with reasons, to be insufficient." },
    { title: "11. International transfers", content: "11.1. CAMBRA will not transfer personal data outside the European Economic Area (or the territory identified in the Jurisdiction Annex) without ensuring a valid transfer mechanism: an adequacy decision, Standard Contractual Clauses approved by the European Commission (or the equivalent instrument applicable under the Jurisdiction Annex), or another appropriate safeguard under Chapter V GDPR. 11.2. Existing transfers and their mechanisms are documented on the Sub-processors page (/Subprocessors) alongside the sub-processor list." },
    { title: "12. Deletion and return", content: "12.1. At the Controller's choice, CAMBRA will delete or return all personal data after the end of the provision of services, and will delete existing copies, unless Union or national law requires their retention. 12.2. Unless instructed otherwise, deletion will be completed within 90 days of termination, with written certification on the Controller's request." },
    { title: "13. Liability", content: "13.1. Each party is liable in accordance with Article 82 et seq. GDPR and with the liability regime agreed in the main contract. 13.2. Nothing in this Agreement limits a party's liability towards data subjects or supervisory authorities in respect of anything that is not legally capable of limitation." },
    { title: "14. Term, governing law and jurisdiction", content: "14.1. This Agreement enters into force on the date of its acceptance and remains in force for as long as CAMBRA processes personal data on behalf of the Controller. 14.2. GOVERNING LAW AND JURISDICTION: those identified in the Jurisdiction Annex corresponding to the Controller's country. In the absence of an applicable annex, this Agreement is governed by French law and submitted to the competent commercial courts of Paris, France — consistent with the platform's Terms & Conditions, the contracting entity being CAMBRA Global SASU, a company incorporated under French law. 14.3. In the event of a conflict between this Agreement and the main contract on data protection matters, this Agreement prevails. In the event of a conflict between this Agreement and standard contractual clauses applicable to a transfer, the latter prevail." },
    { title: "Annex I — Description of the processing", content: "The nature, purpose, duration, categories of data subjects and types of personal data are those summarised in Section 3.2 for the standard service. Where a specific operation departs from that description, it is documented in the corresponding order or configuration record and forms part of this Annex." },
    { title: "Annex II — Technical and organisational measures", content: "Encryption in transit and at rest; access control with authentication and least privilege; activity logging; backups; vulnerability management; secure deletion; business continuity; and pseudonymisation where appropriate. The detailed and current statement of these measures is available on request at privacy@cambra.global." },
    { title: "Annex III — Authorised sub-processors and transfers", content: "The current list of authorised sub-processors, their country, the service they provide and the applicable transfer mechanism is published and kept up to date on the Sub-processors page (/Subprocessors). That page carries its own last-updated date, which is the reference point for the 30-day notice period in Section 7.2." },
    { title: "Annex IV — Jurisdiction Annex", content: "Where the Controller is established outside France, the country sheet from CAMBRA's jurisdiction annex applies and is provided on request at privacy@cambra.global. For EU Member States and EEA countries the substance of this Agreement is unchanged (the GDPR applies directly); only the complementary national law, the supervisory authority, the governing law and the binding language change. For countries with their own adequate law (Switzerland, Andorra) the corresponding inclusion clause applies and replaces the references to the GDPR." },
    { title: "Status of this document", content: "This is version 1.0 of the Agreement. Its legal review status is tracked internally and this text may be amended; material changes are notified with at least 30 days' advance notice in accordance with the Terms & Conditions. For any question about this Agreement: privacy@cambra.global." },
  ],
};
