// LEGAL-1 (2026-07-24) — English master text. FR/ES are translations.
// Changes vs previous version: "EU-based infrastructure" claim removed from §1
// (not demonstrable); former §9 "Network directory" removed (feature deprecated,
// route redirects home); sections renumbered. [REVISIÓN JURÍDICA] markers are
// listed in src/docs/Decision_Log_LEGAL1.md.
// REFERRAL-1 (2026-08-03) — new §8 "Referral discount programme"; former §8-15
// renumbered to §9-16. §9 (provider program, formerly §8) untouched in substance.

export default {
  badge: "Legal",
  title: "Terms & Conditions.",
  lastUpdated: "Last updated: 3 August 2026",
  back: "Back",
  sections: [
    { title: "1. Publisher & legal identity", content: "The CAMBRA platform is published by CAMBRA GLOBAL SASU, a French société par actions simplifiée unipersonnelle registered under SIREN 105 452 916, with registered office at 42 rue Vivienne, 75002 Paris, France. Contact: support@cambra.global. Publication director: the legal representative of CAMBRA GLOBAL SASU. Hosting is provided by Base44." },
    { title: "2. Acceptance", content: "By accessing or using the CAMBRA platform, you agree to be bound by these Terms & Conditions. If you do not agree, do not use the platform. CAMBRA reserves the right to update these terms with reasonable advance notice (at least 30 days for material changes) communicated by email and in-app notification." },
    { title: "3. Platform purpose", content: "CAMBRA provides payment-cost analysis, benchmarking and recovery services for independent commerce brands, covering both online and in-store card payments. The platform is intended for business use only (B2B). You must be at least 18 years old and duly authorized to represent the brand or entity you register on behalf of." },
    { title: "4. Audit outputs & estimates", content: "All Analyzer outputs, payment savings estimates and benchmark comparisons are estimates derived from your inputs and the CAMBRA network dataset. They are operational guidance — not financial, legal, accounting or fiscal advice. CAMBRA does not guarantee any specific savings outcome. Always consult qualified advisors before material decisions." },
    { title: "5. Data ownership & licence", content: "You retain full ownership of all data you submit. By using the platform, you grant CAMBRA a limited, worldwide, non-exclusive, revocable licence to process that data for the sole purpose of delivering the service. Aggregated and fully anonymized data (from which no individual brand can be re-identified) may be used to improve benchmarks. We will never share identifiable data with third parties without your explicit consent, except as required by law." },
    { title: "6. Pricing — free audit", content: "Access to the Analyzer, benchmarks, scoring and dashboard is currently offered free of charge to early-partner brands. No credit card is required. CAMBRA may introduce paid tiers in the future with at least 30 days' advance notice; early partners will be honoured under their original commercial conditions for a reasonable transition period." },
    { title: "7. Recovery service — success fee", content: "If you opt in to the Recovery service, CAMBRA acts on your behalf to renegotiate your card-payment rates — online (PSP) and in-store (TPV / physical terminal) — with your current provider, or migrate you to a better one where relevant. The fee is 25% of verified payment savings, calculated over a 24-month agreement from the moment savings become measurable on your real PSP or provider statements. Key rules: (a) no upfront fee, no subscription, no minimum; (b) if no verified savings are recovered, you owe nothing; (c) 'verified savings' means the delta between your baseline effective rate and your new effective rate, evidenced by actual PSP or TPV provider statements reconciled by CAMBRA; (d) after the 24-month agreement, 100% of ongoing savings stay with you; (e) the specific terms of each recovery mandate are formalized in a separate written mandate signed before any negotiation is undertaken." },
    { title: "8. Referral discount programme", content: "CAMBRA operates a referral programme that reduces the success fee defined in Section 7. Mechanism: (a) the standard success fee is 25% of verified savings; (b) for each referred business that becomes an activated referral, your own success fee is reduced by 5 percentage points, with no limit on the number of businesses you may refer; (c) the reduction is cumulative across activated referrals but is subject to an absolute floor of 5% — your fee will never fall below 5% of verified savings; (d) a business referred through your link enters at 20% instead of 25% — a single-step entry reduction that is not obtained again through its own referrals, which are governed by point (b) for that business. Definition — 'activated referral': a referred business that has reached verified savings within the meaning of Section 7(c), i.e. savings that are measurable and evidenced by its actual provider statements as reconciled by CAMBRA, and whose recovery has been activated. Registration, completing an analysis, opening an account or clicking a referral link do not, individually or together, constitute an activated referral. Persistence: once a reduction has been obtained, it is permanent for the remainder of your own 24-month agreement, including where the referred business subsequently terminates its service, revokes its mandate or ceases activity for any reason; a reduction already acquired is never reversed. Temporal scope: each reduction applies to success fees invoiced from the month following the verified activation of the corresponding referral. It is not retroactive and does not give rise to any credit, rebate or recalculation of fees already invoiced. Non-cumulative with other discounts: referral reductions do not combine with any other commercial discount, promotion or negotiated fee, save for the reductions of this programme, which do combine with each other up to the 5% floor. No cash consideration: CAMBRA pays no money, commission, revenue share or benefit in kind for referring a business. The sole benefit of the programme is the reduction of your own success fee. Accordingly, referring a business under this programme does not make you an agent, broker, intermediary or remunerated introducer of CAMBRA, and creates no entitlement to remuneration of any kind. CAMBRA may amend or discontinue the programme for future referrals with 30 days' notice; reductions already acquired remain governed by the persistence rule above." },
    { title: "9. Provider program", content: "CAMBRA operates a two-tier provider program described on our For Providers page (/ForProviders). Tier 1 (Listed) covers payment providers whose public pricing enters our achievable benchmark — no fee, no exclusivity, no compensation flows either way. Tier 2 (Partner) covers payment providers who offer an exclusive rate for merchants introduced through CAMBRA in exchange for a referral arrangement; when we present a Partner offer to a merchant it is labeled as a CAMBRA-exclusive offer, visually and semantically separate from our public benchmark. Our public benchmark is never influenced by Partner arrangements: CAMBRA always recommends the option that saves the brand the most, whether the winning anchor is Listed, Partner, or the merchant's existing provider. The specific commercial terms of each partnership are formalized in a signed agreement and disclosed to any interested provider upon written request to support@cambra.global." },
    { title: "10. Acceptable use", content: "You agree not to: reverse-engineer the platform, scrape benchmark data, misrepresent your brand, upload unlawful content, attempt to access another user's data, or use CAMBRA to build a directly competing service. Violations may result in immediate suspension without refund." },
    { title: "11. Intellectual property", content: "The CAMBRA platform, brand, methodology, benchmarks and software are the exclusive property of CAMBRA GLOBAL SASU. No provision of these Terms transfers any intellectual property right to you, except the limited licence to use the service." },
    { title: "12. Limitation of liability", content: "To the maximum extent permitted by French law, CAMBRA is not liable for indirect, incidental, special or consequential damages arising from use of the platform. Total aggregate liability is capped at the greater of (a) the amounts paid by you to CAMBRA in the twelve months preceding the claim, or (b) €5,000. Nothing in these Terms limits liability for gross negligence, wilful misconduct or death/personal injury." },
    { title: "13. Withdrawal (B2B)", content: "The platform is a professional B2B service. The 14-day consumer withdrawal right under the French Consumer Code does not apply. You may nevertheless terminate your account at any time from Account settings under Section 14 below." },
    { title: "14. Termination", content: "You may terminate your account at any time from Account settings. Ongoing recovery mandates continue under their existing terms unless the mandate itself is revoked in writing. CAMBRA may suspend or terminate access for material violations of these terms or for prolonged inactivity (>24 months). Upon termination, your data is handled according to our Privacy Policy." },
    { title: "15. Governing law & jurisdiction", content: "These Terms are governed by French law. Any dispute will first be addressed through good-faith negotiation. If unresolved within 60 days, the parties may resort to mediation (CMAP, Paris). Failing amicable resolution, exclusive jurisdiction lies with the competent commercial courts of Paris, France." },
    { title: "16. Contact", content: "For any contractual question: support@cambra.global. For legal notices: 42 rue Vivienne, 75002 Paris, France." },
  ],
};