// LEGAL-1 (2026-07-24) — English master text. FR/ES are translations.
// Changes vs previous version: "EU-based infrastructure" claim removed from §1
// (not demonstrable); former §9 "Network directory" removed (feature deprecated,
// route redirects home); sections renumbered. [REVISIÓN JURÍDICA] markers are
// listed in src/docs/Decision_Log_LEGAL1.md.

export default {
  badge: "Legal",
  title: "Terms & Conditions.",
  lastUpdated: "Last updated: 24 July 2026",
  back: "Back",
  sections: [
    { title: "1. Publisher & legal identity", content: "The CAMBRA platform is published by CAMBRA GLOBAL SASU, a French société par actions simplifiée unipersonnelle registered under SIREN 105 452 916, with registered office at 42 rue Vivienne, 75002 Paris, France. Contact: support@cambra.global. Publication director: the legal representative of CAMBRA GLOBAL SASU. Hosting is provided by Base44." },
    { title: "2. Acceptance", content: "By accessing or using the CAMBRA platform, you agree to be bound by these Terms & Conditions. If you do not agree, do not use the platform. CAMBRA reserves the right to update these terms with reasonable advance notice (at least 30 days for material changes) communicated by email and in-app notification." },
    { title: "3. Platform purpose", content: "CAMBRA provides payment-cost analysis, benchmarking and recovery services for independent commerce brands, covering both online and in-store card payments. The platform is intended for business use only (B2B). You must be at least 18 years old and duly authorized to represent the brand or entity you register on behalf of." },
    { title: "4. Audit outputs & estimates", content: "All Analyzer outputs, payment savings estimates and benchmark comparisons are estimates derived from your inputs and the CAMBRA network dataset. They are operational guidance — not financial, legal, accounting or fiscal advice. CAMBRA does not guarantee any specific savings outcome. Always consult qualified advisors before material decisions." },
    { title: "5. Data ownership & licence", content: "You retain full ownership of all data you submit. By using the platform, you grant CAMBRA a limited, worldwide, non-exclusive, revocable licence to process that data for the sole purpose of delivering the service. Aggregated and fully anonymized data (from which no individual brand can be re-identified) may be used to improve benchmarks. We will never share identifiable data with third parties without your explicit consent, except as required by law." },
    { title: "6. Pricing — free audit", content: "Access to the Analyzer, benchmarks, scoring and dashboard is currently offered free of charge to early-partner brands. No credit card is required. CAMBRA may introduce paid tiers in the future with at least 30 days' advance notice; early partners will be honoured under their original commercial conditions for a reasonable transition period." },
    { title: "7. Recovery service — success fee", content: "If you opt in to the Recovery service, CAMBRA acts on your behalf to renegotiate your card-payment rates — online (PSP) and in-store (TPV / physical terminal) — with your current provider, or migrate you to a better one where relevant. The fee is 25% of verified payment savings, calculated over a 24-month agreement from the moment savings become measurable on your real PSP or provider statements. Key rules: (a) no upfront fee, no subscription, no minimum; (b) if no verified savings are recovered, you owe nothing; (c) 'verified savings' means the delta between your baseline effective rate and your new effective rate, evidenced by actual PSP or TPV provider statements reconciled by CAMBRA; (d) after the 24-month agreement, 100% of ongoing savings stay with you; (e) the specific terms of each recovery mandate are formalized in a separate written mandate signed before any negotiation is undertaken." },
    { title: "8. Provider program", content: "CAMBRA operates a two-tier provider program described on our For Providers page (/ForProviders). Tier 1 (Listed) covers payment providers whose public pricing enters our achievable benchmark — no fee, no exclusivity, no compensation flows either way. Tier 2 (Partner) covers payment providers who offer an exclusive rate for merchants introduced through CAMBRA in exchange for a referral arrangement; when we present a Partner offer to a merchant it is labeled as a CAMBRA-exclusive offer, visually and semantically separate from our public benchmark. Our public benchmark is never influenced by Partner arrangements: CAMBRA always recommends the option that saves the brand the most, whether the winning anchor is Listed, Partner, or the merchant's existing provider. The specific commercial terms of each partnership are formalized in a signed agreement and disclosed to any interested provider upon written request to support@cambra.global." },
    { title: "9. Acceptable use", content: "You agree not to: reverse-engineer the platform, scrape benchmark data, misrepresent your brand, upload unlawful content, attempt to access another user's data, or use CAMBRA to build a directly competing service. Violations may result in immediate suspension without refund." },
    { title: "10. Intellectual property", content: "The CAMBRA platform, brand, methodology, benchmarks and software are the exclusive property of CAMBRA GLOBAL SASU. No provision of these Terms transfers any intellectual property right to you, except the limited licence to use the service." },
    { title: "11. Limitation of liability", content: "To the maximum extent permitted by French law, CAMBRA is not liable for indirect, incidental, special or consequential damages arising from use of the platform. Total aggregate liability is capped at the greater of (a) the amounts paid by you to CAMBRA in the twelve months preceding the claim, or (b) €5,000. Nothing in these Terms limits liability for gross negligence, wilful misconduct or death/personal injury." },
    { title: "12. Withdrawal (B2B)", content: "The platform is a professional B2B service. The 14-day consumer withdrawal right under the French Consumer Code does not apply. You may nevertheless terminate your account at any time from Account settings under Section 13 below." },
    { title: "13. Termination", content: "You may terminate your account at any time from Account settings. Ongoing recovery mandates continue under their existing terms unless the mandate itself is revoked in writing. CAMBRA may suspend or terminate access for material violations of these terms or for prolonged inactivity (>24 months). Upon termination, your data is handled according to our Privacy Policy." },
    { title: "14. Governing law & jurisdiction", content: "These Terms are governed by French law. Any dispute will first be addressed through good-faith negotiation. If unresolved within 60 days, the parties may resort to mediation (CMAP, Paris). Failing amicable resolution, exclusive jurisdiction lies with the competent commercial courts of Paris, France." },
    { title: "15. Contact", content: "For any contractual question: support@cambra.global. For legal notices: 42 rue Vivienne, 75002 Paris, France." },
  ],
};