import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
import { requireAdminOrInternal } from '../../shared/internalGate.ts';
import { isBusinessHour, policyIsActive, sanitizeExternalText } from '../../shared/commercialAutonomy.ts';
import { callCambraClaude } from '../../shared/commercialModelRouter.ts';

async function claude(prompt:string){return (await callCambraClaude(prompt,{tier:'standard',maxTokens:1200})).text}
function parse(t:string){const c=t.replace(/```json\s*/gi,'').replace(/```/g,'').trim();try{return JSON.parse(c)}catch{}const m=c.match(/\{[\s\S]*\}/);if(m){try{return JSON.parse(m[0])}catch{}}return null}

Deno.serve(async(req)=>{let task:any=null;try{
 const base44=createClientFromRequest(req);const body=await req.json().catch(()=>({}));const gate=await requireAdminOrInternal(req,base44,body);if(!gate.ok)return gate.response;const svc=base44.asServiceRole;
 const now=new Date();const manualOverride=gate.isAdmin&&body?.manual_override===true;task=await svc.entities.AgentTask.create({brand_id:'_platform',agent_name:'commercial_followup_worker',task_type:'due_followups',status:'running',requires_approval:false,risk_level:3,input_summary:'Due acquisition/provider follow-up sweep',started_at:now.toISOString()});
 const dueFollowups=await svc.entities.CommunicationThread.filter({status:'awaiting_counterparty',automation_paused:false,next_action_at:{$lte:now.toISOString()}},'next_action_at',100).catch(()=>[]);const dueReplies=await svc.entities.CommunicationThread.filter({status:'awaiting_cambra',automation_paused:false,next_action_at:{$lte:now.toISOString()}},'next_action_at',100).catch(()=>[]);const due=[...dueReplies,...dueFollowups].filter((x:any,i:number,a:any[])=>a.findIndex(y=>y.id===x.id)===i);let sent=0,closed=0,skipped=0;const failures:any[]=[];
 for(const thread of due){
   const policies=await svc.entities.CommercialPolicy.filter({policy_key:thread.policy_key,status:'active'},'-approved_at',5).catch(()=>[]);const policy=policies.find((p:any)=>p.version===thread.policy_version&&policyIsActive(p))||null;if(!policy||(!manualOverride&&!isBusinessHour(policy,now))){skipped++;continue;}
   const messages=await svc.entities.CommunicationMessage.filter({thread_id:thread.id},'-created_date',30).catch(()=>[]);const lastInbound=messages.find((m:any)=>m.direction==='inbound');const lastOutbound=messages.find((m:any)=>m.direction==='outbound');if(lastInbound&&(!lastOutbound||Date.parse(lastInbound.received_at||lastInbound.created_date||0)>Date.parse(lastOutbound.sent_at||lastOutbound.created_date||0))){const internal=Deno.env.get('INTERNAL_CALL_SECRET')||'';const rr=await svc.functions.invoke('commercialReplyAgent',{thread_id:thread.id,message_id:lastInbound.id,internal_secret:internal}).catch((e:any)=>({data:{ok:false,error:String(e?.message||e)}}));const rd=rr?.data||rr||{};if(rd.ok===false)failures.push({thread_id:thread.id,error:rd.error||'reply_processing_failed'});else skipped++;continue;}
   const followups=messages.filter((m:any)=>m.direction==='outbound'&&m.raw_event_json?.followup_step).length;const max=Math.max(0,Math.min(Number(policy.max_followups||0),5));
   if(followups>=max){await svc.entities.CommunicationThread.update(thread.id,{status:'closed',automation_paused:true,pause_reason:'followup_sequence_complete',next_action_at:null});closed++;continue;}
   const step=followups+1;const transcript=[...messages].reverse().slice(-8).map((m:any)=>({direction:m.direction,subject:m.subject,text:String(m.text_body||'').slice(0,1800)}));
   const engine=thread.engine;const prompt=[`Write follow-up #${step} for CAMBRA ${engine}.`,'Use the actual thread. Do not invent facts, savings, fees, provider answers, people or authority. Keep the same language. No “just following up”, no fake urgency, no generic enthusiasm. Max 60 words. For provider negotiation, ask only for the pending pricing/clarification/contract response; never accept anything. Return ONLY JSON {"subject":"...","body":"..."}.','THREAD:',JSON.stringify(transcript)].join('\n');const draft=parse(await claude(prompt));if(!draft?.subject||!draft?.body){failures.push({thread_id:thread.id,error:'draft_unparseable'});continue;}
   const intervals=Array.isArray(policy.followup_intervals_hours)?policy.followup_intervals_hours:[];const nextHours=Number(intervals[step]||intervals[intervals.length-1]||120);const next=new Date(Date.now()+Math.max(24,nextHours)*3600000).toISOString();const internal=Deno.env.get('INTERNAL_CALL_SECRET')||'';
   const r=await svc.functions.invoke('commercialSendMessage',{thread_id:thread.id,action:'follow_up',classification:'follow_up',subject:sanitizeExternalText(draft.subject,300),text:sanitizeExternalText(draft.body,5000),agent_name:'commercial_followup_worker',idempotency_key:`followup:${thread.id}:${step}:${thread.policy_version}`,next_action_at:step>=max?null:next,internal_secret:internal}).catch((e:any)=>({data:{ok:false,error:String(e?.message||e)}}));const rd=r?.data||r||{};if(rd.ok===false){failures.push({thread_id:thread.id,error:rd.error});continue;}
   const created=await svc.entities.CommunicationMessage.get(rd.message_id).catch(()=>null);if(created)await svc.entities.CommunicationMessage.update(created.id,{raw_event_json:{...(created.raw_event_json||{}),followup_step:step}}).catch(()=>null);if(step>=max)await svc.entities.CommunicationThread.update(thread.id,{next_action_at:null});sent++;
 }
 await svc.entities.AgentTask.update(task.id,{status:'completed',output_summary:`Due follow-ups: ${sent} sent, ${closed} closed, ${skipped} skipped, ${failures.length} failed`,output_payload_json:{due:due.length,sent,closed,skipped,failures:failures.slice(0,20)},completed_at:new Date().toISOString()});return Response.json({ok:true,task_id:task.id,due:due.length,sent,closed,skipped,failed:failures.length});
}catch(error){console.error('commercialFollowUpWorker failed',error);if(task?.id){try{const b=createClientFromRequest(req);await b.asServiceRole.entities.AgentTask.update(task.id,{status:'failed',error:'commercial_followup_failed',completed_at:new Date().toISOString()})}catch{}}return Response.json({ok:false,error:'commercial_followup_failed',task_id:task?.id||null},{status:500})}});
