import { safeBestEffort } from '../../shared/bestEffort.ts';
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
const PLATFORM = '_platform';
const ALLOWED = new Set(['founderCopilotAgent','investorUpdateAgent','qaAgent','leadDiscoveryAgent','leadEnrichmentAgent','leadScoringAgent','crmAgent','outreachAgent','followUpAgent','meetingAgent','blogAgent','newsletterAgent','linkedinAgent','xTwitterAgent','seoAgent','competitorMonitorAgent','providerResearchAgent','providerMonitorAgent','gdprAgent','complianceAgent','legalReviewAgent','contractIPAgent','codeReviewAgent','securityAgent','qaMonitorAgent','engineeringReportAgent','fixValidatorAgent','discoveryTechStackAgent','spendIntelligenceAgent','recommendationEngineAgent','brainOrchestrator']);
const SAFE_BATCH=['qaMonitorAgent','providerMonitorAgent','gdprAgent','complianceAgent'];
Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req); const user = await base44.auth.me().catch((error:any)=>safeBestEffort(error,{operation:'adminAgentOperations',fallback:null,severity:'secondary'}));
  if (!user) return Response.json({ ok: false, error: 'Unauthorized' }, { status: 401 });
  if (user.role !== 'admin') return Response.json({ ok: false, error: 'Forbidden' }, { status: 403 });
  const body = await req.json().catch(() => ({})); const action = String(body?.action || 'status'); const svc = base44.asServiceRole;
  if (action === 'status') { const tasks = await svc.entities.AgentTask.list('-created_date', 5000, 0, ['id','agent_name','task_type','status','output_summary','error','created_date','started_at','completed_at']).catch((error:any)=>safeBestEffort(error,{operation:'adminAgentOperations',fallback:[],severity:'secondary'})); const latest: Record<string, any> = {}; for (const t of tasks) if (t.agent_name && !latest[t.agent_name]) latest[t.agent_name] = t; return Response.json({ ok: true, latest, recent: tasks.slice(0, 80) }); }
  if (action === 'run') { const functionName = String(body?.function_name || ''); if (!ALLOWED.has(functionName)) return Response.json({ ok: false, error: 'agent_not_allowlisted' }, { status: 400 }); const args = body?.args && typeof body.args === 'object' ? body.args : {}; let result:any=null;let invokeError:any=null;try{const invoked=await svc.functions.invoke(functionName,args);result=invoked?.data??invoked??null;}catch(error:any){invokeError=error;result=error?.response?.data??error?.data??null;}const ok=!invokeError && result?.ok !== false;const errorCode=String(result?.error||invokeError?.message||'agent_run_failed');await svc.entities.OperationalLog.create({ brand_id: PLATFORM, event_type: ok ? 'status_changed' : 'error', message: 'admin_agent_manual_run', metadata_json: { function_name: functionName, requested_by: user.email || user.id || 'admin', ok, error:ok?null:errorCode.slice(0,160) } }).catch((error:any)=>safeBestEffort(error,{operation:'adminAgentOperations',fallback:null,severity:'secondary'})); return Response.json({ ok, function_name: functionName, result, error: ok ? null : errorCode }, { status: ok ? 200 : 502 }); }
  if(action==='run_safe_batch'){const results=[];for(const functionName of SAFE_BATCH){try{const result=await svc.functions.invoke(functionName,{});results.push({function_name:functionName,ok:(result?.data??result)?.ok!==false,result:result?.data??result??null});}catch(error:any){results.push({function_name:functionName,ok:false,error:String(error?.message||error).slice(0,160)});}}await svc.entities.OperationalLog.create({brand_id:PLATFORM,event_type:'status_changed',message:'admin_safe_agent_batch_run',metadata_json:{functions:SAFE_BATCH,requested_by:user.email||user.id||'admin',results:results.map((row:any)=>({function_name:row.function_name,ok:row.ok}))}}).catch((error:any)=>safeBestEffort(error,{operation:'adminAgentOperations',fallback:null,severity:'secondary'}));return Response.json({ok:results.every((row:any)=>row.ok),safe_batch:true,results});}
  return Response.json({ ok: false, error: 'unsupported_action' }, { status: 400 });
});
