import { createClientFromRequest } from 'npm:@base44/sdk@0.8.41';
import { requireAdminOrInternal } from '../../shared/internalGate.ts';
import { normalizeEmail, sanitizeExternalText } from '../../shared/commercialAutonomy.ts';
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/i;const TITLES=['account manager','enterprise account executive','sales director','partnerships','business development','payments','commercial'];
function valid(email:any){const e=normalizeEmail(email);return EMAIL.test(e)&&!e.endsWith('@example.test')?e:''}
async function apollo(provider:any){const key=Deno.env.get('APOLLO_API_KEY');if(!key)return[];const payload:any={page:1,per_page:20,person_titles:TITLES};if(provider.website)payload.q_organization_domains_list=[String(provider.website).replace(/^https?:\/\//,'').split('/')[0]];else payload.q_organization_name=provider.name;const r=await fetch('https://api.apollo.io/api/v1/mixed_people/api_search',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)return[];return(Array.isArray(d.people)?d.people:[]).map((p:any)=>({name:p.name||'',email:valid(p.email),title:p.title||'',source:'apollo',source_reference:String(p.id||''),confidence:p.email?'medium':'low',evidence:{apollo_id:p.id||null,linkedin_url:p.linkedin_url||null,organization:p.organization?.name||null}})).filter((x:any)=>x.email)}
async function publicResearch(provider:any){const key=Deno.env.get('PERPLEXITY_API_KEY');if(!key)return[];const prompt=`Find publicly verifiable B2B commercial/contact emails for ${provider.name}, specifically payments/merchant acquiring/account management/partnerships/sales in Europe. Return ONLY JSON array [{"name":"","email":"","title":"","source_url":""}]. Do not infer or guess email patterns. Only include an email if explicitly present in a public source.`;const r=await fetch('https://api.perplexity.ai/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:'sonar-pro',messages:[{role:'user',content:prompt}],max_tokens:1200})});const d=await r.json().catch(()=>({}));if(!r.ok)return[];let t=String(d?.choices?.[0]?.message?.content||'').replace(/```json\s*/gi,'').replace(/```/g,'').trim();let arr:any=[];try{arr=JSON.parse(t)}catch{const m=t.match(/\[[\s\S]*\]/);if(m)try{arr=JSON.parse(m[0])}catch{}}return(Array.isArray(arr)?arr:[]).map((x:any)=>({name:sanitizeExternalText(x.name,200),email:valid(x.email),title:sanitizeExternalText(x.title,200),source:'public_research',source_reference:sanitizeExternalText(x.source_url,1000),confidence:'medium',evidence:{source_url:x.source_url||null}})).filter((x:any)=>x.email)}
Deno.serve(async(req)=>{try{const base44=createClientFromRequest(req);const body=await req.json().catch(()=>({}));const gate=await requireAdminOrInternal(req,base44,body);if(!gate.ok)return gate.response;const svc=base44.asServiceRole;const provider=await svc.entities.Provider.get(String(body?.provider_id||'')).catch(()=>null);if(!provider)return Response.json({ok:false,error:'provider_required'},{status:404});const brandId=String(body?.brand_id||'');const recoverId=String(body?.recover_id||'');const candidates:any[]=[];
// 1) Merchant-specific relationship evidence already learned by CAMBRA.
const merchantRows=brandId?await svc.entities.ProviderContact.filter({provider_id:provider.id,brand_id:brandId,active:true},'-last_verified_at',50).catch(()=>[]):[];for(const c of merchantRows)candidates.push({...c,rank:100});
// 2) Explicit addresses present in merchant-owned provider documents/notes. Never infer an address.
if(brandId){const docs=await svc.entities.Document.filter({owner_type:'brand',owner_id:brandId},'-uploaded_at',100).catch(()=>[]);const providerNeedle=String(provider.name||'').toLowerCase();for(const d of docs){const hay=[d.title,...(Array.isArray(d.tags)?d.tags:[])].join(' ').toLowerCase();if(providerNeedle&& !hay.includes(providerNeedle))continue;const text=String(d.notes||'');for(const m of text.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)){const email=valid(m[0]);if(email)candidates.push({name:'',email,title:'',source:'merchant_relationship',source_reference:d.id,confidence:'high',merchant_specific:true,validated:true,evidence:{document_id:d.id,category:d.category||null},rank:98});}}}
const crm=valid(provider.contact_email);if(crm)candidates.push({name:provider.account_manager||'',email:crm,title:'',source:'provider_crm',source_reference:provider.id,confidence:'high',merchant_specific:false,validated:true,rank:90});const directory=await svc.entities.ProviderContact.filter({provider_id:provider.id,active:true},'-last_verified_at',100).catch(()=>[]);for(const c of directory)if(!candidates.some(x=>x.email===c.email))candidates.push({...c,rank:c.source==='provider_referral'?95:80});if(!candidates.length||body?.refresh===true){for(const c of await apollo(provider))candidates.push({...c,rank:60});if(!candidates.some(x=>x.rank>=60))for(const c of await publicResearch(provider))candidates.push({...c,rank:50});}candidates.sort((a,b)=>(b.rank||0)-(a.rank||0));const best=candidates.find(c=>valid(c.email));if(!best)return Response.json({ok:false,error:'provider_contact_unresolved',provider_id:provider.id,searched:{merchant_relationship:true,provider_crm:true,apollo:!!Deno.env.get('APOLLO_API_KEY'),public_research:!!Deno.env.get('PERPLEXITY_API_KEY')}},{status:409});const email=valid(best.email);const existing=await svc.entities.ProviderContact.filter({provider_id:provider.id,email,active:true},'-created_date',1).catch(()=>[]);let row=existing[0]||null;const now=new Date().toISOString();if(!row)row=await svc.entities.ProviderContact.create({provider_id:provider.id,provider_name:provider.name,brand_id:brandId||null,recover_id:recoverId||null,name:best.name||'',email,title:best.title||'',department:'commercial',source:best.source||'manual',source_reference:best.source_reference||'',source_evidence_json:best.evidence||{},confidence:best.confidence||'medium',merchant_specific:Boolean(best.merchant_specific||brandId&&best.source==='merchant_relationship'),validated:best.validated===true,active:true,last_verified_at:now});await svc.entities.Provider.update(provider.id,{contact_email:email,account_manager:best.name||provider.account_manager||'',contact_resolution_status:'resolved'}).catch(()=>null);return Response.json({ok:true,provider_id:provider.id,contact:{id:row.id,email,name:row.name||best.name||'',source:row.source||best.source,confidence:row.confidence||best.confidence,merchant_specific:!!row.merchant_specific}})}catch(error){console.error('providerContactResolver failed',error);return Response.json({ok:false,error:'provider_contact_resolution_failed'},{status:500})}});
