import { useEffect, useMemo, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { AlertTriangle, Calculator, CircleDollarSign, Gauge, RefreshCw, ShieldAlert, Target, TrendingUp } from 'lucide-react';

const money = (value) => value == null ? '—' : new Intl.NumberFormat(undefined,{ style:'currency',currency:'EUR',maximumFractionDigits:0 }).format(Number(value));
const pct = (v) => v == null ? '—' : `${Number(v).toFixed(1)}%`;
const channels = ['AI_OUTBOUND','PARTNERS','MERCHANT_REFERRALS','PAID_MEDIA','ORGANIC_SEO','ANALYZER_INBOUND','STRATEGIC_ECOSYSTEM','CROSS_SELL'];

function MetricCard({ label,figure,sub,icon:Icon }){return <div className="rounded-2xl border p-4 bg-card"><div className="flex items-center gap-2 text-muted-foreground"><Icon size={14}/><p className="text-[10px] uppercase font-black tracking-wide">{label}</p></div><p className="text-2xl font-black mt-2">{figure}</p>{sub&&<p className="text-[11px] text-muted-foreground mt-1">{sub}</p>}</div>}

export default function AdminGrowth(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[scenario,setScenario]=useState({ channel:'AI_OUTBOUND',metric_key:'CONVERSION_RATE',multiplier:1.2 }),[targetDraft,setTargetDraft]=useState(null);
  const invoke=async(payload={})=>{setBusy(true);setError('');try{const r=await base44.functions.invoke('getEuropeMarketsCommandCenter',{view:'growth',...payload}),d=r?.data||r;if(d?.ok===false)throw new Error(d.error);setData(d);return d}catch(e){setError(e?.message||'Growth command center failed');return null}finally{setBusy(false)}};
  useEffect(()=>{invoke()},[]);
  const path=data?.growth_path||{}; const currentGap=useMemo(()=>path.target_gaps?.find(x=>x.period_key===path.current_period_key)||path.target_gaps?.[0]||null,[path]); const currentForecast=useMemo(()=>path.forecasts?.find(x=>x.period_key===path.current_period_key)||path.forecasts?.[0]||null,[path]);
  const startTargetEdit=()=>{const t=(data?.target_registry||[]).find(x=>x.target_key===currentGap?.target_key)||(data?.target_registry||[])[0];if(t)setTargetDraft({...t})};
  const saveTarget=async()=>{if(!targetDraft)return;const saved=await invoke({action:'configure_target',...targetDraft,confirmation:'SAVE_GROWTH_TARGET'});if(saved?.ok){setTargetDraft(null);await invoke()}};
  const runScenario=()=>invoke({action:'run_scenario',scenario_key:`CUSTOM:${scenario.channel}:${scenario.metric_key}`,changes:[scenario]});
  return <div className="space-y-6 pb-12">
    <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><TrendingUp size={20}/><h1 className="text-xl font-black">Growth Path · Actual vs Plan</h1><span className="text-[10px] rounded-full border px-2 py-1">SHADOW · RECOMMEND ONLY</span><span className="text-[10px] rounded-full border px-2 py-1">{path.engine_version||'V1'}</span></div><p className="text-sm text-muted-foreground mt-2 max-w-4xl">Deterministic navigation across bookings, verified economic value, revenue and cash. Targets are editable plans; assumptions stay labelled; acquisition channel and business-line revenue are never double counted.</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>invoke()} className="h-9 px-3 rounded-lg border text-xs font-bold inline-flex items-center gap-2"><RefreshCw size={12} className={busy?'animate-spin':''}/>Refresh</button><button disabled={busy} onClick={()=>invoke({action:'recompute',confirmation:'RECOMPUTE_GROWTH_PATH'})} className="h-9 px-3 rounded-lg bg-foreground text-background text-xs font-black inline-flex items-center gap-2"><Calculator size={13}/>Recompute & snapshot</button></div></div>
    {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/5 p-3 text-sm">{error}</div>}
    {path.limitations?.length>0&&<div className="rounded-2xl border border-amber-500/30 bg-amber-500/5 p-4"><div className="flex gap-2 items-center font-black text-sm"><AlertTriangle size={15}/>Truth limitations</div><ul className="mt-2 space-y-1 text-xs text-muted-foreground">{path.limitations.map((x,i)=><li key={i}>• {x}</li>)}</ul></div>}

    <div className="grid grid-cols-2 lg:grid-cols-6 gap-3">
      <MetricCard label="Actual revenue" figure={money(path.actuals?.revenue)} sub="Operational evidence" icon={CircleDollarSign}/><MetricCard label={`${currentGap?.period_key||'Current'} target`} figure={money(currentGap?.target)} sub="Founder plan" icon={Target}/><MetricCard label="Base projection" figure={money(currentGap?.projected)} sub={currentForecast?.distribution?.status==='CALIBRATED_RANGE'?'Evidence-qualified P50 estimate':'Cold-start scenario'} icon={TrendingUp}/><MetricCard label="Projected gap" figure={money(currentGap?.projected_gap)} sub="Target minus projection" icon={Gauge}/><MetricCard label="Actual attainment" figure={pct(currentGap?.attainment_pct)} sub="Not target probability" icon={Target}/><MetricCard label="Target probability" figure={currentGap?.target_probability==null?'WITHHELD':pct(currentGap.target_probability*100)} sub={currentGap?.target_probability==null?'Needs qualified outcome evidence':'Evidence-qualified estimate; not a promise'} icon={ShieldAlert}/>
    </div>

    <section className="grid xl:grid-cols-[1.2fr_.8fr] gap-4">
      <div className="rounded-2xl border p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-black">Path by period</h2><p className="text-xs text-muted-foreground mt-1">Revenue target, actual and evidence-labelled scenario/estimate range. Quantile labels appear only when the backend marks the range evidence-qualified.</p></div><button onClick={startTargetEdit} className="text-xs font-bold border rounded-lg px-3 py-2">Edit current target</button></div><div className="overflow-auto mt-4"><table className="w-full min-w-[720px] text-xs"><thead><tr className="text-left text-muted-foreground border-b"><th className="py-2">Period</th><th>Target</th><th>Actual</th><th>Low{currentForecast?.distribution?.status==='CALIBRATED_RANGE'?' / P10':''}</th><th>Base{currentForecast?.distribution?.status==='CALIBRATED_RANGE'?' / P50':''}</th><th>High{currentForecast?.distribution?.status==='CALIBRATED_RANGE'?' / P90':''}</th><th>Gap</th><th>Confidence index</th></tr></thead><tbody>{(path.forecasts||[]).map(f=>{const g=(path.target_gaps||[]).find(x=>x.target_key===f.target_key),d=f.distribution||{};return <tr key={f.target_key} className="border-b last:border-0"><td className="py-3 font-black">{f.period_key}</td><td>{money(f.target_value)}</td><td>{money(g?.actual)}</td><td>{money(d.p10??d.low)}</td><td>{money(d.p50??d.base)}</td><td>{money(d.p90??d.high)}</td><td>{money(g?.projected_gap)}</td><td>{Math.round(Number(f.confidence||0)*100)}%</td></tr>})}</tbody></table></div></div>
      <div className="rounded-2xl border p-5"><div className="flex items-center gap-2"><ShieldAlert size={16}/><h2 className="font-black">Binding constraint</h2></div><p className="text-xl font-black mt-4">{path.binding_constraint?.type||'—'}</p><p className="text-sm text-muted-foreground mt-2">{path.binding_constraint?.effect||'No constraint result.'}</p><div className="space-y-2 mt-4">{(path.constraints||[]).slice(0,6).map(x=><div key={x.type} className="rounded-xl border p-3 flex items-center justify-between gap-3"><div><p className="text-xs font-black">{x.type}</p><p className="text-[11px] text-muted-foreground mt-1">{x.binding?'Binding':'Evidence warning'}</p></div><span className="text-xs font-black">{x.severity}/100</span></div>)}</div></div>
    </section>

    {data?.brief&&<section className="rounded-2xl border p-5"><h2 className="font-black">Founder morning brief</h2><p className="text-xs text-muted-foreground mt-1">Generated {new Date(data.brief.generated_at).toLocaleString()} from canonical evidence.</p><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-3 mt-4">{(data.brief.attention_json||[]).slice(0,8).map((x,i)=><div key={`${x.market}-${i}`} className="rounded-xl border p-3 text-xs"><b>{x.market} · {x.blocker}</b><p className="text-muted-foreground mt-1">{x.next_action}</p></div>)}</div></section>}

    {targetDraft&&<section className="rounded-2xl border p-5"><h2 className="font-black">Edit strategic target</h2><p className="text-xs text-muted-foreground mt-1">Saving creates a new active version and supersedes the prior target. It does not change forecasts, send limits or execution authority.</p><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mt-4"><label className="text-xs">Period<input value={targetDraft.period_key||''} onChange={e=>setTargetDraft({...targetDraft,period_key:e.target.value})} className="mt-1 w-full rounded-lg border bg-transparent p-2"/></label><label className="text-xs">Start<input type="date" value={targetDraft.period_start||''} onChange={e=>setTargetDraft({...targetDraft,period_start:e.target.value})} className="mt-1 w-full rounded-lg border bg-transparent p-2"/></label><label className="text-xs">End<input type="date" value={targetDraft.period_end||''} onChange={e=>setTargetDraft({...targetDraft,period_end:e.target.value})} className="mt-1 w-full rounded-lg border bg-transparent p-2"/></label><label className="text-xs">Metric<select value={targetDraft.metric_key||'REVENUE'} onChange={e=>setTargetDraft({...targetDraft,metric_key:e.target.value})} className="mt-1 w-full rounded-lg border bg-background p-2"><option>BOOKINGS</option><option>VERIFIED_ECONOMIC_VALUE</option><option>REVENUE</option><option>CASH</option></select></label><label className="text-xs">Target EUR<input type="number" min="0" value={targetDraft.target_value??''} onChange={e=>setTargetDraft({...targetDraft,target_value:Number(e.target.value)})} className="mt-1 w-full rounded-lg border bg-transparent p-2"/></label></div><div className="flex gap-2 mt-4"><button disabled={busy} onClick={saveTarget} className="rounded-lg bg-foreground text-background px-4 py-2 text-xs font-black">Save new version</button><button onClick={()=>setTargetDraft(null)} className="rounded-lg border px-4 py-2 text-xs font-bold">Cancel</button></div></section>}

    <section className="rounded-2xl border p-5"><div className="flex items-center gap-2"><Calculator size={16}/><h2 className="font-black">Scenario lab</h2></div><p className="text-xs text-muted-foreground mt-1">Temporary single-variable scenario. It never persists or executes unless explicitly saved through the governed API.</p><div className="grid md:grid-cols-4 gap-3 mt-4"><label className="text-xs">Channel<select value={scenario.channel} onChange={e=>setScenario({...scenario,channel:e.target.value})} className="mt-1 w-full rounded-lg border bg-background p-2">{channels.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs">Metric<select value={scenario.metric_key} onChange={e=>setScenario({...scenario,metric_key:e.target.value})} className="mt-1 w-full rounded-lg border bg-background p-2"><option>CONVERSION_RATE</option><option>ANNUAL_REACHABLE_VOLUME</option><option>AVERAGE_BOOKING_EUR</option><option>REVENUE_REALIZATION_RATE</option><option>CONTRIBUTION_MARGIN_RATE</option></select></label><label className="text-xs">Multiplier<input type="number" min="0" max="100" step="0.05" value={scenario.multiplier} onChange={e=>setScenario({...scenario,multiplier:Number(e.target.value)})} className="mt-1 w-full rounded-lg border bg-transparent p-2"/></label><div className="flex items-end"><button disabled={busy} onClick={runScenario} className="w-full rounded-lg border px-4 py-2 text-xs font-black">Run scenario</button></div></div></section>

    <section className="grid lg:grid-cols-2 gap-4"><div className="rounded-2xl border p-5"><h2 className="font-black">What CAMBRA recommends</h2><div className="space-y-3 mt-4">{(path.recommendations||[]).map(r=><div key={r.recommendation_key} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><p className="text-sm font-black">{r.action}</p><span className="text-[10px] rounded-full border px-2 py-1 h-fit">{r.authority}</span></div><p className="text-xs text-muted-foreground mt-2">{r.why}</p><div className="grid grid-cols-3 gap-2 mt-3 text-[11px]"><span>Cost {r.cost_eur==null?'—':money(r.cost_eur)}</span><span>Impact {r.expected_impact==null?'—':money(r.expected_impact)}</span><span>Execute: NO</span></div></div>)}</div></div><div className="rounded-2xl border p-5"><h2 className="font-black">Marginal allocation</h2><div className="space-y-3 mt-4">{(path.marginal_allocation||[]).slice(0,8).map(r=><div key={r.option_key} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><p className="text-xs font-black">{r.action}</p><span className="text-xs font-black">{r.marginal_return==null?'UNKNOWN':`${r.marginal_return}×`}</span></div><p className="text-[11px] text-muted-foreground mt-2">Cost {money(r.cost_eur)} · contribution {money(r.expected_incremental_contribution_eur)} · confidence {Math.round(Number(r.confidence||0)*100)}%</p></div>)}</div></div></section>

    <section className="rounded-2xl border overflow-auto"><div className="p-5"><h2 className="font-black">Europe · 33-market intelligence</h2><p className="text-xs text-muted-foreground mt-1">Intelligence remains available for every market. Commercial action uses only P10/P11-ready markets.</p></div><table className="w-full text-xs min-w-[900px]"><thead><tr className="text-left border-y text-muted-foreground"><th className="p-3">Market</th><th>Launch</th><th>Activation</th><th>Score</th><th>Maturity</th><th>Localization</th><th>Regulation</th><th>Production</th><th>Strategy</th><th>Next action</th></tr></thead><tbody>{(data?.markets||[]).map(x=><tr key={x.market_code} className="border-b last:border-0"><td className="p-3 font-black">{x.market_code}</td><td>{x.launch_state}</td><td>{x.activation_state}</td><td>{x.attractiveness_score==null?'UNRANKED':x.attractiveness_score}</td><td>T{x.data_maturity}</td><td>{x.localization_readiness?.translation_readiness||'UNKNOWN'}</td><td>{x.regulatory_readiness?.gate||'REVIEW'}</td><td>{x.production_readiness?.sealed?'SEALED':'BLOCKED'}</td><td>{x.strategy}</td><td>{x.next_action}</td></tr>)}</tbody></table></section>
    <section className="rounded-2xl border p-5"><h2 className="font-black">Authority, lineage & truth boundary</h2><div className="grid md:grid-cols-2 xl:grid-cols-5 gap-3 mt-3">{Object.entries(data?.truth_boundary||{}).map(([k,v])=><div key={k} className="rounded-xl border p-3"><p className="text-[10px] uppercase font-black text-muted-foreground">{k}</p><p className="text-xs mt-1">{String(v)}</p></div>)}</div><details className="mt-4"><summary className="text-xs font-black cursor-pointer">Show number lineage</summary><div className="grid md:grid-cols-2 gap-2 mt-3">{(path.lineage||[]).map(x=><div key={x.metric} className="rounded-xl border p-3 text-xs"><b>{x.metric}</b><p className="text-muted-foreground mt-1 break-all">{(x.sources||[]).join(' · ')||'No source evidence'}</p></div>)}</div></details></section>
  </div>
}
