import { useEffect, useMemo, useState } from 'react';
import { Bot, Play, RefreshCw, ShieldCheck } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { CLUSTERS } from '@/lib/agentRegistry';

const NAME = {
  founderCopilotAgent:'founder_copilot', investorUpdateAgent:'investor_update', qaAgent:'qa', leadDiscoveryAgent:'lead_discovery', leadEnrichmentAgent:'lead_enrichment', leadScoringAgent:'lead_scoring', crmAgent:'crm', outreachAgent:'outreach', followUpAgent:'follow_up', meetingAgent:'meeting', blogAgent:'blog', newsletterAgent:'newsletter', linkedinAgent:'linkedin', xTwitterAgent:'x_twitter', seoAgent:'seo', competitorMonitorAgent:'competitor_monitor', providerResearchAgent:'provider_research', providerMonitorAgent:'provider_monitor', gdprAgent:'gdpr', complianceAgent:'compliance', legalReviewAgent:'legal_review', contractIPAgent:'contract_ip', codeReviewAgent:'code_review', securityAgent:'security', qaMonitorAgent:'qa_monitor', engineeringReportAgent:'engineering_report', fixValidatorAgent:'fix_validator', discoveryTechStackAgent:'discovery_tech_stack', spendIntelligenceAgent:'spend_intelligence', recommendationEngineAgent:'recommendation_engine', brainOrchestrator:'brain_orchestrator', systemHealthAgent:'system_health',
};
const statusClass = (s) => s === 'completed' ? 'bg-emerald-500/10 text-emerald-700 border-emerald-500/20' : s === 'failed' ? 'bg-rose-500/10 text-rose-700 border-rose-500/20' : s ? 'bg-amber-500/10 text-amber-700 border-amber-500/20' : 'bg-secondary text-muted-foreground border-border';

export default function AdminAgents() {
  const [data, setData] = useState({ latest: {}, recent: [] }); const [loading, setLoading] = useState(true); const [running, setRunning] = useState(''); const [error, setError] = useState('');
  const agents = useMemo(() => CLUSTERS.flatMap(c => c.agents.map(a => ({ ...a, cluster: c.label }))), []);
  const load = async () => { setLoading(true); setError(''); try { const r = await base44.functions.invoke('adminAgentOperations', { action: 'status' }); setData(r?.data || r || { latest:{}, recent:[] }); } catch(e) { setError(e?.message || 'Could not load agent operations'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const run = async (fn) => { setRunning(fn); setError(''); try { await base44.functions.invoke('adminAgentOperations', { action:'run', function_name: fn, args:{} }); await load(); } catch(e) { setError(e?.message || `Could not run ${fn}`); } finally { setRunning(''); } };
  return <div className="space-y-6">
    <div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Bot size={18}/><h1 className="text-2xl font-black tracking-tight">AI Operations</h1></div><p className="text-xs text-muted-foreground mt-1">Admin control plane for CAMBRA agents. Manual runs are allowlisted and logged; external/financial effects still require their existing approval gates.</p></div><button onClick={load} disabled={loading} className="inline-flex items-center gap-2 h-8 px-3 rounded-lg border text-xs font-bold"><RefreshCw size={12} className={loading?'animate-spin':''}/>Refresh</button></div>
    <div className="rounded-2xl border bg-card p-4 flex items-center gap-3"><ShieldCheck size={18}/><div><p className="text-sm font-bold">Guardrail</p><p className="text-xs text-muted-foreground">This page can invoke only the fixed agent allowlist. It cannot call arbitrary backend functions or bypass Approval, ECL, billing or legal gates.</p></div></div>
    {error && <div className="rounded-xl border border-rose-300 bg-rose-50 p-3 text-xs text-rose-700">{error}</div>}
    {CLUSTERS.map(cluster => <section key={cluster.id} className="space-y-3"><div><h2 className="text-sm font-black">{cluster.label}</h2><p className="text-[11px] text-muted-foreground">{cluster.description}</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{cluster.agents.map(a => { const t = data.latest?.[NAME[a.fn]]; return <div key={a.fn} className="rounded-2xl border bg-card p-4 space-y-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{a.label}</p><p className="text-[11px] text-muted-foreground font-mono">{a.fn}</p></div><span className={`rounded-full border px-2 py-1 text-[10px] font-bold ${statusClass(t?.status)}`}>{t?.status || 'never run'}</span></div><p className="text-xs text-muted-foreground min-h-8">{a.description}</p><div className="text-[10px] text-muted-foreground">Risk L{a.risk} · {a.auto ? 'auto-capable' : 'manual/approval'}{t?.completed_at ? ` · last ${new Date(t.completed_at).toLocaleString()}` : ''}</div><button onClick={() => run(a.fn)} disabled={!!running} className="inline-flex items-center gap-1.5 h-8 px-3 rounded-lg bg-foreground text-background text-[11px] font-bold disabled:opacity-50"><Play size={11}/>{running===a.fn?'Running…':'Run now'}</button></div>; })}</div></section>)}
  </div>;
}
