import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, Bot, BrainCircuit, CheckCircle2, Clock3, Gauge, Landmark, Layers3, MessageSquare, RefreshCw, ShieldAlert, Sparkles, TrendingUp, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';

// COMMAND-C3 (2026-08-17) — Number(null) is 0 and Number.isFinite(0) is true, so
// these formatters used to render an honest `value: null` as "€0". A metric whose
// source could not be read must show an em dash, never a zero.
const known=n=>n!==null&&n!==undefined&&n!==''&&Number.isFinite(Number(n));
const eur=n=>known(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)): '—';
const num=n=>known(n)?new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Number(n)):'—';
const metricValue=m=>m?.unit?.startsWith?.('EUR')?eur(m.value):num(m?.value);
const riskTone=r=>String(r||'').toLowerCase()==='critical'?'border-rose-500/30 bg-rose-500/5':String(r||'').toLowerCase()==='high'?'border-orange-500/30 bg-orange-500/5':'border-border/60 bg-card';
function Metric({label,m,why=null,icon:Icon}){return <div className="rounded-2xl border border-border/60 bg-card p-4 min-w-0"><div className="flex items-center justify-between gap-2"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground font-bold truncate">{label}</p>{Icon&&<Icon size={13} className="text-muted-foreground shrink-0"/>}</div><p className="text-xl md:text-2xl font-black mt-2 tabular-nums truncate">{metricValue(m)}</p><div className="flex items-center justify-between gap-2 mt-2"><span className="text-[9px] uppercase text-muted-foreground" title={m?.unavailable_sources?.length?`Source unavailable: ${m.unavailable_sources.join(', ')}`:undefined}>{m?.unavailable_sources?.length?'source unavailable':(m?.confidence||'unknown')}</span>{why&&<Link to={`/admin/chat?ask=${encodeURIComponent(why)}`} className="text-[10px] font-bold underline">Why?</Link>}</div></div>}
export default function AdminCommand(){
 const [data,setData]=useState(null),[brief,setBrief]=useState(null),[coverage,setCoverage]=useState(null),[loading,setLoading]=useState(true),[briefLoading,setBriefLoading]=useState(false),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [r,c]=await Promise.all([base44.functions.invoke('getFounderOSCommandCenter',{}),base44.functions.invoke('getAdminOperationsCockpit',{}).catch(()=>({data:{ok:false,degraded_sources:['operations_cockpit_unavailable'],data_complete:false}}))]);const d=r?.data||r,cv=c?.data||c;if(d?.ok===false)throw new Error(d.error);setData(d);setCoverage(cv)}catch(e){setError(e?.message||'Founder OS failed to load')}finally{setLoading(false)}};
 const loadBrief=async()=>{setBriefLoading(true);try{const r=await base44.functions.invoke('founderChiefOfStaff',{});const d=r?.data||r;if(d?.ok!==false)setBrief(d)}catch{}finally{setBriefLoading(false)}};
 useEffect(()=>{load();loadBrief()},[]);
 if(loading&&!data)return <div className="p-8 text-sm text-muted-foreground">Loading CAMBRA Founder OS…</div>;
 const m=data?.metrics||{},b=brief?.brief,attention=data?.attention||[],risks=data?.risks||[],opp=data?.opportunities||[];
 return <div className="space-y-6 pb-10">
  {/* COMMAND-C3: the founder snapshot now reports its OWN coverage. This banner
      previously only covered the operations cockpit, so a failed Invoice read on
      the money metrics produced no warning at all. */}
  {data?.data_complete===false&&<div data-testid="snapshot-degraded" className="rounded-xl border border-rose-500/30 bg-rose-500/5 p-3 text-xs text-rose-700"><b>Canonical sources unavailable:</b> {(data.degraded_sources||['unknown source']).join(', ')}. Metrics that depend on them show <b>—</b>, not a zero. A missing read is not a value of zero.</div>}
  {coverage?.data_complete===false&&<div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-amber-700"><b>Data coverage degraded:</b> {(coverage.degraded_sources||['unknown source']).join(', ')}. Founder OS will not interpret missing reads as healthy zeroes.</div>}
  <section className="rounded-[28px] border border-white/10 bg-card/80 p-5 md:p-7 overflow-hidden relative"><div className="absolute inset-0 pointer-events-none bg-gradient-to-br from-white/[0.04] via-transparent to-transparent"/><div className="relative flex flex-col lg:flex-row lg:items-end justify-between gap-5"><div><div className="flex items-center gap-2 text-[10px] uppercase tracking-[.22em] text-muted-foreground font-black"><Gauge size={12}/> CAMBRA Global · Founder OS</div><h1 className="text-3xl md:text-4xl font-black tracking-tight mt-3">Run the company from here.</h1><p className="text-sm text-muted-foreground mt-2 max-w-2xl">Observe what matters, ask why, make material decisions and tell CAMBRA what to do. Routine operations stay autonomous underneath.</p></div><div className="flex gap-2"><Link to="/admin/chat" className="h-10 px-4 rounded-full bg-foreground text-background text-sm font-black inline-flex items-center gap-2"><MessageSquare size={14}/>Ask CAMBRA</Link><Link to="/admin/documentation?topic=emergency_controls" className="h-10 px-4 rounded-full border border-rose-500/30 text-xs font-black inline-flex items-center gap-2"><ShieldAlert size={13}/>Emergency</Link><button onClick={()=>{load();loadBrief()}} className="h-10 px-4 rounded-full border text-xs font-bold inline-flex items-center gap-2"><RefreshCw size={12} className={(loading||briefLoading)?'animate-spin':''}/>Refresh</button></div></div>
   <div className="relative mt-6 grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-2.5"><Metric label="Collected" m={m.collected_revenue} icon={Landmark} why="Why is collected revenue at this level?"/><Metric label="Verified savings" m={m.verified_savings} icon={CheckCircle2} why="Why are verified savings at this level?"/><Metric label="Active merchants" m={m.active_merchants} icon={Users}/><Metric label="Provider accrued" m={m.provider_accrued} icon={TrendingUp} why="Why is provider accrued revenue at this level?"/><Metric label="Aggregate addressable" m={m.aggregate_addressable} icon={Layers3} why="Why is aggregate addressable volume at this level?"/><Metric label="Aggregate committed" m={m.aggregate_committed} icon={Layers3}/><Metric label="Company health" m={m.company_health} icon={Gauge} why="Why is company health at this score?"/><Metric label="Needs you" m={m.founder_attention} icon={ShieldAlert}/></div>
   <div className="relative mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-muted-foreground"><span>Snapshot {data?.generated_at?new Date(data.generated_at).toLocaleString():'—'}</span><span>Health freshness {data?.freshness?.health_age_minutes==null?'unknown':`${Math.round(data.freshness.health_age_minutes)} min`}</span><span>Financial values derive from deterministic ledgers.</span></div>
  </section>

  <section className="grid xl:grid-cols-[1.15fr_.85fr] gap-4">
   <div className="rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Sparkles size={15}/><h2 className="text-sm font-black">Chief of Staff brief</h2></div><p className="text-[11px] text-muted-foreground mt-1">Evidence-bounded narrative. Unknowns stay unknown.</p></div><button onClick={loadBrief} disabled={briefLoading} className="text-[10px] font-bold underline">Regenerate</button></div>{b?<div className="mt-4"><div className="flex items-center gap-2"><span className={`w-2 h-2 rounded-full ${b.status==='critical'?'bg-rose-500':b.status==='attention'?'bg-amber-500':'bg-emerald-500'}`}/><p className="text-lg font-black">{b.headline}</p></div><div className="grid md:grid-cols-2 gap-2 mt-4">{[['Money',b.money],['Growth',b.growth],['Merchant value',b.merchant_value],['Aggregate',b.aggregate],['Providers',b.providers],['Operations',b.operations],['AI workforce',b.ai_workforce]].filter(([,v])=>v).map(([k,v])=><div key={k} className="rounded-xl border border-border/50 p-3"><p className="text-[10px] uppercase font-bold text-muted-foreground">{k}</p><p className="text-xs mt-1 leading-relaxed">{v}</p></div>)}</div>{b.unknowns?.length>0&&<p className="mt-3 text-[10px] text-muted-foreground">Unknown: {b.unknowns.join(' · ')}</p>}</div>:<div className="mt-5 rounded-xl border border-dashed p-6 text-xs text-muted-foreground">{briefLoading?'Generating evidence-bounded brief…':'Chief of Staff unavailable. Deterministic metrics above remain available.'}</div>}</div>
   <div className="rounded-2xl border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-black">What needs you</h2><p className="text-[11px] text-muted-foreground mt-1">Only founder-authority or strategically material items.</p></div><Link to="/admin/approvals" className="text-[10px] font-bold underline">All approvals</Link></div><div className="mt-3 space-y-2">{attention.length?attention.slice(0,7).map(x=><div key={x.id} className={`rounded-xl border p-3 ${riskTone(x.risk)}`}><div className="flex justify-between gap-3"><div className="min-w-0"><div className="flex gap-1.5 items-center"><span className="text-[9px] uppercase font-black text-muted-foreground">{x.type.replaceAll('_',' ')}</span>{x.financial_impact!=null&&<span className="text-[9px] font-bold">· {eur(x.financial_impact)}</span>}</div><p className="text-xs font-black mt-1 truncate">{x.title}</p><p className="text-[10px] text-muted-foreground mt-1 line-clamp-2">{x.summary}</p></div><span className="text-xs font-black shrink-0">{Math.round(x.priority||0)}</span></div><div className="flex gap-3 mt-2">{x.approval_id?<Link to="/admin/approvals" className="text-[10px] font-bold underline">Decide</Link>:<Link to="/admin/chat?ask=What%20should%20we%20do%20about%20this%20issue%3F" className="text-[10px] font-bold underline">Investigate</Link>}<Link to={`/admin/chat?ask=${encodeURIComponent(`Explain why this needs my attention: ${x.title}. Show evidence.`)}`} className="text-[10px] font-bold underline">Why?</Link></div></div>):<div className="rounded-xl border border-dashed p-6 text-center"><CheckCircle2 size={18} className="mx-auto mb-2"/><p className="text-xs font-bold">Nothing material needs you.</p><p className="text-[10px] text-muted-foreground mt-1">CAMBRA can keep operating under current policies.</p></div>}</div></div>
  </section>

  <section className="grid lg:grid-cols-3 gap-4"><div className="rounded-2xl border bg-card p-5 lg:col-span-2"><div className="flex items-center justify-between"><div><h2 className="text-sm font-black">Recommended actions</h2><p className="text-[11px] text-muted-foreground mt-1">Ranked signals; execution remains policy-governed.</p></div><Link to="/admin/chat?ask=What%20should%20I%20do%20today%3F" className="text-[10px] font-bold underline">Ask CAMBRA</Link></div><div className="grid md:grid-cols-2 gap-2 mt-3">{[...attention.slice(0,3).map(x=>({title:x.title,why:x.summary,action:x.ai_recommendation||'Review and decide',risk:x.risk})),...opp.slice(0,5).map(x=>({title:x.title,why:x.type,action:x.recommended_action,risk:x.risk}))].slice(0,8).map((x,i)=><div key={`${x.title}-${i}`} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><p className="text-xs font-bold">{x.title}</p><span className="text-[9px] uppercase text-muted-foreground">{x.risk||'—'}</span></div><p className="text-[10px] text-muted-foreground mt-1 line-clamp-2">{x.why}</p><p className="text-[10px] font-semibold mt-2">→ {x.action||'Inspect'}</p></div>)}</div></div><div className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><AlertTriangle size={14}/><h2 className="text-sm font-black">Risks</h2></div><div className="mt-3 space-y-2">{risks.length?risks.slice(0,7).map((r,i)=><div key={i} className="rounded-xl border p-3"><p className="text-xs font-bold">{r.title}</p><p className="text-[10px] text-muted-foreground mt-1">{r.impact||r.type}</p><p className="text-[10px] mt-1">Mitigation: {r.mitigation}</p></div>):<p className="text-xs text-muted-foreground">No surfaced cross-company risks.</p>}</div></div></section>

  <section className="grid md:grid-cols-2 xl:grid-cols-4 gap-3">{[
   {title:'Maintenance',body:`${data?.operations?.open_incidents||0} incidents · ${data?.operations?.delayed_migrations_gt_5d||0} migrations >5d`,Icon:Activity,to:'/admin/maintenance'},
   {title:'AI workforce',body:`${data?.ai_workforce?.task_count_7d||0} tasks/7d · ${data?.ai_workforce?.failed_7d||0} failed`,Icon:Bot,to:'/admin/agents'},
   {title:'Provider economics',body:`${eur(m.provider_accrued?.value)} accrued · ${eur(m.provider_outstanding?.value)} outstanding`,Icon:TrendingUp,to:'/admin/provider-economics'},
   {title:'Company intelligence',body:`${data?.counts?.pools||0} pools · ${data?.counts?.provider_attributions||0} provider attributions`,Icon:BrainCircuit,to:'/admin/intelligence'}
  ].map(({title,body,Icon,to})=><Link key={title} to={to} className="rounded-2xl border bg-card p-4 hover:bg-secondary/30 transition-colors"><div className="flex justify-between"><Icon size={15}/><ArrowRight size={12}/></div><p className="text-xs font-black mt-4">{title}</p><p className="text-[10px] text-muted-foreground mt-1">{body}</p></Link>)}</section>

  {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/5 p-3 text-xs text-rose-700">{error}</div>}
  <div className="flex items-center gap-2 text-[10px] text-muted-foreground"><Clock3 size={11}/>Founder OS sits above autonomous operations. It observes, explains and governs; it does not become a manual coordination layer.</div>
 </div>;
}
