import{createClientFromRequest}from'npm:@base44/sdk@0.8.41';import{MARKET_CAPABILITIES,POLICY_STATES}from'../../shared/jurisdictionPolicy.ts';
import{handleSeedP10RegulatoryControl}from'../seedP10RegulatoryControl/entry.ts';
import{handleRegulatoryMonitoringWorker}from'../regulatoryMonitoringWorker/entry.ts';
import{handleManageLegalExecution}from'../manageLegalExecution/entry.ts';
import{handleSeedP11LegalExecution}from'../seedP11LegalExecution/entry.ts';
const NON_OVERRIDABLE=new Set(['ACCESS_BANK_ACCOUNT_DATA','INITIATE_PAYMENT','HOLD_FUNDS','ACT_AS_PSP','ACT_AS_PSP_AGENT']);
Deno.serve(async req=>{const routed=await req.clone().json().catch(()=>({}));if(routed.action==='seed_p10_regulatory_control')return handleSeedP10RegulatoryControl(req);if(routed.action==='regulatory_monitoring')return handleRegulatoryMonitoringWorker(req);if(routed.action==='manage_legal_execution')return handleManageLegalExecution(req);if(routed.action==='seed_p11_legal_execution')return handleSeedP11LegalExecution(req);try{const b=createClientFromRequest(req),u=await b.auth.me().catch(()=>null);if(!u||u.role!=='admin')return Response.json({ok:false,error:'Forbidden'},{status:403});const body=await req.json().catch(()=>({})),s=b.asServiceRole,action=String(body.action||''),jurisdiction=String(body.jurisdiction||'').toUpperCase(),capability=String(body.capability||'').toUpperCase(),reason=String(body.reason||'').trim(),now=new Date().toISOString();if(!/^[A-Z]{2}$/.test(jurisdiction)||!MARKET_CAPABILITIES.includes(capability)||reason.length<5)return Response.json({ok:false,error:'jurisdiction_capability_reason_required'},{status:400});
if(action==='set_kill_switch'){const blocked=body.blocked===true,key=`market-control:${jurisdiction}:${capability}`,old=(await s.entities.MarketCapabilityControl.filter({control_key:key},'-updated_at',1).catch(()=>[]))[0],row={control_key:key,jurisdiction,capability,blocked,reason,effective_from:blocked?now:(old?.effective_from||now),effective_to:blocked?undefined:now,updated_at:now,updated_by:u.email};if(old)await s.entities.MarketCapabilityControl.update(old.id,row);else await s.entities.MarketCapabilityControl.create(row);await s.entities.Event.create({brand_id:'_platform',event_type:'country_policy_changed',source:'market_policy_admin',entity_type:'MarketCapabilityControl',entity_id:old?.id||key,payload_json:{action,actor:u.email,jurisdiction,capability,before:old||null,after:row},status:'processed',processed_at:now}).catch(()=>null);return Response.json({ok:true,action,jurisdiction,capability,blocked})}
if(action==='override'){const next=String(body.new_state||'').toUpperCase();if(!POLICY_STATES.includes(next))return Response.json({ok:false,error:'valid_new_state_required'},{status:400});if(NON_OVERRIDABLE.has(capability)&&next!=='BLOCKED')return Response.json({ok:false,error:'regulated_capability_requires_evidence_backed_policy_not_override'},{status:409});const p=(await s.entities.JurisdictionCapabilityPolicy.filter({jurisdiction,capability,active:true},'-effective_from',1).catch(()=>[]))[0],oldState=String(p?.state||'BLOCKED'),expires=body.expires_at?String(body.expires_at):new Date(Date.now()+7*86400000).toISOString();if(Date.parse(expires)<=Date.now())return Response.json({ok:false,error:'future_expiry_required'},{status:400});const row=await s.entities.MarketPolicyOverride.create({override_key:`override:${jurisdiction}:${capability}:${Date.now()}`,jurisdiction,capability,old_state:oldState,new_state:next,reason,evidence_refs:Array.isArray(body.evidence_refs)?body.evidence_refs:[],scope_json:body.scope_json||{},effective_from:now,expires_at:expires,actor_email:u.email,created_at:now});await s.entities.Event.create({brand_id:'_platform',event_type:'manual_override_applied',source:'market_policy_admin',entity_type:'MarketPolicyOverride',entity_id:row.id,payload_json:{actor:u.email,jurisdiction,capability,old_state:oldState,new_state:next,reason,evidence_refs:row.evidence_refs||[],expires_at:expires},status:'processed',processed_at:now}).catch(()=>null);return Response.json({ok:true,action,override:row})}
if(action==='supersede_policy'){const next=String(body.new_state||'').toUpperCase();if(!POLICY_STATES.includes(next))return Response.json({ok:false,error:'valid_new_state_required'},{status:400});const old=(await s.entities.JurisdictionCapabilityPolicy.filter({jurisdiction,capability,active:true},'-effective_from',1).catch(()=>[]))[0];if(old)await s.entities.JurisdictionCapabilityPolicy.update(old.id,{active:false,effective_to:now});const version=String(body.policy_version||`manual-${now.slice(0,10)}-${Date.now()}`),row=await s.entities.JurisdictionCapabilityPolicy.create({policy_key:`${version}:${jurisdiction}:${capability}`,jurisdiction,capability,state:next,reason_code:String(body.reason_code||'manual_evidence_review'),human_readable_reason:reason,evidence_refs:Array.isArray(body.evidence_refs)?body.evidence_refs:[],confidence:String(body.confidence||'UNKNOWN'),effective_from:now,reviewed_at:now,next_review_at:String(body.next_review_at||new Date(Date.now()+90*86400000).toISOString()),policy_version:version,supersedes_policy_id:old?.id||'',active:true,created_by_actor:u.email});await s.entities.Event.create({brand_id:'_platform',event_type:'country_policy_changed',source:'market_policy_admin',entity_type:'JurisdictionCapabilityPolicy',entity_id:row.id,payload_json:{actor:u.email,jurisdiction,capability,old_policy_id:old?.id||null,new_policy_id:row.id,old_state:old?.state||null,new_state:next,evidence_refs:row.evidence_refs||[]},status:'processed',processed_at:now}).catch(()=>null);return Response.json({ok:true,action,policy:row})}
return Response.json({ok:false,error:'unknown_action'},{status:400})}catch(e){console.error(e);return Response.json({ok:false,error:'market_policy_admin_failed'},{status:500})}});
