import { safeBestEffort } from '../../shared/bestEffort.ts';
import{createClientFromRequest}from'npm:@base44/sdk@0.8.41';
import{requireAdminOrInternal}from'../../shared/internalGate.ts';
import{P3_RESEARCH_SNAPSHOT}from'../../shared/p3SeedData.ts';
import{P3_SCHEMA_VERSION,P3_RESOLVER_POLICY_VERSION,P3_PROMOTION_POLICY_VERSION,sha256,validateObservation,validateComponent}from'../../shared/p3RateIntelligence.ts';
import { internalErrorResponse } from '../../shared/publicErrors.ts';
import { scopedIntelligenceKey } from '../../shared/intelligenceTenantScope.ts';

const SNAPSHOT_AT='2026-08-10T00:00:00.000Z';
const now=()=>new Date().toISOString();
async function first(s:any,entity:string,q:any){return(await s.entities[entity].filter(q,'-updated_date',1).catch((error:any)=>safeBestEffort(error,{operation:'seedP3RateIntelligence',fallback:[],severity:'secondary'})))[0]||null}
async function upsert(s:any,entity:string,keyField:string,key:string,data:any){const old=await first(s,entity,{[keyField]:key});if(old){await s.entities[entity].update(old.id,data);return{row:{...old,...data},created:false}}const row=await s.entities[entity].create(data);return{row,created:true}}
const researchState=(o:string)=>o==='VERIFIED_PUBLIC'?'PUBLIC_PRICING_FOUND':o==='PUBLIC_PARTIAL'?'PUBLIC_PARTIAL_PRICING_FOUND':o==='CUSTOM_QUOTE_VERIFIED'?'CUSTOM_PRICING_CONFIRMED':o==='NOT_PUBLIC_VERIFIED'?'NO_PUBLIC_PRICING_FOUND_AFTER_RESEARCH':o==='CONFLICT_RECORDED'?'CONFLICTING_SOURCES':o==='CANDIDATE_UNRESOLVED'?'REQUIRES_DEEP_RESEARCH':'UNKNOWN_AFTER_RESEARCH';

Deno.serve(async req=>{try{const b=createClientFromRequest(req),body=await req.json().catch(()=>({})),g=await requireAdminOrInternal(req,b,body);if(!g.ok)return g.response as Response;const s=b.asServiceRole,runAt=now();
const providers=await s.entities.Provider.list('-created_date',1000).catch((error:any)=>safeBestEffort(error,{operation:'seedP3RateIntelligence',fallback:[],severity:'secondary'})),products=await s.entities.ProviderProduct.list('-created_date',2000).catch((error:any)=>safeBestEffort(error,{operation:'seedP3RateIntelligence',fallback:[],severity:'secondary'})),methods=await s.entities.PaymentMethod.list('-created_date',1000).catch((error:any)=>safeBestEffort(error,{operation:'seedP3RateIntelligence',fallback:[],severity:'secondary'})),avail=await s.entities.ProviderMarketAvailability.list('-created_date',5000).catch((error:any)=>safeBestEffort(error,{operation:'seedP3RateIntelligence',fallback:[],severity:'secondary'}));
const providerByKey=new Map(providers.map((x:any)=>[x.provider_key,x])),productByKey=new Map(products.map((x:any)=>[x.product_key,x])),methodByKey=new Map(methods.map((x:any)=>[x.method_key,x]));
let universeCreated=0,statesCreated=0,passesCreated=0,evidenceCreated=0,snapshotsCreated=0,observationsCreated=0,componentsCreated=0,assertionsCreated=0,watchesCreated=0,edgeStatesCreated=0;
// Defensible 33-market research universe. Material P/S/R actors all end in a researched state; C actors remain discovery candidates, not material truth.
for(const marketRow of P3_RESEARCH_SNAPSHOT.markets as unknown as any[]){for(const actor of marketRow.actors as any[]){const p:any=providerByKey.get(actor.slug),key=`${P3_RESEARCH_SNAPSHOT.snapshot_version}:${marketRow.market}:${actor.slug}:${actor.family}`;const u=await upsert(s,'MarketResearchUniverse','universe_key',key,{universe_key:key,snapshot_version:P3_RESEARCH_SNAPSHOT.snapshot_version,market:marketRow.market,provider_id:p?.id,provider_slug:actor.slug,provider_name:actor.name,family:actor.family,materiality:actor.materiality,materiality_reason:actor.evidence_level==='R'?'primary pricing research':actor.evidence_level==='P'?'primary presence/product research':actor.evidence_level==='S'?'official multi-market evidence':'discovery candidate pending identity/deeper verification',research_outcome:actor.research_outcome,source_refs:[],researched_at:SNAPSHOT_AT,notes:`baseline=${marketRow.baseline_state}; evidence_level=${actor.evidence_level}`});if(u.created)universeCreated++;
const rsKey=`p3:${marketRow.market}:${actor.slug}:${actor.family}`;const st=researchState(actor.research_outcome);const rs=await upsert(s,'RateResearchState','research_key',rsKey,{research_key:rsKey,market:marketRow.market,provider_id:p?.id,provider_slug:actor.slug,family:actor.family,state:st,last_researched_at:SNAPSHOT_AT,source_count:actor.evidence_level==='C'?0:1,primary_source_count:['R','P'].includes(actor.evidence_level)?1:0,observation_count:0,unresolved_gaps:actor.evidence_level==='C'?['DISCOVERY_CANDIDATE_REQUIRES_IDENTITY_AND_PRIMARY_EVIDENCE']:[]});if(rs.created)statesCreated++;
const passKey=`${P3_RESEARCH_SNAPSHOT.snapshot_version}:${marketRow.market}:${actor.slug}:${actor.family}`;const rp=await upsert(s,'RateResearchPass','pass_key',passKey,{pass_key:passKey,market:marketRow.market,provider_id:p?.id,provider_slug:actor.slug,family:actor.family,status:actor.evidence_level==='C'?'PARTIAL':'COMPLETED',queries_attempted:[`${actor.name} ${marketRow.market} merchant acquiring payments pricing official`],source_urls_attempted:[],languages_used:['local','en'],sources_discovered:actor.evidence_level==='C'?0:1,sources_verified:['R','P'].includes(actor.evidence_level)?1:0,observations_created:0,observations_updated:0,candidates_rejected:0,conflicts:0,unresolved_gaps:actor.evidence_level==='C'?['PRIMARY_EVIDENCE_NOT_YET_PROMOTED']:[],worker:'p3_initial_deep_research',parser_version:'deep-research-p3-2026-08-10',checkpoint_cursor:'complete',retry_count:0,idempotency_key:passKey,started_at:SNAPSHOT_AT,completed_at:SNAPSHOT_AT,errors:[]});if(rp.created)passesCreated++;}}
// Every verified P2 product-market edge gets a P3 research state; no hidden NOT_RESEARCHED handoff.
for(const edge of avail as any[]){if(edge.research_state!=='RESOLVED'||!edge.product_id||!edge.market)continue;const p=providers.find((x:any)=>x.id===edge.provider_id),prod=products.find((x:any)=>x.id===edge.product_id);if(!p||!prod)continue;const anchored=(P3_RESEARCH_SNAPSHOT.rate_anchors as unknown as any[]).find(a=>a.provider===p.provider_key&&a.product===prod.product_key&&a.market===edge.market);const state=anchored?(anchored.visibility==='PUBLIC_PARTIAL'?'PUBLIC_PARTIAL_PRICING_FOUND':'PUBLIC_PRICING_FOUND'):prod.pricing_visibility==='CUSTOM_QUOTE'?'CUSTOM_PRICING_CONFIRMED':'UNKNOWN_AFTER_RESEARCH';const key=`p3-edge:${edge.market}:${p.provider_key}:${prod.product_key}:${edge.channel||'ANY'}`;const x=await upsert(s,'RateResearchState','research_key',key,{research_key:key,market:edge.market,provider_id:p.id,provider_slug:p.provider_key,provider_product_id:prod.id,family:'P2_VERIFIED_PRODUCT_MARKET_EDGE',state,last_researched_at:SNAPSHOT_AT,source_count:(edge.evidence_refs||[]).length,primary_source_count:(edge.evidence_refs||[]).length?1:0,observation_count:anchored?1:0,unresolved_gaps:anchored?[]:['NO_CANONICAL_NUMERIC_RATE_PROMOTED_FROM_THIS_EDGE']});if(x.created)edgeStatesCreated++;}
// Primary rate anchors: immutable evidence -> normalized snapshot -> canonical ProviderPricingVersion -> atomic components/assertions -> watch target.
for(const a of P3_RESEARCH_SNAPSHOT.rate_anchors as unknown as any[]){const p:any=providerByKey.get(a.provider),prod:any=productByKey.get(a.product),method:any=a.method?methodByKey.get(a.method):null;if(!p||!prod)continue;const sourceKey=`p3-source:${await sha256({url:a.source,market:a.market,provider:a.provider})}`;const normalized={provider:a.provider,product:a.product,market:a.market,channel:a.channel,method:a.method||null,visibility:a.visibility,model:a.model,components:a.components,conditions:a.conditions||null,processing_currency:a.processing_currency||null,settlement_currency:a.settlement_currency||null};const contentHash=await sha256(normalized);
const evidenceScope={tenant_scope:'global',domain:'rate_intelligence',purpose:'official_provider_pricing_research',retention_policy_key:'intelligence_public_research',legal_basis:'public_information'};const rawEvKey=`p3-evidence:${a.key}:${contentHash.slice(0,16)}`;const scopedEvKey=scopedIntelligenceKey(rawEvKey,evidenceScope,'evidence');if(!scopedEvKey.ok)throw new Error(`p3_evidence_scope_invalid:${scopedEvKey.error}`);const evKey=scopedEvKey.key;let ev=await first(s,'IntelligenceEvidence',{tenant_scope:'global',domain:evidenceScope.domain,purpose:evidenceScope.purpose,evidence_key:evKey});if(!ev){ev=await s.entities.IntelligenceEvidence.create({...evidenceScope,evidence_key:evKey,evidence_hash:await sha256({...evidenceScope,source:a.source,normalized}),content_hash:await sha256({...evidenceScope,normalized}),source_type:'official_pricing',source_reference:a.source,source_url:a.source,vertical:'payments',provider_id:p.id,provider_slug:a.provider,observed_at:SNAPSHOT_AT,recorded_at:runAt,truth_level:'verified_official',confidence:Number(a.confidence||95)/100,parser_version:'deep-research-p3-2026-08-10',payload_json:normalized,is_demo:false,quarantined:false,jurisdiction:a.market,subject:a.key,fact_key:a.key,value_json:normalized,source_name:p.canonical_name||p.name,source_quality:'OFFICIAL_PROVIDER',retrieved_at:SNAPSHOT_AT,verification_status:'VERIFIED',verified_at:SNAPSHOT_AT,verified_by:'p3_primary_research',freshness_status:'CURRENT',source_market:a.market,source_language:'local',source_scope_type:'MARKET',applicable_markets:[a.market],excluded_markets:[],researched_at:SNAPSHOT_AT,observation_provenance:'VERIFIED_PRIMARY'});evidenceCreated++;}
const snapshot=await upsert(s,'RateSourceSnapshot','snapshot_key',sourceKey,{snapshot_key:sourceKey,source_url:a.source,source_type:'OFFICIAL_PROVIDER_PRICING',provider_id:p.id,market:a.market,language:'local',retrieved_at:SNAPSHOT_AT,content_hash:contentHash,normalized_content_hash:contentHash,pricing_section_hash:contentHash,normalized_extract_json:normalized,parser_version:'p3-anchor-parser-1',extractor_version:'deep-research-p3-2026-08-10',status:'HEALTHY'});if(snapshot.created)snapshotsCreated++;
const pricingKey=`p3:${a.key}`;let obs=await first(s,'ProviderPricingVersion',{pricing_key:pricingKey});const observation:any={pricing_key:pricingKey,provider_id:p.id,provider_slug:a.provider,provider_product_id:prod.id,product_key:a.product,vertical:'payments',channel:a.channel,country:a.market,market:a.market,pricing_dimension:'canonical_rate_observation',currency:a.processing_currency||a.settlement_currency||undefined,pricing_visibility:a.visibility,pricing_model:a.model,observation_type:'PUBLIC_PUBLISHED',scope_type:'MARKET',applicable_markets:[a.market],excluded_markets:[],payment_method_id:method?.id,processing_currency:a.processing_currency,settlement_currency:a.settlement_currency,effective_date_certainty:'UNKNOWN',first_seen_at:SNAPSHOT_AT,last_seen_at:SNAPSHOT_AT,recorded_at:runAt,retrieved_at:SNAPSHOT_AT,verified_at:SNAPSHOT_AT,verification_status:'VERIFIED_PRIMARY',observation_completeness:a.completeness||'COMPLETE',confidence_score:a.confidence||95,confidence_band:'VERIFIED_HIGH',status:'CURRENT',research_pass_id:`${P3_RESEARCH_SNAPSHOT.snapshot_version}:${a.market}:${a.provider}:${a.product}`,source_snapshot_id:snapshot.row.id,evidence_assertion_ids:[],access_scope:'GLOBAL_PUBLIC',sensitivity_class:'PUBLIC',source_owner:p.canonical_name||p.name,sharing_policy:'PUBLIC_REUSE',promotion_policy_version:P3_PROMOTION_POLICY_VERSION,extractor_version:'deep-research-p3-2026-08-10',parser_version:'p3-anchor-parser-1',resolver_policy_version:P3_RESOLVER_POLICY_VERSION,truth_level:'verified_official',knowledge_state:'active',source_evidence_id:ev.id,source_reference:a.source,content_hash:contentHash,confidence:Number(a.confidence||95)/100,version:1,is_demo:false,observed_at:SNAPSHOT_AT,conditions_json:a.conditions||{}};
const validation=validateObservation(observation,a.components.map((c:any)=>({component_type:c.type,percentage_ppm:c.percentage_ppm,amount_minor:c.amount_minor,currency:c.currency,minimum_amount_minor:c.minimum_amount_minor,maximum_amount_minor:c.maximum_amount_minor,value_mode:c.mode||'KNOWN'})));if(!validation.ok)throw new Error(`p3_anchor_invalid:${a.key}:${validation.errors.join(',')}`);observation.semantic_fingerprint=await sha256(normalized);
if(!obs){obs=await s.entities.ProviderPricingVersion.create(observation);observationsCreated++;}else{await s.entities.ProviderPricingVersion.update(obs.id,{last_seen_at:runAt,verified_at:SNAPSHOT_AT,source_snapshot_id:snapshot.row.id,semantic_fingerprint:observation.semantic_fingerprint});}
const assertionIds:string[]=[];let seq=0;for(const c of a.components as any[]){seq++;const rc:any={component_key:`${pricingKey}:component:${seq}`,pricing_observation_id:obs.id,component_type:c.type,fee_layer:c.layer||'OTHER',percentage_ppm:c.percentage_ppm,amount_minor:c.amount_minor,currency:c.currency,minimum_amount_minor:c.minimum_amount_minor,maximum_amount_minor:c.maximum_amount_minor,unit_basis:c.basis||'PER_TRANSACTION',value_mode:c.mode||'KNOWN',tax_treatment:'UNKNOWN',condition_json:c.condition||{},component_sequence:seq,semantic_fingerprint:await sha256(c)};const cv=validateComponent(rc);if(!cv.ok)throw new Error(`p3_component_invalid:${a.key}:${cv.errors.join(',')}`);const assertionKey=`${pricingKey}:component:${seq}:assertion`;const ar=await upsert(s,'EvidenceAssertion','assertion_key',assertionKey,{assertion_key:assertionKey,subject_type:'ProviderPricingVersion',subject_id:obs.id,predicate:`rate_component:${c.type}`,value_json:c,market:a.market,product_id:prod.id,channel:a.channel,evidence_id:ev.id,assertion_status:'SUPPORTS',extracted_at:SNAPSHOT_AT,confidence:'VERIFIED',verification_status:'VERIFIED'});if(ar.created)assertionsCreated++;assertionIds.push(ar.row.id);rc.source_assertion_id=ar.row.id;const cr=await upsert(s,'RateComponent','component_key',rc.component_key,rc);if(cr.created)componentsCreated++;}
await s.entities.ProviderPricingVersion.update(obs.id,{evidence_assertion_ids:assertionIds});
const watchKey=`p3-watch:${a.market}:${a.provider}:${await sha256(a.source)}`;const cadence=a.key.includes('promotion')?24:168;const w=await upsert(s,'PricingWatchTarget','watch_key',watchKey,{watch_key:watchKey,provider_id:p.id,provider_slug:a.provider,market:a.market,provider_product_id:prod.id,source_url:a.source,source_type:'OFFICIAL_PROVIDER_PRICING',priority:a.confidence>=98?'HIGH':'NORMAL',cadence_hours:cadence,freshness_sla_hours:cadence*2,last_checked_at:SNAPSHOT_AT,last_changed_at:SNAPSHOT_AT,fresh_until:new Date(Date.parse(SNAPSHOT_AT)+cadence*2*3600000).toISOString(),next_check_at:new Date(Date.parse(SNAPSHOT_AT)+cadence*3600000).toISOString(),status:'ACTIVE',failure_count:0,last_snapshot_id:snapshot.row.id,policy_version:'p3-watch-1.0.0'});if(w.created)watchesCreated++;
const stateKey=`p3-edge:${a.market}:${a.provider}:${a.product}:${a.channel}`;const oldState=await first(s,'RateResearchState',{research_key:stateKey});if(oldState)await s.entities.RateResearchState.update(oldState.id,{state:a.visibility==='PUBLIC_PARTIAL'?'PUBLIC_PARTIAL_PRICING_FOUND':'PUBLIC_PRICING_FOUND',last_researched_at:SNAPSHOT_AT,source_count:1,primary_source_count:1,observation_count:1,unresolved_gaps:[]});}
await s.entities.Event.create({brand_id:'_platform',event_type:'p3_rate_intelligence_seeded',source:'seedP3RateIntelligence',entity_type:'ProviderPricingVersion',entity_id:P3_RESEARCH_SNAPSHOT.snapshot_version,payload_json:{schema_version:P3_SCHEMA_VERSION,markets:33,research_universe:P3_RESEARCH_SNAPSHOT.markets.reduce((n:number,m:any)=>n+m.actors.length,0),rate_anchors:P3_RESEARCH_SNAPSHOT.rate_anchors.length,universeCreated,statesCreated,passesCreated,edgeStatesCreated,evidenceCreated,snapshotsCreated,observationsCreated,componentsCreated,assertionsCreated,watchesCreated,no_p4_models:true},status:'processed',processed_at:runAt}).catch((error:any)=>safeBestEffort(error,{operation:'seedP3RateIntelligence',fallback:null,severity:'secondary'}));
return Response.json({ok:true,schema_version:P3_SCHEMA_VERSION,snapshot_version:P3_RESEARCH_SNAPSHOT.snapshot_version,markets:33,research_universe:P3_RESEARCH_SNAPSHOT.markets.reduce((n:number,m:any)=>n+m.actors.length,0),rate_anchors:P3_RESEARCH_SNAPSHOT.rate_anchors.length,created:{universeCreated,statesCreated,passesCreated,edgeStatesCreated,evidenceCreated,snapshotsCreated,observationsCreated,componentsCreated,assertionsCreated,watchesCreated},no_p4_models:true})}catch(e){console.error(e);return internalErrorResponse(e, 'seedP3RateIntelligence');}});
