import{createClientFromRequest}from'npm:@base44/sdk@0.8.41';
import{requireAdminOrInternal}from'../../shared/internalGate.ts';
import{P3_SCHEMA_VERSION,P3_RESOLVER_POLICY_VERSION,resolvePricing,evaluateComponents,validateObservation}from'../../shared/p3RateIntelligence.ts';
import{handleProjectVerifiedPaymentsToP4}from'../projectVerifiedPaymentsToP4/entry.ts';
import{handleRequestP4Estimate}from'../requestP4Estimate/entry.ts';

const max=(n:any,d=500)=>Math.max(1,Math.min(Number(n||d),2000));
function tenantSafe(rows:any[],g:any,q:any){if(g.isAdmin)return rows;const tenant=String(q?.tenant_id||'');return rows.filter(r=>r.access_scope!=='TENANT_PRIVATE'||(tenant&&r.tenant_id===tenant));}
Deno.serve(async req=>{const routed=await req.clone().json().catch(()=>({}));if(routed.action==='project_verified_payments_to_p4')return handleProjectVerifiedPaymentsToP4(req);if(routed.action==='request_p4_estimate')return handleRequestP4Estimate(req);try{const b=createClientFromRequest(req),body=await req.json().catch(()=>({})),g=await requireAdminOrInternal(req,b,body);if(!g.ok)return g.response;const s=b.asServiceRole,action=String(body.action||'summary'),q=body.query||{};
if(action==='summary'){const [u,obs,watch,states,conflicts,components]=await Promise.all([s.entities.MarketResearchUniverse.list('-researched_at',2000).catch(()=>[]),s.entities.ProviderPricingVersion.filter({vertical:'payments'},'-recorded_at',2000).catch(()=>[]),s.entities.PricingWatchTarget.list('-last_checked_at',2000).catch(()=>[]),s.entities.RateResearchState.list('-last_researched_at',3000).catch(()=>[]),s.entities.KnowledgeConflict.filter({vertical:'payments'},'-created_at',1000).catch(()=>[]),s.entities.RateComponent.list('-created_date',3000).catch(()=>[])]);const marketRows:any={};for(const m of u){const k=m.market||(m.jurisdiction??'UNKNOWN');marketRows[k]??={market:k,material:0,candidates:0,verified_public:0,public_partial:0,unknown_after_research:0,custom_quote:0,conflicts:0};if(['MATERIAL_TIER_1','MATERIAL_TIER_2'].includes(m.materiality))marketRows[k].material++;if(m.materiality==='DISCOVERY_CANDIDATE')marketRows[k].candidates++;if(m.research_outcome==='VERIFIED_PUBLIC')marketRows[k].verified_public++;if(m.research_outcome==='PUBLIC_PARTIAL')marketRows[k].public_partial++;if(m.research_outcome==='UNKNOWN_AFTER_RESEARCH')marketRows[k].unknown_after_research++;if(m.research_outcome==='CUSTOM_QUOTE_VERIFIED')marketRows[k].custom_quote++;if(m.research_outcome==='CONFLICT_RECORDED')marketRows[k].conflicts++;}
const publicObs=obs.filter((x:any)=>x.access_scope!=='TENANT_PRIVATE');return Response.json({ok:true,schema_version:P3_SCHEMA_VERSION,resolver_policy_version:P3_RESOLVER_POLICY_VERSION,metrics:{markets:Object.keys(marketRows).length,research_universe:u.length,pricing_observations:publicObs.length,rate_components:components.length,verified_primary:publicObs.filter((x:any)=>x.verification_status==='VERIFIED_PRIMARY').length,public_complete:publicObs.filter((x:any)=>x.pricing_visibility==='PUBLIC_COMPLETE').length,public_partial:publicObs.filter((x:any)=>x.pricing_visibility==='PUBLIC_PARTIAL').length,custom_quote:publicObs.filter((x:any)=>x.pricing_visibility==='CUSTOM_QUOTE').length,stale:publicObs.filter((x:any)=>x.status==='STALE'||x.verification_status==='STALE').length,conflicts:conflicts.filter((x:any)=>x.status==='open'||x.status==='investigating').length,watch_targets:watch.filter((x:any)=>x.status==='ACTIVE').length,research_states:states.length,not_researched:states.filter((x:any)=>x.state==='NOT_RESEARCHED').length,legacy_fallback_usage:0},markets:Object.values(marketRows),truth_boundary:'P3 is factual rate truth only; no P4 statistical benchmarks or P5 achievable-rate inference.'})}
if(action==='resolve'||action==='current'||action==='history'){const base:any={vertical:'payments'};if(q.provider_slug)base.provider_slug=q.provider_slug;if(q.provider_id)base.provider_id=q.provider_id;const rows=tenantSafe(await s.entities.ProviderPricingVersion.filter(base,'-recorded_at',max(q.limit,1000)).catch(()=>[]),g,q).filter((r:any)=>!r.is_demo);if(action==='history')return Response.json({ok:true,schema_version:P3_SCHEMA_VERSION,observations:rows.filter((r:any)=>(!q.market||(r.market||r.country)===q.market)&&(!q.channel||r.channel===q.channel)&&(!q.provider_product_id||r.provider_product_id===q.provider_product_id)).sort((a:any,b:any)=>String(b.recorded_at||b.observed_at||'').localeCompare(String(a.recorded_at||a.observed_at||'')))});const result=resolvePricing(rows,{...q,date:q.date||new Date().toISOString()});if(result.match){const components=await s.entities.RateComponent.filter({pricing_observation_id:result.match.id},'component_sequence',200).catch(()=>[]);return Response.json({ok:true,schema_version:P3_SCHEMA_VERSION,resolver_policy_version:P3_RESOLVER_POLICY_VERSION,result:{...result,components}})}return Response.json({ok:true,schema_version:P3_SCHEMA_VERSION,resolver_policy_version:P3_RESOLVER_POLICY_VERSION,result})}
if(action==='evaluate'){const id=String(q.pricing_observation_id||'');const obs=await s.entities.ProviderPricingVersion.get(id).catch(()=>null);if(!obs)return Response.json({ok:false,error:'pricing_observation_not_found'},{status:404});if(!g.isAdmin&&obs.access_scope==='TENANT_PRIVATE'&&(!q.tenant_id||q.tenant_id!==obs.tenant_id))return Response.json({ok:false,error:'forbidden_private_pricing'},{status:403});const components=await s.entities.RateComponent.filter({pricing_observation_id:id},'component_sequence',300).catch(()=>[]);const valid=validateObservation(obs,components);if(!valid.ok)return Response.json({ok:false,error:'invalid_canonical_observation',validation:valid},{status:409});const evaluation=evaluateComponents(components,{transaction_amount_minor:q.transaction_amount_minor,transaction_currency:q.transaction_currency,terminal_count:q.terminal_count,monthly_volume_minor:q.monthly_volume_minor});return Response.json({ok:true,observation_id:id,evaluation,confidence:obs.confidence_score,verification_status:obs.verification_status,evidence_assertion_ids:obs.evidence_assertion_ids||[]})}
if(action==='research_status'){const filter:any={};if(q.market)filter.market=q.market;if(q.provider_slug)filter.provider_slug=q.provider_slug;const rows=await s.entities.RateResearchState.filter(filter,'market',max(q.limit,2000)).catch(()=>[]);return Response.json({ok:true,rows})}
if(action==='watch'){const filter:any={};if(q.market)filter.market=q.market;if(q.provider_slug)filter.provider_slug=q.provider_slug;return Response.json({ok:true,rows:await s.entities.PricingWatchTarget.filter(filter,'next_check_at',max(q.limit,1000)).catch(()=>[])})}
if(action==='conflicts'){const filter:any={vertical:'payments'};if(q.provider_slug)filter.provider_slug=q.provider_slug;if(q.market)filter.country=q.market;return Response.json({ok:true,rows:await s.entities.KnowledgeConflict.filter(filter,'-created_at',max(q.limit,1000)).catch(()=>[])})}
return Response.json({ok:false,error:'unknown_action'},{status:400})}catch(e){console.error(e);return Response.json({ok:false,error:'rate_intelligence_query_failed'},{status:500})}});
